project_id = "tvksbtrelpzhbyeutzgp"

[functions.fetch-updates]
verify_jwt = false

[functions.generate-weekly-brief]
verify_jwt = false

[functions.subscribe-email]
verify_jwt = false

[functions.translate-articles]
verify_jwt = false