// GENERATED by scripts/ptest/export-packs.ts (DOC 261) — do not edit by hand.
// Rebuild: deno run --allow-read --allow-write --allow-env scripts/ptest/export-packs.ts
// Drift guard: tests/edge/ptest/packs.test.ts
import type { BlockCatalogue } from "./types.ts";

export const CYBER_BLOCK_CATALOGUE: BlockCatalogue = {
  "product": "cppa-cyber",
  "spine_version": "cyber-skeleton-assembler@c2-spine-v1.1-2026-08-26",
  "generated_on": "2026-09-14",
  "generated_from": [
    "cyber-nist-mid-tuning",
    "cyber-iso-strong-tuning",
    "cyber-sibling-notes-adversarial",
    "cyber-perfect-record",
    "cyber-clinical-diagnostics-platform-perfect"
  ],
  "entries": [
    {
      "block_key": "cover:0",
      "section_id": "cover",
      "section_title": "Assessment Profile",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR §§ 7120"
      ]
    },
    {
      "block_key": "cover:1",
      "section_id": "cover",
      "section_title": "Assessment Profile",
      "kind": "skeleton",
      "fixed_text_prefix": "Reliance notice. This report evaluates audit readiness from information supplied by the Company. It does not represent that End User Privacy has performed the i",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary:0",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "skeleton",
      "fixed_text_prefix": "This assessment evaluates the Company’s cybersecurity program as the Company describes it in its answers, the evidence categories the Company identifies as avai",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary:1",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "lead",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7123(c)",
        "§ 7124"
      ]
    },
    {
      "block_key": "executive_summary:2",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary:3",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7122",
        "§ 7122(d)",
        "§ 7123(c)"
      ]
    },
    {
      "block_key": "purpose_scope_record:0",
      "section_id": "purpose_scope_record",
      "section_title": "1. Purpose, Scope, and Assessment Record",
      "kind": "skeleton",
      "fixed_text_prefix": "Article 9 requires an independent cybersecurity audit for businesses within its scope. This report serves a narrower purpose: it organizes the Company’s present",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "purpose_scope_record:1",
      "section_id": "purpose_scope_record",
      "section_title": "1. Purpose, Scope, and Assessment Record",
      "kind": "skeleton",
      "fixed_text_prefix": "The readiness analysis does not convert management descriptions into auditor findings. Where the Company provides only a maturity selection or narrative descrip",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "purpose_scope_record:2",
      "section_id": "purpose_scope_record",
      "section_title": "1. Purpose, Scope, and Assessment Record",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "purpose_scope_record:3",
      "section_id": "purpose_scope_record",
      "section_title": "1. Purpose, Scope, and Assessment Record",
      "kind": "skeleton",
      "fixed_text_prefix": "The Company may identify the frameworks it expects to rely on and describe the intended audit scope. Those facts are useful to readiness because they show how t",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "purpose_scope_record:4",
      "section_id": "purpose_scope_record",
      "section_title": "1. Purpose, Scope, and Assessment Record",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7123(c)"
      ]
    },
    {
      "block_key": "purpose_scope_record:5",
      "section_id": "purpose_scope_record",
      "section_title": "1. Purpose, Scope, and Assessment Record",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7001(v)",
        "11 CCR § 7120",
        "§ 7120",
        "§ 7120(b)(1)",
        "§ 7120(b)(2)",
        "§ 7120(b)(2)(A)",
        "§ 7123(b)(2)"
      ]
    },
    {
      "block_key": "purpose_scope_record:7",
      "section_id": "purpose_scope_record",
      "section_title": "1. Purpose, Scope, and Assessment Record",
      "kind": "skeleton",
      "fixed_text_prefix": "Prior cybersecurity audits, assessments, and certifications may be useful evidence and may reduce duplication where they actually cover the relevant California ",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "purpose_scope_record:8",
      "section_id": "purpose_scope_record",
      "section_title": "1. Purpose, Scope, and Assessment Record",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR §§ 7121"
      ]
    },
    {
      "block_key": "purpose_scope_record:9",
      "section_id": "purpose_scope_record",
      "section_title": "1. Purpose, Scope, and Assessment Record",
      "kind": "skeleton",
      "fixed_text_prefix": "A useful readiness conclusion depends on how much of the record is actually populated. Missing maturity, notes, or evidence information should therefore be visi",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "purpose_scope_record:10",
      "section_id": "purpose_scope_record",
      "section_title": "1. Purpose, Scope, and Assessment Record",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "auditor_evidence:0",
      "section_id": "auditor_evidence",
      "section_title": "2. Auditor Engagement and Evidence Readiness",
      "kind": "skeleton",
      "fixed_text_prefix": "The statutory audit must be performed by a qualified, objective, independent professional. The Company’s answers do not identify the auditor’s identity, qualifi",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "auditor_evidence:1",
      "section_id": "auditor_evidence",
      "section_title": "2. Auditor Engagement and Evidence Readiness",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7122"
      ]
    },
    {
      "block_key": "auditor_evidence:2",
      "section_id": "auditor_evidence",
      "section_title": "2. Auditor Engagement and Evidence Readiness",
      "kind": "skeleton",
      "fixed_text_prefix": "For readiness purposes, evidence matters independently from implementation. A policy or procedure may show that a control is designed or documented, while a con",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "auditor_evidence:3",
      "section_id": "auditor_evidence",
      "section_title": "2. Auditor Engagement and Evidence Readiness",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "program_readiness:0",
      "section_id": "program_readiness",
      "section_title": "3. Cybersecurity Program Readiness",
      "kind": "skeleton",
      "fixed_text_prefix": "The component-by-component analysis is not a substitute for understanding the cybersecurity program as a whole. References below are to the California Privacy P",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "program_readiness:1",
      "section_id": "program_readiness",
      "section_title": "3. Cybersecurity Program Readiness",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "program_readiness:2",
      "section_id": "program_readiness",
      "section_title": "3. Cybersecurity Program Readiness",
      "kind": "skeleton",
      "fixed_text_prefix": "This report presents all eighteen § 7123(c) components. Because the Company’s answers do not include a separate applicability determination for each component, ",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7122(d)",
        "11 CCR § 7123(c)",
        "§ 7123(c)"
      ]
    },
    {
      "block_key": "program_readiness:3",
      "section_id": "program_readiness",
      "section_title": "3. Cybersecurity Program Readiness",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7123(c)(1)(B)",
        "§ 7123(c)(1)(A)"
      ]
    },
    {
      "block_key": "cross_cutting:0",
      "section_id": "cross_cutting",
      "section_title": "4. Cross-Cutting Findings and Readiness Gaps",
      "kind": "skeleton",
      "fixed_text_prefix": "The component discussion establishes the record one control at a time. This section identifies the few matters that actually affect the overall readiness conclu",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "cross_cutting:1",
      "section_id": "cross_cutting",
      "section_title": "4. Cross-Cutting Findings and Readiness Gaps",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "incident_context:0",
      "section_id": "incident_context",
      "section_title": "5. Security-Incident Context",
      "kind": "skeleton",
      "fixed_text_prefix": "Incident history can inform readiness, particularly the incident-response component, but the Company’s answers capture only the number of incidents in the prece",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "incident_context:1",
      "section_id": "incident_context",
      "section_title": "5. Security-Incident Context",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7123(e)(9)"
      ]
    },
    {
      "block_key": "readiness_actions:0",
      "section_id": "readiness_actions",
      "section_title": "6. Readiness Actions",
      "kind": "skeleton",
      "fixed_text_prefix": "This section converts the assessment into a practical audit-preparation plan. These are EndUserPrivacy (EUP) readiness actions generated from the Company’s answ",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7123(e)(4)"
      ]
    },
    {
      "block_key": "readiness_actions:1",
      "section_id": "readiness_actions",
      "section_title": "6. Readiness Actions",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7123(e)(9)",
        "§ 7122"
      ]
    },
    {
      "block_key": "readiness_conclusion:0",
      "section_id": "readiness_conclusion",
      "section_title": "7. Readiness Conclusion",
      "kind": "skeleton",
      "fixed_text_prefix": "This conclusion answers a narrow and useful question: based on the Company’s present description of its cybersecurity program and the evidence categories identi",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "readiness_conclusion:1",
      "section_id": "readiness_conclusion",
      "section_title": "7. Readiness Conclusion",
      "kind": "lead",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7123(c)",
        "§ 7124"
      ]
    },
    {
      "block_key": "readiness_conclusion:2",
      "section_id": "readiness_conclusion",
      "section_title": "7. Readiness Conclusion",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "evidence_preservation:0",
      "section_id": "evidence_preservation",
      "section_title": "8. Evidence Preservation and Continuing Readiness",
      "kind": "skeleton",
      "fixed_text_prefix": "Article 9 requires the business and auditor to retain documents relevant to the cybersecurity audit for at least five years after completion.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "evidence_preservation:1",
      "section_id": "evidence_preservation",
      "section_title": "8. Evidence Preservation and Continuing Readiness",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_a_matrix:0",
      "section_id": "appendix_a_matrix",
      "section_title": "Appendix A — Component Readiness Matrix",
      "kind": "skeleton",
      "fixed_text_prefix": "A compact matrix consolidating the eighteen component records and the findings of this report.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_a_matrix:1",
      "section_id": "appendix_a_matrix",
      "section_title": "Appendix A — Component Readiness Matrix",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_b_evidence:0",
      "section_id": "appendix_b_evidence",
      "section_title": "Appendix B — Evidence Readiness Index",
      "kind": "skeleton",
      "fixed_text_prefix": "A component-by-component index of the evidence categories the Company identifies as available. The appendix preserves the distinction between an evidence catego",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_b_evidence:1",
      "section_id": "appendix_b_evidence",
      "section_title": "Appendix B — Evidence Readiness Index",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_c_actions:0",
      "section_id": "appendix_c_actions",
      "section_title": "Appendix C — Readiness Action Register",
      "kind": "skeleton",
      "fixed_text_prefix": "A consolidated action register of the material findings, organized by remediation owner where available and by action type. Each item identifies whether it conc",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_c_actions:1",
      "section_id": "appendix_c_actions",
      "section_title": "Appendix C — Readiness Action Register",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7123(e)(9)"
      ]
    },
    {
      "block_key": "appendix_d_record:0",
      "section_id": "appendix_d_record",
      "section_title": "Appendix D — Assessment Record",
      "kind": "skeleton",
      "fixed_text_prefix": "A structured preservation of the profile and control facts this report rests on, together with the report record, so the assessment can be reviewed and reperfor",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_d_record:1",
      "section_id": "appendix_d_record",
      "section_title": "Appendix D — Assessment Record",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR §§ 7121",
        "§ 7123(c)"
      ]
    },
    {
      "block_key": "appendix_d_record:2",
      "section_id": "appendix_d_record",
      "section_title": "Appendix D — Assessment Record",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "signature:0",
      "section_id": "signature",
      "section_title": "Signature",
      "kind": "skeleton",
      "fixed_text_prefix": "This information is provided for the purposes of a cybersecurity audit as required pursuant to 11 CCR §§ 7120–7124.",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR §§ 7120"
      ]
    },
    {
      "block_key": "signature:1",
      "section_id": "signature",
      "section_title": "Signature",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "signature:2",
      "section_id": "signature",
      "section_title": "Signature",
      "kind": "skeleton",
      "fixed_text_prefix": "This signature acknowledges the information above, and is not the certification described in 11 CCR § 7124.",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7124"
      ]
    },
    {
      "block_key": "submission_and_attestation:0",
      "section_id": "submission_and_attestation",
      "section_title": "Submission and Attestation",
      "kind": "corpus",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7124",
        "11 CCR § 7124(d)(4)"
      ]
    },
    {
      "block_key": "table_of_authorities:0",
      "section_id": "table_of_authorities",
      "section_title": "Authorities Cited",
      "kind": "rule",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7001(v)",
        "11 CCR § 7120",
        "11 CCR § 7122",
        "11 CCR § 7123(c)(1)",
        "11 CCR § 7123(c)(1)(B)",
        "11 CCR § 7123(e)(9)",
        "11 CCR § 7124"
      ]
    }
  ]
};
