// CYBER-REGISTRY-WIRING (2026-07-24) — cppa-cybersecurity verified-authority registry.
//
// Authored per the CYBER-REGISTRY-AUTHORING dispatch on the exact pattern of
// admt-verified-authorities.ts and risk-verified-authorities.ts (same row shape,
// same resolver contract).
//
// AUTHORING RULE (audit standing order): every row MUST pass corpus-pin from
// the first commit. Any proposition that cannot carry an exact contiguous
// substring of cppa_authorities.full_text (status='current') is EXCLUDED,
// never paraphrased, never labelled verbatim. KNOWN_PARAPHRASED_KEYS is
// therefore EMPTY on entry.
//
// Coverage: 11 CCR §§ 7120–7124 (Article 9 — Cybersecurity Audits).
//   § 7120 applicability/thresholds; § 7121 timing; § 7122 auditor
//   independence; § 7123 scope (incl. eighteen per-component rows for
//   (c)(1)–(c)(18)); § 7124 certification/submission.

import type {
  VerifiedAuthorityRegistry,
  VerifiedAuthorityRow,
} from "../verified-authority-resolver.ts";

export const CYBER_VERIFIED_AUTHORITY_VERSION = "cyber-va-w1-2026-07-24";

const CCR_URL =
  "https://cppa.ca.gov/regulations/pdf/ccpa_updates_cyber_risk_admt_appr_text.pdf";
const VOD = "2026-07-24";
const ART9 = "11 CCR Art. 9 (Cybersecurity Audits)";

const R = (r: VerifiedAuthorityRow): VerifiedAuthorityRow => r;

export const CYBER_VERIFIED_AUTHORITIES: VerifiedAuthorityRegistry = {
  cyber_audit_required: R({
    proposition_key: "cyber_audit_required",
    citation: "11 CCR \u00a7 7120",
    subsection: "11 CCR \u00a7 7120(a)",
    verbatim_quote: "Every business whose processing of consumers’ personal information presents\nsignificant risk to consumers’ security as set forth in subsection (b) must\ncomplete a cybersecurity audit.",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_threshold_significant_risk: R({
    proposition_key: "cyber_threshold_significant_risk",
    citation: "11 CCR \u00a7 7120",
    subsection: "11 CCR \u00a7 7120(b)",
    verbatim_quote: "A business’s processing of consumers’ personal information presents\nsignificant risk to consumers’ security if any of the following is true:",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_threshold_gross_rev: R({
    proposition_key: "cyber_threshold_gross_rev",
    citation: "11 CCR \u00a7 7120",
    subsection: "11 CCR \u00a7 7120(b)(1)",
    verbatim_quote: "The business meets the threshold set forth in Civil Code section 1798.140,\nsubdivision (d)(1)(C), in the preceding calendar year; or",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_threshold_250k_or_50k_spi: R({
    proposition_key: "cyber_threshold_250k_or_50k_spi",
    citation: "11 CCR \u00a7 7120",
    subsection: "11 CCR \u00a7 7120(b)(2)",
    verbatim_quote: "The business meets the threshold set forth in Civil Code section 1798.140,\nsubdivision (d)(1)(A); and",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_first_audit_deadline: R({
    proposition_key: "cyber_first_audit_deadline",
    citation: "11 CCR \u00a7 7121",
    subsection: "11 CCR \u00a7 7121(a)",
    verbatim_quote: "A business must complete its first cybersecurity audit report no later than:",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_recurring_cadence: R({
    proposition_key: "cyber_recurring_cadence",
    citation: "11 CCR \u00a7 7121",
    subsection: "11 CCR \u00a7 7121(b)",
    verbatim_quote: "After April 1, 2030, if on January 1 of one year, a business meets the criteria of\nsection 7120 for the preceding year, the business must complete a\ncybersecurity audit that covers the next 12 months, and the business must\ncomplete its cybersecurity audit report for that period by April 1 of the\nfollowing year.",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_auditor_qualified_independent: R({
    proposition_key: "cyber_auditor_qualified_independent",
    citation: "11 CCR \u00a7 7122",
    subsection: "11 CCR \u00a7 7122(a)",
    verbatim_quote: "Every business required to complete a cybersecurity audit pursuant to this\nArticle must do so using a qualified, objective, independent professional\n(“auditor”) using procedures and standards accepted in the profession of\nauditing,",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_auditor_knowledge: R({
    proposition_key: "cyber_auditor_knowledge",
    citation: "11 CCR \u00a7 7122",
    subsection: "11 CCR \u00a7 7122(a)(1)",
    verbatim_quote: "To be qualified, an auditor must have knowledge of cybersecurity and how\nto audit a business’s cybersecurity program.",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_auditor_impartial: R({
    proposition_key: "cyber_auditor_impartial",
    citation: "11 CCR \u00a7 7122",
    subsection: "11 CCR \u00a7 7122(a)(2)",
    verbatim_quote: "The auditor may be internal or external to the business but must exercise\nobjective and impartial judgment on all issues within the scope of the\ncybersecurity audit,",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_internal_reporting_line: R({
    proposition_key: "cyber_internal_reporting_line",
    citation: "11 CCR \u00a7 7122",
    subsection: "11 CCR \u00a7 7122(a)(3)",
    verbatim_quote: "If a business uses an internal auditor, to maintain the auditor’s\nindependence, the highest-ranking auditor must report directly to a\nmember of the business’s executive management team who does not\nhave direct responsibility for the business’s cybersecurity program.",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_business_disclose: R({
    proposition_key: "cyber_business_disclose",
    citation: "11 CCR \u00a7 7122",
    subsection: "11 CCR \u00a7 7122(c)",
    verbatim_quote: "The business must make good-faith efforts to disclose to the auditor all facts\nrelevant to the cybersecurity audit and must not misrepresent any fact\nrelevant to the cybersecurity audit.",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_evidence_over_attestation: R({
    proposition_key: "cyber_evidence_over_attestation",
    citation: "11 CCR \u00a7 7122",
    subsection: "11 CCR \u00a7 7122(d)",
    verbatim_quote: "No finding of any cybersecurity audit may rely primarily on assertions or\nattestations by the business’s management.",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_report_to_exec: R({
    proposition_key: "cyber_report_to_exec",
    citation: "11 CCR \u00a7 7122",
    subsection: "11 CCR \u00a7 7122(f)",
    verbatim_quote: "The cybersecurity audit report must be provided to a member of the business’s\nexecutive management team who has direct responsibility for the business’s\ncybersecurity program.",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_retention_5yr: R({
    proposition_key: "cyber_retention_5yr",
    citation: "11 CCR \u00a7 7122",
    subsection: "11 CCR \u00a7 7122(g)",
    verbatim_quote: "The business and the auditor must retain all documents relevant to each\ncybersecurity audit for a minimum of five (5) years after completion of the\ncybersecurity audit.",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_scope_protects_pi: R({
    proposition_key: "cyber_scope_protects_pi",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(a)",
    verbatim_quote: "The cybersecurity audit must assess how the business’s cybersecurity\nprogram: protects personal information from unauthorized access, destruction,\nuse, modification, or disclosure; and protects against unauthorized activity\nresulting in the loss of availability of personal information.",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_scope_assess_program: R({
    proposition_key: "cyber_scope_assess_program",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(b)",
    verbatim_quote: "The cybersecurity audit must assess:",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_components_chapeau: R({
    proposition_key: "cyber_components_chapeau",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)",
    verbatim_quote: "The cybersecurity audit must assess the following components, if applicable:",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c1_authentication: R({
    proposition_key: "cyber_c1_authentication",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(1)",
    verbatim_quote: "Authentication, including:",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c2_encryption: R({
    proposition_key: "cyber_c2_encryption",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(2)",
    verbatim_quote: "Encryption of personal information, at rest and in transit.",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c3_access_controls: R({
    proposition_key: "cyber_c3_access_controls",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(3)",
    verbatim_quote: "Account management and access controls, including:",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c4_inventory: R({
    proposition_key: "cyber_c4_inventory",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(4)",
    verbatim_quote: "Inventory and management of personal information and the business’s\ninformation system, including:",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c5_secure_config: R({
    proposition_key: "cyber_c5_secure_config",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(5)",
    verbatim_quote: "Secure configuration of hardware and software, including:",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c6_vuln_pentest: R({
    proposition_key: "cyber_c6_vuln_pentest",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(6)",
    verbatim_quote: "Internal and external vulnerability scans, penetration testing, and\nvulnerability disclosure and reporting",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c7_audit_logs: R({
    proposition_key: "cyber_c7_audit_logs",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(7)",
    verbatim_quote: "Audit-log management, including the centralized storage, retention, and\nmonitoring of logs.",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c8_network_monitoring: R({
    proposition_key: "cyber_c8_network_monitoring",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(8)",
    verbatim_quote: "Network monitoring and defenses, including the deployment of:",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c9_antivirus: R({
    proposition_key: "cyber_c9_antivirus",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(9)",
    verbatim_quote: "Antivirus and antimalware protections.",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c10_segmentation: R({
    proposition_key: "cyber_c10_segmentation",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(10)",
    verbatim_quote: "Segmentation of an information system",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c11_ports: R({
    proposition_key: "cyber_c11_ports",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(11)",
    verbatim_quote: "Limitation and control of ports, services, and protocols.",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c12_awareness: R({
    proposition_key: "cyber_c12_awareness",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(12)",
    verbatim_quote: "Cybersecurity awareness, including how the business maintains current\nknowledge of changing cybersecurity threats and countermeasures.",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c13_training: R({
    proposition_key: "cyber_c13_training",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(13)",
    verbatim_quote: "Cybersecurity education and training, including training for each\nemployee, independent contractor, and any other personnel to whom the\nbusiness provides access to its information system",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c14_secure_dev: R({
    proposition_key: "cyber_c14_secure_dev",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(14)",
    verbatim_quote: "Secure development and coding best practices, including code-reviews\nand testing.",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c15_third_party_oversight: R({
    proposition_key: "cyber_c15_third_party_oversight",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(15)",
    verbatim_quote: "Oversight of service providers, contractors, and third parties to ensure\ncompliance with sections 7051 and 7053.",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c16_retention_disposal: R({
    proposition_key: "cyber_c16_retention_disposal",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(16)",
    verbatim_quote: "Retention schedules and proper disposal of personal information no\nlonger required to be retained,",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c17_incident_response: R({
    proposition_key: "cyber_c17_incident_response",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(17)",
    verbatim_quote: "How the business manages its responses to security incidents (i.e., its\nincident response management).",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_c18_bcdr: R({
    proposition_key: "cyber_c18_bcdr",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(c)(18)",
    verbatim_quote: "Business-continuity and disaster-recovery plans, including data-recovery\ncapabilities and backups.",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_scope_additional_components: R({
    proposition_key: "cyber_scope_additional_components",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(d)",
    verbatim_quote: "Nothing in this section prohibits a cybersecurity audit from assessing\ncomponents of a cybersecurity program that are not set forth in subsections\n(b) or (c).",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_report_contents_chapeau: R({
    proposition_key: "cyber_report_contents_chapeau",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(e)",
    verbatim_quote: "The cybersecurity audit report must:",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_report_gaps: R({
    proposition_key: "cyber_report_gaps",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(e)(3)",
    verbatim_quote: "Identify and describe in detail the status of any gaps or weaknesses of the\npolicies and procedures in subsection (b)(1), the applicable components in\nsubsection (c), and any additional component assessed in accordance with\nsubsection (d),",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_report_signed_attestation: R({
    proposition_key: "cyber_report_signed_attestation",
    citation: "11 CCR \u00a7 7123",
    subsection: "11 CCR \u00a7 7123(e)(8)",
    verbatim_quote: "Include a statement that is signed and dated by the highest-ranking\nauditor that certifies that they completed an independent review of the\nbusiness’s cybersecurity program and information system,",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_cert_required: R({
    proposition_key: "cyber_cert_required",
    citation: "11 CCR \u00a7 7124",
    subsection: "11 CCR \u00a7 7124(a)",
    verbatim_quote: "Each calendar year that a business is required to complete a cybersecurity\naudit pursuant to this Article, it must submit to the Agency a written\ncertification that the business completed the cybersecurity audit as required\nby this Article.",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_cert_by_april1: R({
    proposition_key: "cyber_cert_by_april1",
    citation: "11 CCR \u00a7 7124",
    subsection: "11 CCR \u00a7 7124(b)",
    verbatim_quote: "The business must submit the certification no later than April 1 following any\nyear that the business is required to complete a cybersecurity audit.",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_cert_by_exec: R({
    proposition_key: "cyber_cert_by_exec",
    citation: "11 CCR \u00a7 7124",
    subsection: "11 CCR \u00a7 7124(c)",
    verbatim_quote: "The written certification must be completed by a member of the business’s\nexecutive management team who:",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_cert_portal_and_attest: R({
    proposition_key: "cyber_cert_portal_and_attest",
    citation: "11 CCR \u00a7 7124",
    subsection: "11 CCR \u00a7 7124(d)",
    verbatim_quote: "The written certification must be completed and submitted to the Agency via\nits website at https://cppa.ca.gov/.",
    depth_class: "subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
  cyber_cert_attestation_text: R({
    proposition_key: "cyber_cert_attestation_text",
    citation: "11 CCR \u00a7 7124",
    subsection: "11 CCR \u00a7 7124(d)(4)",
    verbatim_quote: "I attest\nthat I meet the requirements of California Code of Regulations, Title 11,\nsection 7124, subsection (c), to submit this certification.",
    depth_class: "sub_subsection",
    governing_anchor: ART9,
    verified_on: VOD,
    primary_source_url: CCR_URL,
  }),
};

export const CYBER_VERIFIED_AUTHORITY_ROWS: VerifiedAuthorityRow[] =
  Object.values(CYBER_VERIFIED_AUTHORITIES);
