// COACHING CONTENT RULE — coaching describes the SHAPE of a complete answer
// (dimensions, specificity, separateness). It NEVER describes the CONTENT of a
// compliant answer (what facts satisfy the law, what answer "passes").
// goodAnswer examples are clearly fictional and illustrate FORM, never a template.
// Voice: imperative, active, plain subject-verb-object, one idea per sentence,
// specific over vague, no ornamental legalese. Layered: coachLead = one line an
// expert acts on instantly; goodAnswer/commonMistake = the expansion for newer users.
// ENUMERATED-FIELD ADDENDUM — for selects, radios, and pills, coaching explains
// WHAT FACTS DETERMINE the accurate choice and WHAT EVIDENCE to check. It never
// recommends an option, never suggests claiming an exemption, and never implies
// which selection is favourable. goodAnswer shows a FICTIONAL determination —
// facts mapped to a selection — illustrating method, not a preferred outcome.

// src/components/cppa/CPPACyberRailEntries.ts
// StatuteRail entries for the CPPA Cybersecurity Audit Readiness tool (Module 2).
//
// GENERATED — do not hand-edit `regulationText`. Every regulationText below is a
// BYTE-EXACT contiguous substring of the approved `public.provision_texts`
// corpus excerpt for the cited provision (cppa-7120 / cppa-7122 / cppa-7123 /
// cppa-7124), after the resolver's normalization, EXCEPT where a field's
// regulationText is explicitly labelled as a summary because the cited
// provision (typically a Civil Code definition or the CPPA CPI-adjustment
// notice) is not verbatim in the verified corpus. Regenerate verbatim entries
// with `npx tsx scripts/item371/gen-cyber-rail.ts`; the pin is enforced by
// src/registry/__tests__/cyber-rail-corpus-pin.test.ts.

import type { RailEntry } from "@/components/intake/StatuteRail";

const CPPA_URL = "https://cppa.ca.gov/regulations/pdf/ccpa_updates_cyber_risk_admt_appr_text.pdf";
const CPI_ADJUSTMENT_URL = "https://www.cppa.ca.gov/regulations/cpi_adjustment.html";

export const CPPA_CYBER_RAIL: Record<string, RailEntry> = {
  entity_name: {
    fieldLabel: "Entity name",
    citation: "11 CCR § 7124(d)(1)",
    citationUrl: CPPA_URL,
    plainSummary: "The annual certification submitted to the Agency carries the business's name and a point of contact. The name recorded here is the one the readiness report and any downstream certification will carry; entering it does not by itself establish that a cybersecurity audit is legally required for this entity.",
    regulationText: "The business's name and point of contact for the business, including the contact's name, phone number, and email address.",
    coachLead: "Give the registered legal entity being assessed, including its legal suffix, not the trading brand.",
    coachBody: "The name matches the entity whose systems and processing are actually in scope for this readiness review. Where a group files separately, name the subsidiary under assessment rather than the parent.",
    goodAnswer: "A retail group whose California operations sit in a separate incorporated subsidiary, Larkspur Home Co., Inc., records that subsidiary's registered name, with the consumer-facing brand noted nowhere in this field.",
    commonMistake: "Recording the marketing brand instead of the registered legal name. The report identifies the filer at the entity level, so a brand name leaves that identity ambiguous.",
  },
  profile_industry: {
    fieldLabel: "Industry sector",
    citation: "11 CCR § 7123(b)(1)",
    citationUrl: CPPA_URL,
    plainSummary: "The audit assesses the cybersecurity program against the business's size and complexity and the nature and scope of its processing activities. Sector is the shorthand that carries that context into every component finding.",
    regulationText: "The business's establishment, implementation, and maintenance of its cybersecurity program, including the related written documentation thereof (e.g., policies and procedures), that is appropriate to the business's size and complexity and the nature and scope of its processing activities, taking into account the state of the art and cost of implementing the components of a cybersecurity program",
    coachLead: "Name the sector of the operations actually under audit, not the corporate group's sector.",
    coachBody: "Sector sets the threat context the component findings are weighed against. Where the assessed scope spans several business lines, name each one and explain the boundary in Audit scope rationale.",
    goodAnswer: "A healthcare-services subsidiary owned by a private-equity firm records healthcare, because the systems in scope are the clinical-scheduling platform rather than the parent's finance stack.",
    commonMistake: "Recording the parent's sector. That pulls the wrong threat context into all eighteen component findings.",
  },
  incidents_12mo: {
    fieldLabel: "Reportable security incidents in last 12 months",
    citation: "11 CCR § 7123(c)(17)",
    citationUrl: CPPA_URL,
    plainSummary: "The audit expressly reaches security incidents that occurred during the audit period, including how they were handled and any notifications made. The count recorded here follows the regulatory definition in 11 CCR § 7123(c)(17)(A) — not a notification threshold — and an honest \"Unknown / not yet reviewed\" is a valid answer when the register has not yet been checked against that definition.",
    regulationText: "How the business manages its responses to security incidents (i.e., its incident response management). (A) For the purposes of subsection (17), \"security incident\" means an occurrence that actually or imminently jeopardizes the confidentiality, integrity, or availability of the business's information system or the personal information the system processes, stores, or transmits, or that constitutes a violation or imminent threat of violation of the business's cybersecurity program; unauthorized access, destruction, use, modification, or disclosure of personal information; or unauthorized activity resulting in the loss of availability of personal information is a security incident. (B) The business's incident response management includes: (i) The business's documentation of predetermined instructions or procedures to detect, respond to, limit the consequences of, and recover from malicious attacks against its information system (i.e., the business's incident response plan); and (ii) How the business tests its incident-response capabilities; and",
    coachLead: "Count every incident that meets the § 7123(c)(17)(A) definition, not the ones that crossed a notification threshold.",
    coachBody: "Check the incident register against that definition — actual or imminent jeopardy to the system or the personal information it holds, or a violation or imminent threat of violation of the cybersecurity program — and count each qualifying incident once. Choose Unknown / not yet reviewed where the register has not been checked against that definition, rather than guessing at a number.",
    goodAnswer: "Meridian Data Co. checks eleven raised tickets against the § 7123(c)(17)(A) definition and finds four that qualify, including two that never crossed its internal notification threshold; it records four.",
    commonMistake: "Counting only the incidents that triggered a notification. § 7123(c)(17)(A) defines a security incident on its own terms, independent of whether any notification duty was triggered.",
  },
  framework: {
    fieldLabel: "Primary security framework in use",
    citation: "11 CCR § 7123(f)",
    citationUrl: CPPA_URL,
    plainSummary: "A business may leverage an audit, assessment, or evaluation prepared for another purpose toward this Article's requirement, provided it meets every element alone or with supplementation. The primary framework recorded here is the baseline the assessment measures supplementation against.",
    regulationText: "A business may utilize a cybersecurity audit, assessment, or evaluation that it has prepared for another purpose, provided that it meets all of the requirements of this Article, either on its own or through supplementation. For example, a business may have engaged in an audit that uses the National Institute of Standards and Technology Cybersecurity Framework 2.0 and meets all of the requirements of this Article.",
    coachLead: "Name the framework the programme is actually operated against day to day.",
    coachBody: "This is the framework that governs control design, not the one the business aspires to, and it is separate from any completed audit or assessment named under Frameworks in scope below. Where controls run informally against no published framework, that is the accurate answer; if the choice is Other, name it in Audit scope rationale.",
    goodAnswer: "A logistics operator maintains an ISO 27001 statement of applicability that drives its control set, while an unfinished NIST CSF mapping sits in a spreadsheet; it records ISO 27001 as primary.",
    commonMistake: "Naming the framework a certification project is heading towards. § 7123(f) leverage turns on work already prepared, so an in-flight programme yields no evidence to supplement.",
  },
  profile_audit: {
    fieldLabel: "Last independent security audit",
    citation: "11 CCR § 7122(a)",
    citationUrl: CPPA_URL,
    plainSummary: "The audit must be performed by a qualified, objective, independent professional using procedures and standards accepted in the profession of auditing. Only work meeting that full test — not independence alone — counts as an independent audit for this field.",
    regulationText: "Every business required to complete a cybersecurity audit pursuant to this Article must do so using a qualified, objective, independent professional (\"auditor\") using procedures and standards accepted in the profession of auditing, such as procedures and standards provided or adopted by the American Institute of Certified Public Accountants, the Public Company Accountability Oversight Board, the Information Systems Audit and Control Association, or the International Organization for Standardization.",
    enforcementNote: "The § 7124 certification is signed under penalty of perjury by an executive who meets § 7124(c), and includes an attestation that the business made no attempt to influence the auditor's decisions or assessments.",
    coachLead: "Pick the time band that matches the completion date of the most recent independent audit, not an exact date.",
    coachBody: "The qualifying test covers knowledge of cybersecurity auditing, objectivity, independence, and accepted procedures and standards together, not independence on its own. Record the exact completion date, scope, and the auditor's relationship to the program in Prior audit scope.",
    goodAnswer: "A firm whose own security team runs quarterly internal reviews last engaged an outside audit firm fourteen months ago; it selects 12–24 months ago and records the exact date and the firm's name in Prior audit scope.",
    commonMistake: "Treating independence as the entire qualifying test. § 7122(a) also calls for knowledge of cybersecurity auditing and accepted procedures and standards, not independence by itself.",
  },
  in_scope_frameworks: {
    fieldLabel: "Frameworks in scope for this audit",
    citation: "11 CCR § 7123(f)",
    citationUrl: CPPA_URL,
    plainSummary: "A business may utilise a cybersecurity audit, assessment, or evaluation it prepared for another purpose toward the § 7123 requirement — provided the prior work meets every element of this Article, alone or through supplementation. The frameworks recorded here name what the assessment treats as available for that leverage.",
    regulationText: "A business may utilize a cybersecurity audit, assessment, or evaluation that it has prepared for another purpose, provided that it meets all of the requirements of this Article, either on its own or through supplementation. For example, a business may have engaged in an audit that uses the National Institute of Standards and Technology Cybersecurity Framework 2.0 and meets all of the requirements of this Article.",
    coachLead: "Confirm any framework carried over from your primary-framework answer; do not leave a suggested selection unexamined.",
    coachBody: "Select only frameworks with an actual report, letter, or set of workpapers behind them. Choose \"No prior framework work to rely on\" when nothing exists to lean on, and keep \"None / informal\" for informal practice, which can still coexist with a named framework's evidence.",
    goodAnswer: "Thornfield Logistics confirms SOC 2 because a current report exists, removes a carried-over NIST CSF suggestion because no assessed work backs it, and leaves the rest blank.",
    commonMistake: "Accepting a carried-over suggestion without checking for supporting work behind it. § 7123(f) leverage depends on work that was actually done, not on which framework the program happens to run on.",
  },
  audit_scope_rationale: {
    fieldLabel: "Audit scope rationale",
    citation: "11 CCR § 7123(b)",
    citationUrl: CPPA_URL,
    plainSummary: "The audit must assess the programme's establishment, implementation, and maintenance as appropriate to the business's size and complexity, each applicable component in subsection (c), and how compliance with the programme is implemented and enforced. The rationale recorded here is what the scope memo carries forward.",
    regulationText: "The cybersecurity audit must assess: (1) The business's establishment, implementation, and maintenance of its cybersecurity program, including the related written documentation thereof (e.g., policies and procedures), that is appropriate to the business's size and complexity and the nature and scope of its processing activities, taking into account the state of the art and cost of implementing the components of a cybersecurity program; and (2) Each of the components of a cybersecurity program listed in subsection (c) that the auditor deems applicable to the business's information system. (3) How the business implements and enforces compliance with its cybersecurity program as described in subsection (b)(1), the applicable components in subsection (c), and any additional components as set forth in subsection (d).",
    coachLead: "Give three things: what is in scope, what is out and why, and what any prior audit is supplemented with.",
    coachBody: "Name systems and processing activities rather than departments, and state the specific fact that removes any excluded system from scope rather than a category label standing in for that fact. Where a prior framework audit is leveraged under § 7123(f), name the components the supplementation covers individually.",
    goodAnswer: "Brightwell Fitness writes: in scope, the customer-facing mobile application and its cloud backend; out of scope, the internal expense-reporting tool, because a system-level review confirmed it holds no consumer personal information; leveraging the 2026 SOC 2 Type II report and supplementing for retention and segmentation, which that report does not test directly.",
    commonMistake: "Writing 'company-wide' and stopping, or naming a department's usual function as if that alone explained an exclusion. A boundary claim is not a scope memo without the specific fact behind each exclusion and each supplementation.",
  },
  auditor_engagement_status: {
    fieldLabel: "Auditor engagement status",
    citation: "11 CCR § 7122(a)(2)",
    citationUrl: CPPA_URL,
    plainSummary: "The auditor may be internal or external but must exercise objective and impartial judgment, must be free from influence by the business, and must not participate in activities the audit may assess — including writing procedures, preparing documents, making programme recommendations, or implementing the programme.",
    regulationText: "The auditor may be internal or external to the business but must exercise objective and impartial judgment on all issues within the scope of the cybersecurity audit, must be free to make decisions and assessments without influence by the business being audited, including the business's owners, managers, or employees; and must not participate in activities that may compromise the auditor's independence. For example, the auditor must not participate in business activities that the auditor may assess in the current or subsequent cybersecurity audits, including developing procedures, preparing the business's documents, making recommendations regarding the business's cybersecurity program (separate from articulating audit findings), or implementing or maintaining the business's cybersecurity program.",
    enforcementNote: "Where an internal auditor is used, § 7122(a)(3) additionally requires the highest-ranking auditor to report to an executive without direct responsibility for the cybersecurity programme, who also sets that auditor's evaluation and compensation.",
    coachLead: "Describe the auditor's relationship to the programme, not their competence.",
    coachBody: "The determining facts are who employs the auditor, whether they have built or maintained any part of the programme, and — if internal — who they report to and who sets their compensation. Where a written-independence option is selected, confirm that the underlying confirmation actually exists rather than assuming external status alone establishes it.",
    goodAnswer: "A manufacturer's internal audit lead has never authored a security procedure and reports to the general counsel rather than to the Chief Information Security Officer who runs the program; the facts recorded reflect an internal auditor with a reporting line outside the program.",
    commonMistake: "Treating a well-credentialed consultant as independent when the same firm wrote the policies. Participation in the work under review is what § 7122(a)(2) disqualifies, not the auditor's credentials.",
  },
  prior_audit_scope: {
    fieldLabel: "Prior audit scope",
    citation: "11 CCR § 7122(g)",
    citationUrl: CPPA_URL,
    plainSummary: "The business and the auditor must retain all documents relevant to each cybersecurity audit for at least five years after completion. What the last audit covered, and whether its record survives, determines how much of it can be leveraged now.",
    regulationText: "The business and the auditor must retain all documents relevant to each cybersecurity audit for a minimum of five (5) years after completion of the cybersecurity audit.",
    coachLead: "Say what the last audit covered, when, and where its papers live now.",
    coachBody: "Period, scope boundary, and the location of the report and workpapers are three separate facts. Where the papers are gone or were never held, saying so is more useful than an optimistic description of coverage.",
    goodAnswer: "A distributor records a FY2025 SOC 2 Type II over the production systems, with report, sampling worksheets, and management letter held in the governance system, and notes that the 2022 penetration-test workpapers were lost in a vendor transition.",
    commonMistake: "Assuming every past audit of any kind falls under this five-year duty. § 7122(g) reaches documents relevant to a cybersecurity audit conducted under this Article, not an unrelated historical review.",
  },
  // DOC 263 (2026-09-16) — the seven profile keys F01 found with no rail entry
  // (q1_revenue, q2_consumers, q5_sell_share, q5c_share_revenue_50pct,
  // q15_sensitive_pi, q15c_spi_volume, remediation_owner), plus the revenue
  // threshold follow-up question the F06/F07 fix introduces.
  q1_revenue: {
    fieldLabel: "Annual gross revenue",
    citation: "Cal. Civ. Code § 1798.140(d)(1)(A); 11 CCR § 7120(b)(2)",
    citationUrl: CPPA_URL,
    plainSummary: "One basis for the cybersecurity-audit duty turns on a business's annual worldwide gross revenue measured against a dollar threshold in Civil Code § 1798.140(d)(1)(A) that the Agency adjusts for inflation every odd-numbered year. The Under $25M / $25M to under $50M / $50M to $100M / Over $100M band on its own cannot resolve which side of that adjusted threshold a business in the middle band sits on, which is why a follow-up question checks the dated figure directly.",
    regulationText: "Summary of Cal. Civ. Code § 1798.140(d)(1)(A) (verbatim text is not in the verified corpus): the subdivision sets an annual worldwide gross revenue figure, adjusted for inflation by the Agency every odd-numbered year, that determines this basis for the cybersecurity-audit duty. 11 CCR § 7120(b)(2) is quoted verbatim from the approved text: The business meets the threshold set forth in Civil Code section 1798.140, subdivision (d)(1)(A); and",
    coachLead: "Use total worldwide gross revenue for the calendar year this question names, not a general sense of company size.",
    coachBody: "Check the approved financial records for that year rather than estimating. Where the figure sits inside a band that straddles the adjusted threshold, leave applicability unresolved instead of assuming either side.",
    goodAnswer: "Larkspur Home Co. pulls its audited financial statements and records $41 million in total worldwide gross revenue for the named calendar year, before selecting the matching band.",
    commonMistake: "Estimating from California sales alone. The revenue figure covers all worldwide gross revenue, not the portion earned in California.",
  },
  q1_revenue_threshold_check: {
    fieldLabel: "Revenue above the adjusted CCPA threshold",
    citation: "Cal. Civ. Code § 1798.140(d)(1)(A); CPPA CPI Adjustment Notice",
    citationUrl: CPI_ADJUSTMENT_URL,
    plainSummary: "The revenue band above may straddle the adjusted threshold in Civil Code § 1798.140(d)(1)(A). This question checks the dated dollar figure directly against the named calendar year's financial records so the band's breadth does not stand in for an actual determination.",
    regulationText: "Summary of Cal. Civ. Code § 1798.140(d)(1)(A) and the CPPA's Consumer Price Index adjustment (verbatim text is not in the verified corpus): the Civil Code sets the annual gross revenue threshold for this prong, and the Agency adjusts that dollar figure for inflation every odd-numbered year. The figure effective January 1, 2025 is $26,625,000, per the Agency's published CPI adjustment notice; a later odd-numbered-year adjustment can change it.",
    coachLead: "Compare the named calendar year's revenue to the adjusted dollar figure for that year, using approved financial records.",
    coachBody: "The threshold changes at each odd-numbered-year adjustment, so use the figure that was in effect for the year this question names. Select Unsure where the figure has not been checked against financial records rather than guessing.",
    goodAnswer: "Larkspur Home Co. checks its audited financials against the adjusted figure published for the named year and confirms its revenue was below it, so it selects No.",
    commonMistake: "Answering from the revenue band selected earlier. That band spans the adjusted threshold, so it cannot by itself answer whether revenue was above or below the dated figure.",
  },
  q2_consumers: {
    fieldLabel: "California consumers' personal information processed annually",
    citation: "11 CCR § 7120(b)(2)(A)",
    citationUrl: CPPA_URL,
    plainSummary: "11 CCR § 7120(b)(2)(A) sets 250,000 consumers or households processed in the preceding calendar year as one of two population thresholds that, combined with the Civil Code § 1798.140(d)(1)(A) revenue threshold, can trigger the cybersecurity-audit duty. The household route and the consumer route are separate ways to reach that number, so each distinct person should be counted once regardless of how many systems hold a record of them.",
    regulationText: "Processed the personal information of 250,000 or more consumers or households in the preceding calendar year; or",
    coachLead: "Count distinct California residents once, and treat the household route as separate from the consumer route.",
    coachBody: "Reconcile the systems that hold personal information and remove duplicates before comparing the total against the bands. Where the estimate rests on households rather than individual consumers, say so rather than folding the two counts together.",
    goodAnswer: "Cascade Outfitters reconciles its order system and its loyalty program, finds 180,000 distinct purchasers and 90,000 account holders with 50,000 people in both groups, and records 220,000 distinct people for the consumer route.",
    commonMistake: "Adding the household count to the individual-consumer count as if they were the same population. § 7120(b)(2)(A) treats consumers and households as separate routes to the same threshold.",
  },
  q5_sell_share: {
    fieldLabel: "Sale or sharing of personal information for cross-context behavioral advertising",
    citation: "Cal. Civ. Code § 1798.140(ah), (ai)",
    citationUrl: CPPA_URL,
    plainSummary: "Whether the business sells or shares personal information determines whether the revenue-share question below is asked, and it feeds the definitions the audit report needs to describe accurately. \"Sell\" and \"share\" carry the specific meanings set out in Civil Code § 1798.140(ah) and (ai), which reach more activity than a plain-language reading of either word suggests.",
    regulationText: "Summary of Cal. Civ. Code § 1798.140(ah) and (ai) (verbatim text is not in the verified corpus): subdivision (ah) defines selling, sale, and sold broadly, covering a disclosure of personal information to a third party for monetary or other valuable consideration, without an advertising purpose being necessary; subdivision (ai) defines sharing as a disclosure of personal information to a third party for cross-context behavioral advertising, whether or not for consideration.",
    coachLead: "Trace what is actually disclosed, to whom, and for what, rather than relying on a vendor contract's label.",
    coachBody: "A sale under § 1798.140(ah) can happen without cash changing hands and without any advertising purpose; sharing under § 1798.140(ai) is specifically about cross-context behavioral advertising. Check disclosures made through vendors as well as those the business makes directly.",
    goodAnswer: "Brightwell Fitness finds that its app sends device identifiers to an ad-measurement partner for cross-context behavioral advertising and separately provides a mailing list to a printing vendor for consideration; it records both selling and sharing.",
    commonMistake: "Assuming no sale occurred because no cash was exchanged. Consideration under § 1798.140(ah) includes non-monetary value, so a barter or service exchange can still be a sale.",
  },
  q5c_share_revenue_50pct: {
    fieldLabel: "50% or more of revenue from selling or sharing personal information",
    citation: "Cal. Civ. Code § 1798.140(d)(1)(C); 11 CCR § 7120(b)(1)",
    citationUrl: CPPA_URL,
    plainSummary: "11 CCR § 7120(b)(1) makes the Civil Code § 1798.140(d)(1)(C) revenue-share threshold — 50% or more of annual gross revenue from selling or sharing personal information — an independent basis for the cybersecurity-audit duty, separate from the population-based thresholds in § 7120(b)(2). The percentage is calculated from the same period's total revenue, not from whether any selling or sharing activity exists at all.",
    regulationText: "The business meets the threshold set forth in Civil Code section 1798.140, subdivision (d)(1)(C), in the preceding calendar year; or",
    coachLead: "Compare the same period's numerator and denominator before answering.",
    coachBody: "Use revenue from selling or sharing personal information as the numerator and total annual gross revenue as the denominator, both from the same period. Selling or sharing personal information at all does not by itself clear this percentage.",
    goodAnswer: "Meridian Data Co. finds $6 million in revenue from selling and sharing personal information against $10 million in total annual gross revenue for the same year — 60% — and selects Yes.",
    commonMistake: "Selecting Yes merely because the business sells or shares personal information. The question is a percentage of total revenue for a stated period, not a yes/no about the underlying activity.",
  },
  q15_sensitive_pi: {
    fieldLabel: "Processing of sensitive personal information",
    citation: "Cal. Civ. Code § 1798.140(ae)",
    citationUrl: CPPA_URL,
    plainSummary: "Whether the business processes sensitive personal information determines whether the volume question below is asked, and it feeds one of the population thresholds in 11 CCR § 7120(b)(2)(B). Civil Code § 1798.140(ae) defines the category through a list broader than the handful of examples usually mentioned.",
    regulationText: "Summary of Cal. Civ. Code § 1798.140(ae) (verbatim text is not in the verified corpus): the subdivision defines sensitive personal information through a list of categories — including government identifiers, account log-in credentials in combination with access credentials, precise geolocation, racial or ethnic origin, religious or philosophical beliefs, union membership, the contents of certain mail, email, and text messages, genetic data, biometric information used for unique identification, health information, and information concerning sex life or sexual orientation — together with qualifications on when each category applies.",
    coachLead: "Check the full statutory list of categories against the actual data elements the business holds, not a short set of examples.",
    coachBody: "Review the data inventory category by category rather than relying on impressions of what the business collects. Where that review has not been completed, record the answer as unresolved rather than selecting No.",
    goodAnswer: "Fernbrook Clinics reviews its intake forms against the statutory categories and finds patient health records and precise appointment-location data, so it records Yes.",
    commonMistake: "Treating the three examples shown on the page as the entire list. § 1798.140(ae) names a longer set of categories, several of which carry their own qualifying conditions.",
  },
  q15c_spi_volume: {
    fieldLabel: "California consumers with sensitive personal information processed annually",
    citation: "11 CCR § 7120(b)(2)(B)",
    citationUrl: CPPA_URL,
    plainSummary: "11 CCR § 7120(b)(2)(B) sets 50,000 consumers whose sensitive personal information is processed in the preceding calendar year as one of the two population thresholds that, combined with the Civil Code § 1798.140(d)(1)(A) revenue threshold, can trigger the cybersecurity-audit duty. This population is counted separately from the all-processing consumer count above it.",
    regulationText: "Processed the sensitive personal information of 50,000 or more consumers in the preceding calendar year.",
    coachLead: "Count distinct people across every sensitive-information category, not records or fields.",
    coachBody: "Reconcile the systems and categories that hold sensitive personal information and remove duplicates before comparing the total to the bands. This population is separate from the all-processing consumer count above it.",
    goodAnswer: "Fernbrook Clinics finds 30,000 people with health records and 25,000 with precise-location records, with 10,000 people in both groups, for 45,000 distinct people, and selects Fewer than 50,000.",
    commonMistake: "Counting each sensitive-information field or record separately. The threshold turns on the number of distinct people, not the volume of data held about them.",
  },
  remediation_owner: {
    fieldLabel: "Remediation owner",
    citation: "Product readiness field (no statutory citation)",
    plainSummary: "Findings from this readiness assessment need someone to track them to closure. Naming that person or role here does not itself satisfy any provision of the audit regulations; it is a project-management fact the report carries alongside the legal findings.",
    regulationText: "This question has no statutory basis of its own; it records who coordinates remediation of the readiness findings.",
    coachLead: "Name the person or role who coordinates closing the findings, separate from who fixes each one.",
    coachBody: "Where responsibility is shared, name the coordinator and describe how individual findings are assigned rather than inventing a single owner. Leave the field blank if no one has been assigned yet.",
    goodAnswer: "Thornfield Logistics names its Director of Security Engineering as the coordinator of the remediation plan, with each finding assigned its own accountable owner in the tracking system.",
    commonMistake: "Naming a department instead of a person or role. A coordinator needs to be identifiable, not a general team name.",
  },
  c1_auth: {
    fieldLabel: "C1: Authentication",
    citation: "11 CCR § 7123(c)(1)",
    citationUrl: CPPA_URL,
    plainSummary: "Authentication of users seeking access to personal information, including multi-factor authentication (MFA), phishing-resistant MFA for employees and contractors, and strong password practices. The password element applies only if the business actually uses passwords.",
    regulationText: "Authentication, including: (A) Multi-factor authentication (including multi-factor authentication that is resistant to phishing attacks for employees, independent contractors, and any other personnel, service providers, and contractors); and (B) If the business uses passwords or passphrases, strong unique passwords or passphrases (e.g., passwords that are at least eight characters in length, not on the business's disallowed list of commonly used passwords, and not reused).",
    enforcementNote: "Authentication failures — weak or missing MFA, shared credentials, excessive access — appear in the majority of breach enforcement actions in the corpus.",
    coachLead: "Name the authentication factors, who they cover, and which records back each claim.",
    coachBody: "Separate the MFA method from the population it reaches, state whether it resists phishing, and note password rules where passwords remain, keeping any planned rollout out of the current rating. Match each fact to a record you can produce today — a policy, a configuration export, or a sample sign-in log — with its date and coverage, and leave the evidence checklist blank rather than guessing at what exists.",
    goodAnswer: "Thornfield Freight records: hardware-key MFA for the 40 administrators, app-push MFA for the 900 office staff, SMS fallback still live on the legacy warehouse portal, password rules enforced by the directory but not by that portal, a current configuration export and a sampled sign-in log on file, and no training-completion record for the fallback method.",
    commonMistake: "Reporting 'MFA enabled' as one fact. The component asks separately about phishing resistance and about passwords, so one undifferentiated claim leaves both untested.",
  },
  c2_encryption: {
    fieldLabel: "C2: Encryption of personal information",
    citation: "11 CCR § 7123(c)(2)",
    citationUrl: CPPA_URL,
    plainSummary: "Encryption of personal information both at rest and in transit. The Agency declined to mandate a specific encryption standard, preserving flexibility across business types and scenarios.",
    regulationText: "Encryption of personal information, at rest and in transit.",
    coachLead: "State at-rest and in-transit encryption separately, each with its coverage and its exceptions.",
    coachBody: "Name the mechanism, the systems it covers, and any stores or channels it does not reach yet, for each state, keeping planned rollouts separate from what is active today. Match each claim to a record on file — a configuration export, an architecture diagram, or a scan report — noting its date, and leave the checklist blank where availability has not been checked.",
    goodAnswer: "Sandhill Marketplace records: at rest, disk and column encryption across the primary databases and object storage, excluding an on-premises reporting replica; in transit, TLS 1.2+ on all external endpoints, with two internal batch transfers still unencrypted; it has a current configuration export for the primary databases on file and none yet for the reporting replica.",
    commonMistake: "Answering 'everything is encrypted.' Without the two states named and the exceptions listed, the auditor cannot distinguish full coverage from partial coverage.",
  },
  c3_account_access: {
    fieldLabel: "C3: Account management and access controls",
    citation: "11 CCR § 7123(c)(3)",
    citationUrl: CPPA_URL,
    plainSummary: "Least-privilege access, limiting and monitoring privileged accounts, restricting access to personal information to those who need it, and restricting physical access to personal information. The final regulations expanded scope to account- and application-level configuration.",
    regulationText: "Account management and access controls, including: (A) Restricting each person's, account's, or application's privileges and access to personal information to what is necessary for that person, account, or application to perform their duties. For example: (i) If the person is an employee, independent contractor, or any other personnel, restricting their privileges and access to personal information to what is necessary to perform the respective job functions of each individual, and revoking their privileges and access when their job functions no longer require them, including when their employment or contract is terminated; (ii) If the person is a service provider or contractor, restricting their privileges and access to personal information to what is necessary for the specific business purpose(s) set forth in, and in compliance with, the written contract between the business and the service provider or contractor required by the CCPA and section 7051; and (iii) Restricting the privileges and access of third parties to whom the business sells or shares personal information to the personal information that is necessary for the limited and specified purpose(s) set forth within the contract between the business and the third party required by the CCPA and section 7053. (B) Restricting the number of privileged accounts, restricting those privileged accounts' access functions to only those necessary to perform the account-holder's job, restricting the use of privileged accounts to when they are necessary to perform functions, and using a privileged-access management solution (e.g., to ensure just-in-time temporary assignment of privileged access). (C) Restricting and monitoring the creation of new accounts for employees, independent contractors, or other personnel; service providers or contractors; and privileged accounts, and ensuring that the accounts' access and privileges are limited as set forth in subsections (c)(3)(A) and (B). (D) Restricting and monitoring physical access to personal information (e.g., through the use of badges, secure physical file locations, and enforcement of clean-desk policies).",
    coachLead: "Cover four things: least privilege, privileged accounts, account creation, and physical access — each with its supporting records.",
    coachBody: "Name how privileges are scoped and revoked, how privileged accounts are limited and monitored, how new accounts are approved, and how physical access to personal information is restricted, keeping planned changes separate from what runs today. Match each of the four to a record such as an access-review report, a privileged-account log, or a badge-access policy, with its date and coverage, and leave a limb's evidence blank rather than assuming it exists.",
    goodAnswer: "Fernbrook Clinics records: role-based access reviewed quarterly, 12 privileged accounts under just-in-time elevation with session recording, joiner-mover-leaver tickets in place for account creation, and badge-controlled access to the two rooms holding paper records; it holds the latest access-review report and a sample privileged-account log, with no separate record yet for the badge system.",
    commonMistake: "Answering only for logical access. Physical restriction of personal information sits inside the same component, and its absence reads as an unassessed limb rather than a strong control.",
  },
  c4_inventory: {
    fieldLabel: "C4: Inventory and management of personal information and systems",
    citation: "11 CCR § 7123(c)(4)",
    citationUrl: CPPA_URL,
    plainSummary: "A current inventory of personal information, data flows, hardware, and software. Scope extends to every system through which personal information is processed or accessible, including cloud and third-party systems the business does not own or operate.",
    regulationText: "Inventory and management of personal information and the business's information system, including: (A) Personal information inventories (e.g., maps and flows identifying where personal information is stored, and how it can be accessed) and the classification and tagging of personal information (e.g., how personal information is tagged and how those tags are used to control the use and disclosure of personal information); (B) Hardware and software inventories, and the use of allowlisting (i.e., discrete lists of authorized hardware and software to control what is permitted to connect to and execute on the business's information system); and (C) Hardware and software approval processes, and preventing the connection of unauthorized hardware and devices to the business's information system.",
    coachLead: "Separate the personal-information inventory from the hardware-and-software inventory, and name how each is kept current.",
    coachBody: "Cover classification and tagging of personal information, the allowlist of authorized hardware and software, and the approval process that keeps unauthorized devices off the network, alongside the refresh source and date for each inventory. Match each claim to a record such as an inventory export, a data-flow map, or a review log, with its date and scope, and leave an untested claim's evidence blank.",
    goodAnswer: "Sandhill Marketplace records: a data map refreshed at each quarterly review, last completed in March, covering 31 systems including two processors' platforms, with personal information tagged by sensitivity in the catalog tool; an asset inventory synced nightly from cloud configuration with an allowlist enforced at the network edge, no coverage yet of retail-store point-of-sale hardware, and a current inventory export plus the March review log on file.",
    commonMistake: "Treating a one-time mapping exercise as an inventory. A stale map is evidence of an inventory that once existed, not of one that is maintained.",
  },
  c5_secure_config: {
    fieldLabel: "C5: Secure configuration of hardware and software",
    citation: "11 CCR § 7123(c)(5)",
    citationUrl: CPPA_URL,
    plainSummary: "Hardening of systems, patch management, change management, and masking of sensitive personal information where appropriate, for both on-premises and cloud environments. Note: the approved text prints the Civil Code cross-reference as § 1798.145(ae)(1)(A)–(B); that identifier is reproduced as printed and is flagged for legal maintenance.",
    regulationText: "Secure configuration of hardware and software, including: (A) Software updates and upgrades; (B) Securing on-premises and cloud-based environments; (C) Masking (i.e., systematically removing or replacing with symbols such as asterisks or bullets) the sensitive personal information set forth in Civil Code section 1798.145, subdivisions (ae)(1)(A) and (B) and other personal information as appropriate by default in applications; (D) Security patch management (e.g., receiving systematic notifications of security-related software updates and upgrades; and identifying, deploying, and verifying their implementation); and (E) Change management (i.e., processes and procedures to ensure that changes to information system(s) do not undermine existing safeguards).",
    coachLead: "Name the hardening baseline, the patch timeframes, and the process that reviews changes before they ship.",
    coachBody: "State the configuration standard systems are measured against, the timeframe patches are held to by severity, and the approval step that catches an undocumented change, keeping any planned rollout separate from what runs today. Match each to a record such as a baseline policy, a patch-compliance report, or a change-log export, with its date, and leave the evidence blank where you have not checked for one.",
    goodAnswer: "Meridian Data Co. records: CIS Level 1 baselines enforced by configuration policy with drift alerting, critical patches inside 14 days and high inside 30, a change-advisory step in place before production changes ship, account numbers masked by default in the support console, and a current patch-compliance report and change-log export on file, with no drift-alert report yet for the reporting environment.",
    commonMistake: "Citing a patching policy without the timeframes it commits to. The audit assesses what is implemented, and an undated commitment cannot be tested against the evidence.",
  },
  c6_vuln_mgmt: {
    fieldLabel: "C6: Vulnerability scanning and penetration testing",
    citation: "11 CCR § 7123(c)(6)",
    citationUrl: CPPA_URL,
    plainSummary: "Internal and external vulnerability scans, penetration testing, and processes for vulnerability disclosure and reporting — such as bug-bounty and ethical-hacking programs.",
    regulationText: "Internal and external vulnerability scans, penetration testing, and vulnerability disclosure and reporting (e.g., bug bounty and ethical hacking programs).",
    enforcementNote: "Unpatched known vulnerabilities are cited in a significant share of breach enforcement actions, including major fines for failure to remediate known CVEs within reasonable timeframes.",
    coachLead: "Separate scanning from penetration testing from disclosure intake, each with what backs it up.",
    coachBody: "Give cadence and coverage for internal and external scanning, the date and scope of the last penetration test, and the route an outside researcher uses to report a vulnerability, keeping remediation timeframes attached to each. Match each to a record such as a scan report, a pen-test report, or a disclosure-policy page, with its date, and leave the checklist blank for anything you have not confirmed exists.",
    goodAnswer: "Brightwell Fitness records: authenticated weekly scans across production and staging, an external penetration test of the customer-facing application completed in February, no test yet of the internal network, a published security contact routed to the on-call queue, and the February pen-test report and a sample scan report on file.",
    commonMistake: "Folding penetration testing into scanning. They are named separately in the component, and an automated scan does not evidence a test.",
  },
  c7_audit_logs: {
    fieldLabel: "C7: Audit-log management",
    citation: "11 CCR § 7123(c)(7)",
    citationUrl: CPPA_URL,
    plainSummary: "Centralized storage, retention, and monitoring of audit logs to support detection of unauthorized activity and post-incident analysis.",
    regulationText: "Audit-log management, including the centralized storage, retention, and monitoring of logs.",
    coachLead: "State what is logged, where it is centralized, how long it is kept, and who reviews it.",
    coachBody: "Cover centralized storage, retention, and monitoring together, including any systems whose logs never reach the central store. Match each to a record such as a log-retention configuration, a sample log export, or a review log, with its date and coverage, and leave the checklist blank where you have not checked.",
    goodAnswer: "Thornfield Freight records: application, infrastructure, and identity logs shipped to one platform with 400-day retention, alert rules reviewed monthly by the security team, the legacy loan-origination system writing only to local disk, and a current retention-configuration export and a sample of the monthly review log on file.",
    commonMistake: "Answering 'we log everything.' Retention period and review are separate limbs of the component, and log volume is not evidence of either.",
  },
  c8_network_mon: {
    fieldLabel: "C8: Network monitoring and defenses",
    citation: "11 CCR § 7123(c)(8)",
    citationUrl: CPPA_URL,
    plainSummary: "Defenses to detect unauthorized access, use, modification, destruction, or disclosure of personal information. Bot-, intrusion-detection and intrusion-prevention tools are examples, not mandates — the component evaluates whether detection and defense are present and effective. The component also reaches data-loss-prevention systems as a distinct item, not only detection and prevention tools.",
    regulationText: "Network monitoring and defenses, including the deployment of: (A) Technologies, such as bot-detection, intrusion-detection, and intrusion-prevention, which a business may use to detect unsuccessful login attempts, monitor the activity of authorized users, and detect and prevent unauthorized access, destruction, use, modification, or disclosure of personal information; or unauthorized activity resulting in the loss of availability of personal information; and (B) Data-loss-prevention systems (e.g., software to detect and prevent unauthorized access, use, or disclosure of personal information).",
    coachLead: "Name the detection technologies, what they watch, and whether data-loss prevention is among them.",
    coachBody: "Say which detection and prevention technologies are deployed, across which environments, and who acts on the alerts, listing data-loss prevention separately from the rest. Match each to a record such as a monitoring-configuration export, a sampled alert report, or a data-loss-prevention policy, with its date and coverage, and leave the evidence blank for anything unconfirmed.",
    goodAnswer: "Sandhill Marketplace records: intrusion detection and flow-log analysis across the three production accounts routed to a 24/7 provider, data-loss prevention deployed only on email with no coverage of endpoint egress, and a current detection-configuration export plus one sampled alert report on file.",
    commonMistake: "Naming a firewall as network monitoring. A control that blocks by rule is not the same as one that detects anomalous activity, and the component asks about detection.",
  },
  c9_anti_malware: {
    fieldLabel: "C9: Antivirus and anti-malware protections",
    citation: "11 CCR § 7123(c)(9)",
    citationUrl: CPPA_URL,
    plainSummary: "Deployment and maintenance of antivirus and anti-malware solutions across endpoints and servers that process personal information.",
    regulationText: "Antivirus and antimalware protections.",
    coachLead: "Name the product, the device classes it runs on, and the classes it does not.",
    coachBody: "Say which endpoints, servers, and environments carry the agent, how coverage is measured, and where exclusions sit, keeping planned expansion separate from current coverage. Match the claim to a record such as a coverage report or a configuration export, with its date, and leave the evidence blank where coverage has not been measured.",
    goodAnswer: "Cascade Outfitters records: an endpoint-protection agent on all 1,200 laptops and all Windows servers, coverage verified from the inventory each month at 98%, the Linux build fleet deliberately excluded and compensated by image immutability, and a current monthly coverage report on file.",
    commonMistake: "Reporting deployment without a coverage measurement. Unmeasured coverage cannot distinguish a 98% deployment from a 60% one.",
  },
  c10_segmentation: {
    fieldLabel: "C10: Segmentation of an information system",
    citation: "11 CCR § 7123(c)(10)",
    citationUrl: CPPA_URL,
    plainSummary: "Segmentation of information systems — for example via properly configured firewalls, routers, and switches — to isolate systems processing personal information and limit the blast radius of a compromise.",
    regulationText: "Segmentation of an information system (e.g., via properly configured firewalls, routers, switches).",
    coachLead: "Describe the boundaries, what each isolates, and how the rules are verified.",
    coachBody: "Name the zones or network boundaries, state which of them isolate systems processing personal information, and say how the rule sets are reviewed, treating a flat network as a legitimate answer when stated plainly. Match each to a record such as a network diagram, a firewall-rule export, or a review log, with its date, and leave the checklist blank where unconfirmed.",
    goodAnswer: "Thornfield Freight records: production, corporate, and guest networks separated by firewall with default-deny between them, the personal-information data tier in private subnets reachable only from the application tier, rule sets reviewed twice a year, and a current network diagram plus the latest rule-review log on file.",
    commonMistake: "Claiming segmentation because separate cloud accounts exist. Account boundaries without enforced network rules are an organisational split, not a segmentation control.",
  },
  c11_port_protocol: {
    fieldLabel: "C11: Port and protocol management and protection",
    citation: "11 CCR § 7123(c)(11)",
    citationUrl: CPPA_URL,
    plainSummary: "Limitation and control of ports, services, and protocols to reduce attack surface. Added as a distinct component in the final regulations.",
    regulationText: "Limitation and control of ports, services, and protocols.",
    coachLead: "State the default posture, the approved exceptions, and who reviews them.",
    coachBody: "Say whether the environment is deny-by-default, where approved ports and protocols are recorded, and how the exception list is kept from growing unreviewed, naming any legacy protocol still in use. Match each to a record such as a security-group export or an exception-list review, with its date, and leave the checklist blank where unconfirmed.",
    goodAnswer: "Meridian Data Co. records: deny-by-default security groups with 34 registered exceptions held in the configuration repository, quarterly recertification of the list, one legacy plaintext file-transfer service still open to a single partner, and a current security-group export plus the latest recertification log on file.",
    commonMistake: "Answering with a tool name only. The component is about limitation and control, so the posture and the exception process are the substance.",
  },
  c12_awareness: {
    fieldLabel: "C12: Cybersecurity awareness",
    citation: "11 CCR § 7123(c)(12)",
    citationUrl: CPPA_URL,
    plainSummary: "How the business maintains current knowledge of evolving cybersecurity threats and appropriate countermeasures. The final regulations split awareness from training — a robust training program may not satisfy this component on its own.",
    regulationText: "Cybersecurity awareness, including how the business maintains current knowledge of changing cybersecurity threats and countermeasures.",
    coachLead: "Describe how threat knowledge is gathered and acted on — not how staff are trained.",
    coachBody: "Name the intelligence sources, who reviews them, how often, and a recent protection change that resulted, keeping training completion and phishing-exercise results in component 13 unless they also refresh what the business knows about changing threats. Match the claim to a record such as a briefing log or an intelligence-source list, with its date, and leave the checklist blank where unconfirmed.",
    goodAnswer: "Meridian Data Co. records: sector intelligence feeds reviewed weekly by the security team, a monthly threat briefing to engineering leadership, two control changes in the last year traced to that intake, and the briefing log and a sample intelligence-source list on file.",
    commonMistake: "Reusing the training answer here. The final regulations split awareness from training, so a strong training programme leaves this component unevidenced.",
  },
  c13_training: {
    fieldLabel: "C13: Cybersecurity education and training",
    citation: "11 CCR § 7123(c)(13)",
    citationUrl: CPPA_URL,
    plainSummary: "Training for employees, independent contractors, and anyone granted access to the business's information systems. Onboarding, annual, and post-breach timing are the regulation's examples of when that training can occur, not a fixed schedule every program follows.",
    regulationText: "Cybersecurity education and training, including training for each employee, independent contractor, and any other personnel to whom the business provides access to its information system (e.g., when their employment or contract begins, annually thereafter, and after a personal information security breach, as described in Civil Code section 1798.150).",
    coachLead: "Name the audiences, when training actually happens, and the completion records behind it.",
    coachBody: "Cover every audience with system access — employees, contractors, and other personnel — and the timing your program actually uses, since onboarding, annual, and post-breach are the regulation's examples of timing, not a fixed schedule. Match each audience to a completion record, with its date and rate, and leave the checklist blank for any audience you have not measured.",
    goodAnswer: "Cascade Outfitters records: onboarding training within five days and annual refreshers for all 400 employees at 96% completion, contractors covered only where badged, no post-incident training after the phishing incident in October, and the current completion report on file for employees only.",
    commonMistake: "Reporting only employee training. Contractors and other personnel with system access are named in the component, and their omission is a coverage gap, not a detail.",
  },
  c14_secure_dev: {
    fieldLabel: "C14: Secure development and coding practices",
    citation: "11 CCR § 7123(c)(14)",
    citationUrl: CPPA_URL,
    plainSummary: "Secure coding standards, code reviews, and security testing as part of the software development lifecycle (SDLC) — the stages a piece of software moves through from design to release.",
    regulationText: "Secure development and coding best practices, including code-reviews and testing.",
    coachLead: "Name the standard, the review gate, and the security testing — and what backs each claim.",
    coachBody: "Say what secure-coding standard is followed, whether code review is enforced or advisory, and which automated security tests run before release, or say plainly that the business does not develop software. Match each to a record such as the coding standard, a branch-protection configuration, or a scan report, with its date, and leave the checklist blank where unconfirmed.",
    goodAnswer: "Brightwell Fitness records: an internal secure-coding standard derived from an industry top-ten list, two-reviewer approval enforced by branch protection, static analysis and dependency scanning blocking on high findings, no dynamic testing in the pipeline, and a current branch-protection configuration export and a sample scan report on file.",
    commonMistake: "Marking the component not applicable because development is outsourced. Outsourced development remains inside the programme and moves the question into third-party oversight rather than out of scope.",
  },
  c15_third_party: {
    fieldLabel: "C15: Oversight of service providers, contractors, and third parties",
    citation: "11 CCR § 7123(c)(15)",
    citationUrl: CPPA_URL,
    plainSummary: "Oversight of vendors and contractors to ensure they meet the business's cybersecurity program obligations. Because scope expressly reaches third-party environments, this intersects with nearly every technical component. The obligations being checked are the service-provider and third-party contract terms set out in 11 CCR §§ 7051 and 7053.",
    regulationText: "Oversight of service providers, contractors, and third parties to ensure compliance with sections 7051 and 7053.",
    enforcementNote: "Third-party vendor breaches are a leading source of personal-information exposure; regulators have held businesses liable for incidents caused by inadequately vetted service providers.",
    coachLead: "State how vendors are tiered, what checks each tier gets under §§ 7051 and 7053, and how ongoing oversight happens.",
    coachBody: "Cover entry diligence, contract terms, and continuing monitoring, naming how many vendors sit in each tier and treating a signed contract as a starting point rather than the whole answer. Match each tier to a record such as a vendor-tiering list, a contract-review log, or an annual-reassessment report, with its date, and leave the checklist blank where unconfirmed.",
    goodAnswer: "Fernbrook Clinics records: 22 vendors with access to personal information tiered by data sensitivity, security review and contractual terms completed before onboarding for the top two tiers, annual reassessment for tier one only, no ongoing monitoring of tier three, and the current vendor-tiering list plus the tier-one reassessment report on file.",
    commonMistake: "Treating a signed contract as oversight. The component asks how compliance is ensured, which is a continuing activity rather than a document on file.",
  },
  c16_retention: {
    fieldLabel: "C16: Retention schedules and proper disposal of personal information",
    citation: "11 CCR § 7123(c)(16)",
    citationUrl: CPPA_URL,
    plainSummary: "Retention schedules and secure disposal of personal information no longer needed — by shredding, erasing, or otherwise rendering it unreadable. Schedules should be scoped to California personal information and sensitive personal information, not just general records.",
    regulationText: "Retention schedules and proper disposal of personal information no longer required to be retained, by (A) shredding, (B) erasing, or (C) otherwise modifying the personal information in those records to make it unreadable or undecipherable through any means.",
    coachLead: "State the schedule's coverage, what enforces it, and how records are actually destroyed.",
    coachBody: "Say whether the schedule reaches personal information and sensitive personal information specifically, what enforces deletion at the end of a period, and which disposal method — shredding, erasing, or otherwise rendering records unreadable — is used, including backups and archives. Match each to a record such as the retention schedule, a deletion log, or a destruction certificate, with its date, and leave the checklist blank where unconfirmed.",
    goodAnswer: "Meridian Data Co. records: a retention schedule covering nine categories of personal information with automated lifecycle deletion in the primary stores, manual quarterly purge in the analytics warehouse, backups aged out at 35 days rather than deleted on request, and the current retention schedule plus a sample deletion log on file.",
    commonMistake: "Pointing to a records-retention policy written for corporate documents. The component is about personal information, and a general schedule that never names it does not reach the control.",
  },
  c17_incident: {
    fieldLabel: "C17: Security-incident response management",
    citation: "11 CCR § 7123(c)(17)",
    citationUrl: CPPA_URL,
    plainSummary: "The incident response program — documented procedures, response capabilities, and testing — plus a review of actual security incidents during the audit period, including breach notifications sent to California consumers or agencies.",
    regulationText: "How the business manages its responses to security incidents (i.e., its incident response management). (A) For the purposes of subsection (17), \"security incident\" means an occurrence that actually or imminently jeopardizes the confidentiality, integrity, or availability of the business's information system or the personal information the system processes, stores, or transmits, or that constitutes a violation or imminent threat of violation of the business's cybersecurity program; unauthorized access, destruction, use, modification, or disclosure of personal information; or unauthorized activity resulting in the loss of availability of personal information is a security incident. (B) The business's incident response management includes: (i) The business's documentation of predetermined instructions or procedures to detect, respond to, limit the consequences of, and recover from malicious attacks against its information system (i.e., the business's incident response plan); and (ii) How the business tests its incident-response capabilities; and",
    enforcementNote: "Absence of an incident response plan, or failure to follow one, is cited as an aggravating factor in enforcement across multiple jurisdictions.",
    coachLead: "Cover the documented plan, the last test, and the incidents in the period — cross-referenced, not re-typed.",
    coachBody: "Name the plan and its owner, the date and outcome of the last response test, and what happened during the period, referring back to the incident-count and notification answers rather than re-entering those facts here. Match each to a record such as the incident-response plan, a test report, or an incident log, with its date, and leave the checklist blank where unconfirmed.",
    goodAnswer: "Meridian Data Co. records: an incident response plan with severity tiers and role assignments held in the runbook repository, a tabletop exercise on a ransomware scenario in September, two incidents in the period consistent with its incident count above, one of which triggered the consumer notification recorded there, and the plan document plus the September test report on file.",
    commonMistake: "Describing the plan and stopping. The component expressly reaches the handling of incidents that occurred, so a period with unexamined incidents leaves the larger half of the answer missing.",
  },
  c18_continuity: {
    fieldLabel: "C18: Business-continuity and disaster-recovery planning",
    citation: "11 CCR § 7123(c)(18)",
    citationUrl: CPPA_URL,
    plainSummary: "Business-continuity and disaster-recovery (BC/DR) plans — the plans that keep the business running and restore systems after a disruption — plus data-recovery capabilities, backups, and testing to ensure availability of personal information during disruptions.",
    regulationText: "Business-continuity and disaster-recovery plans, including data-recovery capabilities and backups.",
    coachLead: "Name the recovery objectives, the backup regime, and the date of the last proven restore.",
    coachBody: "State recovery-time and recovery-point objectives for the systems processing personal information, how backups are taken and isolated, and when a restore was last performed and timed rather than assumed, naming any untested system. Match each to a record such as a backup configuration, a restore-test report, or a runbook, with its date, and leave the checklist blank where unconfirmed.",
    goodAnswer: "Thornfield Freight records: four-hour recovery time and fifteen-minute recovery point for the order platform, immutable daily backups in a separate account, a full restore drill completed in June, no tested recovery path yet for the reporting warehouse, and the June restore-test report plus the current backup configuration on file.",
    commonMistake: "Citing backup frequency as recovery capability. Until a restore has been performed and timed, the recovery objective is a target rather than a demonstrated control.",
  },
  evidence_availability: {
    fieldLabel: "Evidence available (per component)",
    citation: "11 CCR § 7122(g)",
    citationUrl: CPPA_URL,
    plainSummary: "The business and its auditor must retain all documents relevant to each cybersecurity audit for at least five years after completion. The evidence types recorded per component name what the auditor can test today.",
    regulationText: "The business and the auditor must retain all documents relevant to each cybersecurity audit for a minimum of five (5) years after completion of the cybersecurity audit.",
    enforcementNote: "ISO 19011 evidence typing — documentary, testimonial, observation, analytical — is the profession-standard method a § 7122(a) auditor applies. Recording that nothing is on file converts a self-rated maturity into an insufficient-basis finding, which is accurate rather than adverse.",
    coachLead: "Record only records that exist today and could be handed over unedited.",
    coachBody: "Each evidence type corresponds to a file already on hand for this specific component. Where nothing exists, the honest absence produces a defensible finding based on limited information instead of an untestable maturity claim.",
    goodAnswer: "For its authentication component, a SaaS records a policy document, a runbook, and a sample access-review report — three files it can produce — and records no configuration export, because that capability has not been built.",
    commonMistake: "Claiming every evidence type to signal preparedness. If the auditor asks for the file and it does not exist, the maturity claim collapses with it.",
  },
  cyber_certification: {
    fieldLabel: "Annual certification to the Agency (§ 7124)",
    citation: "11 CCR § 7124(c)",
    citationUrl: CPPA_URL,
    plainSummary: "Each year an audit is required, the business must submit a written certification to the Agency by April 1 of the following year, via the Agency's website. The signer must be an executive-management member who is directly responsible for cybersecurity-audit compliance, has sufficient knowledge of the audit, and has authority to submit it. The submission carries the business's name and contact, a statement that the audit was completed, the audit period by month and year, an electronically signed attestation under penalty of perjury that the signer meets § 7124(c) and that the business made no attempt to influence the auditor, and the signer's name, title, and date.",
    regulationText: "The written certification must be completed by a member of the business's executive management team who: (1) Is directly responsible for the business's cybersecurity-audit compliance; (2) Has sufficient knowledge of the business's cybersecurity audit to provide accurate information; and (3) Has the authority to submit the business's certification to the Agency.",
    enforcementNote: "The attestation is made under penalty of perjury under California law, and expressly covers non-interference with the auditor's decisions and assessments as well as the accuracy of the submission.",
    coachLead: "Identify the signer and the audit period before the audit closes, not after.",
    coachBody: "Three facts settle readiness for the certification: which executive meets all three § 7124(c) conditions, the months the audit covers, and who owns the April 1 submission date. Each is a person or a date, not a policy.",
    goodAnswer: "A retailer's programme records that its Chief Information Security Officer is the § 7124(c) signer, the audit period runs March through December 2027, and the privacy office owns the April 1, 2028 submission in the compliance calendar.",
    commonMistake: "Assuming general counsel or the chief executive can sign by default. § 7124(c) turns on direct responsibility for audit compliance and sufficient knowledge of the audit, which is a factual test about one named person.",
  },
  // DOC 159 (2026-09-03) — the three questions the model-vs-law build added
  // or wired: the § 7123(e)(9)/(10) notification facts, the § 7123(b)(2)
  // not-applicable basis, and the § 7123(c)(1)(B) password predicate
  // (FC-L4, collected since 2026-08-25 and read since doc 159).
  //
  // DOC 263 (2026-09-16) — incident_notifications is retained as the legacy
  // combined answer; consumer_notice_status and agency_notice_status below
  // are the two new page keys that record the same two facts separately
  // (F07/master-table P04).
  incident_notifications: {
    fieldLabel: "Notifications made for the reported incidents",
    citation: "11 CCR § 7123(e)(9)",
    citationUrl: CPPA_URL,
    plainSummary: "The audit report must include a sample copy, with personal information removed, or a description of any notification the business gave to affected consumers under Civ. Code § 1798.82(a), and under § 7123(e)(10) the same for any notification the business was required to give to an agency with jurisdiction over privacy laws in California, together with the dates, details and remediation measures. The answer here tells the readiness report which of that material the business needs to have ready. This field holds the legacy combined answer to that question; the consumer notification status and agency notification status questions elsewhere on this page ask the same two facts separately. Treat those as the current record where both are answered, and use this field to preserve the earlier combined history.",
    regulationText: "(9) If the business provided notification to affected consumer(s) pursuant to Civil Code section 1798.82, subdivision (a), include a sample copy of the notification(s), excluding any personal information; or a description of the notification(s).",
    coachLead: "Answer from the incident register: who was actually notified, if anyone.",
    coachBody: "The answer turns on two facts for each reported incident: whether affected consumers were notified under the California breach statute, and whether an agency with jurisdiction over privacy laws in California was notified because the law called for it. Check the register and the notification file before selecting, and use the separate consumer and agency notification questions below where a more precise record is needed.",
    goodAnswer: "A retailer with one reported incident finds in its register that consumers received a breach letter and the Attorney General received the sample copy, and selects the option covering both consumers and an agency.",
    commonMistake: "Selecting the no-notification option because the incident felt minor. The question is what the register shows was sent, not how serious the incident seemed.",
  },
  consumer_notice_status: {
    fieldLabel: "Consumer notification status",
    citation: "11 CCR § 7123(e)(9); Cal. Civ. Code § 1798.82(a)",
    citationUrl: CPPA_URL,
    plainSummary: "11 CCR § 7123(e)(9) calls for the audit report to include a sample copy, with personal information excluded, or a description of any notification the business gave to affected consumers under Civil Code § 1798.82(a). This question records that fact on its own, separate from the agency-notification question and separate from the combined legacy answer recorded elsewhere on this page.",
    regulationText: "(9) If the business provided notification to affected consumer(s) pursuant to Civil Code section 1798.82, subdivision (a), include a sample copy of the notification(s), excluding any personal information; or a description of the notification(s).",
    coachLead: "Separate whether notice to consumers was called for from whether it was actually sent.",
    coachBody: "Check the notification file and the incident register for each reported incident rather than relying on memory. Select Unsure where that check has not been completed yet.",
    goodAnswer: "Cascade Outfitters checks its notification file, confirms breach letters went to affected California residents for one incident, and selects Notice provided.",
    commonMistake: "Selecting No notification was needed because none was sent. A notice can be called for and simply not yet sent, which is a different fact from no notice ever being called for.",
  },
  agency_notice_status: {
    fieldLabel: "Agency notification status",
    citation: "11 CCR § 7123(e)(10)",
    citationUrl: CPPA_URL,
    plainSummary: "11 CCR § 7123(e)(10) calls for the audit report to include a sample copy, with personal information excluded, or a description of any notification the business was required to give an agency with jurisdiction over privacy laws in California, along with the dates, details, and remediation measures. This question records that fact on its own, separate from the consumer-notification question and the combined legacy answer recorded elsewhere on this page.",
    regulationText: "(10) If the business was required to notify any agency with jurisdiction over privacy laws in California of unauthorized access, destruction, use, modification, or disclosure of personal information; or unauthorized activity resulting in the loss of availability of personal information, include a sample copy of the notification(s), excluding any personal information; or a description of the required notification(s), the date(s) and details of the activity that gave rise to the required notification(s), and any related remediation measures taken by the business.",
    coachLead: "Check whether an agency with jurisdiction over California privacy laws actually needed to be notified, separate from the consumer notice.",
    coachBody: "Confirm the notification duty and, separately, whether notice was sent, using the notification file for each incident. Select Unsure where that confirmation has not been completed.",
    goodAnswer: "Cascade Outfitters confirms the Attorney General received the sample notification for its one reported incident and selects Notice provided.",
    commonMistake: "Assuming agency notice was called for whenever consumer notice was sent. The two notification duties turn on separate facts, and one can apply without the other.",
  },
  component_not_applicable: {
    fieldLabel: "Basis for a not-applicable component",
    citation: "11 CCR § 7123(b)(2)",
    citationUrl: CPPA_URL,
    plainSummary: "The audit assesses each listed component that the auditor deems applicable to the business's information system, which means every resource organized for processing personal information, whether or not the business owns it. Reporting a component as not applicable records the business's position; the auditor makes the determination, and needs the fact the position rests on.",
    regulationText: "(2) Each of the components of a cybersecurity program listed in subsection (c) that the auditor deems applicable to the business's information system.",
    coachLead: "State the fact that takes the component outside the information system, not a preference.",
    coachBody: "A complete answer names what the business does not do or does not operate, and where the function sits instead; not applicable is different from not implemented, since a component that could apply but currently has no control running is reported as not implemented and rated accordingly. Because the information system includes resources the business does not own, a vendor running the function does not by itself take the component out of scope — say how that vendor is overseen.",
    goodAnswer: "A logistics operator records that it writes no software, that every application it uses is vendor-hosted, and that vendor secure-development practices are covered under its third-party oversight component.",
    commonMistake: "Treating a component that is not yet implemented as not applicable. Not applicable means the component cannot apply to the information system; a component that could apply but is absent is reported as not implemented.",
  },
  password_auth_used: {
    fieldLabel: "Passwords or passphrases in the authentication method",
    citation: "11 CCR § 7123(c)(1)(B)",
    citationUrl: CPPA_URL,
    plainSummary: "The authentication component has two elements: multi-factor authentication, and, if the business uses passwords or passphrases, strong unique passwords or passphrases. The second element applies only where passwords are actually part of the method, so this answer decides whether the readiness report assesses it.",
    regulationText: "(B) If the business uses passwords or passphrases, strong unique passwords or passphrases (e.g., passwords that are at least eight characters in length, not on the business's disallowed list of commonly used passwords, and not reused).",
    coachLead: "Answer for every system that authenticates access to personal information, not only the main directory.",
    coachBody: "Passwords count wherever they remain a factor, including a password-plus-push method, a legacy portal, a service account, or a vendor console. Passwordless means no password or passphrase is used as any factor anywhere in the systems that reach personal information.",
    goodAnswer: "A firm whose workforce signs in with hardware keys still records Yes, because its warehouse portal accepts a password with an SMS code and two vendor consoles use passwords.",
    commonMistake: "Answering No because the primary sign-in is passwordless while a legacy system or a vendor console still accepts a password.",
  },
};
