// LIA ANALOGY HOOKS — pinned, generated file (doc 213 / doc 222).
//
// Generated by `generate-corpus-hooks` (action "generate") from RATIFIED
// `public.authority_hooks` rows. Do not hand-edit the hooks array:
// regenerate it. Run: lia-hooks-v2-2026-09-10-0
//
// EXCLUDED ROWS (named, not silently dropped):
//   4ef4d633-ba56-4d2c-bf33-c75b503f3e62#v1 — hook_status is "contested", not "ratified"
//   164d80ea-f506-4a91-8a8f-0a337c490333#v1 — hook row is retired
//   095239df-0839-4480-996c-138ecc48a7e2#v1 — hook_status is "contested", not "ratified"
//   fddd8eec-7ba0-481a-b770-c0f653a8ab8f#v1 — hook_status is "contested", not "ratified"
//   a6505e9d-5b63-4aa9-af09-bf262ceef13a#v1 — hook_status is "contested", not "ratified"
//   f2f155df-e7f0-4f32-bbc9-25dc80ee7131#v1 — hook_status is "contested", not "ratified"

import type { AuthorityHook } from "../../../../_shared/corpus/hook-types.ts";


export const LIA_HOOKS_VERSION = "lia-hooks-v2-2026-09-10-0";

export const LIA_HOOKS: readonly AuthorityHook[] = [
  {
    "hook_id": "enforcement_actions:69eee35f-a280-47be-8159-bf778767ff31:v1",
    "profile_id": "0af0876d-5855-4d97-94ae-e1a5fb2f4bd4",
    "source_row_id": "69eee35f-a280-47be-8159-bf778767ff31",
    "fact_atoms": [
      "class:behavioral_advertising",
      "flag:large_scale",
      "data_category:Browsing/behavioural data",
      "relationship:customer",
      "state:intake.purpose_details.interest_type=Commercial / revenue-related",
      "state:intake.purpose_details.marketing_channels.online_advertising=true"
    ],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [
      "class:behavioral_advertising"
    ],
    "finding_span": "The lawfulness of processing is a fundamental aspect of data protection law and the processing of personal data without an appropriate legal basis is a clear and serious violation of a data subject's fundamental right to data protection .",
    "fact_pattern_paraphrase": "large-scale cross-border processing of members' first party and third party behavioural data for behavioural and targeted advertising, relying on consent and on a commercial legitimate interest",
    "finding_paraphrase": "processing personal data without an appropriate legal basis is a clear and serious violation of the data subject's fundamental right to data protection",
    "settledness": "R3",
    "posture": "rejected",
    "factor_id": "Balancing of interests, rights and freedoms",
    "bears_on_element": "balancing",
    "authority_label": "DPC, LinkedIn, decision of 22 October 2024",
    "regulator": "DPC",
    "relevance": {
      "instrument": "EU GDPR",
      "factor_ids": [
        "Balancing of interests, rights and freedoms",
        "Interest legitimacy",
        "Reasonable expectations of the data subject"
      ],
      "use_case_class": "behavioral_advertising",
      "relationship": "customer",
      "data_categories": [
        "Browsing/behavioural data",
        "Device/technical data",
        "Contact data"
      ],
      "flags": [
        "large_scale"
      ],
      "outcome_posture": "rejected"
    },
    "authority_label_short": "DPC, LinkedIn",
    "hook_version": 1,
    "source_status": "sa_decision",
    "status_label": "supervisory-authority decision — persuasive, non-binding outside its jurisdiction",
    "verb": "found",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "section",
      "ref": "7",
      "anchor_span": "Issue B – Legitimate interests as a lawful basis under Article 6(1)(f) GDPR"
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [
      {
        "atom": "class:behavioral_advertising",
        "source_span": "A factual assessment of the processing carried out by LinkedIn for the purposes of BA & TA",
        "materiality_reason": "the inquiry concerned processing for behavioural advertising and targeted advertising purposes"
      },
      {
        "atom": "flag:large_scale",
        "source_span": "Cross border processing",
        "materiality_reason": "processing was cross-border, platform-wide member data used for advertising at scale"
      },
      {
        "atom": "data_category:Browsing/behavioural data",
        "source_span": "First party data and third party data",
        "materiality_reason": "behavioural and third party data were combined to build advertising profiles"
      },
      {
        "atom": "relationship:customer",
        "source_span": "Further to a complaint-based inquiry commenced pursuant to Section 110 of the Data Protection Act 2018",
        "materiality_reason": "the data subjects were LinkedIn members whose personal data was processed for advertising"
      },
      {
        "atom": "state:intake.purpose_details.interest_type=Commercial / revenue-related",
        "source_span": "Issue B – Legitimate interests as a lawful basis under Article 6(1)(f) GDPR",
        "materiality_reason": "the interest asserted was the controller's commercial advertising revenue interest"
      },
      {
        "atom": "state:intake.purpose_details.marketing_channels.online_advertising=true",
        "source_span": "Definition of BA & TA",
        "materiality_reason": "the processing was delivered through online targeted advertising"
      }
    ],
    "distinguishing_pairs": [
      {
        "record_atom": "class:behavioral_advertising",
        "why_material": "the finding was made about behavioural and targeted advertising; a record processing for a non-advertising purpose does not share the interest and expectation profile assessed here",
        "exclusion_span": null,
        "record_polarity": "absent",
        "source_polarity": "present",
        "source_fact_span": "A factual assessment of the processing carried out by LinkedIn for the purposes of BA & TA",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      },
      {
        "record_atom": "flag:large_scale",
        "why_material": "the seriousness of the unlawful processing turned on platform-wide, cross-border scale; small-scale processing is materially different",
        "exclusion_span": null,
        "record_polarity": "absent",
        "source_polarity": "present",
        "source_fact_span": "Cross border processing",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      },
      {
        "record_atom": "data_category:Browsing/behavioural data",
        "why_material": "the assessment rested on combining behavioural and third party data beyond members' reasonable expectations",
        "exclusion_span": null,
        "record_polarity": "absent",
        "source_polarity": "present",
        "source_fact_span": "First party data and third party data",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      },
      {
        "record_atom": "state:intake.purpose_details.interest_type=Commercial / revenue-related",
        "why_material": "the balancing failed against a purely commercial advertising interest; a security or compliance interest weighs differently",
        "exclusion_span": null,
        "record_polarity": "absent",
        "source_polarity": "present",
        "source_fact_span": "Issue B – Legitimate interests as a lawful basis under Article 6(1)(f) GDPR",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      }
    ],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The company has stated that it processes browsing and behavioural data on a large scale for behavioural advertising, that the people affected are its customers, and that its interest in the processing is commercial. It also markets to them through online advertising. In its decision on LinkedIn, the Irish Data Protection Commission found that LinkedIn could not rely on legitimate interests under Article 6(1)(f) GDPR for this kind of processing — analysing members' data to target them with ads — because the rights and interests of the people affected outweighed LinkedIn's own interests. That decision weighs against the company's position here. But the outcome depends on this company's own facts: its purposes, the data involved, its safeguards, the effects on people, and what those people could reasonably expect. Section IV weighs those facts. (DPC, Inquiry into LinkedIn Ireland Unlimited Company, decision of 22 October 2024, § 7; decision of a lead supervisory authority applying the GDPR.)",
    "status_in_citation": true
  },
  {
    "hook_id": "edpb_guidelines:545af69d-ed08-47e8-b631-16b92cca1204:v1",
    "profile_id": "63bf2fe9-9459-45d1-a981-5ecd13fa1de6",
    "source_row_id": "545af69d-ed08-47e8-b631-16b92cca1204",
    "fact_atoms": [
      "class:employee_monitoring",
      "relationship:employee",
      "data_category:Employment data"
    ],
    "distinguishing_atoms": [
      "relationship:customer"
    ],
    "not_distinguishable": false,
    "required_atoms": [
      "relationship:employee",
      "class:employee_monitoring"
    ],
    "finding_span": "an employee in his/her workplace is in most cases not likely expecting to be monitored\nby his or her employer",
    "fact_pattern_paraphrase": "an employer monitors employees in the workplace",
    "finding_paraphrase": "an employee in the workplace is in most cases not likely to expect monitoring by his or her employer",
    "settledness": "R1",
    "posture": "conditional",
    "factor_id": "Reasonable expectations of the data subject",
    "bears_on_element": "balancing",
    "authority_label": "EDPB, Guidelines 3/2019 on processing of personal data through video devices",
    "regulator": "the EDPB",
    "relevance": {
      "instrument": "EU GDPR",
      "factor_ids": [
        "Reasonable expectations of the data subject",
        "Relationship with the individual"
      ],
      "use_case_class": "employee_monitoring",
      "relationship": "employee",
      "data_categories": [],
      "flags": [],
      "outcome_posture": "conditional"
    },
    "authority_label_short": "EDPB Guidelines 3/2019",
    "hook_version": 1,
    "source_status": "edpb_guidelines_final",
    "status_label": "EDPB Guidelines, adopted 29 January 2020 — interpretive guidance, not binding law",
    "verb": "states",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "paragraph",
      "ref": "37",
      "anchor_span": "37. For instance, an employee in his/her workplace is in most cases not likely expecting to be monitored\nby his or her employer.12"
    },
    "recognised_proposition": "an employee in the workplace is in most cases not likely expecting to be monitored by the employer, so reasonable expectations weigh against the monitoring",
    "condition_text": "only where the data subject cannot objectively expect the monitoring in the circumstances, signs informing the data subject being irrelevant to that objective expectation",
    "condition_atoms": null,
    "material_facts": [
      {
        "atom": "class:employee_monitoring",
        "source_span": "an employee in his/her workplace is in most cases not likely expecting to be monitored\nby his or her employer",
        "materiality_reason": "the guidance addresses monitoring of an employee by the employer"
      },
      {
        "atom": "relationship:employee",
        "source_span": "an employee in his/her workplace is in most cases not likely expecting to be monitored\nby his or her employer",
        "materiality_reason": "the expectation analysis turns on the employer-employee relationship"
      },
      {
        "atom": "data_category:Employment data",
        "source_span": "an employee in his/her workplace",
        "materiality_reason": "monitoring in the workplace generates data about the employee in the employment context"
      }
    ],
    "distinguishing_pairs": [
      {
        "record_atom": "relationship:employee",
        "why_material": "the expectation finding rests on the employment relationship; a non-employee data subject is outside the situation addressed",
        "exclusion_span": null,
        "record_polarity": "absent",
        "source_polarity": "present",
        "source_fact_span": "an employee in his/her workplace is in most cases not likely expecting to be monitored\nby his or her employer",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      },
      {
        "record_atom": "relationship:customer",
        "why_material": "the guidance contrasts a customer's position, allowing that a bank customer might expect monitoring, so the employee expectation finding does not carry across",
        "exclusion_span": null,
        "record_polarity": "present",
        "source_polarity": "present",
        "source_fact_span": "an employee in his/her workplace is in most cases not likely expecting to be monitored\nby his or her employer",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      },
      {
        "record_atom": "class:employee_monitoring",
        "why_material": "the passage concerns monitoring carried out by an employer over employees, not other processing purposes",
        "exclusion_span": null,
        "record_polarity": "absent",
        "source_polarity": "present",
        "source_fact_span": "an employee in his/her workplace is in most cases not likely expecting to be monitored\nby his or her employer",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      }
    ],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The company has said that people would reasonably expect this monitoring. The EDPB's Guidelines 3/2019 say reasonable expectations must be judged objectively, based on the actual circumstances — not just on what the individual personally expected. The guidelines add that employees generally do not expect their employer to monitor them at work. Posting signs may help meet transparency requirements, but signs alone do not decide what a person could reasonably expect. This guidance weighs against the company's position if an objective third party would not have expected the monitoring here. Section IV addresses whether that is the case. (EDPB, Guidelines 3/2019 on processing of personal data through video devices ¶37; EDPB Guidelines, adopted 29 January 2020 — interpretive guidance.)",
    "status_in_citation": true
  },
  {
    "hook_id": "enforcement_actions:72fb23c2-beba-4eee-9cfc-d850d1a55553:v1",
    "profile_id": "66742297-f9da-48ca-9657-4a72c45ce601",
    "source_row_id": "72fb23c2-beba-4eee-9cfc-d850d1a55553",
    "fact_atoms": [
      "class:employee_monitoring",
      "relationship:employee",
      "data_category:Employment data"
    ],
    "distinguishing_atoms": [
      "flag:special_category"
    ],
    "not_distinguishable": false,
    "required_atoms": [
      "class:employee_monitoring",
      "relationship:employee"
    ],
    "finding_span": "Sérstök þörf þarf að vera svo að vöktun með vinnuskilum, þ.e. vöktun með vinnuframlagi starfsmanna, sé heimil",
    "fact_pattern_paraphrase": "an employer used restaurant CCTV to take timestamped screenshots of an employee and annotate what he was doing, monitoring his work performance without specific information to staff",
    "finding_paraphrase": "monitoring of employees' work performance may be permitted only where a special need exists, such as supervision being impossible by other means, necessity under a collective or pay agreement especially performance-based time-measured pay, or area safety not otherwise being ensurable, and a prior data protection impact assessment is carried out",
    "settledness": "R3",
    "posture": "conditional",
    "factor_id": "Interest legitimacy",
    "bears_on_element": "purpose",
    "authority_label": "Persónuvernd, Stjörnuna ehf, decision of 24 March 2024",
    "regulator": "Persónuvernd",
    "relevance": {
      "instrument": "EU GDPR",
      "factor_ids": [
        "Interest legitimacy",
        "Necessity and less-intrusive means",
        "Reasonable expectations of the data subject",
        "Safeguards and mitigations",
        "Relationship with the individual"
      ],
      "use_case_class": "employee_monitoring",
      "relationship": "employee",
      "data_categories": [
        "Employment data",
        "Other"
      ],
      "flags": [],
      "outcome_posture": "conditional"
    },
    "authority_label_short": "Persónuvernd, Stjörnuna ehf",
    "hook_version": 1,
    "source_status": "sa_decision",
    "status_label": "supervisory-authority decision — persuasive, non-binding outside its jurisdiction",
    "verb": "found",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "section",
      "ref": "Mál númer 2021051091",
      "anchor_span": "Sérstök þörf þarf að vera svo að vöktun með vinnuskilum, þ.e. vöktun með vinnuframlagi starfsmanna, sé heimil"
    },
    "recognised_proposition": "monitoring of employees' work performance may in principle be permissible, but only where a special need for it exists",
    "condition_text": "a special need is shown, for example that supervision cannot be arranged by other means, that the monitoring is necessary under a collective agreement or other pay arrangement, particularly where pay is performance-based and time-measured, or that safety in the area cannot otherwise be ensured, and a data protection impact assessment is carried out before the monitoring begins",
    "condition_atoms": null,
    "material_facts": [
      {
        "atom": "class:employee_monitoring",
        "source_span": "rafrænni vöktun með vinnuskilum hans á veitingastaðnum Subway",
        "materiality_reason": "the processing assessed was electronic monitoring of an employee's work performance, which triggers the special-need test"
      },
      {
        "atom": "relationship:employee",
        "source_span": "Starfsmaður Subway kvartaði yfir vöktun fyrirtækisins með vinnuskilum hans",
        "materiality_reason": "the data subject was a member of staff in a subordinate employment relationship with the controller"
      },
      {
        "atom": "data_category:Employment data",
        "source_span": "verslunarstjóri staðarins hefði í tilgreint sinn tekið fjölda skjáskota af kvartanda úr eftirlitsmyndavélum staðarins og skráð á þau hvað kvartandi aðhafðist á hverjum tíma",
        "materiality_reason": "the records were timestamped CCTV screenshots annotated with what the employee was doing at each moment, i.e. work-performance data"
      }
    ],
    "distinguishing_pairs": [
      {
        "record_atom": "class:employee_monitoring",
        "why_material": "the special-need test is stated for monitoring of staff work performance; processing outside employee monitoring is not addressed",
        "exclusion_span": null,
        "record_polarity": "absent",
        "source_polarity": "present",
        "source_fact_span": "vöktun með vinnuskilum, þ.e. vöktun með vinnuframlagi starfsmanna",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      },
      {
        "record_atom": "relationship:employee",
        "why_material": "the heightened need requirement rests on the employment relationship and the imbalance between employer and staff",
        "exclusion_span": null,
        "record_polarity": "absent",
        "source_polarity": "present",
        "source_fact_span": "Starfsmaður Subway kvartaði yfir vöktun fyrirtækisins með vinnuskilum hans",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      },
      {
        "record_atom": "flag:special_category",
        "why_material": "the authority assessed ordinary work-performance images only and said nothing about monitoring involving special category data",
        "exclusion_span": null,
        "record_polarity": "present",
        "source_polarity": "absent",
        "source_fact_span": "verslunarstjóri staðarins hefði í tilgreint sinn tekið fjölda skjáskota af kvartanda úr eftirlitsmyndavélum staðarins og skráð á þau hvað kvartandi aðhafðist á hverjum tíma",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      }
    ],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The company has said that monitoring employees' work performance serves a legitimate interest. Iceland's data protection authority, Persónuvernd, has held that monitoring employees' work performance is permitted only where a specific need justifies it — for example, if supervision cannot reasonably be done by less intrusive means, if the monitoring is required under a collective agreement or a performance-based pay arrangement, or if safety in the area cannot otherwise be assured. In the case cited, the authority found that a restaurant manager's use of security-camera footage to check an employee's work performance did not match the system's stated purpose — security and protecting property — and lacked adequate justification. This decision is relevant to the company's asserted interest, but it speaks more directly to whether the monitoring is necessary and proportionate, and whether it matches its stated purpose. Section II addresses interest legitimacy; necessity and proportionality are addressed separately in Section III. (Persónuvernd, Monitoring of an Employee's Work Performance at a Subway Restaurant, Stjarnan ehf., Case No. 2021051091, decision of 12 March 2024; decision of the Icelandic supervisory authority applying the GDPR and Icelandic electronic-surveillance rules.)",
    "status_in_citation": true
  },
  {
    "hook_id": "regulatory_guidance:7fbe6585-e52c-4ec8-a0cd-e9b309571a21:v1",
    "profile_id": "a22b1399-d1b7-483d-b3dd-a1ced6c7339f",
    "source_row_id": "7fbe6585-e52c-4ec8-a0cd-e9b309571a21",
    "fact_atoms": [
      "class:direct_marketing",
      "state:intake.purpose_details.marketing_channels.post=true",
      "relationship:customer",
      "data_category:Contact data",
      "state:intake.purpose_details.interest_type=Commercial / revenue-related",
      "state:intake.balancing_details.opt_out_available=Yes — unconditional, on request, with no consequence"
    ],
    "distinguishing_atoms": [
      "flag:electronic_marketing",
      "flag:special_category",
      "flag:children"
    ],
    "not_distinguishable": false,
    "required_atoms": [
      "class:direct_marketing"
    ],
    "finding_span": "If your direct marketing activity doesn't need consent under PECR, then you might be able to rely on the legitimate interests as your data protection reason (\"lawful basis\").",
    "fact_pattern_paraphrase": "direct marketing that does not need consent under PECR, such as postal marketing of a programme to past attendees who have not objected, using name and address data with an opt-out in the mailing",
    "finding_paraphrase": "the controller might be able to rely on legitimate interests as its lawful basis, where it can show the use is proportionate, has a minimal privacy impact and is not a surprise to people or they are not likely to object",
    "settledness": "R1",
    "posture": "conditional",
    "factor_id": "Interest legitimacy",
    "bears_on_element": "purpose",
    "authority_label": "ICO, Plan direct marketing",
    "regulator": "the ICO",
    "relevance": {
      "instrument": "UK GDPR",
      "factor_ids": [
        "Interest legitimacy",
        "Necessity and less-intrusive means",
        "Balancing of interests, rights and freedoms",
        "Reasonable expectations of the data subject",
        "Potential harms and severity",
        "Safeguards and mitigations",
        "Third-party interests",
        "Children's data",
        "Special-category and ePrivacy interplay"
      ],
      "use_case_class": "direct_marketing",
      "relationship": null,
      "data_categories": [],
      "flags": [
        "special_category",
        "children",
        "electronic_marketing",
        "eprivacy_terminal_equipment"
      ],
      "outcome_posture": "conditional"
    },
    "authority_label_short": "ICO, Plan direct marketing",
    "hook_version": 1,
    "source_status": "regulator_guidance",
    "status_label": "ICO regulatory guidance — non-binding",
    "verb": "states",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "heading",
      "ref": "How does legitimate interests apply to direct marketing?",
      "anchor_span": "How does legitimate interests apply to direct marketing?"
    },
    "recognised_proposition": "legitimate interests might be available as the lawful basis for a direct marketing activity",
    "condition_text": "the direct marketing activity does not need consent under PECR and the controller can show the use of people's information is proportionate, has a minimal privacy impact and is not a surprise to people or they are not likely to object",
    "condition_atoms": null,
    "material_facts": [
      {
        "atom": "class:direct_marketing",
        "source_span": "If your direct marketing activity doesn't need consent under PECR",
        "materiality_reason": "the guidance addresses the lawful basis for direct marketing activity specifically"
      },
      {
        "atom": "state:intake.purpose_details.marketing_channels.post=true",
        "source_span": "A theatre wants to send details of its programme of summer performances by post to people who have attended events in the past and have not previously objected to receiving its direct marketing.",
        "materiality_reason": "the worked example is postal marketing, the paradigm channel that does not need PECR consent"
      },
      {
        "atom": "relationship:customer",
        "source_span": "people who have attended events in the past and have not previously objected to receiving its direct marketing",
        "materiality_reason": "the recipients had an existing relationship with the controller, feeding expectations in the balancing test"
      },
      {
        "atom": "data_category:Contact data",
        "source_span": "The theatre considers it is necessary to process the name and address details for this purpose",
        "materiality_reason": "only basic contact details were used, keeping privacy impact minimal"
      },
      {
        "atom": "state:intake.purpose_details.interest_type=Commercial / revenue-related",
        "source_span": "The theatre's purpose of direct marketing to increase its revenues is a legitimate interest.",
        "materiality_reason": "the interest identified at the purpose test was commercial revenue growth"
      },
      {
        "atom": "state:intake.balancing_details.opt_out_available=Yes — unconditional, on request, with no consequence",
        "source_span": "it includes details within the mailing about how to opt out",
        "materiality_reason": "a clear opt-out is treated as the safeguard supporting reliance on legitimate interests"
      }
    ],
    "distinguishing_pairs": [
      {
        "record_atom": "flag:electronic_marketing",
        "why_material": "the recognition is expressly framed only for marketing that does not require PECR consent, so electronic marketing caught by the PECR consent rules falls outside it",
        "exclusion_span": null,
        "record_polarity": "present",
        "source_polarity": "absent",
        "source_fact_span": "If your direct marketing activity doesn't need consent under PECR",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      },
      {
        "record_atom": "flag:special_category",
        "why_material": "the guidance considered only basic contact data with minimal privacy impact and did not address special category data, which needs an Article 9 condition as well as a lawful basis",
        "exclusion_span": null,
        "record_polarity": "present",
        "source_polarity": "absent",
        "source_fact_span": "The theatre considers it is necessary to process the name and address details for this purpose",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      },
      {
        "record_atom": "flag:children",
        "why_material": "the balancing described concerned adult past attendees, not children, whose expectations and vulnerability alter the balancing test",
        "exclusion_span": null,
        "record_polarity": "present",
        "source_polarity": "absent",
        "source_fact_span": "people who have attended events in the past and have not previously objected to receiving its direct marketing",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      }
    ],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The company has identified direct marketing as the interest it is pursuing. The ICO says direct marketing can be a legitimate interest, and that legitimate interests can be an appropriate lawful basis where the activity does not need consent under PECR. To rely on legitimate interests, though, the company must complete the three-part test: identify a legitimate purpose, show the proposed use of personal information is necessary and proportionate to that purpose, and show its interests are not overridden by the rights and interests of the people affected. Relevant factors include the privacy impact of the activity, whether people would reasonably expect their information to be used this way, and whether they are likely to object. Section II addresses whether the company's stated interest is legitimate; Sections III and IV address necessity and balancing separately. (ICO guidance (\"Plan direct marketing,\" section \"How does legitimate interests apply to direct marketing?\"); regulatory guidance interpreting the UK GDPR and PECR.)",
    "status_in_citation": true
  },
  {
    "hook_id": "edpb_guidelines:697ad8e1-6700-4a63-8888-12214dcc6c8b:v1",
    "profile_id": "cbd38bc6-53b1-444e-b242-d0858c372a43",
    "source_row_id": "697ad8e1-6700-4a63-8888-12214dcc6c8b",
    "fact_atoms": [
      "class:employee_monitoring",
      "relationship:employee",
      "data_category:Browsing/behavioural data",
      "data_category:Communications data",
      "state:intake.necessity_details.achievable_without_personal_data=Yes — the purpose could be achieved without personal data, or with anonymised or synthetic data"
    ],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [
      "class:employee_monitoring",
      "relationship:employee"
    ],
    "finding_span": "If misuse can be prevented (e.g., by using web filters) the employer has no general\nright to monitor.",
    "fact_pattern_paraphrase": "an employer monitoring employees' internet use where misuse could instead be prevented by technical means such as web filters",
    "finding_paraphrase": "where misuse can be prevented by technical means such as web filters the employer has no general right to monitor",
    "settledness": "R3",
    "posture": "conditional",
    "factor_id": "Necessity and less-intrusive means",
    "bears_on_element": "necessity",
    "authority_label": "Article 29 Working Party, Opinion 2/2017 on data processing at work",
    "regulator": "the Article 29 Working Party",
    "relevance": {
      "instrument": "EU GDPR",
      "factor_ids": [
        "Necessity and less-intrusive means"
      ],
      "use_case_class": "employee_monitoring",
      "relationship": "employee",
      "data_categories": [
        "Browsing/behavioural data"
      ],
      "flags": [],
      "outcome_posture": "conditional"
    },
    "authority_label_short": "WP29 Opinion 2/2017",
    "hook_version": 1,
    "source_status": "wp29_opinion",
    "status_label": "Article 29 Working Party opinion, 8 June 2017 — historical interpretive guidance, not endorsed by the EDPB; current relevance verified 2026-09-08",
    "verb": "advised",
    "appeal_note": null,
    "verified_as_of": "2026-09-08",
    "pinpoint": {
      "kind": "section",
      "ref": "6.4",
      "anchor_span": "6.4 Proportionality and data minimisation"
    },
    "recognised_proposition": "monitoring of employees at work may be justified only as a proportionate response to the risks faced by the employer",
    "condition_text": "only where misuse cannot be prevented by less intrusive technical means such as web filters, prevention being given much more weight than detection",
    "condition_atoms": null,
    "material_facts": [
      {
        "atom": "class:employee_monitoring",
        "source_span": "Data processing at work must be a proportionate response to the risks faced by an employer.",
        "materiality_reason": "the guidance addresses monitoring of workers by an employer at work"
      },
      {
        "atom": "relationship:employee",
        "source_span": "most monitoring has the potential to infringe on the\nprivate lives of employees",
        "materiality_reason": "the data subjects are employees whose private lives may be infringed by monitoring"
      },
      {
        "atom": "data_category:Browsing/behavioural data",
        "source_span": "internet misuse can be detected without the necessity of analysing website\ncontent",
        "materiality_reason": "the monitoring at issue concerns internet use and website content"
      },
      {
        "atom": "data_category:Communications data",
        "source_span": "a blanket ban on communication for personal reasons is impractical",
        "materiality_reason": "the same passage treats monitoring of personal communications at work"
      },
      {
        "atom": "state:intake.necessity_details.achievable_without_personal_data=Yes — the purpose could be achieved without personal data, or with anonymised or synthetic data",
        "source_span": null,
        "materiality_reason": "the finding turns on a less intrusive preventive alternative being available instead of monitoring"
      }
    ],
    "distinguishing_pairs": [
      {
        "record_atom": "state:intake.necessity_details.achievable_without_personal_data=Yes — the purpose could be achieved without personal data, or with anonymised or synthetic data",
        "why_material": "the guidance's premise is that a preventive, less intrusive technical measure exists; where none does, the passage says nothing about the employer's position",
        "exclusion_span": null,
        "record_polarity": "absent",
        "source_polarity": "present",
        "source_fact_span": "If misuse can be prevented (e.g., by using web filters) the employer has no general",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      },
      {
        "record_atom": "relationship:employee",
        "why_material": "the proportionality reasoning rests on the employment relationship and its imbalance of power; monitoring of customers or the public is not addressed",
        "exclusion_span": null,
        "record_polarity": "absent",
        "source_polarity": "present",
        "source_fact_span": "most monitoring has the potential to infringe on the\nprivate lives of employees",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      },
      {
        "record_atom": "data_category:Browsing/behavioural data",
        "why_material": "the example concerns internet use and website content; other categories of workplace data are not the subject of this finding",
        "exclusion_span": null,
        "record_polarity": "absent",
        "source_polarity": "present",
        "source_fact_span": "internet misuse can be detected without the necessity of analysing website\ncontent",
        "exclusion_paraphrase": null,
        "source_expressly_excludes": false
      }
    ],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "In WP29 Opinion 2/2017, the Article 29 Working Party advised that monitoring of employees at work must be a proportionate response to the risks faced by the employer, and that where misuse can instead be prevented by technical means, the employer has no general right to monitor. The information provided by the company describes employee monitoring; whether it meets that standard is addressed in Section III. (Article 29 Working Party, Opinion 2/2017 on data processing at work § 6.4; Article 29 Working Party opinion, 8 June 2017 — historical interpretive guidance, not endorsed by the EDPB.)",
    "status_in_citation": true
  }
];

// ── [RATIFY] — the direction matrix (doc 213 §4, as amended by doc 222 §3 and doc 224), as data ──
//
// Mirrors `directionFor` (hook-types.ts) row-for-row; that function is what
// a report actually renders through. This table exists only so the byte-pin
// test in tests/edge/run-li-assessment/doc213-hook-join.test.ts can catch
// the two drifting apart. Rows 14–15 are the join's own rows (hook-join.ts):
// the stored two-leg selection and nomination happen before `directionFor`.

export interface LiaHookMatrixRow {
  readonly posture: string;
  readonly fact_agreement: string;
  readonly engine_verdict: string;
  readonly shape: string;
  readonly note: string;
}

export const LIA_HOOK_DIRECTION_MATRIX: readonly LiaHookMatrixRow[] = [
  {
    posture: "accepted",
    fact_agreement: "same",
    engine_verdict: "any",
    shape: "S1 supports",
    note: "hedged to `likely` language; never lifts a verdict (Law B3-9)",
  },
  {
    posture: "accepted",
    fact_agreement: "different / unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "nothing to say",
  },
  {
    posture: "conditional",
    fact_agreement: "same",
    engine_verdict: "passes, and every condition_atom holds on the record",
    shape: "S5b recognised + condition satisfied",
    note: "the engine's pass is what satisfies the condition; the hook only echoes it (doc 222 §3)",
  },
  {
    posture: "conditional",
    fact_agreement: "same",
    engine_verdict: "otherwise (fails / uncertain, or condition_atoms null / not all held)",
    shape: "S5a recognised, condition unresolved",
    note: "the guidance is relevant; whether its condition is met is Section {section}'s question — never asserted here (the doc 218 D1 defect)",
  },
  {
    posture: "conditional",
    fact_agreement: "different (a distinguishing pair holds)",
    engine_verdict: "passes",
    shape: "omit + assessor flag `authority_not_dispositive` (`rule_missing` when the pair expressly excludes)",
    note: "a silent source under a pass is nothing missing; an express exclusion under a pass is the lawyer's rule",
  },
  {
    posture: "conditional",
    fact_agreement: "different (a distinguishing pair holds)",
    engine_verdict: "fails / uncertain",
    shape: "S6 source silent (S6x where the pair expressly excludes)",
    note: "\"does not extend\" only from an authored `source_expressly_excludes` pair with a verified exclusion span (doc 222 §2.4)",
  },
  {
    posture: "conditional",
    fact_agreement: "unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "",
  },
  {
    posture: "rejected",
    fact_agreement: "same",
    engine_verdict: "fails / uncertain",
    shape: "S2 cuts against and applied",
    note: "the verdict already reflects it",
  },
  {
    posture: "rejected",
    fact_agreement: "same",
    engine_verdict: "passes",
    shape: "omit + assessor flag `rule_missing`",
    note:
      "the lawyer's rule: an adverse authority on the same facts under a pass means a rule is missing — never printed as \"risk noted\"",
  },
  {
    posture: "rejected",
    fact_agreement: "different (a distinguishing pair holds)",
    engine_verdict: "any",
    shape: "S3 cuts against but distinguished",
    note: "renders only from the pair (source fact / record fact); never from an atom's generic phrase",
  },
  {
    posture: "rejected",
    fact_agreement: "unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "",
  },
  {
    posture: "contested (R4)",
    fact_agreement: "same",
    engine_verdict: "any",
    shape: "S4 noted as a boundary",
    note: "prints the derived status and the appeal note; no relation drawn",
  },
  {
    posture: "contested (R4)",
    fact_agreement: "different / unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "a contested decision on different facts adds nothing (doc 222 §3)",
  },
  {
    posture: "any",
    fact_agreement: "unknown from atoms",
    engine_verdict: "—",
    shape: "the stored two-leg selection's agreement, if one exists; else omit + flag `selection_pending`; legs disagreed → omit + flag `selection_unsettled` (the ROO item)",
    note: "doc 224 §1: a call is made only where no stored decision exists AND the pre-filter says either answer could print",
  },
  {
    posture: "any",
    fact_agreement: "`required_atoms` not all held",
    engine_verdict: "—",
    shape: "not nominated",
    note: "",
  },
];

// ── [RATIFY] — the atom-phrase map (doc 213 §5) ──────────────────────────
//
// One ratified clause per closed-list atom value in the hook vocabulary
// (§0: `class:`, `flag:`, `relationship:`, `data_category:`, `instrument:`,
// and the `state:intake.<path>=<value>` combinations a first hook batch is
// likely to need — doc 213 §3's selection rule draws the first batch from
// the same profiles as the already-ratified W1-W7 rules, so the `state:`
// atoms below are exactly those rules' own trigger values). Every value
// named in doc 213 §5's own text is reproduced verbatim; the rest ("add the
// others in the same register") are this build's own drafting, listed in
// full in 213A-TRACK-H2-BUILD-LOG-2026-09-07.md for the CEO's ratification
// pass alongside the matrix and the shapes.

export const LIA_ATOM_PHRASES: Readonly<Record<string, string>> = {
  // — classes (RULE_PRODUCT_REGISTRY.lia.typed_state_vocabulary.classes) —
  "class:fraud_prevention": "its processing is carried out for fraud prevention",
  "class:direct_marketing": "its processing is carried out for direct marketing",
  "class:employee_monitoring": "it monitors employees",
  "class:behavioral_advertising": "its processing is for behavioural advertising",
  "class:research_analytics": "its processing is for research or analytics",
  "class:it_security": "its processing is for network and information security",
  "class:product_improvement": "its processing is for product improvement",
  "class:contractual_administration": "its processing is carried out for contractual administration",

  // — flags (RULE_PRODUCT_REGISTRY.lia.typed_state_vocabulary.flags) —
  "flag:children": "children are among the people affected",
  "flag:special_category": "special-category data is processed",
  "flag:eprivacy_terminal_equipment": "it accesses information stored on a user's device",
  "flag:electronic_marketing": "its processing is for electronic marketing",
  "flag:public_authority": "it is a public authority",
  "flag:large_scale": "the processing is large-scale",
  "flag:automated_decision": "the processing involves automated decision-making",

  // — relationships (RULE_PRODUCT_REGISTRY.lia.typed_state_vocabulary.relationships) —
  "relationship:employee": "the people affected are its employees",
  "relationship:customer": "the people affected are its customers",
  "relationship:prospect": "the people affected are its prospects",
  "relationship:public": "the people affected are members of the public with no relationship to it",

  // — data categories (LIA_DATA_CATEGORIES / src/pages/LIAssessment.enums.ts DATA_CATEGORIES) —
  "data_category:Contact data": "it processes contact data",
  "data_category:Purchase/transaction history": "it processes purchase or transaction history",
  "data_category:Browsing/behavioural data": "it processes browsing or behavioural data",
  "data_category:Location data": "it processes location data",
  "data_category:Employment data": "it processes employment data",
  "data_category:Financial data": "it processes financial data",
  "data_category:Health or medical data": "it processes health or medical data",
  "data_category:Biometric data": "it processes biometric data",
  "data_category:Special category data": "it processes special-category data",
  "data_category:Communications data": "it processes communications data",
  "data_category:Device/technical data": "it processes device or technical data",
  "data_category:Other": "it processes other categories of data not separately listed",

  // — instruments (RULE_PRODUCT_REGISTRY.lia.instrument_scope) —
  "instrument:EU GDPR": "its processing is assessed under the EU GDPR",
  "instrument:UK GDPR": "its processing is assessed under the UK GDPR",

  // — state: atoms — ONE PHRASE PER CLOSED OPTION the hook drafter may emit.
  // The drafter (generate-corpus-hooks/_local/vocabulary.ts, STATE_ATOM_ENUMS)
  // admits exactly these `state:intake.` paths and option strings; a drafted
  // hook holding an atom with no phrase here would fail at render as an
  // `unresolved_slot` AFTER the drafting spend, so the map covers the whole
  // closed vocabulary and tests/edge/corpus/doc213-vocabulary-phrase-coverage
  // .test.ts pins the two sets to each other in both directions. Doc 213
  // §5's own three examples are reproduced verbatim; the rest are this
  // build's drafting in the same register, for the CEO's ratification pass.

  // opt-out (intake.balancing_details.opt_out_available — three options)
  "state:intake.balancing_details.opt_out_available=No opt-out is available": "no opt-out is available",
  "state:intake.balancing_details.opt_out_available=Yes — unconditional, on request, with no consequence":
    "an unconditional opt-out is available",
  "state:intake.balancing_details.opt_out_available=Yes — but conditional or subject to review":
    "an opt-out is available only on conditions or subject to review",

  // interest type (intake.purpose_details.interest_type — the intake's eight
  // closed options, LIAssessmentIntake.tsx "What type of interest is this?")
  "state:intake.purpose_details.interest_type=Commercial / revenue-related": "its interest is commercial or revenue-related",
  "state:intake.purpose_details.interest_type=Operational / service delivery": "its interest is operational or concerns service delivery",
  "state:intake.purpose_details.interest_type=Security / fraud prevention": "its interest is security or fraud prevention",
  "state:intake.purpose_details.interest_type=Legal / regulatory compliance": "its interest is legal or regulatory compliance",
  "state:intake.purpose_details.interest_type=Public interest / societal benefit": "its interest is a public interest or societal benefit",
  "state:intake.purpose_details.interest_type=Research / product improvement": "its interest is research or product improvement",
  "state:intake.purpose_details.interest_type=Political / electoral campaigning": "its interest is political or electoral campaigning",
  "state:intake.purpose_details.interest_type=Other (describe below)": "its interest is of a kind it has described in its own words",

  // Article 9(2) condition (intake.balancing_details.art9_condition — twelve
  // options; doc 206E field N1)
  "state:intake.balancing_details.art9_condition=Explicit consent (Art. 9(2)(a))":
    "it relies on explicit consent as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Employment, social security or social protection law (Art. 9(2)(b))":
    "it relies on employment, social security or social protection law as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Vital interests (Art. 9(2)(c))":
    "it relies on vital interests as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Not-for-profit body's legitimate activities (Art. 9(2)(d))":
    "it relies on the legitimate activities of a not-for-profit body as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Data manifestly made public by the individual (Art. 9(2)(e))":
    "it relies on data manifestly made public by the individual as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Legal claims or judicial acts (Art. 9(2)(f))":
    "it relies on legal claims or judicial acts as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Substantial public interest (Art. 9(2)(g))":
    "it relies on substantial public interest as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Health or social care (Art. 9(2)(h))":
    "it relies on health or social care as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Public health (Art. 9(2)(i))":
    "it relies on public health as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Archiving, research or statistics (Art. 9(2)(j))":
    "it relies on archiving, research or statistics as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=None identified":
    "it has identified no Article 9(2) condition for the special-category data",
  "state:intake.balancing_details.art9_condition=Not yet assessed":
    "the Article 9(2) condition for the special-category data has not yet been assessed",

  // necessity (intake.necessity_details.achievable_without_personal_data —
  // three options; doc 206E field N6)
  "state:intake.necessity_details.achievable_without_personal_data=Yes — the purpose could be achieved without personal data, or with anonymised or synthetic data":
    "it has recorded that the purpose could be achieved without personal data, or with anonymised or synthetic data",
  "state:intake.necessity_details.achievable_without_personal_data=No — personal data is required (explain why below)":
    "it has recorded that personal data is required for the purpose",
  "state:intake.necessity_details.achievable_without_personal_data=Not assessed":
    "whether the purpose could be achieved without personal data has not yet been assessed",

  // booleans the intake records directly (each `true` mirrors a flag above;
  // the `false` forms are the only way to phrase an ABSENCE)
  "state:intake.balancing_details.special_category_data=true": "special-category data is processed",
  "state:intake.balancing_details.special_category_data=false": "no special-category data is processed",
  "state:intake.balancing_details.children_data_subjects=true": "children are among the people affected",
  "state:intake.balancing_details.children_data_subjects=false": "children are not among the people affected",

  // direct-marketing channels (intake.purpose_details.marketing_channels.* —
  // doc 206E field N4)
  "state:intake.purpose_details.marketing_channels.automated_calls=true": "it markets by automated calls",
  "state:intake.purpose_details.marketing_channels.automated_calls=false": "it does not market by automated calls",
  "state:intake.purpose_details.marketing_channels.live_calls=true": "it markets by live calls",
  "state:intake.purpose_details.marketing_channels.live_calls=false": "it does not market by live calls",
  "state:intake.purpose_details.marketing_channels.email_sms=true": "it markets by e-mail or SMS",
  "state:intake.purpose_details.marketing_channels.email_sms=false": "it does not market by e-mail or SMS",
  "state:intake.purpose_details.marketing_channels.post=true": "it markets by post",
  "state:intake.purpose_details.marketing_channels.post=false": "it does not market by post",
  "state:intake.purpose_details.marketing_channels.online_advertising=true": "it markets by online advertising",
  "state:intake.purpose_details.marketing_channels.online_advertising=false": "it does not market by online advertising",
  "state:intake.purpose_details.marketing_channels.none=true": "it uses no direct-marketing channel",
  "state:intake.purpose_details.marketing_channels.none=false": "it uses at least one direct-marketing channel",
};

// ── [RATIFY] — the sentence shapes (doc 213 §5 as amended by doc 222 §4 and,
// 2026-09-09, PROMOTED to doc 238's paragraph-form shapes) ──────────────────
//
// PROMOTED 2026-09-09 (CEO ruling, this session): the clause-form shapes
// below were replaced wholesale by what shipped for the rest of this session
// as `LIA_HOOK_SHAPES_PROPOSED_2026_09` — doc 237 §5 found no shape, in any
// product, could produce a CEO-approved hook paragraph (docs 223B/233/234/
// 236 are all 4-7-sentence paragraphs built around a verbatim quoted clause,
// a hedge, and a forward-looking section pointer; every shape shipped before
// today was a 2-4-sentence clause). Every slot is still a record substring,
// a ratified phrase, a ratified paraphrase, or a pair's authored facts, plus
// the three new slots doc 238 added: {quote} (the verbatim, verified
// `finding_span`, quoted by the template — quote marks are ratified template
// text, never drafted content), {governing_provision} (unused by any LIA
// shape — LIA's sources ARE its own governing law's authorities), and
// {hedge} (a hook's own `hedge_sentence`, positioned where every approved
// paragraph actually places it: before the forward-looking pointer and the
// citation, never after — S1/S2 only, the "matching" shapes an approved
// hedge ever sits on). NONE of this reproduces any specific ratified
// paragraph byte-for-byte on its own — the four hooks whose EXACT ratified
// prose doesn't fit even this generalised skeleton (0af0876d, 63bf2fe9,
// 66742297, a22b1399; each hook's own "Implementation note" in doc 223B says
// so) render through `AuthorityHook.literal_sentence_override` instead
// (hook-types.ts), which bypasses this shape map entirely for that hook.
// This promoted map is the DEFAULT path every other/future hook still uses.

export const LIA_HOOK_SHAPES: Readonly<Record<"S1" | "S2" | "S3" | "S4" | "S5a" | "S5b" | "S6" | "S6x", string>> = {
  S1:
    "The company has stated that {customer_fact}. In {authority}, {regulator} {verb} that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding supports the company's position on the {factor}. {hedge}Section {section} records that determination. ({citation}; {status}.)",
  S2:
    "The company has stated that {customer_fact}. In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding cuts against the company's position on the {factor}. {hedge}Whether that holds on this record is addressed in Section {section}. ({citation}; {status}.)",
  S3:
    "In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding turned on the fact that {source_fact}; on this record the company has instead stated that {record_fact}. The decision marks a boundary rather than a finding against the company. ({citation}; {status}.)",
  S4:
    "In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". The company has stated that {customer_fact}. That decision is {status}; it is noted as a boundary and is not applied. ({citation}.)",
  S5a:
    "In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}. That guidance is relevant to the company's asserted {factor}; whether its condition is satisfied is addressed in Section {section}. ({citation}; {status}.)",
  S5b:
    "In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}. That guidance is relevant to the company's asserted {factor}; whether its condition is satisfied is addressed in Section {section}. The facts identified in Section {section} satisfy that stated condition. ({citation}; {status}.)",
  S6:
    "The company has stated that {record_fact}. In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}, but does not address whether legitimate interests is available where {record_fact}. The conclusion in Section {section} therefore rests on the separately identified rules and facts, not on that guidance. ({citation}; {status}.)",
  S6x:
    "The company has stated that {record_fact}. In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}, and that {exclusion_paraphrase}; that exclusion applies to processing of the kind the company describes. Whether it applies here is addressed in Section {section}. ({citation}; {status}.)",
};

// ── [RATIFY] — concept equivalence (doc 222 §2.3) ────────────────────────
//
// Two atoms naming the SAME underlying fact share a concept; the render
// dedupes `{customer_fact}` by concept (the doc 218 D4 "special-category
// data is processed; it processes special-category data" defect). This
// table carries no legal meaning — only "these two atoms say one thing" —
// which is why it may be generic where the withdrawn objected-phrase map
// could not. An atom absent here is its own concept. NOTE (build deviation
// from doc 222 §2.3's example table): the interest-type state atoms
// "Security / fraud prevention" and "Research / product improvement" each
// straddle two classes, so they are their own concepts rather than being
// conflated with one class — under-deduping is the safe direction.

export const LIA_ATOM_CONCEPTS: Readonly<Record<string, string>> = {
  "flag:special_category": "special_category",
  "data_category:Special category data": "special_category",
  "state:intake.balancing_details.special_category_data=true": "special_category",
  "flag:children": "children",
  "state:intake.balancing_details.children_data_subjects=true": "children",
  "class:direct_marketing": "direct_marketing",
  "flag:electronic_marketing": "electronic_marketing",
  "state:intake.purpose_details.marketing_channels.email_sms=true": "electronic_marketing",
};

/** The concept an atom names — itself when the table has no entry. */
export function liaAtomConcept(atom: string): string {
  return LIA_ATOM_CONCEPTS[atom] ?? atom;
}

// ── [RATIFY] — factor phrases (doc 222 §5): the `{factor}` slot, without a
// leading article (every shape supplies "the") ──────────────────────────

export const LIA_FACTOR_PHRASES: Readonly<Record<string, string>> = {
  "Interest legitimacy": "legitimacy of its interest",
  "Necessity and less-intrusive means": "necessity",
  "Balancing of interests, rights and freedoms": "balance",
  "Reasonable expectations of the data subject": "reasonable expectations",
  "Potential harms and severity": "potential harms",
  "Safeguards and mitigations": "safeguards",
  "Relationship with the individual": "relationship with the people affected",
  "Children's data": "children's data",
  "Special-category and ePrivacy interplay": "special-category data and ePrivacy",
  "Third-party interests": "third-party interests",
  "Scale, frequency and duration": "scale",
};

// ── [RATIFY] — source status labels (doc 222 §2.7) ───────────────────────
//
// The PRINTED status is derived from the source row at generate time
// (`status_label`, dated where the source carries a date); these are the
// undated fallbacks by `source_status`, and — for a v1 hook with no source
// status at all — the legacy settledness labels. "Settled law or adopted
// guidance" is withdrawn: it conflated binding law with interpretive
// guidance (ChatGPT review of doc 221, adopted 2026-09-08).

export const LIA_SOURCE_STATUS_LABELS: Readonly<Record<string, string>> = {
  edpb_guidelines_final: "EDPB guidelines — interpretive guidance, not binding law",
  edpb_opinion: "EDPB Article 64 opinion — Board opinion, not a judicial decision",
  wp29_opinion: "Article 29 Working Party opinion — historical interpretive guidance",
  regulator_guidance: "regulatory guidance — non-binding",
  sa_decision: "supervisory-authority decision — persuasive, non-binding outside its jurisdiction",
  sa_decision_affirmed: "supervisory-authority decision, affirmed on appeal",
  sa_decision_appeal_pending: "under appeal",
};

// ── RATIFIED by the CEO 2026-09-08 — the appeal sentence ─────────────────
//
// Where an appeal is known to have been made (`source_status` =
// sa_decision_appeal_pending, derived at generate time from the source row's
// appeal_status or the curation note), the join appends this sentence,
// verbatim, after the hook's sentence. The appeal's particulars
// (`appeal_note`: docket, date) are record-block data and are never printed.

export const LIA_APPEAL_SENTENCE = "This matter is subject to an appeal which could invalidate this ruling.";

export const LIA_SETTLEDNESS_LABELS: Readonly<Record<"R1" | "R2" | "R3" | "R4", string>> = {
  R1: "adopted guidance or settled authority",
  R2: "a settled line of decisions",
  R3: "a single supervisory authority's decision",
  R4: "under appeal / contested",
};
