// LIA AUTHORITY HOOKS — pinned, generated file (doc 213).
//
// Generated by `generate-corpus-hooks` (action "generate") from ratified,
// unretired `public.authority_hooks` rows whose profile is itself stamped
// (§2's "generate" action). Do not hand-edit `LIA_HOOKS`: regenerate it.
// Run: lia-hooks-v0-empty-2026-09-07-0
//
// EXCLUDED ROWS: none — zero rows have been drafted yet (§3's first batch
// has not run). `LIA_HOOKS` ships `[]` until the first ratified hook lands;
// every consumer (hook-join.ts, lia-persuasive-authority.ts) already
// degrades to a no-op on an empty array, so this file shipping empty is the
// SAME "unstamped hook is inert" law an unstamped rule already answers to
// (lia-rules.ts).
//
// The three `[RATIFY]` blocks below (`LIA_HOOK_DIRECTION_MATRIX`,
// `LIA_ATOM_PHRASES`, `LIA_HOOK_SHAPES`) are doc 213 §4/§5's own proposed
// bytes, transcribed here verbatim for the CEO to ratify (§8: "The direction
// matrix, the atom-phrase map and the four shapes — presented with rendered
// samples from the first settled hooks, not as JSON"). `LIA_HOOK_DIRECTION_
// MATRIX` is data only — `directionFor` (hook-types.ts) is the code that
// actually implements the matrix; the table exists so a byte-pin test can
// catch the two drifting apart. `generate-corpus-hooks`'s own `generate`
// action copies `LIA_ATOM_PHRASES` and `LIA_HOOK_DIRECTION_MATRIX` verbatim
// from this canonical file (doc 213 §2) once that function ships.

import type { AuthorityHook } from "../../../../_shared/corpus/hook-types.ts";

export const LIA_HOOKS_VERSION = "lia-hooks-v0-empty-2026-09-07";

export const LIA_HOOKS: readonly AuthorityHook[] = [];

// ── [RATIFY] — the direction matrix (doc 213 §4), as data ───────────────
//
// Mirrors the table in doc 213 §4 cell-for-cell (markdown emphasis and
// backtick styling dropped — this is a data structure, not markdown).
// `directionFor` (hook-types.ts) is what a report actually renders through;
// this table exists only so the byte-pin test in
// tests/edge/run-li-assessment/doc213-hook-join.test.ts can catch the two
// drifting apart.

export interface LiaHookMatrixRow {
  readonly posture: string;
  readonly fact_agreement: string;
  readonly engine_verdict: string;
  readonly shape: string;
  readonly note: string;
}

export const LIA_HOOK_DIRECTION_MATRIX: readonly LiaHookMatrixRow[] = [
  {
    posture: "accepted",
    fact_agreement: "same",
    engine_verdict: "any",
    shape: "S1 supports",
    note: "hedged to `likely` language; never lifts a verdict (Law B3-9)",
  },
  {
    posture: "accepted",
    fact_agreement: "different / unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "nothing to say",
  },
  {
    posture: "rejected / conditional",
    fact_agreement: "same",
    engine_verdict: "fails / uncertain",
    shape: "S2 cuts against and applied",
    note: "the verdict already reflects it",
  },
  {
    posture: "rejected / conditional",
    fact_agreement: "same",
    engine_verdict: "passes",
    shape: "omit + assessor flag `rule_missing`",
    note:
      "the lawyer's rule: an adverse authority on the same facts under a pass means a rule is missing — never printed as \"risk noted\"",
  },
  {
    posture: "rejected / conditional",
    fact_agreement: "different",
    engine_verdict: "any",
    shape: "S3 cuts against but distinguished",
    note: "requires the distinguishing atom on the record; hedged",
  },
  {
    posture: "rejected / conditional",
    fact_agreement: "unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "",
  },
  {
    posture: "contested (R4)",
    fact_agreement: "same or different",
    engine_verdict: "any",
    shape: "S4 noted as a boundary",
    note: "prints the status (\"under appeal, reported 1 April 2026\"); no relation",
  },
  {
    posture: "any",
    fact_agreement: "`required_atoms` not all held",
    engine_verdict: "—",
    shape: "not nominated",
    note: "",
  },
];

// ── [RATIFY] — the atom-phrase map (doc 213 §5) ──────────────────────────
//
// One ratified clause per closed-list atom value in the hook vocabulary
// (§0: `class:`, `flag:`, `relationship:`, `data_category:`, `instrument:`,
// and the `state:intake.<path>=<value>` combinations a first hook batch is
// likely to need — doc 213 §3's selection rule draws the first batch from
// the same profiles as the already-ratified W1-W7 rules, so the `state:`
// atoms below are exactly those rules' own trigger values). Every value
// named in doc 213 §5's own text is reproduced verbatim; the rest ("add the
// others in the same register") are this build's own drafting, listed in
// full in 213A-TRACK-H2-BUILD-LOG-2026-09-07.md for the CEO's ratification
// pass alongside the matrix and the shapes.

export const LIA_ATOM_PHRASES: Readonly<Record<string, string>> = {
  // — classes (RULE_PRODUCT_REGISTRY.lia.typed_state_vocabulary.classes) —
  "class:fraud_prevention": "its processing is carried out for fraud prevention",
  "class:direct_marketing": "its processing is carried out for direct marketing",
  "class:employee_monitoring": "it monitors employees",
  "class:behavioral_advertising": "its processing is for behavioural advertising",
  "class:research_analytics": "its processing is for research or analytics",
  "class:it_security": "its processing is for network and information security",
  "class:product_improvement": "its processing is for product improvement",
  "class:contractual_administration": "its processing is carried out for contractual administration",

  // — flags (RULE_PRODUCT_REGISTRY.lia.typed_state_vocabulary.flags) —
  "flag:children": "children are among the people affected",
  "flag:special_category": "special-category data is processed",
  "flag:eprivacy_terminal_equipment": "it accesses information stored on a user's device",
  "flag:electronic_marketing": "its processing is for electronic marketing",
  "flag:public_authority": "it is a public authority",
  "flag:large_scale": "the processing is large-scale",
  "flag:automated_decision": "the processing involves automated decision-making",

  // — relationships (RULE_PRODUCT_REGISTRY.lia.typed_state_vocabulary.relationships) —
  "relationship:employee": "the people affected are its employees",
  "relationship:customer": "the people affected are its customers",
  "relationship:prospect": "the people affected are its prospects",
  "relationship:public": "the people affected are members of the public with no relationship to it",

  // — data categories (LIA_DATA_CATEGORIES / src/pages/LIAssessment.enums.ts DATA_CATEGORIES) —
  "data_category:Contact data": "it processes contact data",
  "data_category:Purchase/transaction history": "it processes purchase or transaction history",
  "data_category:Browsing/behavioural data": "it processes browsing or behavioural data",
  "data_category:Location data": "it processes location data",
  "data_category:Employment data": "it processes employment data",
  "data_category:Financial data": "it processes financial data",
  "data_category:Health or medical data": "it processes health or medical data",
  "data_category:Biometric data": "it processes biometric data",
  "data_category:Special category data": "it processes special-category data",
  "data_category:Communications data": "it processes communications data",
  "data_category:Device/technical data": "it processes device or technical data",
  "data_category:Other": "it processes other categories of data not separately listed",

  // — instruments (RULE_PRODUCT_REGISTRY.lia.instrument_scope) —
  "instrument:EU GDPR": "its processing is assessed under the EU GDPR",
  "instrument:UK GDPR": "its processing is assessed under the UK GDPR",

  // — state: atoms — ONE PHRASE PER CLOSED OPTION the hook drafter may emit.
  // The drafter (generate-corpus-hooks/_local/vocabulary.ts, STATE_ATOM_ENUMS)
  // admits exactly these `state:intake.` paths and option strings; a drafted
  // hook holding an atom with no phrase here would fail at render as an
  // `unresolved_slot` AFTER the drafting spend, so the map covers the whole
  // closed vocabulary and tests/edge/corpus/doc213-vocabulary-phrase-coverage
  // .test.ts pins the two sets to each other in both directions. Doc 213
  // §5's own three examples are reproduced verbatim; the rest are this
  // build's drafting in the same register, for the CEO's ratification pass.

  // opt-out (intake.balancing_details.opt_out_available — three options)
  "state:intake.balancing_details.opt_out_available=No opt-out is available": "no opt-out is available",
  "state:intake.balancing_details.opt_out_available=Yes — unconditional, on request, with no consequence":
    "an unconditional opt-out is available",
  "state:intake.balancing_details.opt_out_available=Yes — but conditional or subject to review":
    "an opt-out is available only on conditions or subject to review",

  // interest type (intake.purpose_details.interest_type — the intake's eight
  // closed options, LIAssessmentIntake.tsx "What type of interest is this?")
  "state:intake.purpose_details.interest_type=Commercial / revenue-related": "its interest is commercial or revenue-related",
  "state:intake.purpose_details.interest_type=Operational / service delivery": "its interest is operational or concerns service delivery",
  "state:intake.purpose_details.interest_type=Security / fraud prevention": "its interest is security or fraud prevention",
  "state:intake.purpose_details.interest_type=Legal / regulatory compliance": "its interest is legal or regulatory compliance",
  "state:intake.purpose_details.interest_type=Public interest / societal benefit": "its interest is a public interest or societal benefit",
  "state:intake.purpose_details.interest_type=Research / product improvement": "its interest is research or product improvement",
  "state:intake.purpose_details.interest_type=Political / electoral campaigning": "its interest is political or electoral campaigning",
  "state:intake.purpose_details.interest_type=Other (describe below)": "its interest is of a kind it has described in its own words",

  // Article 9(2) condition (intake.balancing_details.art9_condition — twelve
  // options; doc 206E field N1)
  "state:intake.balancing_details.art9_condition=Explicit consent (Art. 9(2)(a))":
    "it relies on explicit consent as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Employment, social security or social protection law (Art. 9(2)(b))":
    "it relies on employment, social security or social protection law as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Vital interests (Art. 9(2)(c))":
    "it relies on vital interests as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Not-for-profit body's legitimate activities (Art. 9(2)(d))":
    "it relies on the legitimate activities of a not-for-profit body as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Data manifestly made public by the individual (Art. 9(2)(e))":
    "it relies on data manifestly made public by the individual as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Legal claims or judicial acts (Art. 9(2)(f))":
    "it relies on legal claims or judicial acts as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Substantial public interest (Art. 9(2)(g))":
    "it relies on substantial public interest as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Health or social care (Art. 9(2)(h))":
    "it relies on health or social care as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Public health (Art. 9(2)(i))":
    "it relies on public health as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=Archiving, research or statistics (Art. 9(2)(j))":
    "it relies on archiving, research or statistics as its Article 9(2) condition",
  "state:intake.balancing_details.art9_condition=None identified":
    "it has identified no Article 9(2) condition for the special-category data",
  "state:intake.balancing_details.art9_condition=Not yet assessed":
    "the Article 9(2) condition for the special-category data has not yet been assessed",

  // necessity (intake.necessity_details.achievable_without_personal_data —
  // three options; doc 206E field N6)
  "state:intake.necessity_details.achievable_without_personal_data=Yes — the purpose could be achieved without personal data, or with anonymised or synthetic data":
    "it has recorded that the purpose could be achieved without personal data, or with anonymised or synthetic data",
  "state:intake.necessity_details.achievable_without_personal_data=No — personal data is required (explain why below)":
    "it has recorded that personal data is required for the purpose",
  "state:intake.necessity_details.achievable_without_personal_data=Not assessed":
    "whether the purpose could be achieved without personal data has not yet been assessed",

  // booleans the intake records directly (each `true` mirrors a flag above;
  // the `false` forms are the only way to phrase an ABSENCE)
  "state:intake.balancing_details.special_category_data=true": "special-category data is processed",
  "state:intake.balancing_details.special_category_data=false": "no special-category data is processed",
  "state:intake.balancing_details.children_data_subjects=true": "children are among the people affected",
  "state:intake.balancing_details.children_data_subjects=false": "children are not among the people affected",

  // direct-marketing channels (intake.purpose_details.marketing_channels.* —
  // doc 206E field N4)
  "state:intake.purpose_details.marketing_channels.automated_calls=true": "it markets by automated calls",
  "state:intake.purpose_details.marketing_channels.automated_calls=false": "it does not market by automated calls",
  "state:intake.purpose_details.marketing_channels.live_calls=true": "it markets by live calls",
  "state:intake.purpose_details.marketing_channels.live_calls=false": "it does not market by live calls",
  "state:intake.purpose_details.marketing_channels.email_sms=true": "it markets by e-mail or SMS",
  "state:intake.purpose_details.marketing_channels.email_sms=false": "it does not market by e-mail or SMS",
  "state:intake.purpose_details.marketing_channels.post=true": "it markets by post",
  "state:intake.purpose_details.marketing_channels.post=false": "it does not market by post",
  "state:intake.purpose_details.marketing_channels.online_advertising=true": "it markets by online advertising",
  "state:intake.purpose_details.marketing_channels.online_advertising=false": "it does not market by online advertising",
  "state:intake.purpose_details.marketing_channels.none=true": "it uses no direct-marketing channel",
  "state:intake.purpose_details.marketing_channels.none=false": "it uses at least one direct-marketing channel",
};

// ── [RATIFY] — the four sentence shapes (doc 213 §5), verbatim ──────────
//
// Every slot is a record substring, a ratified phrase (LIA_ATOM_PHRASES),
// or a ratified paraphrase (a hook's own `fact_pattern_paraphrase` /
// `finding_paraphrase`). Reproduced byte-for-byte from doc 213 §5 — this
// build does not improve the wording.

export const LIA_HOOK_SHAPES: Readonly<Record<"S1" | "S2" | "S3" | "S4", string>> = {
  S1:
    "The company has stated that {customer_fact}. In {authority}, {regulator} found that where {fact_pattern}, {finding}. That finding supports the company's position on {factor}. ({authority} — {status}.)",
  S2:
    "The company has stated that {customer_fact}. In {authority}, {regulator} found that where {fact_pattern}, {finding}. That finding cuts against the company's position on {factor}, and the {factor} finding in Section {section} reflects it. ({authority} — {status}.)",
  S3:
    "In {authority}, {regulator} found that where {fact_pattern}, {finding}. The feature the regulator objected to — {distinguishing_feature} — is absent on this record: the company has stated that {customer_fact}. The decision marks the boundary the company's processing stays inside, not a finding against it. ({authority} — {status}.)",
  S4:
    "In {authority}, {regulator} found that where {fact_pattern}, {finding}; the decision is {status} and is noted as a boundary rather than applied. ({authority}.)",
};
