// LIA AUTHORITY RULES — pinned, generated file (doc 207C).
//
// Generated by `generate-corpus-rules` from ratified `public.authority_rules`
// rows. Do not hand-edit the rules array: regenerate it. Only ratified rows
// (rule row and primary profile both carrying ratified_by / ratified_at /
// ledger_ref, profile `rule_or_pattern = 'rule'`) are ever emitted.
//
// Seeded empty: no authority rule has been ratified yet.

import type { AuthorityRule } from "../../../../_shared/corpus/rule-types.ts";

export const LIA_RULES_VERSION = "lia-rules-v1-2026-09-07-0";

export const LIA_RULES: readonly AuthorityRule[] = [];

// ── LIA_RULE_CONTEXT ────────────────────────────────────────────────────
// The typed state the LIA rule pass supplies to every trigger. A rule may
// only name a flag, class, relationship, data category, verdict element or
// state root listed here; the build-time generator
// (generate-corpus-rules) rejects anything else, so a shipped rule can
// never reference state the pass does not populate.
export const LIA_RULE_CONTEXT = {
  flags: [
    "special_category",
    "children",
    "eprivacy_terminal_equipment",
    "electronic_marketing",
    "public_authority",
    "large_scale",
    "automated_decision",
  ],
  classes: [
    "direct_marketing",
    "fraud_prevention",
    "employee_monitoring",
    "behavioral_advertising",
    "research_analytics",
    "it_security",
    "contractual_administration",
    "product_improvement",
  ],
  relationships: ["customer", "employee", "prospect", "public"],
  verdict_elements: ["purpose", "necessity", "balancing"],
  state_roots: [
    "intake.",
    "interest_legitimacy.",
    "child_factor.",
    "public_authority_exclusion.",
    "scale_frequency_duration.",
    "eprivacy_short_circuit.",
    "precedent_class_posture.",
    "reasonable_expectations.",
    "potential_harms.",
    "opt_out_feasibility.",
    "relationship_with_individual.",
    "automated_decision_analysis.",
    "alternatives_considered.",
  ],
} as const;
