// Weekly drift detection: scans the updates feed for items that mention a
// tracked law AND a drift keyword (delayed, enjoined, etc.), records findings
// in regulatory_drift_alerts, and emails ALERT_EMAIL with a digest.
//
// Does NOT mutate regulatory_milestones automatically — humans confirm.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";
import { LAW_ALIASES, DRIFT_KEYWORDS, detectLawSlug } from "../_shared/lawAliases.ts";

const LOOKBACK_DAYS = 30;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  try {
    const since = new Date(Date.now() - LOOKBACK_DAYS * 24 * 60 * 60 * 1000).toISOString();

    // Pull recent updates (limit 500 — well within feed volume)
    const { data: recent, error } = await supabase
      .from("updates")
      .select("id, title, summary, category, url, law_slug, published_at")
      .gte("published_at", since)
      .eq("is_hidden", false)
      .limit(500);
    if (error) throw error;

    // Active milestones for matching
    const { data: milestones } = await supabase
      .from("regulatory_milestones")
      .select("id, law_slug, title, milestone_date")
      .is("superseded_by", null);

    const msByLaw = new Map<string, { id: string; title: string; date: string }[]>();
    for (const m of milestones ?? []) {
      const arr = msByLaw.get(m.law_slug as string) ?? [];
      arr.push({ id: m.id as string, title: m.title as string, date: m.milestone_date as string });
      msByLaw.set(m.law_slug as string, arr);
    }

    const findings: Array<{
      milestone_id: string | null;
      law_slug: string;
      signal_keyword: string;
      matched_update_id: string;
      matched_update_title: string;
      matched_update_url: string;
    }> = [];

    for (const u of recent ?? []) {
      const haystack = `${u.title ?? ""} ${u.summary ?? ""}`.toLowerCase();
      const matchedKeyword = DRIFT_KEYWORDS.find((k) => haystack.includes(k));
      if (!matchedKeyword) continue;

      const slug = u.law_slug ?? detectLawSlug(u.title, u.category, u.summary);
      if (!slug) continue;

      const lawMilestones = msByLaw.get(slug) ?? [];
      const targetMs = lawMilestones[0]?.id ?? null;

      findings.push({
        milestone_id: targetMs,
        law_slug: slug,
        signal_keyword: matchedKeyword,
        matched_update_id: u.id as string,
        matched_update_title: u.title as string,
        matched_update_url: u.url as string,
      });
    }

    // Dedupe against existing unreviewed alerts (same update + same milestone)
    let inserted = 0;
    for (const f of findings) {
      const { data: existing } = await supabase
        .from("regulatory_drift_alerts")
        .select("id")
        .eq("matched_update_id", f.matched_update_id)
        .eq("law_slug", f.law_slug)
        .limit(1);
      if (existing && existing.length > 0) continue;
      const { error: insErr } = await supabase.from("regulatory_drift_alerts").insert(f);
      if (!insErr) inserted++;
    }

    // Email digest if anything new
    const alertEmail = Deno.env.get("ALERT_EMAIL");
    const resendKey = Deno.env.get("RESEND_API_KEY");
    if (inserted > 0 && alertEmail && resendKey) {
      const rows = findings
        .slice(0, 20)
        .map(
          (f) =>
            `<tr>
              <td style="padding:6px 10px;border-bottom:1px solid #eee;"><strong>${f.law_slug}</strong></td>
              <td style="padding:6px 10px;border-bottom:1px solid #eee;color:#b91c1c;">${f.signal_keyword}</td>
              <td style="padding:6px 10px;border-bottom:1px solid #eee;"><a href="${f.matched_update_url}">${f.matched_update_title}</a></td>
            </tr>`
        )
        .join("");
      const html = `
        <div style="font-family:system-ui,sans-serif;max-width:640px;">
          <h2 style="color:#0d1f35;">Regulatory drift detected</h2>
          <p>${inserted} new signal${inserted === 1 ? "" : "s"} that a tracked law's date may have changed. Review and update <a href="https://enduserprivacy.com/calendar">/calendar</a> milestones as needed.</p>
          <table style="width:100%;border-collapse:collapse;font-size:14px;">
            <thead><tr style="background:#f5f5f5;">
              <th style="padding:6px 10px;text-align:left;">Law</th>
              <th style="padding:6px 10px;text-align:left;">Signal</th>
              <th style="padding:6px 10px;text-align:left;">Source</th>
            </tr></thead>
            <tbody>${rows}</tbody>
          </table>
          <p style="color:#666;font-size:12px;margin-top:16px;">
            Generated by regulatory-drift-detect. To dismiss false positives,
            mark the alert as reviewed in regulatory_drift_alerts.
          </p>
        </div>`;

      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${resendKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          from: "End User Privacy <alerts@enduserprivacy.com>",
          to: [alertEmail],
          subject: `[Drift] ${inserted} tracked law signal${inserted === 1 ? "" : "s"} — review needed`,
          html,
        }),
      });
    }

    return new Response(
      JSON.stringify({
        ok: true,
        scanned: recent?.length ?? 0,
        findings: findings.length,
        inserted,
        emailed: inserted > 0 && !!(alertEmail && resendKey),
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (e) {
    return new Response(
      JSON.stringify({ ok: false, error: String((e as Error).message ?? e) }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
