// product-test-grade — intake contract registry.
//
// Nine tools read their contract straight from `_shared/intake-contracts`
// (shared module, no deploy-size or cross-_local concern). Three
// (us-notice, eu-notice, registration) read from a BYTE-IDENTICAL mirror of
// `run-stress-job/_local/intake-contracts/*` copied into
// `_local/intake-contracts/` (see tests/edge/product-test/mirror.test.ts —
// importing another function's `_local` tree directly is not permitted, so
// the file is mirrored instead). RoPA has no intake contract anywhere in
// the codebase (doc 271 §4 defect 4); `variants` emits only "golden" and
// "thin-all" for it, built from a hand-picked list of top-level
// optional-looking keys, and says so.

import type { IntakeContract } from "../../../_shared/intake-contracts/types.ts";
import { cppaRiskContract } from "../../../_shared/intake-contracts/cppa-risk-assessment.ts";
import { cppaCybersecurityContract } from "../../../_shared/intake-contracts/cppa-cybersecurity.ts";
import { cppaAdmtContract } from "../../../_shared/intake-contracts/cppa-admt.ts";
import { dpiaFrameworkContract } from "../../../_shared/intake-contracts/dpia-framework.ts";
import { liAssessmentStageBContract } from "../../../_shared/intake-contracts/li-assessment.ts";
import { governanceContract } from "../../../_shared/intake-contracts/governance-assessment.ts";
import { irPlaybookContract } from "../../../_shared/intake-contracts/ir-playbook.ts";
import { biometricContract } from "../../../_shared/intake-contracts/biometric.ts";
import { dpaGeneratorContract } from "../../../_shared/intake-contracts/dpa-generator.ts";
import { usNoticeContract } from "../intake-contracts/us-notice.ts";
import { euNoticeContract } from "../intake-contracts/eu-notice.ts";
import { registrationContract } from "../intake-contracts/registration-assessment.ts";
import type { ProductTestTool } from "../types.ts";

/** `null` = no contract exists for this tool (RoPA only). */
export const CONTRACT_BY_TOOL: Readonly<Record<ProductTestTool, IntakeContract | null>> = {
  "cppa-risk": cppaRiskContract,
  "cppa-cyber": cppaCybersecurityContract,
  "cppa-admt": cppaAdmtContract,
  "dpia": dpiaFrameworkContract,
  "lia": liAssessmentStageBContract,
  "governance": governanceContract,
  "ir-playbook": irPlaybookContract,
  "biometric": biometricContract,
  "dpa": dpaGeneratorContract,
  "ropa": null,
  "us-notice": usNoticeContract,
  "eu-notice": euNoticeContract,
  "registration": registrationContract,
};

/**
 * RoPA has no contract (doc 271 §4 defect 4; intake-gate.ts:22-24). These are
 * the top-level keys of a RoPA activity/persona record that read as
 * optional in practice (PANEL-BRIEF.md §"ropa (no contract)" — every
 * activity answers ROPA_ACTIVITY_ANSWER_KEYS, and the persona-level fields
 * below are not required by any validator). Used ONLY to build the "golden"
 * and "thin-all" RoPA variants; no "thin-one", "blank-required", or
 * "contradict" variants are emitted for RoPA because there is no contract
 * `required` classification to drive them.
 */
export const ROPA_OPTIONAL_LOOKING_KEYS: readonly string[] = [
  "dpo_email",
  "rights_handling_process",
];

/** The `entity/organisation name` key per tool (PANEL-BRIEF.md §"company"). */
export const COMPANY_KEY_BY_TOOL: Readonly<Record<ProductTestTool, string>> = {
  "cppa-risk": "entity_name",
  "cppa-cyber": "profile.company_name",
  "cppa-admt": "organization_name",
  "dpia": "organization_name",
  "lia": "organization_name",
  "governance": "organization_name",
  "ir-playbook": "organizationName",
  "biometric": "orgName",
  "dpa": "entityName",
  "ropa": "org_name",
  "us-notice": "business_name",
  "eu-notice": "controller_name",
  "registration": "organization_name",
};

/** Which geo each tool's harness arm serves (mirrors PANEL_TOOL_GEO in
 *  src/lib/ptestPanels/types.ts, inlined for the same deploy-closure reason
 *  as PRODUCT_TEST_TOOLS above). Used only to pick the "wrong regime"
 *  vocabulary for the `wrong-regime` variant. */
export const GEO_BY_TOOL: Readonly<Record<ProductTestTool, "us" | "eu" | "both">> = {
  "cppa-risk": "us",
  "cppa-cyber": "us",
  "cppa-admt": "us",
  "dpia": "eu",
  "lia": "eu",
  "governance": "eu",
  "ir-playbook": "both",
  "biometric": "both",
  "dpa": "both",
  "ropa": "eu",
  "us-notice": "us",
  "eu-notice": "eu",
  "registration": "eu",
};

/** Deterministic tools (doc 272 §0, corrected 2026-09-18): the CPPA three,
 *  DPIA, LIA and registration. Governance is excluded until the CEO confirms
 *  GOVERNANCE_DETERMINISTIC_ENABLED is on in production — the latest
 *  production governance document (4095e317, 2026-09-17) was generated by
 *  claude-sonnet-5 with the model refinement pass on, so a snapshot pin would
 *  fail on model variance, not on a defect. Mirrors src/lib/productTest/plan.ts. */
export const DETERMINISTIC_TOOLS: ReadonlySet<ProductTestTool> = new Set([
  "cppa-risk", "cppa-cyber", "cppa-admt", "dpia", "lia", "registration",
]);

/** Tools whose report_data carries report_data.skeleton_document (doc 272 preamble). */
export const SKELETON_TOOLS: ReadonlySet<ProductTestTool> = new Set([
  "cppa-risk", "cppa-cyber", "cppa-admt", "dpia", "lia", "governance", "registration",
]);
