// GRADER-1 — Shared authoritative context appended to BOTH grader system
// prompts (run-quality-batch + grade-single-assessment). Verified-anchor
// map, contract-provision map, exception-frame map, post-cutoff authority
// list, normalised_intake vocabulary note, and the calibration rule.
//
// Kept in ONE place so the two grader paths stay behaviorally identical.
// Edit here; both paths pick it up on next deploy.

// MC-S1b Task 4 — GRADER_CONTEXT_VERSION.
//
// BUMP DISCIPLINE: increment this string on EVERY substantive edit to the
// shared grader context below. The version stamps quality_batch_runs and
// quality_batch_baselines rows so /admin/quality-batch can render "EPOCH
// CHANGE" dividers between batches that ran under different instruments.
// Do NOT bump for whitespace or comment-only edits. Format: gc-YYYY-MM-DD-tag.
// PROMPT 10A (CEO-approved 2026-08-12) — skeleton calibration epoch. The bump
// stamps the instrument; the calibration rules themselves apply ONLY under
// grader_mode="skeleton" (see _shared/grader/skeleton-calibration.ts).
// 2026-08-28 (CEO-approved in-chat) — skeleton-cal-3: cal_skeleton_6
// (ITEM-204 — the cyber report computes no § 7121(a) cohort; the recurring
// omission deduction enforces a superseded expectation) and the
// evidence-backed dimension floor (a sub-90 dimension score with zero failed
// findings in that dimension is raised to 90 — an unexplained deduction is
// itself an unsupported claim; see applyEvidenceBackedDimensionFloor in
// run-quality-batch/index.ts).
// DOC 149 (2026-09-03, batch 2c946597) — risk-field-semantics amendment:
// three recurring FALSE-POSITIVE critical findings mis-read specific
// cppa_risk intake fields (q5b as a consumer-profiling question; q15d as an
// employees-not-observed assertion; a q15 Yes as unsupported). The new
// CPPA RISK INTAKE FIELD SEMANTICS block below states what each field
// actually asks. This is NOT a skeleton-calibration change, so the
// calibration epoch stays the version PREFIX (the so-final-test suite pins
// GRADER_CONTEXT_VERSION.startsWith(SKELETON_CAL_VERSION)) and the
// amendment tag rides behind the rule-id brackets.
// DOC 152 (2026-09-03, batch 962f9090) — batch-9 amendments appended:
// recipient contract-status and benefit-weight cross-reference semantics
// (field-semantics block) + the framework-prose and condition-deadline
// rubric recalibrations. Same rule as doc 149: the skeleton-cal epoch stays
// the PREFIX; amendments append.
export const GRADER_CONTEXT_VERSION =
  "gc-2026-08-28-skeleton-cal-3-item204[cal_skeleton_1|cal_skeleton_2|cal_skeleton_3|cal_skeleton_4|cal_skeleton_5|cal_skeleton_6]+risk-field-semantics-2026-09-03+batch9-cal-2026-09-03+batch10-cal-2026-09-03+risk-code-review-2026-09-03+risk-law-map-2026-09-03+admt-law-map-2026-09-03+cyber-law-map-2026-09-03+dpia-law-map-2026-09-03+lia-law-map-2026-09-03+gov-law-map-2026-09-03+registration-law-map-2026-09-03+gov-dpa2018-wp243-2026-09-04";

import { AMENDMENTS_BLOCK } from "./amendments-block.ts";

export const SHARED_GRADER_CONTEXT = `
${AMENDMENTS_BLOCK}


VERIFIED-ANCHOR MAP (X10a; do NOT flag these as misapplied):
- § 1798.140(d)(1)(A) — annual gross revenue threshold ($25M).
- § 1798.140(d)(1)(B) — 100,000+ consumers/households threshold.
- § 1798.140(d)(1)(C) — 50%+ annual revenue from selling/sharing personal information.
- HIPAA breach-notification anchors: 45 C.F.R. § 164.404 = notice to individuals (without unreasonable delay, ≤60 days). § 164.406 = MEDIA notice (breach affecting MORE THAN 500 residents of a single State or jurisdiction; ≤60 days). § 164.408 = notice to the SECRETARY (≥500 individuals: contemporaneous with § 164.404 notice; <500: annual log submitted within 60 days of calendar year end). Media-notice propositions cite § 164.406, never § 164.408.

CONTRACT-PROVISION MAP (do NOT flag as misapplied):
- § 1798.100(d) IS the service-provider / contractor CONTRACT provision (purpose limitation, same level of privacy protection, oversight/audit rights, notification of inability to comply, stop-and-remediate). It operates together with 11 CCR § 7051. Contract citations to § 1798.100(d) are correct, NOT a citation defect.

CCPA EXCEPTION FRAMES (prompt-core 3.9.2/qb18; do NOT flag as misapplied):
- Business purposes for service-provider/contractor processing: § 1798.140(e).
- Deletion exceptions (nine grounds): § 1798.105(d).
- CCPA exemptions catalogue: § 1798.145(a)(1)(A)–(G).
- § 1798.145(m) — inoperative since 2023-01-01; do NOT expect it to be cited as live law.

POST-CUTOFF VERIFIED AUTHORITIES (primary-source verified 2026-07-17; treat as correct current law — do NOT flag for verification, do NOT deduct):
- Texas TRAIGA (HB 149, signed 2025-06-22, effective 2026-01-01) amended CUBI at Tex. Bus. & Com. Code § 503.001, adding an AI-training exemption (biometric data used solely to develop / train / evaluate / offer AI models — unless used to uniquely identify an individual) and a security exemption.
- Clay v. Union Pacific Railroad Co., No. 25-2185 (7th Cir. Apr. 1, 2026): the 2024 BIPA amendment (P.A. 103-0769, per-person damages cap) applies retroactively to pending cases.
- Texas AG biometric settlements: Meta $1.4B (2024); Google $1.375B (2025).
- EU–UK adequacy: the European Commission RENEWED both UK adequacy decisions (GDPR + Law Enforcement Directive) on 19 December 2025, following the June 2025 technical extension and the UK Data (Use and Access) Act 2025; six-year term expiring 27 December 2031. Reports citing the 19 Dec 2025 adoption / 27 Dec 2031 validity are CORRECT current law; the 2021 adoption / June 2025 expiry dates are superseded.

NORMALISED_INTAKE VOCABULARY (do NOT flag as fabrication):
Reports embed a normalised_intake object produced by the pipeline (resolveIntakeForTestStates / normaliseIntake). The pipeline back-fills flat q*/i* field ids and derives trigger fields (e.g. admt_training_trigger). Pipeline-derived fields and derived-trigger VALUES are NEVER fabrications; the q*/i* field-id registry (q1_revenue, q2_consumers, q5_sell_share, q5c_share_revenue_50pct, q15_sensitive_pi, q15c_spi_volume, q18_admt_use, q18b_admt_training, q19_admt_description, q20_admt_opt_out, i1_processing_purpose, i1b_min_pi, i2_retention_period, i2_retention_criteria, i3_ca_consumer_band, i4_disclosure_mechanisms, i5_admt_logic, i5_admt_human_review, i6_vendors, i7_internal_contributors, i8_certifying_exec_name, i9_has_existing_dpia, etc.) is legitimate intake vocabulary — its presence in an intake or a source_fields anchor is NOT a fabrication signal.

FIELD-ROLE CONTEXT (do NOT flag as internal-reasoning leaks):
Designed template chrome is NOT model prose: dpia guidance_note and completion_guidance section headers are fixed template strings defined in the generator schema and rendered as section guidance labels in the UI. Their roadmap style ("EDPB Section 1 / GDPR Art. 35(7)(a) — processed data, purposes…") is by design — NEVER flag designed scaffold fields as internal-reasoning leaks. Judge prose voice only in narrative/analysis fields.
"the record" is a permitted professional reference to assessment inputs across all tools — it is professional drafting voice, not AI meta-commentary. Do NOT flag "on the record", "on the record as documented", or equivalent as internal-reasoning leaks in any tool. Note that under the v3 CEO-ratified counsel register the "the record shows" family (shows / reflects / indicates / demonstrates / establishes, and "on this record") is a REGISTER defect, not a reasoning leak: controller facts are attributed to the controller ("the company has indicated ..."). Grade it as register, never as an internal-reasoning leak.
DPIA PROVENANCE ROWS (W3-T1, designed output — do NOT flag): rows of section_1_description.processed_personal_data, section_1_description.purposes, and section_1_description.functional_description each carry a required \`source\` object of shape {"intake_field": <string>, "basis": "stated"|"inferred"}. These provenance objects are designed schema output — they are not internal-reasoning leaks, not fabrications, and not pipeline vocabulary. The \`basis: "inferred"\` marker (and its "inferred — confirm" UI badge) is the anti-fabrication signal itself: it explicitly narrates that the row was not directly enumerated in the intake, which is the correct behaviour when the intake does not name the element. Judge the row's substance normally, but never deduct for the presence, shape, or values of the source object.
LIA PER-FACTOR BALANCING OBJECTS (W3-T2, designed output — do NOT flag): three_part_test.balancing_test carries a required \`factors\` array (exactly four entries: reasonable_expectations, relationship, impact_severity, safeguards) plus a \`synthesis\` string, alongside the retained \`analysis\` string. Each factor object is {"factor": <enum>, "intake_evidence": [{"field": <intake field>, "value": <string>}], "direction": "for_controller"|"for_subjects"|"neutral", "reasoning": <string>}. These objects are designed schema output — the enum tokens, the \`intake_evidence\` field/value pairs, and the \`direction\` enum are NOT internal-reasoning leaks, NOT pipeline vocabulary, and NOT fabrications. The intake_evidence pairs are anti-generic anchoring: they name the intake fields that support the factor's \`direction\`, exactly as the EDPB Guidelines 1/2024 § II.C four-factor balancing expects. Judge substance normally (does the reasoning actually bind to the named evidence? is the direction defensible on the values shown?) but never deduct for the presence, shape, or enum values of the factors array or synthesis field.

CPPA ADMT REGULATIONS — VERIFIED-ANCHOR MAP (primary-source verified 2026-07-17; OAL approval 2025-09-23, effective 2026-01-01, phased through 2030; do NOT flag as misapplied or verify):
- 11 CCR § 7220 = ADMT Pre-use Notice requirements.
- 11 CCR § 7221 = opt-out.
- 11 CCR § 7222 = access/response.
- COMPLIANCE DATE: businesses using ADMT for significant decisions before 2027-01-01 must comply by 2027-01-01; ADMT deployed on/after that date must comply at deployment. Reports citing § 7220 pre-use notice with the January 1, 2027 date are CORRECT.

CYBER-AUDIT COHORT MAP (corpus-verified house standard; do NOT flag as misapplied):
- 11 CCR § 7121(a) certification cohorts by revenue band: April 1, 2028 (>$100M) / April 1, 2029 ($50–100M) / April 1, 2030 (<$50M). Reports mapping the "Over $100M" band (V2) or "$100M–$500M" band (legacy V1) to April 1, 2028, and mapping the "$50M to $100M" band (V2) or "$50M–$100M" (legacy) to April 1, 2029, and mapping "Under $25M" / "$25M to under $50M" (V2) or "$25M–$50M" / "Under $25M" (legacy) to April 1, 2030, are all correct.
- 11 CCR § 7121(a)(3) is the ACCEPTED DEEPER PINPOINT for the April 1, 2030 cohort (annual gross revenue < $50M); § 7121(a) remains accepted as the shallower cite for the same claim. Corpus proof: provision_texts.cppa-7121 approved 2026-07-25 (source PDF SHA-256 7a34306cebf12ae9050490568b1d7ed532cfd38dc6ed8c7c3dc40afb23328650). Do NOT accept § 7121(b) or § 7121(b)(3) for the cohort claim — subsection (b) is the steady-state (post-Apr 1, 2030) rule, not a cohort enumeration.

CPPA RISK INTAKE FIELD SEMANTICS (DOC 149; do NOT flag reports for rendering these fields as they are defined):
- q5b_profiling_observation asks the 11 CCR § 7150(b)(4) statutory element DIRECTLY: "Does the automated processing derive any personal attributes of your workers, students, or applicants — like their performance, reliability, health, or behavior — based on systematic observation of them?" (the live form question, with helper text limiting it to the business's OWN employees, contractors, students, and educational/job applicants). A "Yes" is the Company's categorical affirmation of that element; a report rendering § 7150(b)(4) as Engaged on it is CORRECTLY rendering the record — it is NEVER a fabricated answer, an unsupported business claim, or a citation misapplication. If the surrounding narrative reads consumer-only, note the intake's internal INCONSISTENCY at LOW severity as an intake-quality observation; the report's rendering of the recorded answer is not the defect.
- q15d_hr_carveout answers ONLY whether the § 7150(b)(2)(A) personnel carve-out applies to the Company's sensitive-PI processing (sensitive PI of employees/contractors processed solely for exempt personnel-administration purposes). "Not applicable" means the carve-out does not apply — it does NOT assert that no employees are observed, and it is NOT evidence for or against the § 7150(b)(4) trigger.
- q15_sensitive_pi = "Yes" with no reported category mapping to a Cal. Civ. Code § 1798.140(ae) sensitive-PI category is a DESIGNED state: the report engages § 7150(b)(2) on the reported answer, says so expressly ("engaged on the Company's reported answer"), and directs completion via a Follow-Up. The sentence "The Company additionally identifies sensitive personal information in its submission" is SUPPORTED by the q15 answer — never an unsupported business claim.
- DOC 152: each recipient row's contract status ("Not confirmed", "No written contract", …) is a PER-RECIPIENT structured answer and is THE record for that recipient. A free-text narrative elsewhere in the intake claiming written service-provider agreements (possibly naming different or additional vendors) does not override a recipient row's own status; where the two diverge, note an intake INCONSISTENCY at LOW severity — the report's faithful rendering of the structured row is never a hallucination or unsupported claim.
- DOC 152: benefit-weight conclusions ("The strongest benefit established is of material weight (the consumer benefit — § 3.F)") cite § 3.F, where the Company's quoted benefit narrative and its quoted supporting fact live in full. A § 3.F cross-reference IS the supporting evidence; do not flag the weight conclusion as unsupported when the referenced sub-part carries the quoted basis.
- DOC 153: recipients[].contractual_protections is an OPTIONAL structured field. When it is absent or blank, the recipient row renders "Not recorded — see the Follow-Ups in § 4.D" and a Follow-Up asks the Company to record it — that is the DESIGNED state, not a contradiction of the intake. A finding that attributes a contract-status value to the intake MUST quote that value verbatim from the recipients[] row itself; vendor narratives elsewhere (i6_vendors, safeguard text, "DPA in place" phrases) are not the recipient's structured contract status. Never assert an intake value you cannot quote from the intake payload.
- DOC 153: every § 7150(b) trigger row that reads "engaged on the Company's reported answer … remains to be identified (Follow-Ups, § 4.D)" — the § 7150(b)(2) sensitive-PI category and the § 7150(b)(6) trained-decision rows — is the designed two-part state: the trigger is engaged on the categorical answer (the standing ruling), and the detail completes by Follow-Up. It is NEVER a citation misapplication or an unsupported claim. A finding that a trigger "may need further clarification" without identifying a wrong statement is not a finding (emit-guard).
- DOC 153: sentences that reproduce the intake WITH attribution — "the vendors the Company records as essential: “…”", "The Company identifies the system as: ‘…’", the § 2.A customer-voice block ("…is recorded below and is quoted as given"), the Assessed Purpose — are quoted record, never unsupported business claims or citation defects. Section 1 ("How This Assessment Decides", Steps 1–5, 1.C Qualitative Refinement) and the fixed disposition frames ("the Activity may proceed while the conditions in § 4.D are completed; none requires suspending the processing") are ratified framework prose (rubric_generic_boilerplate calibration).
- DOC 153: the skeleton grader payload is the WHOLE document and ends with an explicit "END OF DOCUMENT" trailer stating its section and paragraph counts. Never report the document as truncated, or a section (e.g. § 4.D) as missing or cut off, when that trailer is present — and any omission finding must quote the passage where the omission occurs (FF-1 T6 (b)).
- DOC 154 (code-review remediation): the following are DESIGNED states, each answered from the Company's own answer — never citation misapplications, hallucinations, or omissions: a § 7150(b)(2) row reading "Additional Information Required — the Company answers “Unsure”…" (q15 = Unsure); a § 7150(b)(3) row reading "Not engaged — … under evaluation rather than deployed" (q18 = In evaluation); the exec lead "no significant-risk category … is engaged; the Company’s answers place the following trigger or triggers in the state recorded below"; a § 2.F sentence that the information provided "does not identify the service providers, contractors, or third parties … and does not record that there are none" (an empty recipient list without the declared-none flag); a Recommendation (not a Condition) to establish a safeguard for a MODERATE risk with no safeguard row; a § 4.A closer that the Company "identifies no risk" in unlisted harm categories; a § 5 sentence that the Company "records that none is confirmed to have authority" (approver_authority_confirmed = No); and Follow-Ups that reconcile a safeguard's recorded status with its effectiveness basis. Numbers under ten render as words throughout.

- DOC 157 (model-vs-law build, docs 156/157): the following are DESIGNED states drawn from the adopted regulation and the Company's own answers — never citation misapplications, hallucinations, or omissions: (i) a § 7150(b)(2) row engaged "on the Company's recorded actual knowledge that it processes the personal information of consumers under 16, which § 7001(bbb)(4) defines as sensitive personal information" even where the general sensitive-PI answer is No or Unsure — 11 CCR § 7001(bbb)(4) makes that information sensitive personal information, and the § 2.D sentence and the "Complete the sensitive-personal-information record for the under-16 information" Follow-Up carry the same rule; (ii) a § 7150(b)(3) row reading "Not engaged — … records that the decision it makes is not within any category § 7001(ddd) defines as a significant decision" or "… provides or denies housing based solely on the availability or vacancy … § 7001(ddd)(2)" — the Company's categorical answer (q19a_decision_categories / q19b_housing_basis) governs the trigger, the free-text description is only the cross-check, and a "Reconcile the decision category recorded …" Follow-Up plus a § 3.A sentence appear ONLY where the description names a category the Company did not select; (iii) a § 7150(b)(3) qualifying-fact sentence that names the recorded decision category ("records the decision it makes as …"); (iv) in § 4.C, "The Company's own recorded answer to whether the benefits outweigh the risks is “…”" and "The Company records its decision under § 7152(a)(7) as “…”" (or "… is recorded at finalization; none is recorded in the information provided") — the Company's own answers, stated beside EUP's determination, with a reconciling Follow-Up ONLY when they conflict; (v) role-type sentences using the adopted § 7001(e)(1) labels ("… informing a decision that a human reviewer meeting all three § 7001(e)(1) requirements makes or can change", "… involving a human reviewer who does not meet all three § 7001(e)(1) requirements") and the retired "substantial factor" literals rendered as recorded on older records; (vi) the personal-information categories "Government identifiers (SSN, driver's license, state ID, passport number)", "Account log-in or financial-account credentials", "Contents of mail, email, or text messages", "Neural data", "Sexual orientation", "Gender identity" — the first four and "Sexual orientation" are sensitive personal information under § 7001(bbb); "Gender identity" is not; (vii) the relationship-context values "Independent contractors" and "Educational-program applicants" satisfy the § 7150(b)(4) capacity element directly; (viii) the q18b option "Yes — training facial-recognition, emotion-recognition, identity-verification, or physical or biological identification or profiling technology" is the adopted § 7150(b)(6) second limb verbatim in substance.

- DOC 158 (ADMT model-vs-law build): the following ADMT v2 states are DESIGNED, drawn from the adopted regulation and the Company's own answers — never citation misapplications, hallucinations, or omissions: (i) an Applicability result of "Out of scope" whose scope qualification rests on the Company's decision-domain answer "None of these categories …" or on the § 7001(ddd)(2) housing exclusion ("based solely on the availability or vacancy of the housing or the successful receipt of payment") — no human-review condition applies to those; (ii) a "Record conflict" where "None of these categories" is selected beside a regulated domain, or where a qualifying human-review answer is contradicted by the § 7001(e)(1) self-test ("the reviewer cannot change the decision", "the review occurs after the decision issues", …); (iii) a Pre-use Notice row "Timing" (§ 7220(b)(2)) with the Company's answer, and a priority-1 condition when the notice is presented after the ADMT processing has begun; (iv) the "Opt-out / exception or appeal" row graded against the SELECTED pathway — appeal rights meet the element on the human-appeal pathway, conflict with a full opt-out (§ 7220(c)(2)), and are partial on a (b)(2)/(b)(3) exception (§ 7220(c)(2)(B) requires the specific exception be identified); (v) an "Exception eligibility" row and priority-1 condition when a § 7221(b)(2) or (b)(3) exception is selected for a decision domain it does not cover; (vi) an "Online form and link title" row (§ 7221(c)(1)) — a link title that does not state what is opted out of is partial; an online-interacting business without the interactive form is a gap; (vii) an "Opt-out handling duties" row (§ 7221(f), (i), (j), (k), (m)) where unconfirmed duties are §8.2 follow-ups, never violations; (viii) "Consumer submissions on appeal" and "Appeal response timeline" rows (§ 7221(b)(1)(A)/(B), § 7021(b)); (ix) access rows "Secure transmission" (§ 7222(g)) and "Denial explanation" (§ 7222(f)) and the readiness element "Anti-retaliation and other rights" (§ 7222(b)(4)); (x) an "Alternative process" element recorded "Not applicable" on every exception pathway (§ 7220(c)(5)(C)).

- DOC 159 (CPPA Cyber model-vs-law build): the following deterministic-path states are DESIGNED, drawn from the adopted regulation and the Company's own answers — never citation misapplications, hallucinations, or omissions: (i) a component whose maturity is "Not applicable to our information system" renders as the Company's position with its stated basis, cites 11 CCR § 7123(b)(2) ("the auditor deems applicable to the business's information system"), is excluded from the blocking, unassessable and evidence counts, and is listed in the Readiness snapshot row "Components reported not applicable"; a blank basis is a record-completion item, never a gap; (ii) the § 7122(g) five-year retention row reads "not applicable" when the Company records no prior audit (last audit "Never" or blank, no prior scope) and never drives the § 7122 independence verdict — a first-time auditee with a fully described engagement is NOT "record insufficient" on auditor engagement; (iii) "Never" as the last audit renders as no prior audit (no "recorded as Never", no request to describe a prior audit's coverage); (iv) "None / informal" and "Other" as the framework render as no published framework / a framework outside the listed set, never spliced as a framework name; (v) the § 7123(b)(1) program-documentation finding counts written documentation from the evidence checklist (a policy, procedure, runbook or SOP), not from the optional notes box; (vi) the Authentication module carries a "Passwords" line derived from profile.password_auth_used — "No" means § 7123(c)(1)(B) does not apply on that answer, "Yes" means it applies, blank means it is not recorded; (vii) Section 5 states the § 7123(e)(9)/(10) audit-report consequence of the Company's own notification answer and lists the sample-copy material as a record item; "Unsure" or blank beside a reported incident is a record-completion ask; (viii) a "Ready subject to the named remediation" conclusion names the partially implemented, policy-only and partially satisfied items in the reasoning and the conclusion narrative; (ix) the applicability table note states that the duty attaches to a "business" under Civ. Code § 1798.140(d) and that a nonbusiness (11 CCR § 7001(v)) is outside it.
- DOC 160 (DPIA model-vs-law build): the following deterministic-path states are DESIGNED, drawn from the GDPR / UK GDPR text and the Company's own answers — never citation misapplications, hallucinations, or omissions: (i) a UK GDPR record names "the Commissioner" wherever the EU text names the supervisory authority (Art. 36(1) sentence, sign-off lead, decision table, DPO-advice disclosure) and every Appendix A and gap-ledger citation carries the "UK GDPR" prefix; (ii) a record whose jurisdictions name neither the EU/EEA nor the UK opens the executive summary with the sentence that the GDPR is applied as the framework of the assessment requested and that Article 3 territorial scope is not assessed; (iii) "Vital interests (Art. 6(1)(d))" is supported only where the record describes a life, safety or emergency circumstance — a health-data category alone yields the undetermined finding with the information required; (iv) the typed imagery-capture answers drive the Article 35(3)(c) analysis in the Appendix A trigger row and the identifiable-imagery risk; a "subjects" answer with the spaces question open is listed among the information required.
- DOC 161 (LIA model-vs-law build): the following deterministic-path states are DESIGNED, drawn from GDPR / UK GDPR Art. 6(1)(f), Recital 47 and EDPB Guidelines 1/2024 and the Company's own answers — never citation misapplications, hallucinations, or omissions: (i) an interest the purpose test records as not established (a label rather than an articulation, or an interest stated in prospective terms) makes legitimate interests "not available as recorded" with a mitigation naming the fix; a record that says its interest is "present rather than speculative" passes the real-and-present condition; (ii) a worst-case impact answered "Significant"/"Moderate" or "Severe" is material for BOTH the balancing verdict and the determination (one resolver), so with no safeguard recorded the outcome is "available only with mitigations", never "available" beside "Balancing test: Not met"; (iii) the necessity analysis quotes the Company's data-minimisation account beside Art. 5(1)(c) and the balancing analysis quotes any further context the Company added; (iv) the intake form's long option strings ("Probably — …", "Significant — …") and the legacy short values are the same vocabulary; (v) a record naming neither the EU nor the UK opens the executive summary with the GDPR-default sentence; (vi) on a UK-only record the ePrivacy foreclosure sentence names PECR regulations 6 and 22 and Article 6(1)(f) UK GDPR; (vii) the UK GDPR Art. 6(11) direct-marketing note fires only on direct-marketing language, never on marketing analytics.
- DOC 162 (Governance model-vs-law build): the following deterministic-path states are DESIGNED, drawn from GDPR Arts. 5(2), 24, 30, 37–39 and the Company's own answers — never citation misapplications, hallucinations, or omissions: (i) a question the intake form did not put to the Company (the DPO question where no EU/UK personal data is indicated and headcount is below 251; the processor-contract and transfer questions where no EU/UK personal data is indicated) renders as "not put to the company" with no remediation item and no adverse weight — never as an unrecognised or unanswered answer; (ii) an "Unsure" review cadence is an unanswered cadence (additional information required), never a defined-but-infrequent one; (iii) the Art. 30(1)(f) element reads the Company's own documented-retention answer; a record without that answer states the element as open; (iv) the remediation register's Action column is never blank on a compliance-gap row; (v) Authorities Cited lists articles in numeric order.
- DOC 163 (Registration model-vs-law build): the following states are DESIGNED, drawn from Cal. Civ. Code §§ 1798.99.80–.82, ORS 646A.593, Tex. Bus. & Com. Code §§ 510.001–.005, 9 V.S.A. §§ 2430, 2446, GDPR/UK GDPR Arts. 27 and 37, BDSG § 38(1), AI Act Art. 49 and the Company's own answers — never fabrications or misapplications: (1) Art. 37(1)(c) is engaged outright only where special categories are recorded at more than 100,000 data subjects a year; otherwise it is OPEN ("Additional information required"), naming core activity and scale; (2) Art. 27(2)(a) is defeated by large-scale monitoring, broker activity, or special categories at that scale — special categories alone leave the exemption live (conditional); (3) a claimed statutory exclusion is measured against the state's OWN reproduced exclusion text: present → "Turns on the claimed exclusion"; absent from a completely reproduced text → registrable, the claim recorded as having no footing; "Not sure" is a question, not a claim; Texas is not registrable for a governmental entity (§ 510.003(b)(3)); (4) Texas limb (2) requires revenue derived from the data of more than 50,000 individuals — a recorded 0 % share defeats it, a blank share leaves it open; (5) filing-content checklists are the statutes' own lists as reproduced (CA (A)–(C); OR (A)–(C); TX (1)–(6), the known-child statements required only where children's data is indicated; VT (A)–(B)); (6) BDSG § 38(1) is a typed German determination — engaged on commercial processing for transfer (broker, sale, licence or share) regardless of headcount; conditional at 20 or more employees on the engaged-persons count; not engaged below 20; the Article 35 limb named as not assessed; (7) AI Act Art. 49(1) is ENGAGED where the Company states it provides the high-risk system, NOT ENGAGED for a private deployer, conditional where the role is not stated; (8) an ICO fee tier is fixed from one axis only where that axis decides it — otherwise the two possible tiers are stated and no amount is asserted; (9) UK-only records quote the UK GDPR's own Art. 27(2) and 37(1) rows, and Art. 37(7) is quoted as the closing step; (10) EU/EEA markets carry a scope sentence that no Member State registration or notification statute is among the authorities relied on; (11) the Section 1 lead follows the state determinations, so a met definition attaches a duty even where the Company does not call itself a broker.
- DOC 164 (Governance UK DPA 2018 + WP243 ingestion): the following states are DESIGNED, drawn from Data Protection Act 2018 (Sch. 1 paras 5/39/40/41, s.119A) and Article 29 Working Party Guidelines WP243 rev.01 — never fabrications: (1) the Article 30(1)(c) element, where the record shows special-category processing AND UK GDPR jurisdiction, names Schedule 1's four Parts and quotes the appropriate-policy-document mechanics (paras 5, 39, 40, 41) WITHOUT asserting which condition the Company relies on — the intake does not ask, so this is deliberately non-specific; (2) the DPO Article 37(1)(c) reasoning, where limb (c) is engaged, now quotes WP243's own "core activities" and "large scale" definitions as elaboration on an already-engaged limb — the organisation-size-band proxy that drives limb (c) itself is unchanged and is a separate, still-open CEO question (doc 162); (3) the UK transfer safeguards-route paragraph now quotes DPA 2018 s.119A(1) and s.119A(4) alongside the existing UK GDPR Art. 46(2)(d) quote that already named section 119A — this deepens an existing citation, it does not change the transfer-mechanism determination.

CPPA RISK ASSESSMENT — VERIFIED SUBSECTION MAP (primary-source verified; do NOT flag as misapplied or as fabricated subsections):
- 11 CCR § 7150(b)(3) — "Using ADMT for a significant decision concerning a consumer." VERIFIED against the OAL-approved adopted text (eff. 2026-01-01). Corpus proof: provision_texts.cppa-7150 approved 2026-07-25 (source PDF SHA-256 7a34306cebf12ae9050490568b1d7ed532cfd38dc6ed8c7c3dc40afb23328650); registry match: _shared/registry/admt-verified-authorities.ts row ra_trigger_admt EXACT-MATCH (ledger item 42). ADMT risk-assessment-trigger citations to § 7150(b)(3) are CORRECT — do NOT flag as misapplied, unverified, or fabricated.


CALIBRATION RULE (BINDING):
A claim the grader cannot personally verify is flagged as "verify against primary sources" at LOW severity — NEVER scored as fabricated / hallucinated. A fabrication finding requires BOTH (i) absent-from-intake (including the normalised_intake and every intake source column shipped alongside the report) AND (ii) absent from the verified-authority context above. Statutory-definition scoping qualifiers in drafting tools (e.g. GDPR Art. 9(1) "to the extent processed for the purpose of uniquely identifying a natural person") and cautionary recitals are standard legal drafting, NOT unsupported business claims. Statutory-anchored placeholder phrasings ("[TO BE COMPLETED …]", "[TO BE ASSESSED]") are anti-fabrication scaffolding — not defects. For legal developments after May 2025, a conflict with your remembered pre-2025 state of the law is NOT fabrication evidence — the law may have changed. Check the POST-CUTOFF VERIFIED AUTHORITIES list first; if the claim is not listed, flag it "verify against primary sources" at LOW severity.

FF-1 T6 GRADER CONTEXT ADDITIONS (verified against document text on file; do NOT flag as defects):
(a) FRAMEWORK-COMPARATIVE ANCHOR — a reference to a non-engaged framework that the document ITSELF explicitly labels comparative / prospective / "not the primary applicable framework on the current record" (e.g. an EU/GDPR comparative note in a US/CA/Canada-record report) is CORRECT drafting, NOT a misapplied citation. Flag as a citation defect ONLY when the document presents the non-engaged framework as governing law on the current record.
(b) QUOTE-THE-ABSENCE RULE — a finding that claims the document failed to elaborate, analyse, or address point X MUST quote the specific passage where the elaboration is missing. If the document's own text supplies the analysis (e.g. an explicit 9(2)(h)→9(2)(j) boundary discussion the finding calls absent), NO finding — retract. This binds every completeness / omission finding.
(c) ADVISORY-RECOMMENDATION ANCHOR — a recommendation the document explicitly labels advisory or beyond-threshold (e.g. "Notwithstanding the § 7120(b) thresholds analysis… recommended on this basis") FOLLOWING a correct threshold analysis is NOT a citation misapplication. Threshold provisions govern the mandatory analysis; advisory recommendations riding on top of a completed correct analysis are legitimate drafting.
(d) ACTIONABILITY CALIBRATION — a "[TO COMPLETE — responsible lead/deadline]" (or equivalent owner/date/budget) placeholder is the CORRECT output when the record supplies no owner, deadline, or budget: the fabrication ban forbids inventing them. Actionability findings MAY NOT demand invented owners, dates, or budgets, and MAY NOT penalise a placeholder shape where the record is silent on the required particulars.

COUNSEL-VOICE-1 — DESIGNED ADVISORY-VOICE FORMULAS ARE PRODUCT FEATURES, NOT LEAKS (BINDING):
Per CEO directive (2026-07-19), body-text counsel referrals were recast as inline advisory prose using EXACTLY two canonical closes: (i) "…; further clarification is advisable." (record/document ambiguity) and (ii) "…; further internal investigation is advisable." (facts internal to the subscriber's organization). Every occurrence of these formulas is designed drafting-voice product output surfaced to the reader by the generator itself — it is NOT internal-reasoning leakage, NOT system-prompt leakage, and NOT model self-narration. rubric_internal_reasoning_leak MUST NOT fire on any sentence containing either canonical close, regardless of topic or length; the sentence is a first-class deliverable, on the same footing as an "[TO BE COMPLETED …]" statutory placeholder. Applies to every drafting tool (DPA, DPIA, IR, LI, Governance, Biometric, CPPA Risk / ADMT / Cybersecurity). The legacy "NOTE FOR LEGAL REVIEW — …" heading family is retired from body text; its historical evidence remains whitelisted for back-compat with pre-retarget batches. This anchor is scoped to the two canonical-close formulas and the legacy NOTE block only — genuine model self-narration outside those forms remains flaggable under the existing rubric line.

GRADER-CAL-1 A1 — AXIS CONSOLIDATION (BINDING):
The "formatting" axis carries ZERO weight in the overall score across every tool (both editorial and non-editorial). The rubric_internal_reasoning_leak check now scores under the HALLUCINATION dimension — leaked internal reasoning is a hallucination-adjacent defect, never a formatting defect. Continue to emit dimension_scores.formatting for schema back-compat (rendered as an advisory read-out only); do NOT treat formatting deductions as producing overall-score movement.

GRADER-CAL-1 A3 — POST-CUTOFF VERIFIED AUTHORITY ADDITIONS (do NOT flag; do NOT deduct):
- New York S2659B (Chapter 647 of the Laws of 2024, signed 2024-12-21) — amends N.Y. Gen. Bus. Law § 899-aa (SHIELD-Act breach-notification chain) to expand the "private information" definition to include medical information and health-insurance information, and to require notice to the Department of Financial Services in addition to the Attorney General / Department of State / Division of State Police. Reports citing S2659B / Chapter 647 / 2024-12-21 as current NY breach-notification law are CORRECT.
- New York A8872A (signed December 2024) — companion legislation shortening the outside notice window for breaches affecting NY residents to 30 days from discovery. Reports citing A8872A with the 30-day figure are CORRECT current law. Do NOT reconcile these against pre-2024 SHIELD-Act summaries in your training corpus.

GRADER-CAL-1 A4 — EMIT-GUARD (BINDING):
A "finding" that concludes the document was CORRECT on the point in question ("this citation is correct", "the report properly cites …", "no issue found") is not a finding — do NOT emit it. Findings surface DEFECTS; affirmations belong in strengths, if anywhere. This rule is enforced deterministically in the post-filter regardless of what the model emits.

R-TURN-1 ADDITIONS (2026-07-23, BINDING; do NOT flag as defects):

(1) § 7221 VERIFIED SUBSECTION MAP (item 3): the following § 7221 subsection paths are VERIFIED against the current 11 CCR text via _shared/admt-citation-registry.ts and are CORRECT depth citations — do NOT flag as "rubric_invented_admt_section" or as fabricated subsections: § 7221(a), § 7221(b), § 7221(b)(1), § 7221(b)(2), § 7221(b)(3), § 7221(c), § 7221(c)(1), § 7221(c)(4), § 7221(d), § 7221(e), § 7221(f), § 7221(g), § 7221(h), § 7221(i), § 7221(j), § 7221(k), § 7221(l), § 7221(m), § 7221(n), § 7221(n)(1), § 7221(n)(2). The § 7220/§ 7222 verified paths shipped previously remain in force. A fabrication verdict on any of these paths is a false positive and must be retracted; the registry is the single source of truth and the product prompt's VERIFIED-DEPTH RULE is regenerated from it at build time so drift is impossible.

(2) ADVERSE-EFFECTS ANALYSIS CALIBRATION (item 4): 11 CCR § 7152 REQUIRES the risk assessment to enumerate PROSPECTIVE harms with severity and likelihood judgments — an adverse_effects[] entry is defensibility-judged analytical projection ("what could go wrong if this processing proceeds"), NOT a record-fact claim. Do NOT flag prospective harm enumerations as "fabricated business facts" or as hallucination unless the entry is phrased as a present-tense record fact ("we suffered X on Y date"). Grade the DEFENSIBILITY of the projection (is the harm plausible on the processing described? does the severity/likelihood ranking cohere with the record?) — not the presence of a projection where none is recorded.

(3) DERIVED-TRIGGER NAMING (item 5): the normalised_intake object binds targeted_advertising as DERIVED from q5_sell_share = "Both" | "Share only" per the § 1798.140(ah) "sharing" definition (cross-context behavioural advertising IS a "share" under CCPA post-CPRA); it is not a distinct intake field. A report treating targeted_advertising as an operative trigger while the intake shows q5_sell_share = "Both" or "Share only" is CORRECT — do NOT flag the derivation as fabrication. This binds every fabrication check across CPPA Risk, ADMT, and DPIA.

(4) FIXTURE-CLASS GATING (item 6): the grader user turn may include a "GOLDEN_FIXTURE_SET: <tuning|holdout|adversarial>" header. When the header reads "adversarial" AND the fixture is a sibling-notes pattern (e.g. cppa-cyber adversarial ADMT-sibling notes on uniformly thin evidence), parallel template findings across siblings are the CORRECT honest output — the record supplies the same thin evidence to each sibling, so identical framing is the accurate reflection of the record, not a differentiation defect. Judge differentiation only where the record supplies materially different evidence between siblings.

(5) DRAFTING-INSTRUMENT CALIBRATION (item 7):
  (a) STATUTORY-DEFINITION RECITALS IN DRAFTING INSTRUMENTS — recitals or clauses in a DPA (or any drafting instrument) that recite the statutory definition of a term the clause governs (e.g. GDPR Art. 4(2) "processing" recital opening a processing-instructions clause) are STANDARD LEGAL DRAFTING, not boilerplate deductions. Do NOT flag statutory-definition recitals in drafting-instrument outputs as "boilerplate" or "unsupported deduction".
  (b) GOVERNANCE ORG_SET DEADLINE PLACEHOLDERS — governance org_set entries whose deadline field carries an illustrative default (e.g. "quarterly", "annually", "within 30 days of the effective date") accompanied by a "confirm and tailor to your operational cadence" advisory close are WORKING AS DESIGNED. Do NOT flag illustrative-default deadlines as fabrication or as invented dates; the placeholder is the anti-fabrication signal (the record supplied no cadence, so the tool named the professional default and flagged it for confirmation).
  (c) DPIA CONCLUSION OWNER PLACEHOLDERS — dpia conclusion.responsible_person and equivalent role fields MAY use "owner to be designated" (or equivalent placeholder) when the record supplies no roles; this is anti-fabrication scaffolding, not incompleteness. Do NOT flag "owner to be designated" as missing content — flag ONLY where the record NAMES a role and the report ignored it.

R-TURN-2 ADDITIONS (2026-07-23, BINDING; do NOT flag as defects):

(1) CPPA PENALTY FIGURES — STATUTORY BASE AND 2025-2026 CPI-ADJUSTED FIGURES ARE BOTH CORRECT: the Cal. Civ. Code § 1798.155(a) statutory base is $2,500 per unintentional violation and $7,500 per intentional or minor-related violation; the currently-in-effect CPI-adjusted figures for 2025-2026 are $2,663 and $7,988 respectively. Reports citing EITHER the statutory base (with an "as CPI-adjusted" adjunct) OR the adjusted figures ($2,663 / $7,988) are CORRECT current law — do NOT flag either pair as fabricated, unsupported, or inconsistent, and do NOT deduct on the choice between the two presentations. The canonical drafting form places the statutory base first with the CPI-adjusted figure as an adjunct clause.

(2) COUNSEL-VOICE-1 CANONICAL CLOSES — REINFORCE THE COUNSEL-VOICE-1 CARVE-OUT (item 1, ADMT): the two canonical closes ("…; further clarification is advisable." and "…; further internal investigation is advisable.") are DESIGNED product output — see the COUNSEL-VOICE-1 anchor above. When either close appears in an ADMT (or other CPPA-suite) output alongside a named object satisfying CPPA-HF3 E, do NOT flag the sentence as a hedge, a self-directed deliberation cue, an internal-reasoning leak, or a counsel referral. The banned hedge patterns are the OTHERS enumerated in the tools' NO INTERNAL-DELIBERATION rule ("further analysis is warranted", "further review may be appropriate", "the drafter recommends further inquiry", "additional consideration is needed") — those remain flaggable when they lack a named object.

(3) ADMT CLASSIFICATION/SCOPE-DETERMINATION ANCHOR (item 1(b)): classification and scope-determination duties (whether the service falls within any of the five § 7001(ddd) enumerated significant-decision categories, or whether an ADMT is being used for a significant decision) anchor to 11 CCR § 7200(a) alongside the § 7001(ddd) definition. Reports emitting the pattern "the business must determine whether [the service] falls within any of the five enumerated § 7001(ddd) categories (11 CCR § 7200(a), applying the § 7001(ddd) definition)" are CORRECT; do NOT flag § 7200(a) as misapplied for classification/scope-determination duties, and do NOT flag the pattern as a citation defect. § 7001(ddd) standing alone as the sole anchor for a classification DUTY (with no § 7200(a) operative cite) remains a defect.

(4) CPPA-RISK ENFORCEMENT FALLBACK — SILENCE IS CORRECT: where the CPPA-risk report contains no specific enforcement-corpus item and states the absence without a generic enforcement-posture claim (e.g. "The supplied enforcement corpus does not include an on-point CPPA action; specific enforcement examples are omitted."), that is CORRECT drafting under the R-TURN-2 fallback rewrite. Do NOT flag the absence-statement as incomplete or as a missing enforcement analysis; the reverse (a generic-posture claim like "the CPPA has signalled that X is an enforcement priority" WITHOUT a corpus anchor) is the defect.

R-TURN-3 ADDITIONS (2026-07-23, BINDING; do NOT flag as defects):

(1) LIA INTAKE_EVIDENCE ABSENCE CONVENTION (designed output — do NOT flag): each factor object in three_part_test.balancing_test.factors may carry an "evidence_absence" sibling field alongside "intake_evidence". When intake_evidence is [] (empty array), evidence_absence is a non-empty string in canonical form — "The record supplied to this assessment does not present [what is missing]; document [X] in the balancing record." — and the factor's reasoning characterises the absence rather than hedging into pseudo-evidence. This is the CORRECT output when the record supplies no relevant field for a factor: absence is stated as absence, never silently dropped, never converted into a fabricated "field: not stated" entry. Do NOT flag an empty intake_evidence paired with a populated evidence_absence as missing anchoring, and do NOT flag the canonical absence sentence as hedging, counsel-referral, or internal-reasoning leak. Judge substance normally (does evidence_absence name a real intake field the record could have populated? does the reasoning honour the absence?), but never deduct for the presence, shape, or use of the evidence_absence field.

(2) DPIA ART. 13 vs ART. 14 SOURCE-KEYED CITATIONS (designed output — do NOT flag): the DPIA framework cites GDPR Art. 13 for personal data collected DIRECTLY from the data subject and GDPR Art. 14 for personal data NOT obtained from the data subject (third-party, indirect, inferred, or incidentally captured), keyed to the SOURCE of the specific data flow under analysis. Reports that cite both articles in the same section BECAUSE the record enumerates data flows of both source types are CORRECT — do not flag as inconsistent, contradictory, or over-broad. Reports that cite only Art. 13 or only Art. 14 for a record with a single source type are CORRECT. A citation defect exists only where the report cites the wrong article for the stated source, or defaults to Art. 13 for indirectly-collected data.

(3) DPIA ART. 9(1) GROUNDING RULE (do NOT re-litigate): Art. 9(1)-health (or any Art. 9(1) special category) is engaged ONLY where the record STATES processing of that special category or facts from which the classification follows deterministically (e.g. "clinical triage data", "diagnosis codes", "medication history"). The ART. 9(1) PURPOSE RULE (FF-4 pd7) and its extension to health data are the operative anchors. A report that DECLINES to characterise data as Art. 9(1)-health absent an explicit or deterministic record signal is CORRECT drafting, not incompleteness — the record's silence on health-data status is the reason to abstain.

(4) DPA CLAUSE PARTY-VOICE (designed output — do NOT flag): controller-specific obligations are drafted in the Controller's voice ("Controller shall …") and processor-specific obligations in the Processor's voice ("Processor shall …"). Generic "the Parties shall …" is reserved for mutual duties (e.g. cooperation, confidentiality, notice mechanics). Do NOT flag Controller-voice or Processor-voice clauses as inconsistent with the parties-shall phrasing used in mutual duty clauses, and do NOT demand every duty be recast in "the Parties shall" form.

(5) DPA CONDITIONAL MODULES (designed output — do NOT flag): targeted-advertising, minors / children's-data, HIPAA/PHI, GLBA, and AI/ML-training clauses appear ONLY when the record establishes the corresponding processing fact (SPECULATIVE-CLAUSE BAN, REBUILD-DPA T2 as extended in R-TURN-3). A DPA that OMITS a targeted-advertising or minors clause because the record is silent on that fact is CORRECT — do not flag the omission as incomplete coverage of state-law modules. A DPA that INCLUDES the clause because the record establishes the fact is likewise CORRECT.

POST-C1-FIX-2 ADDITIONS (2026-07-23, BINDING; do NOT flag as defects):

(1) BIOMETRIC / CYBER / GOVERNANCE — SUGGESTED OWNER (CONFIRM) FORM IS DESIGNED OUTPUT: where a functional owner is DERIVED from the intake's orgType (e.g. "Suggested owner (confirm): the HR lead, in coordination with the DPO or Head of Privacy") the "Suggested owner (confirm):" prefix marks the owner as a professional-default suggestion, NOT as a record-fact claim about who occupies the role. Do NOT flag the "Suggested owner (confirm): <role>" form as an invented internal role, an unsupported business claim, or a fabricated ownership assertion. The bare "Owner: <named individual>" form (with a specific personal name that the record did not supply) remains a fabrication defect. The distinction is: SUGGESTED-OWNER-CONFIRM is designed output; a BARE assertion naming a role the intake never mentioned remains a deduction defect.

(2) ADMT NEUTRAL FALLBACK PHRASE IS DESIGNED OUTPUT: the phrase "the applicable ADMT-subchapter provision" appearing in an ADMT report is a NEUTRAL post-resolver fallback used when the model's citation could not be resolved to a pinpoint from the ADMT-citation registry. It replaces the previously-used range-label fallback (which caused the h7_admt_blanket_range defect class). Do NOT flag "the applicable ADMT-subchapter provision" as a missing citation, an unresolved variable, or a placeholder defect. The report retains its other pinpoint citations; the neutral phrase is the correct fallback when a specific pinpoint is unavailable.

(3) FTC RITE AID CITATION — CANONICAL FORM: the correct citation for the FTC Rite Aid facial-recognition matter is "FTC v. Rite Aid Corp., Case No. 2:23-cv-5023 (E.D. Pa. Dec. 19, 2023); FTC Matter/File No. 2023190". Do NOT flag this canonical form as inaccurate. Earlier drafts using "FTC File No. 072-3121" were incorrect and have been corrected in the biometric template.

C2-2 ADDITION (2026-07-24, BINDING; do NOT flag as defects):

(1) IN-PROSE FSOR CITATIONS ARE DESIGNED OUTPUT: ADMT and CPPA-Cybersecurity now receive an FSOR-anchor injection block at assembly time (see _shared/fsor-anchor-block.ts). The injected block is DRAFTING CONTEXT ONLY — the generator is instructed NEVER to echo the internal bracketed "[Agency position — FSOR: <citation>, <package>, <page_ref>]: …" form into report prose, and instead to weave the Agency's position into the analysis in plain professional prose form (e.g., "The Agency's Final Statement of Reasons for 11 CCR § 7001(ddd) explains that behavioural advertising was removed from the significant-decision definition …" or "Per the CPPA's FSOR (Appendix, p. 25), zero-trust architecture was declined as a mandated component …"). Reports containing plain-prose FSOR citations — including the tokens "Final Statement of Reasons", "FSOR", "the Agency explained", "the Agency declined", or an "Appendix, p. NN" page cite — anchored to a real § 7001(ddd) / § 7001(e) / § 7001(e)(1) / § 7123 provision are CORRECT designed output; do NOT flag them as invented Agency positions, unsupported business claims, internal-reasoning leaks, or fabricated commentary. The bracketed injection format itself would be a leak IF echoed verbatim; grade that separately under the existing internal-reasoning-leak rubric.
`.trim();
