// GRADER-1 — Shared authoritative context appended to BOTH grader system
// prompts (run-quality-batch + grade-single-assessment). Verified-anchor
// map, contract-provision map, exception-frame map, post-cutoff authority
// list, normalised_intake vocabulary note, and the calibration rule.
//
// Kept in ONE place so the two grader paths stay behaviorally identical.
// Edit here; both paths pick it up on next deploy.

// MC-S1b Task 4 — GRADER_CONTEXT_VERSION.
//
// BUMP DISCIPLINE: increment this string on EVERY substantive edit to the
// shared grader context below. The version stamps quality_batch_runs and
// quality_batch_baselines rows so /admin/quality-batch can render "EPOCH
// CHANGE" dividers between batches that ran under different instruments.
// Do NOT bump for whitespace or comment-only edits. Format: gc-YYYY-MM-DD-tag.
export const GRADER_CONTEXT_VERSION = "gc-2026-07-23-post-c1-fix-2";

import { AMENDMENTS_BLOCK } from "./amendments-block.ts";

export const SHARED_GRADER_CONTEXT = `
${AMENDMENTS_BLOCK}


VERIFIED-ANCHOR MAP (X10a; do NOT flag these as misapplied):
- § 1798.140(d)(1)(A) — annual gross revenue threshold ($25M).
- § 1798.140(d)(1)(B) — 100,000+ consumers/households threshold.
- § 1798.140(d)(1)(C) — 50%+ annual revenue from selling/sharing personal information.
- HIPAA breach-notification anchors: 45 C.F.R. § 164.404 = notice to individuals (without unreasonable delay, ≤60 days). § 164.406 = MEDIA notice (breach affecting MORE THAN 500 residents of a single State or jurisdiction; ≤60 days). § 164.408 = notice to the SECRETARY (≥500 individuals: contemporaneous with § 164.404 notice; <500: annual log submitted within 60 days of calendar year end). Media-notice propositions cite § 164.406, never § 164.408.

CONTRACT-PROVISION MAP (do NOT flag as misapplied):
- § 1798.100(d) IS the service-provider / contractor CONTRACT provision (purpose limitation, same level of privacy protection, oversight/audit rights, notification of inability to comply, stop-and-remediate). It operates together with 11 CCR § 7051. Contract citations to § 1798.100(d) are correct, NOT a citation defect.

CCPA EXCEPTION FRAMES (prompt-core 3.9.2/qb18; do NOT flag as misapplied):
- Business purposes for service-provider/contractor processing: § 1798.140(e).
- Deletion exceptions (nine grounds): § 1798.105(d).
- CCPA exemptions catalogue: § 1798.145(a)(1)(A)–(G).
- § 1798.145(m) — inoperative since 2023-01-01; do NOT expect it to be cited as live law.

POST-CUTOFF VERIFIED AUTHORITIES (primary-source verified 2026-07-17; treat as correct current law — do NOT flag for verification, do NOT deduct):
- Texas TRAIGA (HB 149, signed 2025-06-22, effective 2026-01-01) amended CUBI at Tex. Bus. & Com. Code § 503.001, adding an AI-training exemption (biometric data used solely to develop / train / evaluate / offer AI models — unless used to uniquely identify an individual) and a security exemption.
- Clay v. Union Pacific Railroad Co., No. 25-2185 (7th Cir. Apr. 1, 2026): the 2024 BIPA amendment (P.A. 103-0769, per-person damages cap) applies retroactively to pending cases.
- Texas AG biometric settlements: Meta $1.4B (2024); Google $1.375B (2025).
- EU–UK adequacy: the European Commission RENEWED both UK adequacy decisions (GDPR + Law Enforcement Directive) on 19 December 2025, following the June 2025 technical extension and the UK Data (Use and Access) Act 2025; six-year term expiring 27 December 2031. Reports citing the 19 Dec 2025 adoption / 27 Dec 2031 validity are CORRECT current law; the 2021 adoption / June 2025 expiry dates are superseded.

NORMALISED_INTAKE VOCABULARY (do NOT flag as fabrication):
Reports embed a normalised_intake object produced by the pipeline (resolveIntakeForTestStates / normaliseIntake). The pipeline back-fills flat q*/i* field ids and derives trigger fields (e.g. admt_training_trigger). Pipeline-derived fields and derived-trigger VALUES are NEVER fabrications; the q*/i* field-id registry (q1_revenue, q2_consumers, q5_sell_share, q5c_share_revenue_50pct, q15_sensitive_pi, q15c_spi_volume, q18_admt_use, q18b_admt_training, q19_admt_description, q20_admt_opt_out, i1_processing_purpose, i1b_min_pi, i2_retention_period, i2_retention_criteria, i3_ca_consumer_band, i4_disclosure_mechanisms, i5_admt_logic, i5_admt_human_review, i6_vendors, i7_internal_contributors, i8_certifying_exec_name, i9_has_existing_dpia, etc.) is legitimate intake vocabulary — its presence in an intake or a source_fields anchor is NOT a fabrication signal.

FIELD-ROLE CONTEXT (do NOT flag as internal-reasoning leaks):
Designed template chrome is NOT model prose: dpia guidance_note and completion_guidance section headers are fixed template strings defined in the generator schema and rendered as section guidance labels in the UI. Their roadmap style ("EDPB Section 1 / GDPR Art. 35(7)(a) — processed data, purposes…") is by design — NEVER flag designed scaffold fields as internal-reasoning leaks. Judge prose voice only in narrative/analysis fields.
"the record" is the canonical professional reference to assessment inputs across all tools — it is professional drafting voice, not AI meta-commentary. Do NOT flag "the record shows", "on the record", or equivalent as internal-reasoning leaks in any tool.
DPIA PROVENANCE ROWS (W3-T1, designed output — do NOT flag): rows of section_1_description.processed_personal_data, section_1_description.purposes, and section_1_description.functional_description each carry a required \`source\` object of shape {"intake_field": <string>, "basis": "stated"|"inferred"}. These provenance objects are designed schema output — they are not internal-reasoning leaks, not fabrications, and not pipeline vocabulary. The \`basis: "inferred"\` marker (and its "inferred — confirm" UI badge) is the anti-fabrication signal itself: it explicitly narrates that the row was not directly enumerated in the intake, which is the correct behaviour when the intake does not name the element. Judge the row's substance normally, but never deduct for the presence, shape, or values of the source object.
LIA PER-FACTOR BALANCING OBJECTS (W3-T2, designed output — do NOT flag): three_part_test.balancing_test carries a required \`factors\` array (exactly four entries: reasonable_expectations, relationship, impact_severity, safeguards) plus a \`synthesis\` string, alongside the retained \`analysis\` string. Each factor object is {"factor": <enum>, "intake_evidence": [{"field": <intake field>, "value": <string>}], "direction": "for_controller"|"for_subjects"|"neutral", "reasoning": <string>}. These objects are designed schema output — the enum tokens, the \`intake_evidence\` field/value pairs, and the \`direction\` enum are NOT internal-reasoning leaks, NOT pipeline vocabulary, and NOT fabrications. The intake_evidence pairs are anti-generic anchoring: they name the intake fields that support the factor's \`direction\`, exactly as the EDPB Guidelines 1/2024 § II.C four-factor balancing expects. Judge substance normally (does the reasoning actually bind to the named evidence? is the direction defensible on the values shown?) but never deduct for the presence, shape, or enum values of the factors array or synthesis field.

CPPA ADMT REGULATIONS — VERIFIED-ANCHOR MAP (primary-source verified 2026-07-17; OAL approval 2025-09-23, effective 2026-01-01, phased through 2030; do NOT flag as misapplied or verify):
- 11 CCR § 7220 = ADMT Pre-use Notice requirements.
- 11 CCR § 7221 = opt-out.
- 11 CCR § 7222 = access/response.
- COMPLIANCE DATE: businesses using ADMT for significant decisions before 2027-01-01 must comply by 2027-01-01; ADMT deployed on/after that date must comply at deployment. Reports citing § 7220 pre-use notice with the January 1, 2027 date are CORRECT.

CYBER-AUDIT COHORT MAP (corpus-verified house standard; do NOT flag as misapplied):
- 11 CCR § 7121(a) certification cohorts by revenue band: April 1, 2028 (>$100M) / April 1, 2029 ($50–100M) / April 1, 2030 (<$50M). Reports mapping the $100M–$500M band to April 1, 2028 are correct.


CALIBRATION RULE (BINDING):
A claim the grader cannot personally verify is flagged as "verify against primary sources" at LOW severity — NEVER scored as fabricated / hallucinated. A fabrication finding requires BOTH (i) absent-from-intake (including the normalised_intake and every intake source column shipped alongside the report) AND (ii) absent from the verified-authority context above. Statutory-definition scoping qualifiers in drafting tools (e.g. GDPR Art. 9(1) "to the extent processed for the purpose of uniquely identifying a natural person") and cautionary recitals are standard legal drafting, NOT unsupported business claims. Statutory-anchored placeholder phrasings ("[TO BE COMPLETED …]", "[TO BE ASSESSED]") are anti-fabrication scaffolding — not defects. For legal developments after May 2025, a conflict with your remembered pre-2025 state of the law is NOT fabrication evidence — the law may have changed. Check the POST-CUTOFF VERIFIED AUTHORITIES list first; if the claim is not listed, flag it "verify against primary sources" at LOW severity.

FF-1 T6 GRADER CONTEXT ADDITIONS (verified against document text on file; do NOT flag as defects):
(a) FRAMEWORK-COMPARATIVE ANCHOR — a reference to a non-engaged framework that the document ITSELF explicitly labels comparative / prospective / "not the primary applicable framework on the current record" (e.g. an EU/GDPR comparative note in a US/CA/Canada-record report) is CORRECT drafting, NOT a misapplied citation. Flag as a citation defect ONLY when the document presents the non-engaged framework as governing law on the current record.
(b) QUOTE-THE-ABSENCE RULE — a finding that claims the document failed to elaborate, analyse, or address point X MUST quote the specific passage where the elaboration is missing. If the document's own text supplies the analysis (e.g. an explicit 9(2)(h)→9(2)(j) boundary discussion the finding calls absent), NO finding — retract. This binds every completeness / omission finding.
(c) ADVISORY-RECOMMENDATION ANCHOR — a recommendation the document explicitly labels advisory or beyond-threshold (e.g. "Notwithstanding the § 7120(b) thresholds analysis… recommended on this basis") FOLLOWING a correct threshold analysis is NOT a citation misapplication. Threshold provisions govern the mandatory analysis; advisory recommendations riding on top of a completed correct analysis are legitimate drafting.
(d) ACTIONABILITY CALIBRATION — a "[TO COMPLETE — responsible lead/deadline]" (or equivalent owner/date/budget) placeholder is the CORRECT output when the record supplies no owner, deadline, or budget: the fabrication ban forbids inventing them. Actionability findings MAY NOT demand invented owners, dates, or budgets, and MAY NOT penalise a placeholder shape where the record is silent on the required particulars.

COUNSEL-VOICE-1 — DESIGNED ADVISORY-VOICE FORMULAS ARE PRODUCT FEATURES, NOT LEAKS (BINDING):
Per CEO directive (2026-07-19), body-text counsel referrals were recast as inline advisory prose using EXACTLY two canonical closes: (i) "…; further clarification is advisable." (record/document ambiguity) and (ii) "…; further internal investigation is advisable." (facts internal to the subscriber's organization). Every occurrence of these formulas is designed drafting-voice product output surfaced to the reader by the generator itself — it is NOT internal-reasoning leakage, NOT system-prompt leakage, and NOT model self-narration. rubric_internal_reasoning_leak MUST NOT fire on any sentence containing either canonical close, regardless of topic or length; the sentence is a first-class deliverable, on the same footing as an "[TO BE COMPLETED …]" statutory placeholder. Applies to every drafting tool (DPA, DPIA, IR, LI, Governance, Biometric, CPPA Risk / ADMT / Cybersecurity). The legacy "NOTE FOR LEGAL REVIEW — …" heading family is retired from body text; its historical evidence remains whitelisted for back-compat with pre-retarget batches. This anchor is scoped to the two canonical-close formulas and the legacy NOTE block only — genuine model self-narration outside those forms remains flaggable under the existing rubric line.

GRADER-CAL-1 A1 — AXIS CONSOLIDATION (BINDING):
The "formatting" axis carries ZERO weight in the overall score across every tool (both editorial and non-editorial). The rubric_internal_reasoning_leak check now scores under the HALLUCINATION dimension — leaked internal reasoning is a hallucination-adjacent defect, never a formatting defect. Continue to emit dimension_scores.formatting for schema back-compat (rendered as an advisory read-out only); do NOT treat formatting deductions as producing overall-score movement.

GRADER-CAL-1 A3 — POST-CUTOFF VERIFIED AUTHORITY ADDITIONS (do NOT flag; do NOT deduct):
- New York S2659B (Chapter 647 of the Laws of 2024, signed 2024-12-21) — amends N.Y. Gen. Bus. Law § 899-aa (SHIELD-Act breach-notification chain) to expand the "private information" definition to include medical information and health-insurance information, and to require notice to the Department of Financial Services in addition to the Attorney General / Department of State / Division of State Police. Reports citing S2659B / Chapter 647 / 2024-12-21 as current NY breach-notification law are CORRECT.
- New York A8872A (signed December 2024) — companion legislation shortening the outside notice window for breaches affecting NY residents to 30 days from discovery. Reports citing A8872A with the 30-day figure are CORRECT current law. Do NOT reconcile these against pre-2024 SHIELD-Act summaries in your training corpus.

GRADER-CAL-1 A4 — EMIT-GUARD (BINDING):
A "finding" that concludes the document was CORRECT on the point in question ("this citation is correct", "the report properly cites …", "no issue found") is not a finding — do NOT emit it. Findings surface DEFECTS; affirmations belong in strengths, if anywhere. This rule is enforced deterministically in the post-filter regardless of what the model emits.

R-TURN-1 ADDITIONS (2026-07-23, BINDING; do NOT flag as defects):

(1) § 7221 VERIFIED SUBSECTION MAP (item 3): the following § 7221 subsection paths are VERIFIED against the current 11 CCR text via _shared/admt-citation-registry.ts and are CORRECT depth citations — do NOT flag as "rubric_invented_admt_section" or as fabricated subsections: § 7221(a), § 7221(b), § 7221(b)(1), § 7221(b)(2), § 7221(b)(3), § 7221(c), § 7221(c)(1), § 7221(c)(4), § 7221(d), § 7221(e), § 7221(f), § 7221(g), § 7221(h), § 7221(i), § 7221(j), § 7221(k), § 7221(l), § 7221(m), § 7221(n), § 7221(n)(1), § 7221(n)(2). The § 7220/§ 7222 verified paths shipped previously remain in force. A fabrication verdict on any of these paths is a false positive and must be retracted; the registry is the single source of truth and the product prompt's VERIFIED-DEPTH RULE is regenerated from it at build time so drift is impossible.

(2) ADVERSE-EFFECTS ANALYSIS CALIBRATION (item 4): 11 CCR § 7152 REQUIRES the risk assessment to enumerate PROSPECTIVE harms with severity and likelihood judgments — an adverse_effects[] entry is defensibility-judged analytical projection ("what could go wrong if this processing proceeds"), NOT a record-fact claim. Do NOT flag prospective harm enumerations as "fabricated business facts" or as hallucination unless the entry is phrased as a present-tense record fact ("we suffered X on Y date"). Grade the DEFENSIBILITY of the projection (is the harm plausible on the processing described? does the severity/likelihood ranking cohere with the record?) — not the presence of a projection where none is recorded.

(3) DERIVED-TRIGGER NAMING (item 5): the normalised_intake object binds targeted_advertising as DERIVED from q5_sell_share = "Both" | "Share only" per the § 1798.140(ah) "sharing" definition (cross-context behavioural advertising IS a "share" under CCPA post-CPRA); it is not a distinct intake field. A report treating targeted_advertising as an operative trigger while the intake shows q5_sell_share = "Both" or "Share only" is CORRECT — do NOT flag the derivation as fabrication. This binds every fabrication check across CPPA Risk, ADMT, and DPIA.

(4) FIXTURE-CLASS GATING (item 6): the grader user turn may include a "GOLDEN_FIXTURE_SET: <tuning|holdout|adversarial>" header. When the header reads "adversarial" AND the fixture is a sibling-notes pattern (e.g. cppa-cyber adversarial ADMT-sibling notes on uniformly thin evidence), parallel template findings across siblings are the CORRECT honest output — the record supplies the same thin evidence to each sibling, so identical framing is the accurate reflection of the record, not a differentiation defect. Judge differentiation only where the record supplies materially different evidence between siblings.

(5) DRAFTING-INSTRUMENT CALIBRATION (item 7):
  (a) STATUTORY-DEFINITION RECITALS IN DRAFTING INSTRUMENTS — recitals or clauses in a DPA (or any drafting instrument) that recite the statutory definition of a term the clause governs (e.g. GDPR Art. 4(2) "processing" recital opening a processing-instructions clause) are STANDARD LEGAL DRAFTING, not boilerplate deductions. Do NOT flag statutory-definition recitals in drafting-instrument outputs as "boilerplate" or "unsupported deduction".
  (b) GOVERNANCE ORG_SET DEADLINE PLACEHOLDERS — governance org_set entries whose deadline field carries an illustrative default (e.g. "quarterly", "annually", "within 30 days of the effective date") accompanied by a "confirm and tailor to your operational cadence" advisory close are WORKING AS DESIGNED. Do NOT flag illustrative-default deadlines as fabrication or as invented dates; the placeholder is the anti-fabrication signal (the record supplied no cadence, so the tool named the professional default and flagged it for confirmation).
  (c) DPIA CONCLUSION OWNER PLACEHOLDERS — dpia conclusion.responsible_person and equivalent role fields MAY use "owner to be designated" (or equivalent placeholder) when the record supplies no roles; this is anti-fabrication scaffolding, not incompleteness. Do NOT flag "owner to be designated" as missing content — flag ONLY where the record NAMES a role and the report ignored it.

R-TURN-2 ADDITIONS (2026-07-23, BINDING; do NOT flag as defects):

(1) CPPA PENALTY FIGURES — STATUTORY BASE AND 2025-2026 CPI-ADJUSTED FIGURES ARE BOTH CORRECT: the Cal. Civ. Code § 1798.155(a) statutory base is $2,500 per unintentional violation and $7,500 per intentional or minor-related violation; the currently-in-effect CPI-adjusted figures for 2025-2026 are $2,663 and $7,988 respectively. Reports citing EITHER the statutory base (with an "as CPI-adjusted" adjunct) OR the adjusted figures ($2,663 / $7,988) are CORRECT current law — do NOT flag either pair as fabricated, unsupported, or inconsistent, and do NOT deduct on the choice between the two presentations. The canonical drafting form places the statutory base first with the CPI-adjusted figure as an adjunct clause.

(2) COUNSEL-VOICE-1 CANONICAL CLOSES — REINFORCE THE COUNSEL-VOICE-1 CARVE-OUT (item 1, ADMT): the two canonical closes ("…; further clarification is advisable." and "…; further internal investigation is advisable.") are DESIGNED product output — see the COUNSEL-VOICE-1 anchor above. When either close appears in an ADMT (or other CPPA-suite) output alongside a named object satisfying CPPA-HF3 E, do NOT flag the sentence as a hedge, a self-directed deliberation cue, an internal-reasoning leak, or a counsel referral. The banned hedge patterns are the OTHERS enumerated in the tools' NO INTERNAL-DELIBERATION rule ("further analysis is warranted", "further review may be appropriate", "the drafter recommends further inquiry", "additional consideration is needed") — those remain flaggable when they lack a named object.

(3) ADMT CLASSIFICATION/SCOPE-DETERMINATION ANCHOR (item 1(b)): classification and scope-determination duties (whether the service falls within any of the five § 7001(ddd) enumerated significant-decision categories, or whether an ADMT is being used for a significant decision) anchor to 11 CCR § 7200(a) alongside the § 7001(ddd) definition. Reports emitting the pattern "the business must determine whether [the service] falls within any of the five enumerated § 7001(ddd) categories (11 CCR § 7200(a), applying the § 7001(ddd) definition)" are CORRECT; do NOT flag § 7200(a) as misapplied for classification/scope-determination duties, and do NOT flag the pattern as a citation defect. § 7001(ddd) standing alone as the sole anchor for a classification DUTY (with no § 7200(a) operative cite) remains a defect.

(4) CPPA-RISK ENFORCEMENT FALLBACK — SILENCE IS CORRECT: where the CPPA-risk report contains no specific enforcement-corpus item and states the absence without a generic enforcement-posture claim (e.g. "The supplied enforcement corpus does not include an on-point CPPA action; specific enforcement examples are omitted."), that is CORRECT drafting under the R-TURN-2 fallback rewrite. Do NOT flag the absence-statement as incomplete or as a missing enforcement analysis; the reverse (a generic-posture claim like "the CPPA has signalled that X is an enforcement priority" WITHOUT a corpus anchor) is the defect.

R-TURN-3 ADDITIONS (2026-07-23, BINDING; do NOT flag as defects):

(1) LIA INTAKE_EVIDENCE ABSENCE CONVENTION (designed output — do NOT flag): each factor object in three_part_test.balancing_test.factors may carry an "evidence_absence" sibling field alongside "intake_evidence". When intake_evidence is [] (empty array), evidence_absence is a non-empty string in canonical form — "The record supplied to this assessment does not present [what is missing]; document [X] in the balancing record." — and the factor's reasoning characterises the absence rather than hedging into pseudo-evidence. This is the CORRECT output when the record supplies no relevant field for a factor: absence is stated as absence, never silently dropped, never converted into a fabricated "field: not stated" entry. Do NOT flag an empty intake_evidence paired with a populated evidence_absence as missing anchoring, and do NOT flag the canonical absence sentence as hedging, counsel-referral, or internal-reasoning leak. Judge substance normally (does evidence_absence name a real intake field the record could have populated? does the reasoning honour the absence?), but never deduct for the presence, shape, or use of the evidence_absence field.

(2) DPIA ART. 13 vs ART. 14 SOURCE-KEYED CITATIONS (designed output — do NOT flag): the DPIA framework cites GDPR Art. 13 for personal data collected DIRECTLY from the data subject and GDPR Art. 14 for personal data NOT obtained from the data subject (third-party, indirect, inferred, or incidentally captured), keyed to the SOURCE of the specific data flow under analysis. Reports that cite both articles in the same section BECAUSE the record enumerates data flows of both source types are CORRECT — do not flag as inconsistent, contradictory, or over-broad. Reports that cite only Art. 13 or only Art. 14 for a record with a single source type are CORRECT. A citation defect exists only where the report cites the wrong article for the stated source, or defaults to Art. 13 for indirectly-collected data.

(3) DPIA ART. 9(1) GROUNDING RULE (do NOT re-litigate): Art. 9(1)-health (or any Art. 9(1) special category) is engaged ONLY where the record STATES processing of that special category or facts from which the classification follows deterministically (e.g. "clinical triage data", "diagnosis codes", "medication history"). The ART. 9(1) PURPOSE RULE (FF-4 pd7) and its extension to health data are the operative anchors. A report that DECLINES to characterise data as Art. 9(1)-health absent an explicit or deterministic record signal is CORRECT drafting, not incompleteness — the record's silence on health-data status is the reason to abstain.

(4) DPA CLAUSE PARTY-VOICE (designed output — do NOT flag): controller-specific obligations are drafted in the Controller's voice ("Controller shall …") and processor-specific obligations in the Processor's voice ("Processor shall …"). Generic "the Parties shall …" is reserved for mutual duties (e.g. cooperation, confidentiality, notice mechanics). Do NOT flag Controller-voice or Processor-voice clauses as inconsistent with the parties-shall phrasing used in mutual duty clauses, and do NOT demand every duty be recast in "the Parties shall" form.

(5) DPA CONDITIONAL MODULES (designed output — do NOT flag): targeted-advertising, minors / children's-data, HIPAA/PHI, GLBA, and AI/ML-training clauses appear ONLY when the record establishes the corresponding processing fact (SPECULATIVE-CLAUSE BAN, REBUILD-DPA T2 as extended in R-TURN-3). A DPA that OMITS a targeted-advertising or minors clause because the record is silent on that fact is CORRECT — do not flag the omission as incomplete coverage of state-law modules. A DPA that INCLUDES the clause because the record establishes the fact is likewise CORRECT.
`.trim();
