// ADMT ANALOGY HOOKS — pinned, generated file (doc 213 / doc 222).
//
// Generated by `generate-corpus-hooks` (action "generate") from RATIFIED
// `public.authority_hooks` rows. Do not hand-edit the hooks array:
// regenerate it. Run: admt-hooks-v2-2026-09-09-0
//
// EXCLUDED ROWS (named, not silently dropped):
//   752709f6-9f23-4453-a922-5083c292fb40#v1 — decision vacated on appeal — never a hook source (doc 222 §2.7)

import type { AuthorityHook } from "../../../../_shared/corpus/hook-types.ts";


export const ADMT_HOOKS_VERSION = "admt-hooks-v2-2026-09-09-0";

export const ADMT_HOOKS: readonly AuthorityHook[] = [
  {
    "hook_id": "cppa_fsor_commentary:7f616c44-b6f9-43b0-9891-1fdbd501bffc:v1",
    "profile_id": "1af71e39-c5a0-44cb-b85f-4ff9533d5b66",
    "source_row_id": "7f616c44-b6f9-43b0-9891-1fdbd501bffc",
    "fact_atoms": [
      "state:intake.notice_has_specific_purpose=No — uses generic language"
    ],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [
      "state:intake.notice_has_specific_purpose=No — uses generic language"
    ],
    "finding_span": "to prevent businesses from using vague language about their planned use of ADMT",
    "fact_pattern_paraphrase": "a Pre-use Notice describing the ADMT's purpose in general terms, such as to improve our services, without saying what the ADMT actually decides",
    "finding_paraphrase": "vague language about a planned use of ADMT undermines consumers' exercise of their rights to opt out of and access ADMT, so a Pre-use Notice must describe the purpose in more specific terms",
    "settledness": "R1",
    "posture": "rejected",
    "factor_id": "Notice content",
    "bears_on_element": "Notice content",
    "authority_label": "California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7220(c)(1), p. 45",
    "regulator": "the CPPA",
    "relevance": {
      "instrument": "CPPA Regulations",
      "factor_ids": [
        "Notice content"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [],
      "outcome_posture": "rejected"
    },
    "authority_label_short": "CPPA Final Statement of Reasons",
    "hook_version": 1,
    "source_status": "regulator_guidance",
    "status_label": "CPPA Final Statement of Reasons — agency position, primary regulator commentary",
    "verb": "states",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "page",
      "ref": "p. 45",
      "anchor_span": "to prevent businesses from using vague language about their planned use of ADMT"
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The company has described the ADMT's purpose in its Pre-use Notice in general terms — something like \"to improve our services,\" without saying what the ADMT actually decides. The CPPA's regulations require more specific language than that (11 CCR § 7220(c)(1)). In its Final Statement of Reasons, the CPPA explained why: vague language about a planned ADMT use \"undermines consumers' exercise of their rights to opt-out of and access ADMT\" — a person cannot meaningfully decide whether to opt out of something the notice never actually describes. Whether this company's stated purpose clears that bar is a judgment about this company's own words, not a fixed word count or template. Section 3 addresses whether the notice's purpose statement meets this standard. (California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7220(c)(1).)",
    "status_in_citation": false
  },
  {
    "hook_id": "cppa_fsor_commentary:be2a91bc-0d33-4cd8-a008-a82306816a50:v1",
    "profile_id": "2b0798db-54cb-462b-9d9c-7f1a7f1c65e2",
    "source_row_id": "be2a91bc-0d33-4cd8-a008-a82306816a50",
    "fact_atoms": [],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [],
    "finding_span": "whether it creates new negative impacts or increases the magnitude or likelihood of previously identified negative impacts or diminishes",
    "fact_pattern_paraphrase": "an ADMT, its training data, its safeguards, or its decision use having changed since the business's last risk assessment was completed",
    "finding_paraphrase": "a change is material, and requires an updated risk assessment, where it creates new negative impacts, increases the magnitude or likelihood of previously identified negative impacts, or diminishes the effectiveness of safeguards",
    "settledness": "R1",
    "posture": "rejected",
    "factor_id": "Governance, Record Sufficiency, and Related Risk-Assessment Obligations",
    "bears_on_element": "Governance, Record Sufficiency, and Related Risk-Assessment Obligations",
    "authority_label": "California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7155(a)(3), Appendix p. 148",
    "regulator": "the CPPA",
    "relevance": {
      "instrument": "CPPA Regulations",
      "factor_ids": [
        "Governance, Record Sufficiency, and Related Risk-Assessment Obligations"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [],
      "outcome_posture": "rejected"
    },
    "authority_label_short": "CPPA Final Statement of Reasons",
    "hook_version": 1,
    "source_status": "regulator_guidance",
    "status_label": "CPPA Final Statement of Reasons — agency position, primary regulator commentary",
    "verb": "states",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "page",
      "ref": "Appendix, p. 148",
      "anchor_span": "whether it creates new negative impacts or increases the magnitude or likelihood of previously identified negative impacts or diminishes"
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "A risk assessment is not a one-time document. The CPPA's regulations require it to be updated when the processing changes in a way that matters (11 CCR § 7155(a)(3)). The Final Statement of Reasons gives the actual test: a change is material if it \"creates new negative impacts,\" \"increases the magnitude or likelihood of previously identified negative impacts,\" or \"diminishes the effectiveness of safeguards.\" The Agency specifically rejected a narrower version of this test, saying the narrower wording would let more changes go unassessed. If this company's ADMT, its training data, its safeguards, or its decision use have changed since its last risk assessment, this standard — not a general sense that \"nothing major happened\" — is what decides whether an update was required. Whether that update was completed here is a fact about this company's own record. (California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7155(a)(3), Appendix p. 148.)",
    "status_in_citation": false
  },
  {
    "hook_id": "cppa_fsor_commentary:4b2d39e1-4cd0-4579-9c0f-35f06e476120:v1",
    "profile_id": "2bc06d49-e456-4c8a-92a9-2b13eedb9070",
    "source_row_id": "4b2d39e1-4cd0-4579-9c0f-35f06e476120",
    "fact_atoms": [],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [],
    "finding_span": "based on its observations in the marketplace of businesses inappropriately using cookie banners or controls",
    "fact_pattern_paraphrase": "a business whose only method for a consumer to opt out of ADMT is a cookie banner or cookie-consent tool",
    "finding_paraphrase": "a cookie banner or cookie control is not a valid method for submitting an ADMT opt-out request, a prohibition the Agency kept based on its observations of businesses inappropriately using cookie banners or controls",
    "settledness": "R1",
    "posture": "rejected",
    "factor_id": "Opt-out pathway",
    "bears_on_element": "Opt-out pathway",
    "authority_label": "California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7221(c)(4), Appendix p. 212",
    "regulator": "the CPPA",
    "relevance": {
      "instrument": "CPPA Regulations",
      "factor_ids": [
        "Opt-out pathway"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [],
      "outcome_posture": "rejected"
    },
    "authority_label_short": "CPPA Final Statement of Reasons",
    "hook_version": 1,
    "source_status": "regulator_guidance",
    "status_label": "CPPA Final Statement of Reasons — agency position, primary regulator commentary",
    "verb": "states",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "page",
      "ref": "Appendix, p. 212",
      "anchor_span": "based on its observations in the marketplace of businesses inappropriately using cookie banners or controls"
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The company's only method for a consumer to opt out of ADMT is a cookie banner or cookie-consent tool. The CPPA's regulations specifically prohibit that (11 CCR § 7221(c)(4)). The Agency explained in its Final Statement of Reasons why it kept this rule despite pushback: it was \"based on its observations in the marketplace of businesses inappropriately using cookie banners or controls\" as a substitute for a real ADMT opt-out — the concern is not cookies as such, but businesses burying the ADMT opt-out inside a mechanism built for something else. A cookie banner does not satisfy § 7221(c)'s requirement for a dedicated ADMT opt-out method, regardless of how it is worded. Section 4 addresses whether this company has an opt-out method beyond its cookie tool. (California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7221(c)(4), Appendix p. 212.)",
    "status_in_citation": false
  },
  {
    "hook_id": "cppa_fsor_commentary:f77eaad2-93b8-4858-90f6-e37c147cb4bb:v1",
    "profile_id": "32690a4e-ab09-4b18-8c33-cf5b6a46ee4c",
    "source_row_id": "f77eaad2-93b8-4858-90f6-e37c147cb4bb",
    "fact_atoms": [],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [],
    "finding_span": "These risks include data leakage that can reidentify",
    "fact_pattern_paraphrase": "a business using consumers' personal information to train an ADMT, including an emotion-recognition, facial-recognition, or identity-verification system",
    "finding_paraphrase": "training uses of consumers' personal information pose significant risk to consumers' privacy, including data leakage that can re-identify the people whose information trained the model and a lack of transparency and control, so training is its own risk-assessment trigger",
    "settledness": "R1",
    "posture": "rejected",
    "factor_id": "Governance, Record Sufficiency, and Related Risk-Assessment Obligations",
    "bears_on_element": "Governance, Record Sufficiency, and Related Risk-Assessment Obligations",
    "authority_label": "California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7150(b)(6), Appendix p. 13",
    "regulator": "the CPPA",
    "relevance": {
      "instrument": "CPPA Regulations",
      "factor_ids": [
        "Governance, Record Sufficiency, and Related Risk-Assessment Obligations"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [
        "training_data_use"
      ],
      "outcome_posture": "rejected"
    },
    "authority_label_short": "CPPA Final Statement of Reasons",
    "hook_version": 1,
    "source_status": "regulator_guidance",
    "status_label": "CPPA Final Statement of Reasons — agency position, primary regulator commentary",
    "verb": "states",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "page",
      "ref": "Appendix, p. 13",
      "anchor_span": "These risks include data leakage that can reidentify"
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The company has said it uses consumer personal information to train its ADMT — including, if applicable, an emotion-recognition, facial-recognition, or identity-verification system. The CPPA's regulations treat that training use as its own risk-assessment trigger, separate from using the ADMT to make a decision (11 CCR § 7150(b)(6)). In its Final Statement of Reasons, the CPPA explained why: training uses of personal information \"pose significant risk to consumers' privacy,\" including the risk that the training data can later be used to re-identify the people it came from, and a general lack of transparency and control over how their information was used for training — risks the Agency said apply even where the data is not biometric. A business that trains an ADMT on real consumer data therefore has a risk-assessment obligation under Article 10 that is distinct from — and in addition to — any obligation tied to how the ADMT is later used to decide something about a consumer. This report does not itself conduct that Article 10 risk assessment; whether one has been completed is a fact about this company's own record, not something this section resolves. (California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7150(b)(6), Appendix p. 13.)",
    "status_in_citation": false
  },
  {
    "hook_id": "cppa_fsor_commentary:2951b3e7-c3f6-4ab8-a9fa-e8f2e207ab56:v1",
    "profile_id": "395734d0-c6e7-4245-930c-7689c7bba31f",
    "source_row_id": "2951b3e7-c3f6-4ab8-a9fa-e8f2e207ab56",
    "fact_atoms": [
      "flag:human_appeal_exception"
    ],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [
      "flag:human_appeal_exception"
    ],
    "finding_span": "must know how to interpret and use the output of the ADMT that made the significant decision being appealed",
    "fact_pattern_paraphrase": "a business relying on the human-appeal exception instead of offering a full ADMT opt-out",
    "finding_paraphrase": "the designated human reviewer must know how to interpret and use the ADMT's output, must review it together with any other relevant information, and must have the authority to change the decision",
    "settledness": "R1",
    "posture": "conditional",
    "factor_id": "Opt-out pathway",
    "bears_on_element": "Opt-out pathway",
    "authority_label": "California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7221(b)(2)(A), p. 49",
    "regulator": "the CPPA",
    "relevance": {
      "instrument": "CPPA Regulations",
      "factor_ids": [
        "Opt-out pathway"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [],
      "outcome_posture": "conditional"
    },
    "authority_label_short": "CPPA Final Statement of Reasons",
    "hook_version": 1,
    "source_status": "regulator_guidance",
    "status_label": "CPPA Final Statement of Reasons — agency position, primary regulator commentary",
    "verb": "states",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "page",
      "ref": "p. 49",
      "anchor_span": "must know how to interpret and use the output of the ADMT that made the significant decision being appealed"
    },
    "recognised_proposition": "a business relying on the human-appeal exception must give consumers a reviewer who knows how to interpret and use the ADMT's output, reviews it together with any other relevant information, and has the authority to change the decision",
    "condition_text": "the company relies on the human-appeal exception instead of a full ADMT opt-out, and its appeal reviewer satisfies all three parts of that standard",
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The company relies on the human-appeal exception instead of offering a full ADMT opt-out. The CPPA's regulations set a specific, three-part standard for the reviewer that exception depends on (11 CCR § 7221(b)(2)(A)). In its Final Statement of Reasons, the Agency described the standard directly: the reviewer \"must know how to interpret and use the output of the ADMT that made the significant decision being appealed,\" must review that output together with any other information relevant to the decision, and must have actual authority to change the decision. A reviewer who can only rubber-stamp or forward the ADMT's output — without the knowledge or the authority to actually change it — does not satisfy this exception, even if an appeal process nominally exists. Section 4 addresses whether this company's appeal reviewer meets all three parts of this standard. (California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7221(b)(2)(A), p. 49.)",
    "status_in_citation": false
  },
  {
    "hook_id": "cppa_fsor_commentary:88f44d5e-fbaa-450f-a51e-3855240579fb:v1",
    "profile_id": "78f9f700-ddf8-4e04-b8b9-99f8d8ffce6b",
    "source_row_id": "88f44d5e-fbaa-450f-a51e-3855240579fb",
    "fact_atoms": [
      "flag:vendor_hosted"
    ],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [
      "flag:vendor_hosted"
    ],
    "finding_span": "The Agency also deleted the reference to subsection (b)(4) to align with the Agency",
    "fact_pattern_paraphrase": "a business depending on a third-party vendor for the ADMT it uses, where the vendor's assistance with consumer ADMT access requests is at issue",
    "finding_paraphrase": "the Agency removed surplus wording and an internal cross-reference from the service-provider assistance rule as necessary for the regulations' internal consistency, leaving the duty to assist with ADMT access requests current and unqualified",
    "settledness": "R1",
    "posture": "accepted",
    "factor_id": "Vendor dependency",
    "bears_on_element": "Vendor dependency",
    "authority_label": "California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7222(i), p. 53",
    "regulator": "the CPPA",
    "relevance": {
      "instrument": "CPPA Regulations",
      "factor_ids": [
        "Vendor dependency"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [],
      "outcome_posture": "accepted"
    },
    "authority_label_short": "CPPA Final Statement of Reasons",
    "hook_version": 1,
    "source_status": "regulator_guidance",
    "status_label": "CPPA Final Statement of Reasons — agency position, primary regulator commentary",
    "verb": "states",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "page",
      "ref": "p. 53",
      "anchor_span": "The Agency also deleted the reference to subsection (b)(4) to align with the Agency"
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "When this company depends on a vendor for the ADMT it uses, that vendor's contractual cooperation for access requests is not optional. 11 CCR § 7222(i) requires a service provider or contractor to assist the business in responding to a consumer's ADMT access request. The CPPA's Final Statement of Reasons shows this duty was tightened for clarity, not weakened, during rulemaking. The Agency removed only surplus wording (\"key,\" \"generally\") from the regulation's own example and cleaned up an internal cross-reference — changes the Agency itself describes as necessary for the regulations' internal consistency, not a narrowing of the underlying duty. Whether this company's vendor agreement actually secures that cooperation is a fact about this company's own contract, not this citation. Section 6 addresses the company's vendor-dependency record. (California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7222(i), p. 53.)",
    "status_in_citation": false
  },
  {
    "hook_id": "cppa_fsor_commentary:c6d63d10-272e-4b33-900f-55eb90df5dd6:v1",
    "profile_id": "c7ce8c07-681a-4743-badb-6b36cfc9a6d0",
    "source_row_id": "c6d63d10-272e-4b33-900f-55eb90df5dd6",
    "fact_atoms": [],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [],
    "finding_span": "The Agency chose December 31, 2027",
    "fact_pattern_paraphrase": "ADMT use, or use of personal information to train an ADMT, that began before the regulations took effect and is still ongoing",
    "finding_paraphrase": "the Agency chose December 31, 2027 as the calendar deadline for coming into compliance with the risk-assessment duty for pre-existing processing, roughly 24 months after the regulations were approved, so businesses know precisely when they must comply",
    "settledness": "R1",
    "posture": "conditional",
    "factor_id": "Governance, Record Sufficiency, and Related Risk-Assessment Obligations",
    "bears_on_element": "Governance, Record Sufficiency, and Related Risk-Assessment Obligations",
    "authority_label": "California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7155(c), p. 39",
    "regulator": "the CPPA",
    "relevance": {
      "instrument": "CPPA Regulations",
      "factor_ids": [
        "Governance, Record Sufficiency, and Related Risk-Assessment Obligations"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [],
      "outcome_posture": "conditional"
    },
    "authority_label_short": "CPPA Final Statement of Reasons",
    "hook_version": 1,
    "source_status": "regulator_guidance",
    "status_label": "CPPA Final Statement of Reasons — agency position, primary regulator commentary",
    "verb": "states",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "page",
      "ref": "p. 39",
      "anchor_span": "The Agency chose December 31, 2027"
    },
    "recognised_proposition": "a risk assessment for ADMT use or training use subject to 11 CCR § 7155(c) must be completed by December 31, 2027, a deadline the Agency set at approximately 24 months after the regulations' approval date",
    "condition_text": "the company's ADMT use, or its use of personal information to train an ADMT, began before these regulations took effect and is still ongoing",
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The company's ADMT use — or its use of personal information to train an ADMT — may have begun before these regulations took effect and still be ongoing. If so, there is a firm outer deadline for coming into compliance with the Article 10 risk-assessment duty that use triggers. The CPPA explained in its Final Statement of Reasons that it set that deadline because it wanted businesses to know precisely when they must be in compliance: \"The Agency chose December 31, 2027, as the calendar deadline\" — roughly 24 months after the regulations were approved. That is separate from the January 1, 2027 deadline for the ADMT notice, opt-out, and access duties this report otherwise addresses (11 CCR § 7200(b)); the risk-assessment deadline runs on its own clock. Whether this company's ADMT use is inside or outside that window, and whether a risk assessment has been completed for it, are questions about this company's own timeline, not this citation. (California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7155(c), p. 39.)",
    "status_in_citation": false
  },
  {
    "hook_id": "cppa_fsor_commentary:84d00bed-b711-4b62-be13-b1a739d7b97b:v1",
    "profile_id": "c83fb09d-50db-45ac-a3de-5bff051b40aa",
    "source_row_id": "84d00bed-b711-4b62-be13-b1a739d7b97b",
    "fact_atoms": [],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [],
    "finding_span": "identifying a purpose in non - generic terms is necessary to identify relevant risks and benefits in a risk assessment",
    "fact_pattern_paraphrase": "an access response describing the purpose the ADMT served for the consumer as a generic recital rather than a decision-specific explanation",
    "finding_paraphrase": "identifying a purpose in non-generic terms is necessary both to identify relevant risks and benefits in a risk assessment and to ensure consumers understand how an ADMT was used with respect to them",
    "settledness": "R1",
    "posture": "accepted",
    "factor_id": "Access process",
    "bears_on_element": "Access process",
    "authority_label": "California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7222(b)(1), Appendix p. 67",
    "regulator": "the CPPA",
    "relevance": {
      "instrument": "CPPA Regulations",
      "factor_ids": [
        "Access process"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [],
      "outcome_posture": "accepted"
    },
    "authority_label_short": "CPPA Final Statement of Reasons",
    "hook_version": 1,
    "source_status": "regulator_guidance",
    "status_label": "CPPA Final Statement of Reasons — agency position, primary regulator commentary",
    "verb": "states",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "page",
      "ref": "Appendix, p. 67",
      "anchor_span": "identifying a purpose in non - generic terms is necessary to identify relevant risks and benefits in a risk assessment"
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "When a consumer asks this company to explain a decision the ADMT made about them, the response has to name the specific purpose the ADMT served for that consumer — not a generic company-wide statement (11 CCR § 7222(b)(1)). The CPPA's Final Statement of Reasons ties this directly to why the risk-assessment rules use the same standard: \"identifying a purpose in non-generic terms is necessary to identify relevant risks and benefits in a risk assessment and to ensure consumers understand how an ADMT was used with respect to them.\" The same specificity that a risk assessment needs to actually evaluate a purpose is what a consumer needs to understand a decision made about them. A response that repeats the company's general mission statement does not meet this standard. Section 5 addresses whether this company's access response describes the ADMT's purpose specifically enough. (California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7222(b)(1), Appendix p. 67.)",
    "status_in_citation": false
  },
  {
    "hook_id": "cppa_fsor_commentary:83bcecda-c1fd-4daf-b80f-63d8218a42a1:v1",
    "profile_id": "fa0d32bd-6477-4f82-9780-8a120dd7d667",
    "source_row_id": "83bcecda-c1fd-4daf-b80f-63d8218a42a1",
    "fact_atoms": [
      "flag:significant_decision"
    ],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [
      "flag:significant_decision"
    ],
    "finding_span": "The regulations already include appropriate exceptions for security, fraud prevention, and safety",
    "fact_pattern_paraphrase": "an ADMT described as a security, fraud-prevention, or safety tool whose output also makes or feeds a significant decision, such as denying a transaction as fraudulent",
    "finding_paraphrase": "the regulations already include narrow, specific exceptions for security, fraud prevention, and safety, and a broader carve-out would be less effective at protecting consumer privacy, so the security-tool label does not by itself exempt a significant decision",
    "settledness": "R1",
    "posture": "rejected",
    "factor_id": "Significant decision",
    "bears_on_element": "Significant decision",
    "authority_label": "California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7001(ddd)(6), Appendix p. 24",
    "regulator": "the CPPA",
    "relevance": {
      "instrument": "CPPA Regulations",
      "factor_ids": [
        "Significant decision"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [
        "admt_use"
      ],
      "outcome_posture": "rejected"
    },
    "authority_label_short": "CPPA Final Statement of Reasons",
    "hook_version": 1,
    "source_status": "regulator_guidance",
    "status_label": "CPPA Final Statement of Reasons — agency position, primary regulator commentary",
    "verb": "states",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "page",
      "ref": "Appendix, p. 24",
      "anchor_span": "The regulations already include appropriate exceptions for security, fraud prevention, and safety"
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The company has said its ADMT is a security, fraud-prevention, or safety tool. That description alone does not take the system outside Article 11. The CPPA specifically considered, and rejected, a broader exemption for this category of tool. In its Final Statement of Reasons, the Agency explained that \"the regulations already include appropriate exceptions for security, fraud prevention, and safety\" — narrow, specific ones (11 CCR §§ 7220(d)(2), 7222(c)(2)) — and that a broader carve-out \"would be less effective at protecting consumer privacy\" because it would remove the risk-assessment, notice, and opt-out/access rights for decisions that otherwise qualify. If this tool's output is used to make a decision within one of § 7001(ddd)'s categories — for example, denying a transaction as fraudulent, which is a financial-services decision — labeling it a \"security tool\" does not, by itself, exempt it. Section 2 addresses whether the narrow, specific exceptions actually apply on this company's own facts. (California Privacy Protection Agency, Final Statement of Reasons, CCPA Updates, Cyber, Risk, ADMT, and Insurance Regulations, 11 CCR § 7001(ddd), Appendix p. 24.)",
    "status_in_citation": false
  }
];

// ── [RATIFY — DRAFT, unratified] — the direction matrix (doc 213 §4 / doc
// 222 §3 / doc 224, as data) ──────────────────────────────────────────────
//
// IDENTICAL in shape to LIA_HOOK_DIRECTION_MATRIX/DPIA/Risk's own copies —
// this table transcribes `directionFor` (hook-types.ts, unmodified,
// product-agnostic), which is the code every product's join actually
// renders through. Reproduced here (not imported) so a byte-pin test can
// catch the two drifting apart, mirroring the LIA/DPIA/Risk convention.

export interface AdmtHookMatrixRow {
  readonly posture: string;
  readonly fact_agreement: string;
  readonly engine_verdict: string;
  readonly shape: string;
  readonly note: string;
}

export const ADMT_HOOK_DIRECTION_MATRIX: readonly AdmtHookMatrixRow[] = [
  { posture: "accepted", fact_agreement: "same", engine_verdict: "any", shape: "S1 supports", note: "hedged to `likely` language; never lifts a determination" },
  { posture: "accepted", fact_agreement: "different / unknown", engine_verdict: "any", shape: "omit", note: "nothing to say" },
  { posture: "conditional", fact_agreement: "same", engine_verdict: "passes, and every condition_atom holds on the record", shape: "S5b recognised + condition satisfied", note: "the engine's pass is what satisfies the condition; the hook only echoes it" },
  { posture: "conditional", fact_agreement: "same", engine_verdict: "otherwise (fails / uncertain, or condition_atoms null / not all held)", shape: "S5a recognised, condition unresolved", note: "the guidance is relevant; whether its condition is met is Section {section}'s own question — never asserted here" },
  { posture: "conditional", fact_agreement: "different (a distinguishing pair holds)", engine_verdict: "passes", shape: "omit + flag `authority_not_dispositive` (`rule_missing` when the pair expressly excludes)", note: "a silent source under a pass is nothing missing; an express exclusion under a pass means a rule is missing" },
  { posture: "conditional", fact_agreement: "different (a distinguishing pair holds)", engine_verdict: "fails / uncertain", shape: "S6 source silent (S6x where the pair expressly excludes)", note: "\"does not extend\" only from an authored `source_expressly_excludes` pair with a verified exclusion span" },
  { posture: "conditional", fact_agreement: "unknown", engine_verdict: "any", shape: "omit", note: "" },
  { posture: "rejected", fact_agreement: "same", engine_verdict: "fails / uncertain", shape: "S2 cuts against and applied", note: "the record's own determination already reflects it" },
  { posture: "rejected", fact_agreement: "same", engine_verdict: "passes", shape: "omit + flag `rule_missing`", note: "the lawyer's rule: an adverse authority on the same facts under a pass means a rule is missing — never printed as risk noted" },
  { posture: "rejected", fact_agreement: "different (a distinguishing pair holds)", engine_verdict: "any", shape: "S3 cuts against but distinguished", note: "renders only from the pair (source fact / record fact); never from an atom's generic phrase" },
  { posture: "rejected", fact_agreement: "unknown", engine_verdict: "any", shape: "omit", note: "" },
  { posture: "contested (R4)", fact_agreement: "same", engine_verdict: "any", shape: "S4 noted as a boundary", note: "prints the derived status and the appeal note; no relation drawn" },
  { posture: "contested (R4)", fact_agreement: "different / unknown", engine_verdict: "any", shape: "omit", note: "a contested decision on different facts adds nothing" },
  { posture: "any", fact_agreement: "unknown from atoms", engine_verdict: "—", shape: "the stored two-leg selection's agreement, if one exists; else omit + flag `selection_pending`; legs disagreed → omit + flag `selection_unsettled` (the ROO item)", note: "a call is made only where no stored decision exists AND the pre-filter says either answer could print" },
  { posture: "any", fact_agreement: "`required_atoms` not all held", engine_verdict: "—", shape: "not nominated", note: "" },
];

// ── [RATIFY — DRAFT, unratified] — the atom-phrase map ───────────────────
//
// One ratified clause per closed-list atom value in ADMT's own hook
// vocabulary (`class:`, `flag:`, `state:intake.<path>=<value>` — no
// `relationship:` or `data_category:` atoms exist for ADMT today; see
// generate-corpus-hooks/_local/product-registry.ts's ADMT entry and doc
// 235's own [NEEDS] on why). Every phrase is a short, plain-language,
// third-person description of a record fact — doc 223B's CEO-register bar
// ("The company has stated that it processes browsing and behavioural
// data..." — short sentences, plain words), not LIA's original, more
// formal drafting register.

export const ADMT_ATOM_PHRASES: Readonly<Record<string, string>> = {
  // — classes (decision domain; RULE_PRODUCT_REGISTRY-style HOOK_PRODUCT_REGISTRY.admt.typed_state_vocabulary.classes) —
  // A record's `use_case_class` is the FIRST regulated domain selected on
  // `decision_domains` (doc 235's own first-pass reduction of a multi-select
  // field to one class — see the build log's [NEEDS]).
  "class:lending_financial": "the decision is a credit or lending decision",
  "class:housing": "the decision is a housing decision",
  "class:education": "the decision is an education decision",
  "class:hiring_admission": "the decision is a hiring or admission decision",
  "class:work_allocation": "the decision is a work-allocation, scheduling, or compensation decision",
  "class:employment_action": "the decision is a promotion, demotion, suspension, or termination decision",
  "class:healthcare": "the decision is a healthcare decision",

  // — flags (RULE_PRODUCT_REGISTRY-style HOOK_PRODUCT_REGISTRY.admt.typed_state_vocabulary.flags) —
  "flag:significant_decision": "the system makes a covered significant decision",
  "flag:no_human_review": "the decision is made without any human review",
  "flag:qualifying_human_review": "a human reviewer has authority to change the decision",
  "flag:solely_advertising": "the system is used solely for advertising",
  "flag:vendor_hosted": "the system is hosted by a third-party vendor",
  "flag:biometric_model": "the system uses a biometric, emotion-recognition, or identity-verification model",
  "flag:full_opt_out": "the company provides a full opt-out",
  "flag:human_appeal_exception": "the company relies on the human-appeal exception instead of a full opt-out",
  "flag:hiring_admission_exception": "the company relies on the hiring or admission exception instead of a full opt-out",
  "flag:work_allocation_exception": "the company relies on the work-allocation or compensation exception instead of a full opt-out",

  // — instruments (RULE_PRODUCT_REGISTRY.admt.instrument_scope) —
  "instrument:CPPA ADMT Regulations": "the system is assessed under the CPPA's ADMT regulations",

  // — state: atoms — ONE PHRASE PER CLOSED OPTION the hook drafter may emit.
  // Covers a first-wave subset of ADMT's closed intake options (a handful
  // of the highest-value fields, not the whole contract) — the drafter
  // (generate-corpus-hooks/_local/vocabulary.ts, STATE_ATOM_ENUMS) would
  // need entries added for these paths before a hook drafted against them
  // could pass verification; see doc 235's [NEEDS].

  // human review (intake.human_review — the four closed options)
  "state:intake.human_review=Yes — reviewer knows how to interpret output, reviews it plus other info, and has authority to change the decision":
    "the company reports a qualifying human reviewer — one who understands the output, reviews it together with other information, and can change the decision",
  "state:intake.human_review=Partial — reviewer sees the output but cannot override it":
    "the company reports a reviewer who sees the output but cannot override it",
  "state:intake.human_review=No — fully automated, no human review":
    "the company reports the decision is fully automated, with no human review",
  "state:intake.human_review=Not applicable / unsure":
    "the company has not resolved whether a human reviews the decision",

  // solely advertising (intake.admt_detail.solely_advertising)
  "state:intake.admt_detail.solely_advertising=Yes — solely advertising":
    "the company reports the system is used solely for advertising",
  "state:intake.admt_detail.solely_advertising=No":
    "the company reports the system is used for something beyond advertising",

  // notice purpose specificity (intake.notice_has_specific_purpose)
  "state:intake.notice_has_specific_purpose=Yes":
    "the company reports its Pre-use Notice states a specific purpose",
  "state:intake.notice_has_specific_purpose=No — uses generic language":
    "the company reports its Pre-use Notice uses generic language rather than a specific purpose",
  "state:intake.notice_has_specific_purpose=We have not yet created a Pre-use Notice":
    "the company has not yet created a Pre-use Notice",

  // opt-out description in the notice (intake.notice_has_opt_out_desc)
  "state:intake.notice_has_opt_out_desc=Yes — with specific opt-out instructions":
    "the company reports its notice gives specific opt-out instructions",
  "state:intake.notice_has_opt_out_desc=Mentions opt-out but without clear instructions":
    "the company reports its notice mentions opt-out but gives no clear instructions",
  "state:intake.notice_has_opt_out_desc=No":
    "the company reports its notice does not describe an opt-out",
  "state:intake.notice_has_opt_out_desc=We rely on an exception and describe appeal rights instead":
    "the company reports it relies on an exception and describes appeal rights instead of an opt-out",
  "state:intake.notice_has_opt_out_desc=We rely on an exception and the notice identifies the specific exception":
    "the company reports its notice identifies the specific exception it relies on",

  // access response timeline (intake.access_response_timeline)
  "state:intake.access_response_timeline=Within 45 calendar days (standard)":
    "the company reports a standard 45-calendar-day access response timeline",
  "state:intake.access_response_timeline=Within 45 days with documented 45-day extension capability":
    "the company reports a 45-day response timeline with a documented extension capability",
  "state:intake.access_response_timeline=Our process is not yet defined":
    "the company reports its access response process is not yet defined",

  // human-review override authority (intake.admt_detail.hi_authority_override)
  "state:intake.admt_detail.hi_authority_override=Yes":
    "the company reports its reviewer has authority to change the decision",
  "state:intake.admt_detail.hi_authority_override=No":
    "the company reports its reviewer does not have authority to change the decision",

  // nondiscrimination testing (intake.admt_detail.nondiscrimination_testing)
  "state:intake.admt_detail.nondiscrimination_testing=Yes — documented testing record":
    "the company reports a documented nondiscrimination testing record",
  "state:intake.admt_detail.nondiscrimination_testing=Testing performed but not documented":
    "the company reports nondiscrimination testing was performed but not documented",
  "state:intake.admt_detail.nondiscrimination_testing=No testing performed":
    "the company reports no nondiscrimination testing was performed",
  "state:intake.admt_detail.nondiscrimination_testing=Unsure":
    "the company has not resolved whether nondiscrimination testing was performed",
};

// ── [RATIFY — DRAFT, unratified] — the sentence shapes ───────────────────
//
// Structurally identical slot grammar to LIA's/DPIA's/Risk's own shapes
// (doc 213 §5 / doc 222 §4) — S1-S5b/S6x reused verbatim, since their
// wording names no product-specific legal test by name. S6 alone is
// reworded: LIA's original names "legitimate interests" explicitly, which
// has no ADMT analogue; ADMT's S6 instead names "the {factor} question" —
// the same generalisation this build's doc 235 log documents was needed
// before this shape could serve a product whose eight factors are not one
// named three-part test.

// DOC 238 (2026-09-09) — AMENDED, still [RATIFY — DRAFT, unratified]: same
// amendment as DPIA's/Risk's (see dpia-hooks.ts's doc comment for the full
// rationale). ADMT's own approved prose (doc 236) confirms both pieces this
// build adds: G1–G3 (FSOR, domestic) each open with the CPPA rule before the
// quoted `agency_response` clause, and E1 (foreign enforcement) was the
// specific row doc 236 §4.5's editorial pass restructured to "state the
// California rule first, then the foreign decision" — the same fix as doc
// 234 candidates 1–4. See doc 238 §"ADMT".

export const ADMT_HOOK_SHAPES: Readonly<Record<"S1" | "S2" | "S3" | "S4" | "S5a" | "S5b" | "S6" | "S6x", string>> = {
  S1:
    "The company has stated that {customer_fact}. {governing_provision}In {authority}, {regulator} {verb} that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding supports the company's position on {factor}. {hedge}Section {section} records that determination. ({citation}; {status}.)",
  S2:
    "The company has stated that {customer_fact}. {governing_provision}In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding cuts against the company's position on {factor}. {hedge}Whether that holds on this record is addressed in Section {section}. ({citation}; {status}.)",
  S3:
    "{governing_provision}In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding turned on the fact that {source_fact}; on this record the company has instead stated that {record_fact}. The decision marks a boundary rather than a finding against the company. ({citation}; {status}.)",
  S4:
    "{governing_provision}In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". The company has stated that {customer_fact}. That decision is {status}; it is noted as a boundary and is not applied. ({citation}.)",
  S5a:
    "In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}. That guidance is relevant to the company's position on {factor}; whether its condition is satisfied is addressed in Section {section}. ({citation}; {status}.)",
  S5b:
    "In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}. That guidance is relevant to the company's position on {factor}; whether its condition is satisfied is addressed in Section {section}. The facts identified in Section {section} satisfy that stated condition. ({citation}; {status}.)",
  S6:
    "The company has stated that {record_fact}. In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}, but does not address the {factor} question where {record_fact}. The determination in Section {section} therefore rests on the separately identified rules and facts, not on that guidance. ({citation}; {status}.)",
  S6x:
    "The company has stated that {record_fact}. In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}, and that {exclusion_paraphrase}; that exclusion applies to processing of the kind the company describes. Whether it applies here is addressed in Section {section}. ({citation}; {status}.)",
};

// ── [RATIFY — DRAFT, unratified] — concept equivalence ───────────────────
//
// Two atoms naming the same underlying fact share a concept; the render
// dedupes `{customer_fact}` by concept (doc 222 §2.3). An atom absent here
// is its own concept.

export const ADMT_ATOM_CONCEPTS: Readonly<Record<string, string>> = {
  "flag:no_human_review": "no_human_review",
  "state:intake.human_review=No — fully automated, no human review": "no_human_review",
  "flag:qualifying_human_review": "qualifying_human_review",
  "state:intake.human_review=Yes — reviewer knows how to interpret output, reviews it plus other info, and has authority to change the decision": "qualifying_human_review",
  "state:intake.admt_detail.hi_authority_override=Yes": "qualifying_human_review",
  "flag:solely_advertising": "solely_advertising",
  "state:intake.admt_detail.solely_advertising=Yes — solely advertising": "solely_advertising",
};

/** The concept an atom names — itself when the table has no entry. */
export function admtAtomConcept(atom: string): string {
  return ADMT_ATOM_CONCEPTS[atom] ?? atom;
}

// ── [RATIFY — DRAFT, unratified] — factor phrases: the `{factor}` slot,
// without a leading article (every shape supplies "the" or "on") ─────────
//
// The eight `factor_id` values are ADMT's own CAM vocabulary
// (admt-corpus-map.ts's `factor_id` field — the same eight strings
// `buildFactorMatrixTable()` / `deriveAdmtFiredStates()` already key on),
// used directly as `bears_on_element` (an identity map — ADMT's factors are
// already flat, not grouped into a three-part test the way LIA's are; see
// generate-corpus-hooks/_local/admt-factor-element.ts).
//
// DOC 241 (2026-09-09, V3 gap closure) — a NINTH entry: the Section 7
// Governance factor (admt-corpus-map.ts's ADMT_GOVERNANCE_FACTOR_ID, the
// exact string the three live Governance profiles carry). Doc 236's G1–G3
// (FSOR §§ 7150(b)(6) / 7155(a)(3) / 7155(c)) bear on the Article 10
// risk-assessment duties Section 7 describes, and until this entry existed
// they mapped to no element (doc 236 §3 / §8.2). The phrase is this
// build's own first-pass draft in the same register as the eight above —
// [RATIFY — DRAFT, unratified] like every other entry in this map.

export const ADMT_FACTOR_PHRASES: Readonly<Record<string, string>> = {
  "Significant decision": "the significant-decision determination",
  "Human involvement": "the human-involvement determination",
  "Advertising exclusion": "the advertising-exclusion determination",
  "Notice delivery": "the Pre-use Notice delivery",
  "Notice content": "the Pre-use Notice content",
  "Opt-out pathway": "the opt-out or exception pathway",
  "Access process": "the access and explanation process",
  "Vendor dependency": "the vendor-dependency determination",
  "Governance, Record Sufficiency, and Related Risk-Assessment Obligations": "the governance and related risk-assessment obligations",
};

// ── [RATIFY — DRAFT, unratified] — source status labels ──────────────────
//
// Reused byte-for-byte from LIA_SOURCE_STATUS_LABELS: these describe the
// CITED AUTHORITY's own kind and weight (a supervisory-authority decision,
// EDPB guidance, an Article 29 Working Party opinion), which is unchanged
// whether the authority is cited into an LIA, DPIA, Risk, or ADMT report —
// an ADMT hook citing a GDPR enforcement decision by analogy still cites a
// "supervisory-authority decision," so this vocabulary is genuinely
// product-agnostic, not copied blind. A CPPA Final Statement of Reasons
// label (the FSOR source ADMT's own 38 dark FC rows already draw on) is
// added here as a new entry — the ADMT-specific addition beyond LIA's set.
//
// DOC 238 §5 item 6 FOLLOW-UP (2026-09-09) — `sa_decision` is now the
// CEO-APPROVED doc 236 wording (E1, the only approved ADMT enforcement
// citation: "foreign supervisory-authority decision, cited by analogy —
// decided under the GDPR, not the CCPA or its Article 10/11 regulations"),
// NOT LIA's byte-copy the paragraph above describes — a GDPR decision cited
// into an ADMT report is a foreign authority applied by analogy, and the
// CEO's own approved text says so. Byte-equal to the shared generator's
// per-product entry (generate-corpus-hooks/_local/generate.ts
// `HOOK_PRODUCT_CITATION_CONVENTIONS.admt`, pinned equal by
// tests/edge/corpus/doc238-status-labels-and-tidy.test.ts). The other
// entries remain LIA's bytes.

export const ADMT_SOURCE_STATUS_LABELS: Readonly<Record<string, string>> = {
  edpb_guidelines_final: "EDPB guidelines — interpretive guidance, not binding law",
  edpb_opinion: "EDPB Article 64 opinion — Board opinion, not a judicial decision",
  wp29_opinion: "Article 29 Working Party opinion — historical interpretive guidance",
  regulator_guidance: "regulatory guidance — non-binding",
  sa_decision: "foreign supervisory-authority decision, cited by analogy — decided under the GDPR, not the CCPA or its Article 10/11 regulations",
  sa_decision_affirmed: "supervisory-authority decision, affirmed on appeal",
  sa_decision_appeal_pending: "under appeal",
  // ADMT-specific addition, mirroring doc 231's own CPPA FSOR label
  // ("CPPA Final Statement of Reasons — agency position, primary regulator
  // commentary"), for the 38 already-curated cppa_fsor_commentary FC rows
  // this build's own vocabulary would eventually draft hooks against.
  cppa_fsor_commentary: "CPPA Final Statement of Reasons — agency position, primary regulator commentary",
};

// ── RATIFIED by the CEO 2026-09-08 (byte-mirrored from LIA_APPEAL_SENTENCE,
// run-li-assessment/_local/corpus/maps/lia-hooks.ts) — the appeal sentence ─

export const ADMT_APPEAL_SENTENCE = "This matter is subject to an appeal which could invalidate this ruling.";

export const ADMT_SETTLEDNESS_LABELS: Readonly<Record<"R1" | "R2" | "R3" | "R4", string>> = {
  R1: "adopted guidance or settled authority",
  R2: "a settled line of decisions",
  R3: "a single supervisory authority's decision",
  R4: "under appeal / contested",
};
