// ADMT AUTHORITY HOOKS — pinned, generated file (doc 235, 2026-09-08).
//
// Generated by `generate-corpus-hooks` (action "generate") from ratified,
// unretired `public.authority_hooks` rows whose profile is itself stamped.
// Do not hand-edit `ADMT_HOOKS`: regenerate it. Mirrors LIA's
// `run-li-assessment/_local/corpus/maps/lia-hooks.ts` (doc 213) and its two
// V3 successors, DPIA's `dpia-hooks.ts` (doc 232) and CPPA Risk's
// `risk-hooks.ts` (doc 231) — same file shape, ADMT's own vocabulary.
//
// EXCLUDED ROWS: none — zero rows have been drafted yet. No
// `authority_relevance_profiles` row exists for `product='cppa-admt'`
// (verified read-only 2026-09-08, matching doc 227 §1(b)'s finding).
// `ADMT_HOOKS` ships `[]` until a first hook run drafts and the CEO
// ratifies at least one row; every consumer (hook-join.ts,
// admt-v3-selection.ts) already degrades to a no-op on an empty array —
// the same "an unstamped hook is inert" law LIA/DPIA/Risk ship under.
//
// The `[RATIFY — DRAFT, unratified]` blocks below (the direction matrix,
// the atom-phrase map, the sentence shapes, atom concepts, factor phrases,
// source-status labels, the appeal sentence, settledness labels) are this
// build's own first-pass drafting — ADMT's own vocabulary, adapted from
// LIA's doc 213/222 shapes, held to doc 223B's CEO-register prose bar
// (short sentences, plain words, no padding) rather than to LIA's original,
// more formal register. None of this has been ratified; every block is
// presented for the CEO's ratify/revise/retire pass, the same way LIA's
// first batch was (docs 213A/223/223B).
//
// `generate-corpus-hooks`'s own `generate` action copies every block from
// the marker below to the end of this file verbatim
// (generate-corpus-hooks/_local/admt-hook-context-block.ts, pinned by
// test) — SEE DOC 235's BUILD LOG: `actionGenerate`'s dispatch is not yet
// generalised to reach `admt-hook-context-block.ts`/`admtElementOf` on
// `main` as of this build (the CPPA-Risk agent's generalisation of that
// dispatch lives only on the unmerged `v3-cppa-risk` branch) — this is a
// disclosed `[NEEDS]`, not a defect in this file.

import type { AuthorityHook } from "../../../../_shared/corpus/hook-types.ts";

export const ADMT_HOOKS_VERSION = "admt-hooks-v0-empty-2026-09-08";

export const ADMT_HOOKS: readonly AuthorityHook[] = [];

// ── [RATIFY — DRAFT, unratified] — the direction matrix (doc 213 §4 / doc
// 222 §3 / doc 224, as data) ──────────────────────────────────────────────
//
// IDENTICAL in shape to LIA_HOOK_DIRECTION_MATRIX/DPIA/Risk's own copies —
// this table transcribes `directionFor` (hook-types.ts, unmodified,
// product-agnostic), which is the code every product's join actually
// renders through. Reproduced here (not imported) so a byte-pin test can
// catch the two drifting apart, mirroring the LIA/DPIA/Risk convention.

export interface AdmtHookMatrixRow {
  readonly posture: string;
  readonly fact_agreement: string;
  readonly engine_verdict: string;
  readonly shape: string;
  readonly note: string;
}

export const ADMT_HOOK_DIRECTION_MATRIX: readonly AdmtHookMatrixRow[] = [
  { posture: "accepted", fact_agreement: "same", engine_verdict: "any", shape: "S1 supports", note: "hedged to `likely` language; never lifts a determination" },
  { posture: "accepted", fact_agreement: "different / unknown", engine_verdict: "any", shape: "omit", note: "nothing to say" },
  { posture: "conditional", fact_agreement: "same", engine_verdict: "passes, and every condition_atom holds on the record", shape: "S5b recognised + condition satisfied", note: "the engine's pass is what satisfies the condition; the hook only echoes it" },
  { posture: "conditional", fact_agreement: "same", engine_verdict: "otherwise (fails / uncertain, or condition_atoms null / not all held)", shape: "S5a recognised, condition unresolved", note: "the guidance is relevant; whether its condition is met is Section {section}'s own question — never asserted here" },
  { posture: "conditional", fact_agreement: "different (a distinguishing pair holds)", engine_verdict: "passes", shape: "omit + flag `authority_not_dispositive` (`rule_missing` when the pair expressly excludes)", note: "a silent source under a pass is nothing missing; an express exclusion under a pass means a rule is missing" },
  { posture: "conditional", fact_agreement: "different (a distinguishing pair holds)", engine_verdict: "fails / uncertain", shape: "S6 source silent (S6x where the pair expressly excludes)", note: "\"does not extend\" only from an authored `source_expressly_excludes` pair with a verified exclusion span" },
  { posture: "conditional", fact_agreement: "unknown", engine_verdict: "any", shape: "omit", note: "" },
  { posture: "rejected", fact_agreement: "same", engine_verdict: "fails / uncertain", shape: "S2 cuts against and applied", note: "the record's own determination already reflects it" },
  { posture: "rejected", fact_agreement: "same", engine_verdict: "passes", shape: "omit + flag `rule_missing`", note: "the lawyer's rule: an adverse authority on the same facts under a pass means a rule is missing — never printed as risk noted" },
  { posture: "rejected", fact_agreement: "different (a distinguishing pair holds)", engine_verdict: "any", shape: "S3 cuts against but distinguished", note: "renders only from the pair (source fact / record fact); never from an atom's generic phrase" },
  { posture: "rejected", fact_agreement: "unknown", engine_verdict: "any", shape: "omit", note: "" },
  { posture: "contested (R4)", fact_agreement: "same", engine_verdict: "any", shape: "S4 noted as a boundary", note: "prints the derived status and the appeal note; no relation drawn" },
  { posture: "contested (R4)", fact_agreement: "different / unknown", engine_verdict: "any", shape: "omit", note: "a contested decision on different facts adds nothing" },
  { posture: "any", fact_agreement: "unknown from atoms", engine_verdict: "—", shape: "the stored two-leg selection's agreement, if one exists; else omit + flag `selection_pending`; legs disagreed → omit + flag `selection_unsettled` (the ROO item)", note: "a call is made only where no stored decision exists AND the pre-filter says either answer could print" },
  { posture: "any", fact_agreement: "`required_atoms` not all held", engine_verdict: "—", shape: "not nominated", note: "" },
];

// ── [RATIFY — DRAFT, unratified] — the atom-phrase map ───────────────────
//
// One ratified clause per closed-list atom value in ADMT's own hook
// vocabulary (`class:`, `flag:`, `state:intake.<path>=<value>` — no
// `relationship:` or `data_category:` atoms exist for ADMT today; see
// generate-corpus-hooks/_local/product-registry.ts's ADMT entry and doc
// 235's own [NEEDS] on why). Every phrase is a short, plain-language,
// third-person description of a record fact — doc 223B's CEO-register bar
// ("The company has stated that it processes browsing and behavioural
// data..." — short sentences, plain words), not LIA's original, more
// formal drafting register.

export const ADMT_ATOM_PHRASES: Readonly<Record<string, string>> = {
  // — classes (decision domain; RULE_PRODUCT_REGISTRY-style HOOK_PRODUCT_REGISTRY.admt.typed_state_vocabulary.classes) —
  // A record's `use_case_class` is the FIRST regulated domain selected on
  // `decision_domains` (doc 235's own first-pass reduction of a multi-select
  // field to one class — see the build log's [NEEDS]).
  "class:lending_financial": "the decision is a credit or lending decision",
  "class:housing": "the decision is a housing decision",
  "class:education": "the decision is an education decision",
  "class:hiring_admission": "the decision is a hiring or admission decision",
  "class:work_allocation": "the decision is a work-allocation, scheduling, or compensation decision",
  "class:employment_action": "the decision is a promotion, demotion, suspension, or termination decision",
  "class:healthcare": "the decision is a healthcare decision",

  // — flags (RULE_PRODUCT_REGISTRY-style HOOK_PRODUCT_REGISTRY.admt.typed_state_vocabulary.flags) —
  "flag:significant_decision": "the system makes a covered significant decision",
  "flag:no_human_review": "the decision is made without any human review",
  "flag:qualifying_human_review": "a human reviewer has authority to change the decision",
  "flag:solely_advertising": "the system is used solely for advertising",
  "flag:vendor_hosted": "the system is hosted by a third-party vendor",
  "flag:biometric_model": "the system uses a biometric, emotion-recognition, or identity-verification model",
  "flag:full_opt_out": "the company provides a full opt-out",
  "flag:human_appeal_exception": "the company relies on the human-appeal exception instead of a full opt-out",
  "flag:hiring_admission_exception": "the company relies on the hiring or admission exception instead of a full opt-out",
  "flag:work_allocation_exception": "the company relies on the work-allocation or compensation exception instead of a full opt-out",

  // — instruments (RULE_PRODUCT_REGISTRY.admt.instrument_scope) —
  "instrument:CPPA ADMT Regulations": "the system is assessed under the CPPA's ADMT regulations",

  // — state: atoms — ONE PHRASE PER CLOSED OPTION the hook drafter may emit.
  // Covers a first-wave subset of ADMT's closed intake options (a handful
  // of the highest-value fields, not the whole contract) — the drafter
  // (generate-corpus-hooks/_local/vocabulary.ts, STATE_ATOM_ENUMS) would
  // need entries added for these paths before a hook drafted against them
  // could pass verification; see doc 235's [NEEDS].

  // human review (intake.human_review — the four closed options)
  "state:intake.human_review=Yes — reviewer knows how to interpret output, reviews it plus other info, and has authority to change the decision":
    "the company reports a qualifying human reviewer — one who understands the output, reviews it together with other information, and can change the decision",
  "state:intake.human_review=Partial — reviewer sees the output but cannot override it":
    "the company reports a reviewer who sees the output but cannot override it",
  "state:intake.human_review=No — fully automated, no human review":
    "the company reports the decision is fully automated, with no human review",
  "state:intake.human_review=Not applicable / unsure":
    "the company has not resolved whether a human reviews the decision",

  // solely advertising (intake.admt_detail.solely_advertising)
  "state:intake.admt_detail.solely_advertising=Yes — solely advertising":
    "the company reports the system is used solely for advertising",
  "state:intake.admt_detail.solely_advertising=No":
    "the company reports the system is used for something beyond advertising",

  // notice purpose specificity (intake.notice_has_specific_purpose)
  "state:intake.notice_has_specific_purpose=Yes":
    "the company reports its Pre-use Notice states a specific purpose",
  "state:intake.notice_has_specific_purpose=No — uses generic language":
    "the company reports its Pre-use Notice uses generic language rather than a specific purpose",
  "state:intake.notice_has_specific_purpose=We have not yet created a Pre-use Notice":
    "the company has not yet created a Pre-use Notice",

  // opt-out description in the notice (intake.notice_has_opt_out_desc)
  "state:intake.notice_has_opt_out_desc=Yes — with specific opt-out instructions":
    "the company reports its notice gives specific opt-out instructions",
  "state:intake.notice_has_opt_out_desc=Mentions opt-out but without clear instructions":
    "the company reports its notice mentions opt-out but gives no clear instructions",
  "state:intake.notice_has_opt_out_desc=No":
    "the company reports its notice does not describe an opt-out",
  "state:intake.notice_has_opt_out_desc=We rely on an exception and describe appeal rights instead":
    "the company reports it relies on an exception and describes appeal rights instead of an opt-out",
  "state:intake.notice_has_opt_out_desc=We rely on an exception and the notice identifies the specific exception":
    "the company reports its notice identifies the specific exception it relies on",

  // access response timeline (intake.access_response_timeline)
  "state:intake.access_response_timeline=Within 45 calendar days (standard)":
    "the company reports a standard 45-calendar-day access response timeline",
  "state:intake.access_response_timeline=Within 45 days with documented 45-day extension capability":
    "the company reports a 45-day response timeline with a documented extension capability",
  "state:intake.access_response_timeline=Our process is not yet defined":
    "the company reports its access response process is not yet defined",

  // human-review override authority (intake.admt_detail.hi_authority_override)
  "state:intake.admt_detail.hi_authority_override=Yes":
    "the company reports its reviewer has authority to change the decision",
  "state:intake.admt_detail.hi_authority_override=No":
    "the company reports its reviewer does not have authority to change the decision",

  // nondiscrimination testing (intake.admt_detail.nondiscrimination_testing)
  "state:intake.admt_detail.nondiscrimination_testing=Yes — documented testing record":
    "the company reports a documented nondiscrimination testing record",
  "state:intake.admt_detail.nondiscrimination_testing=Testing performed but not documented":
    "the company reports nondiscrimination testing was performed but not documented",
  "state:intake.admt_detail.nondiscrimination_testing=No testing performed":
    "the company reports no nondiscrimination testing was performed",
  "state:intake.admt_detail.nondiscrimination_testing=Unsure":
    "the company has not resolved whether nondiscrimination testing was performed",
};

// ── [RATIFY — DRAFT, unratified] — the sentence shapes ───────────────────
//
// Structurally identical slot grammar to LIA's/DPIA's/Risk's own shapes
// (doc 213 §5 / doc 222 §4) — S1-S5b/S6x reused verbatim, since their
// wording names no product-specific legal test by name. S6 alone is
// reworded: LIA's original names "legitimate interests" explicitly, which
// has no ADMT analogue; ADMT's S6 instead names "the {factor} question" —
// the same generalisation this build's doc 235 log documents was needed
// before this shape could serve a product whose eight factors are not one
// named three-part test.

// DOC 238 (2026-09-09) — AMENDED, still [RATIFY — DRAFT, unratified]: same
// amendment as DPIA's/Risk's (see dpia-hooks.ts's doc comment for the full
// rationale). ADMT's own approved prose (doc 236) confirms both pieces this
// build adds: G1–G3 (FSOR, domestic) each open with the CPPA rule before the
// quoted `agency_response` clause, and E1 (foreign enforcement) was the
// specific row doc 236 §4.5's editorial pass restructured to "state the
// California rule first, then the foreign decision" — the same fix as doc
// 234 candidates 1–4. See doc 238 §"ADMT".

export const ADMT_HOOK_SHAPES: Readonly<Record<"S1" | "S2" | "S3" | "S4" | "S5a" | "S5b" | "S6" | "S6x", string>> = {
  S1:
    "The company has stated that {customer_fact}. {governing_provision}In {authority}, {regulator} {verb} that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding supports the company's position on {factor}. {hedge}Section {section} records that determination. ({citation}; {status}.)",
  S2:
    "The company has stated that {customer_fact}. {governing_provision}In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding cuts against the company's position on {factor}. {hedge}Whether that holds on this record is addressed in Section {section}. ({citation}; {status}.)",
  S3:
    "{governing_provision}In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding turned on the fact that {source_fact}; on this record the company has instead stated that {record_fact}. The decision marks a boundary rather than a finding against the company. ({citation}; {status}.)",
  S4:
    "{governing_provision}In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". The company has stated that {customer_fact}. That decision is {status}; it is noted as a boundary and is not applied. ({citation}.)",
  S5a:
    "In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}. That guidance is relevant to the company's position on {factor}; whether its condition is satisfied is addressed in Section {section}. ({citation}; {status}.)",
  S5b:
    "In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}. That guidance is relevant to the company's position on {factor}; whether its condition is satisfied is addressed in Section {section}. The facts identified in Section {section} satisfy that stated condition. ({citation}; {status}.)",
  S6:
    "The company has stated that {record_fact}. In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}, but does not address the {factor} question where {record_fact}. The determination in Section {section} therefore rests on the separately identified rules and facts, not on that guidance. ({citation}; {status}.)",
  S6x:
    "The company has stated that {record_fact}. In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}, and that {exclusion_paraphrase}; that exclusion applies to processing of the kind the company describes. Whether it applies here is addressed in Section {section}. ({citation}; {status}.)",
};

// ── [RATIFY — DRAFT, unratified] — concept equivalence ───────────────────
//
// Two atoms naming the same underlying fact share a concept; the render
// dedupes `{customer_fact}` by concept (doc 222 §2.3). An atom absent here
// is its own concept.

export const ADMT_ATOM_CONCEPTS: Readonly<Record<string, string>> = {
  "flag:no_human_review": "no_human_review",
  "state:intake.human_review=No — fully automated, no human review": "no_human_review",
  "flag:qualifying_human_review": "qualifying_human_review",
  "state:intake.human_review=Yes — reviewer knows how to interpret output, reviews it plus other info, and has authority to change the decision": "qualifying_human_review",
  "state:intake.admt_detail.hi_authority_override=Yes": "qualifying_human_review",
  "flag:solely_advertising": "solely_advertising",
  "state:intake.admt_detail.solely_advertising=Yes — solely advertising": "solely_advertising",
};

/** The concept an atom names — itself when the table has no entry. */
export function admtAtomConcept(atom: string): string {
  return ADMT_ATOM_CONCEPTS[atom] ?? atom;
}

// ── [RATIFY — DRAFT, unratified] — factor phrases: the `{factor}` slot,
// without a leading article (every shape supplies "the" or "on") ─────────
//
// The eight `factor_id` values are ADMT's own CAM vocabulary
// (admt-corpus-map.ts's `factor_id` field — the same eight strings
// `buildFactorMatrixTable()` / `deriveAdmtFiredStates()` already key on),
// used directly as `bears_on_element` (an identity map — ADMT's factors are
// already flat, not grouped into a three-part test the way LIA's are; see
// generate-corpus-hooks/_local/admt-factor-element.ts).

export const ADMT_FACTOR_PHRASES: Readonly<Record<string, string>> = {
  "Significant decision": "the significant-decision determination",
  "Human involvement": "the human-involvement determination",
  "Advertising exclusion": "the advertising-exclusion determination",
  "Notice delivery": "the Pre-use Notice delivery",
  "Notice content": "the Pre-use Notice content",
  "Opt-out pathway": "the opt-out or exception pathway",
  "Access process": "the access and explanation process",
  "Vendor dependency": "the vendor-dependency determination",
};

// ── [RATIFY — DRAFT, unratified] — source status labels ──────────────────
//
// Reused byte-for-byte from LIA_SOURCE_STATUS_LABELS: these describe the
// CITED AUTHORITY's own kind and weight (a supervisory-authority decision,
// EDPB guidance, an Article 29 Working Party opinion), which is unchanged
// whether the authority is cited into an LIA, DPIA, Risk, or ADMT report —
// an ADMT hook citing a GDPR enforcement decision by analogy still cites a
// "supervisory-authority decision," so this vocabulary is genuinely
// product-agnostic, not copied blind. A CPPA Final Statement of Reasons
// label (the FSOR source ADMT's own 38 dark FC rows already draw on) is
// added here as a new entry — the ADMT-specific addition beyond LIA's set.

export const ADMT_SOURCE_STATUS_LABELS: Readonly<Record<string, string>> = {
  edpb_guidelines_final: "EDPB guidelines — interpretive guidance, not binding law",
  edpb_opinion: "EDPB Article 64 opinion — Board opinion, not a judicial decision",
  wp29_opinion: "Article 29 Working Party opinion — historical interpretive guidance",
  regulator_guidance: "regulatory guidance — non-binding",
  sa_decision: "supervisory-authority decision — persuasive, non-binding outside its jurisdiction",
  sa_decision_affirmed: "supervisory-authority decision, affirmed on appeal",
  sa_decision_appeal_pending: "under appeal",
  // ADMT-specific addition, mirroring doc 231's own CPPA FSOR label
  // ("CPPA Final Statement of Reasons — agency position, primary regulator
  // commentary"), for the 38 already-curated cppa_fsor_commentary FC rows
  // this build's own vocabulary would eventually draft hooks against.
  cppa_fsor_commentary: "CPPA Final Statement of Reasons — agency position, primary regulator commentary",
};

// ── RATIFIED by the CEO 2026-09-08 (byte-mirrored from LIA_APPEAL_SENTENCE,
// run-li-assessment/_local/corpus/maps/lia-hooks.ts) — the appeal sentence ─

export const ADMT_APPEAL_SENTENCE = "This matter is subject to an appeal which could invalidate this ruling.";

export const ADMT_SETTLEDNESS_LABELS: Readonly<Record<"R1" | "R2" | "R3" | "R4", string>> = {
  R1: "adopted guidance or settled authority",
  R2: "a settled line of decisions",
  R3: "a single supervisory authority's decision",
  R4: "under appeal / contested",
};
