// /all-ptest fixture panel — biometric. Fifteen complete, internally consistent
// intakes authored 2026-09-14 (see ./types.ts and scripts/ptest/PANEL-BRIEF.md).
// Validated by tests/edge/ptest/panels.test.ts.

import type { PanelFixture } from "./types.ts";

export const PANEL_BIOMETRIC: PanelFixture[] = [
  {
    id: "biometric-p01-palmetto-assembly",
    tool: "biometric",
    label: "Illinois-only employer fingerprint time clock, in-house (no vendor), consent obtained, retention published",
    company: "Palmetto Assembly Corp.",
    sector: "Industrial manufacturing",
    geo: "us",
    summary: "An Illinois assembly plant runs an in-house fingerprint time-and-attendance clock with no third-party vendor in the data path, a standalone written release signed before enrolment, and a published, pre-dated retention schedule. Exercises the single-state Illinois BIPA branch with every §15(a)/(b) element answered and no disclosure to any third party.",
    intake: {
      orgName: "Palmetto Assembly Corp.",
      biometricTypes: ["Fingerprint / palm print"],
      orgType: "Employer (employee biometrics)",
      purpose: "Time & attendance / workforce management",
      jurisdictions: ["Illinois, USA (BIPA)"],
      data_source_description: "Fingerprint templates are captured at two ZKTeco time-clock terminals on the Rockford, Illinois assembly floor. Each terminal converts the scanned print into a 384-byte minutiae template on-device and discards the raw scan image before the template is written to the on-premises attendance server (ATT-DB-01); no image ever reaches persistent storage.",
      healthcare_tpo_context: "No",
      entity_is_government: "No",
      glba_financial_institution: "No",
      notice_before_collection: "Written notice given before collection",
      notice_purpose_and_term: "Yes",
      consent_artifact_type: "Standalone written release signed before collection",
      release_artifact_description: "The instrument is the one-page \"Biometric Timekeeping Consent and Release\", adopted 6 January 2025. It is presented at new-hire orientation, separate from the offer letter and handbook acknowledgement, and signed before the employee's first clock-in. It states the identifier collected, the sole purpose (payroll timekeeping), the retention period, and that no template is sold or disclosed to any third party. As of 1 August 2026, all 214 hourly employees at the Rockford plant have a signed release on file, verified in the July payroll-onboarding audit.",
      biometric_consent_withdrawal: "An employee may withdraw by written request to HR; HR moves the employee to a badge-only clock-in within one business day and the template is destroyed within 14 days, logged in the attendance system's audit trail.",
      retention_schedule_text: "Policy HR-22 \"Biometric Timekeeping Retention Schedule\", version 1.3, approved 6 January 2025, states that fingerprint templates are destroyed no later than 30 days after the employee's final shift, or three years after last use if no termination date is recorded. The nightly ATT-PURGE job enforces the schedule automatically.",
      retention_policy_public: "Yes",
      retention_policy_predates_possession: "Yes",
      protection_parity: "Yes",
      destruction_trigger: "The employee's final shift, recorded as the payroll termination date; ATT-PURGE cryptographically erases the template row and logs a destruction record (employee id, purge timestamp) to the attendance system's audit table.",
      sells_or_profits: "No",
      security_measures_description: "Templates are encrypted at rest with AES-256 on ATT-DB-01, which sits on an isolated VLAN with no internet route. Access is limited to two named HR administrators under badge-controlled server-room entry, reviewed quarterly by the Plant HR Manager.",
      disclosure_recipients: "No third party receives the fingerprint template; ATT-DB-01 is self-hosted on plant premises and the payroll export contains only computed hours, never the template.",
      disclosure_bases: ["No disclosures are made"],
      approved_by_name: "Diane Kowalczyk",
      approved_by_title: "Director of Human Resources",
      approval_date: "2025-01-06",
      next_review_due: "2027-01-06",
    },
  },
  {
    id: "biometric-p02-longhorn-precision",
    tool: "biometric",
    label: "Texas-only employer fingerprint access control with a named access-control vendor, consent via onboarding",
    company: "Longhorn Precision Manufacturing LLC",
    sector: "Precision manufacturing",
    geo: "us",
    summary: "A Texas manufacturer uses fingerprint-based physical access control at its machine shop, with a named SaaS access-control vendor in the data path and consent captured as part of onboarding paperwork rather than a standalone release. Exercises the single-state Texas CUBI branch with all four CUBI-specific questions answered and an unpublished (but existing) retention policy.",
    intake: {
      orgName: "Longhorn Precision Manufacturing LLC",
      biometricTypes: ["Fingerprint / palm print"],
      orgType: "Employer (employee biometrics)",
      purpose: "Physical access control",
      jurisdictions: ["Texas, USA (CUBI)"],
      data_source_description: "Fingerprint templates are enrolled at a SecureGate Systems biometric reader mounted at the machine-shop's restricted tool-crib entrance in Fort Worth, Texas. SecureGate's on-premises appliance generates the template and forwards a salted hash to SecureGate's cloud verification service for real-time door-unlock decisions.",
      healthcare_tpo_context: "No",
      entity_is_government: "No",
      glba_financial_institution: "No",
      notice_before_collection: "Notice given before collection, but not in writing",
      consent_artifact_type: "Release executed as a condition of employment (onboarding paperwork)",
      release_artifact_description: "The tool-crib access consent is section 9 of the new-hire onboarding packet, signed alongside the offer acceptance. It names the identifier, the access-control purpose, and SecureGate as the processing vendor, and is filed in the employee's personnel record.",
      biometric_consent_withdrawal: "An employee reassigned away from tool-crib duties has the SecureGate enrolment deactivated and the hash purged from SecureGate's verification database within 5 business days of the access-control ticket closing.",
      retention_schedule_text: "The tool-crib access template is retained only while the employee holds an active tool-crib access badge; SecureGate's platform purges a deactivated enrolment automatically 10 days after the access group is removed. The policy exists in the plant's Access Control Standard Operating Procedure but has not been separately posted to the employee intranet.",
      retention_policy_public: "No",
      protection_parity: "Yes",
      destruction_trigger: "Removal from the tool-crib access group in the HR system, which triggers a SecureGate deprovisioning webhook; the purge and its timestamp are recorded in SecureGate's admin console audit log.",
      sells_or_profits: "No",
      security_measures_description: "The salted hash is encrypted in transit via TLS 1.3 to SecureGate's cloud service and at rest under SecureGate's SOC 2 Type II-audited key management; the on-premises reader stores no template locally after enrolment sync.",
      disclosure_recipients: "SecureGate Systems, Inc. (access-control verification vendor) receives the salted hash for door-unlock matching under a data-processing addendum dated 3 February 2025 that forbids further disclosure and requires deletion within 30 days of contract termination.",
      disclosure_bases: ["Necessary to provide a product or service the subject requested", "Third party contractually promises no further disclosure"],
      tx_destruction_within_one_year: "Yes",
      tx_longer_retention_required_by_law: "No",
      tx_employer_security_collection: "Yes",
      tx_ai_training_use: "No",
      approved_by_name: "Marcus Delgado-Whitfield",
      approved_by_title: "Plant Operations Manager",
      approval_date: "2025-02-10",
      next_review_due: "2027-02-10",
    },
  },
  {
    id: "biometric-p03-noordwaard-voice-systems",
    tool: "biometric",
    label: "Dutch consumer voice-authentication app with Washington-state users, cloud voice-biometrics vendor, clickwrap consent",
    company: "Noordwaard Voice Systems B.V.",
    sector: "Consumer voice-authentication app",
    geo: "eu",
    summary: "A Netherlands-based voice-authentication app serves consumers in Washington state as well as the EU, engaging a Norwegian cloud voice-biometrics vendor for template matching. Exercises the single-US-state Washington branch (RCW 19.375 and the My Health My Data Act) alongside EU/EEA scope, clickwrap consent, and a published retention policy.",
    intake: {
      orgName: "Noordwaard Voice Systems B.V.",
      biometricTypes: ["Voiceprint / speaker recognition"],
      orgType: "Consumer app or platform",
      purpose: "Customer authentication",
      jurisdictions: ["Washington state, USA", "EU / EEA (GDPR)"],
      data_source_description: "Enrolled users speak a five-second passphrase during app setup; the app extracts a voiceprint vector and transmits it (never the raw audio) to VoicePrint Cloud AS's matching API in Oslo for storage and subsequent login verification.",
      healthcare_tpo_context: "No",
      entity_is_government: "No",
      glba_financial_institution: "No",
      notice_before_collection: "Written notice given before collection",
      consent_artifact_type: "Clickwrap or in-product acceptance",
      release_artifact_description: "During onboarding the app presents a dedicated biometric-consent screen (not bundled with the general terms of service) stating the identifier collected, the authentication purpose, the vendor (VoicePrint Cloud AS), and the retention period; the user must tap \"I agree\" before the enrolment microphone activates. The event is timestamped and logged server-side.",
      biometric_consent_withdrawal: "A user can delete their voiceprint from Settings > Privacy > Delete Voice Data; the app calls VoicePrint Cloud AS's deletion endpoint immediately and confirms deletion within 24 hours by push notification.",
      retention_schedule_text: "Voiceprints are retained while the account remains active and are automatically deleted 18 months after the account's last login, per the published Voice Data Retention Policy at noordwaardvoice.example/privacy/retention, last updated 12 March 2026.",
      retention_policy_public: "Yes",
      protection_parity: "Yes",
      destruction_trigger: "18 months of account inactivity, or an explicit deletion request; VoicePrint Cloud AS's scheduled job purges the vector and returns a deletion receipt logged in Noordwaard's compliance record.",
      sells_or_profits: "No",
      security_measures_description: "Voiceprint vectors are encrypted at rest with AES-256 in VoicePrint Cloud AS's Oslo facility and in transit via TLS 1.3; access to the matching API is limited to Noordwaard's authentication service account under a scoped API key rotated quarterly.",
      disclosure_recipients: "VoicePrint Cloud AS (Norway), the voice-matching processor, receives the voiceprint vector under a data-processing agreement dated 20 April 2025 forbidding further disclosure and requiring deletion within 30 days of contract end.",
      disclosure_bases: ["Subject consent to the disclosure", "Necessary to provide a product or service the subject requested", "Third party contractually promises no further disclosure"],
      wa_enrolls_in_database: "Yes",
      wa_commercial_purpose: "Yes",
      wa_security_purpose_only: "No",
      wa_mhmda_health_inference: "No",
      wa_mhmda_privacy_policy_published: "Yes",
      wa_mhmda_collection_consent: "Yes",
      wa_mhmda_share_consent_separate: "Yes",
      wa_mhmda_geofence_health_facility: "No",
      approved_by_name: "Femke van Osselaer",
      approved_by_title: "Head of Trust & Safety",
      approval_date: "2026-03-12",
      next_review_due: "2027-03-12",
    },
  },
  {
    id: "biometric-p04-meridian-national-distribution",
    tool: "biometric",
    label: "Multi-state (Illinois, Texas, Washington) employer access control across distribution centres, vendor involved",
    company: "Meridian National Distribution, Inc.",
    sector: "Warehousing and distribution",
    geo: "us",
    summary: "A national distribution company runs facial-geometry and fingerprint physical access control across distribution centres in Illinois, Texas and Washington, using a single access-control vendor across all three sites. Exercises the multi-state branch with every Illinois, Texas and Washington conditional question answered consistently across a genuinely multi-jurisdictional record.",
    intake: {
      orgName: "Meridian National Distribution, Inc.",
      biometricTypes: ["Facial geometry / facial recognition", "Fingerprint / palm print"],
      orgType: "Employer (employee biometrics)",
      purpose: "Physical access control",
      jurisdictions: ["Illinois, USA (BIPA)", "Texas, USA (CUBI)", "Washington state, USA"],
      data_source_description: "Sentinel Access Technologies readers capture facial geometry at the loading-dock doors and fingerprint templates at the secure-cage doors in the Joliet, Illinois; Fort Worth, Texas; and Kent, Washington distribution centres. Templates are generated on-device and synced to Sentinel's regional cloud tenant for cross-site badge-free access.",
      healthcare_tpo_context: "No",
      entity_is_government: "No",
      glba_financial_institution: "No",
      notice_before_collection: "Written notice given before collection",
      notice_purpose_and_term: "Yes",
      consent_artifact_type: "Standalone written release signed before collection",
      release_artifact_description: "The \"Biometric Access Control Notice, Consent and Release\" (Rev. 2, adopted 9 February 2025) is a standalone document signed at each site's enrolment kiosk before first access. It names both modalities, the physical-access purpose, the vendor, and the retention period. As of 15 July 2026, all 1,840 enrolled warehouse staff across the three sites have a signed release on file.",
      biometric_consent_withdrawal: "An employee submits a Biometric Withdrawal Request to site HR; access reverts to badge-only within one business day and Sentinel deletes both templates within 30 days, with a destruction certificate emailed to the Director of Security.",
      retention_schedule_text: "Policy SEC-14 \"Biometric Access Retention Schedule\", version 2.0, approved 9 February 2025 and posted at each site's notice board, provides that templates are destroyed no later than 30 days after termination or role reassignment away from restricted areas, enforced by Sentinel's automated deprovisioning job.",
      retention_policy_public: "Yes",
      retention_policy_predates_possession: "Yes",
      protection_parity: "Yes",
      destruction_trigger: "Termination or reassignment recorded in the HR system, which triggers a Sentinel deprovisioning webhook that purges both templates and logs a destruction certificate.",
      sells_or_profits: "No",
      security_measures_description: "Templates are encrypted at rest with AES-256 in Sentinel's regional cloud tenant and in transit via TLS 1.3; access is limited to eight named security administrators under MFA-gated SSO, recertified quarterly by the Director of Security, and Sentinel completed an independent penetration test on 4 May 2026 with no critical findings.",
      disclosure_recipients: "Sentinel Access Technologies, Inc. (access-control platform vendor) receives both template types for cross-site matching under a data-processing addendum dated 9 February 2025 forbidding further disclosure and requiring deletion within 30 days of contract end.",
      disclosure_bases: ["Necessary to provide a product or service the subject requested", "Third party contractually promises no further disclosure"],
      tx_destruction_within_one_year: "Yes",
      tx_longer_retention_required_by_law: "No",
      tx_employer_security_collection: "Yes",
      tx_ai_training_use: "No",
      wa_enrolls_in_database: "Yes",
      wa_commercial_purpose: "No",
      wa_security_purpose_only: "Yes",
      wa_mhmda_health_inference: "No",
      wa_mhmda_privacy_policy_published: "Yes",
      wa_mhmda_collection_consent: "Yes",
      wa_mhmda_share_consent_separate: "Yes",
      wa_mhmda_geofence_health_facility: "No",
      approved_by_name: "Carol Ann Whitmore",
      approved_by_title: "VP, People Operations",
      approval_date: "2025-02-09",
      next_review_due: "2027-02-09",
    },
  },
  {
    id: "biometric-p05-brightmart-retail-holdings",
    tool: "biometric",
    label: "Illinois and Texas retail loss-prevention facial recognition on shoppers, no consent obtained, unpublished retention — risk-flagged record",
    company: "Brightmart Retail Holdings, Inc.",
    sector: "Retail (loss prevention)",
    geo: "us",
    summary: "A retail chain runs facial-recognition loss-prevention cameras on shoppers (not employees) at Illinois and Texas store locations through a third-party analytics vendor, honestly recording that no consent or advance notice was given and that no retention schedule has been published — a deliberately risk-heavy but internally consistent record, contrasted with the panel's consent-obtained fixtures.",
    intake: {
      orgName: "Brightmart Retail Holdings, Inc.",
      biometricTypes: ["Facial geometry / facial recognition"],
      orgType: "Other",
      purpose: "Surveillance / monitoring",
      jurisdictions: ["Illinois, USA (BIPA)", "Texas, USA (CUBI)"],
      data_source_description: "Vigil Retail Analytics cameras at store entrances generate a facial-geometry template from every visitor's face and match it against a watchlist of previously flagged individuals; templates of non-matched visitors are also retained pending the vendor's default retention window, which Brightmart has not separately configured.",
      healthcare_tpo_context: "No",
      entity_is_government: "No",
      glba_financial_institution: "No",
      notice_before_collection: "No notice given before collection",
      consent_artifact_type: "No consent obtained",
      release_artifact_description: "No release or consent instrument exists; store entrances carry only a general video-surveillance sign that does not mention facial recognition or biometric identifiers.",
      biometric_consent_withdrawal: "",
      retention_schedule_text: "No written retention schedule has been adopted by Brightmart; templates are held under Vigil Retail Analytics' default 180-day rolling window unless a store manager manually flags a record for extended retention, a practice not documented in any policy.",
      retention_policy_public: "No",
      retention_policy_predates_possession: "Not known",
      protection_parity: "Not known",
      destruction_trigger: "Vigil Retail Analytics' default 180-day rolling deletion, with no Brightmart-side verification that the deletion job has actually run.",
      sells_or_profits: "No",
      security_measures_description: "Vigil Retail Analytics states that templates are encrypted at rest, but Brightmart has not obtained or reviewed an audit report or technical documentation confirming the specifics of that encryption.",
      disclosure_recipients: "Vigil Retail Analytics, Inc. (loss-prevention analytics vendor) receives every captured template for watchlist matching; no data-processing agreement restricting further use has been executed to date.",
      disclosure_bases: ["Necessary to provide a product or service the subject requested"],
      tx_destruction_within_one_year: "Not known",
      tx_longer_retention_required_by_law: "No",
      tx_employer_security_collection: "No",
      tx_ai_training_use: "No",
      notice_purpose_and_term: "No",
      approved_by_name: "",
      approved_by_title: "",
      approval_date: "",
      next_review_due: "",
    },
  },
  {
    id: "biometric-p06-camborne-industrial",
    tool: "biometric",
    label: "UK multinational, Illinois and Washington employee time-and-attendance, electronic-signature consent, in-house system",
    company: "Camborne Industrial Group Ltd",
    sector: "Industrial conglomerate",
    geo: "eu",
    summary: "A UK-headquartered industrial group runs a self-hosted fingerprint time-and-attendance system across its Illinois and Washington plants, with consent captured as an electronic signature during enrolment rather than a standalone release. Exercises Illinois plus Washington together (without Texas) alongside UK GDPR scope, and an in-house system with no third-party vendor.",
    intake: {
      orgName: "Camborne Industrial Group Ltd",
      biometricTypes: ["Fingerprint / palm print"],
      orgType: "Employer (employee biometrics)",
      purpose: "Time & attendance / workforce management",
      jurisdictions: ["Illinois, USA (BIPA)", "Washington state, USA", "United Kingdom (UK GDPR)"],
      data_source_description: "Fingerprint templates are captured at self-hosted Suprema time-clock terminals at the group's Peoria, Illinois and Tacoma, Washington plants. Templates are stored on a single group-managed SQL Server instance (TAC-DB-02) that serves both sites; no third-party service touches the data.",
      healthcare_tpo_context: "No",
      entity_is_government: "No",
      glba_financial_institution: "No",
      notice_before_collection: "Written notice given before collection",
      notice_purpose_and_term: "Yes",
      consent_artifact_type: "Electronic signature captured in the enrolment flow",
      release_artifact_description: "At the enrolment kiosk, the employee reviews a screen naming the identifier, the timekeeping purpose, the retention period, and the fact that no third party receives the template, then signs electronically with a stylus pad; the signed record is stored as a PDF attached to the employee's personnel file in Workday.",
      biometric_consent_withdrawal: "An employee may withdraw via a request to site HR; the employee moves to a PIN-based clock-in within one business day and TAC-DB-02 purges the template within 14 days, logged in the system's change table.",
      retention_schedule_text: "Group Policy HR-GL-08 \"Biometric Timekeeping Data\", version 1.1, approved 11 March 2025, provides that templates are deleted no later than 30 days after the employee's last shift at either site, enforced by a scheduled TAC-PURGE job run nightly.",
      retention_policy_public: "Yes",
      retention_policy_predates_possession: "Yes",
      protection_parity: "Yes",
      destruction_trigger: "The employee's last recorded shift in either plant's roster; TAC-PURGE deletes the template and writes a destruction log entry (employee id, plant code, purge timestamp).",
      sells_or_profits: "No",
      security_measures_description: "TAC-DB-02 is encrypted at rest with AES-256 and reachable only over the group's site-to-site VPN; access is limited to three named regional HR systems administrators recertified twice yearly.",
      disclosure_recipients: "No third party receives the fingerprint template; TAC-DB-02 is managed entirely by group IT and payroll exports carry only computed hours.",
      disclosure_bases: ["No disclosures are made"],
      wa_enrolls_in_database: "Yes",
      wa_commercial_purpose: "No",
      wa_security_purpose_only: "Yes",
      wa_mhmda_health_inference: "No",
      wa_mhmda_privacy_policy_published: "Yes",
      wa_mhmda_collection_consent: "Yes",
      wa_mhmda_share_consent_separate: "Yes",
      wa_mhmda_geofence_health_facility: "No",
      approved_by_name: "Rosalind Ashcombe-Trevithick",
      approved_by_title: "Group HR Director",
      approval_date: "2025-03-11",
      next_review_due: "2027-03-11",
    },
  },
  {
    id: "biometric-p07-emerald-iris-pay",
    tool: "biometric",
    label: "Irish fintech, Texas and Washington consumer iris-scan payment authentication, vendor involved, electronic-signature consent",
    company: "Emerald Iris Pay Ltd",
    sector: "Consumer payments fintech",
    geo: "eu",
    summary: "An Irish fintech offers iris-scan payment authentication to consumers in Texas and Washington as well as its EU home market, using a named US iris-recognition vendor for template matching. Exercises the Texas-plus-Washington combination without Illinois, a consumer (not employee) posture, and a named commercial iris-scan biometric type.",
    intake: {
      orgName: "Emerald Iris Pay Ltd",
      biometricTypes: ["Iris or retina scan"],
      orgType: "Consumer app or platform",
      purpose: "Customer authentication",
      jurisdictions: ["Texas, USA (CUBI)", "Washington state, USA", "EU / EEA (GDPR)"],
      data_source_description: "During enrolment the Emerald Pay app captures an iris image via the phone camera's infrared sensor and converts it to an iris code on-device, which is transmitted (never the raw image) to IrisMatch Technologies, Inc.'s (Austin, Texas) matching service for storage and subsequent payment-authorisation checks.",
      healthcare_tpo_context: "No",
      entity_is_government: "No",
      glba_financial_institution: "Yes",
      notice_before_collection: "Written notice given before collection",
      consent_artifact_type: "Electronic signature captured in the enrolment flow",
      release_artifact_description: "The app presents a dedicated iris-biometric consent screen during account setup naming the identifier, the payment-authentication purpose, IrisMatch Technologies as the processing vendor, and the retention period; the user signs with an in-app electronic signature before the iris scan activates, timestamped and stored server-side.",
      biometric_consent_withdrawal: "A user can delete their iris code from Account > Security > Remove Biometric Login; Emerald calls IrisMatch's deletion API immediately and the user receives an in-app deletion confirmation within minutes.",
      retention_schedule_text: "Iris codes are retained while the payment account is active and deleted automatically 24 months after the account's last transaction, per the published Biometric Data Policy at emeraldirispay.example/legal/biometric, last reviewed 5 May 2026.",
      retention_policy_public: "Yes",
      protection_parity: "Yes",
      destruction_trigger: "24 months of account inactivity or an explicit removal request; IrisMatch's scheduled purge job deletes the iris code and returns a deletion receipt logged in Emerald's compliance record.",
      sells_or_profits: "No",
      security_measures_description: "Iris codes are encrypted at rest with AES-256 in IrisMatch's Austin facility and in transit via TLS 1.3; the matching API is reachable only via a scoped, quarterly-rotated key held by Emerald's authentication service.",
      disclosure_recipients: "IrisMatch Technologies, Inc. (Texas, iris-matching processor) receives the iris code under a data-processing agreement dated 14 June 2025 forbidding further disclosure and requiring deletion within 30 days of contract end.",
      disclosure_bases: ["Subject consent to the disclosure", "Completes a financial transaction the subject requested or authorised", "Third party contractually promises no further disclosure"],
      tx_destruction_within_one_year: "No",
      tx_longer_retention_required_by_law: "No",
      tx_employer_security_collection: "No",
      tx_ai_training_use: "No",
      wa_enrolls_in_database: "Yes",
      wa_commercial_purpose: "Yes",
      wa_security_purpose_only: "No",
      wa_mhmda_health_inference: "No",
      wa_mhmda_privacy_policy_published: "Yes",
      wa_mhmda_collection_consent: "Yes",
      wa_mhmda_share_consent_separate: "Yes",
      wa_mhmda_geofence_health_facility: "No",
      approved_by_name: "Sinead Colquhoun-Barry",
      approved_by_title: "Chief Compliance Officer",
      approval_date: "2026-05-05",
      next_review_due: "2027-05-05",
    },
  },
  {
    id: "biometric-p08-alderwood-health-partners",
    tool: "biometric",
    label: "Illinois-only healthcare vein-pattern patient identification, vendor involved, standalone consent",
    company: "Alderwood Health Partners LLC",
    sector: "Multi-clinic healthcare provider",
    geo: "us",
    summary: "An Illinois clinic network uses palm-vein pattern recognition to identify patients at check-in through a named health-IT vendor's biometric module, with a standalone written consent obtained at registration. Exercises the healthcare-provider organisation type and the healthcare treatment/payment/operations context question answered Yes, contrasting with the employer- and consumer-posture fixtures elsewhere in the panel.",
    intake: {
      orgName: "Alderwood Health Partners LLC",
      biometricTypes: ["Vein pattern recognition"],
      orgType: "Healthcare provider",
      purpose: "Other",
      jurisdictions: ["Illinois, USA (BIPA)"],
      data_source_description: "A palm-vein scanner at check-in in each of Alderwood's four Illinois clinics captures a near-infrared vein-pattern image, converted on-device to an irreversible template by MedID Systems, Inc.'s patient-identification module integrated with the Epic EHR, and used to match returning patients to their existing chart rather than creating a duplicate record.",
      healthcare_tpo_context: "Yes",
      entity_is_government: "No",
      glba_financial_institution: "No",
      notice_before_collection: "Written notice given before collection",
      notice_purpose_and_term: "Yes",
      consent_artifact_type: "Standalone written release signed before collection",
      release_artifact_description: "The \"Patient Biometric Identification Consent\" form is presented at first registration, separate from the general HIPAA Notice of Privacy Practices, naming the vein-pattern identifier, the chart-matching purpose, MedID Systems as the vendor, and the retention period. As of June 2026, 96% of active patients have a signed form on file; the remaining patients are identified by name and date of birth until they next register in person.",
      biometric_consent_withdrawal: "A patient may withdraw at any registration desk; front-desk staff mark the enrolment inactive in Epic the same day and MedID Systems purges the template within 30 days, with a deletion confirmation logged to the patient's chart.",
      retention_schedule_text: "Policy CLIN-19 \"Biometric Patient Identification Retention\", version 1.0, approved 4 January 2025, provides that vein-pattern templates are retained only while the patient record remains active and are deleted no later than 30 days after the patient requests withdrawal or the record is archived under the clinic's standard medical-record retention period.",
      retention_policy_public: "Yes",
      retention_policy_predates_possession: "Yes",
      protection_parity: "Yes",
      destruction_trigger: "Patient withdrawal request or chart archival; MedID Systems' scheduled purge job deletes the template and logs a destruction event to the Epic integration audit trail.",
      sells_or_profits: "No",
      security_measures_description: "Templates are encrypted at rest with AES-256 within MedID Systems' HIPAA-compliant hosting environment and in transit via TLS 1.3 to the Epic integration layer; access is limited to registration staff under role-based EHR permissions logged and reviewed quarterly by the Privacy Officer.",
      disclosure_recipients: "MedID Systems, Inc. (patient-identification vendor) receives the vein-pattern template for chart-matching under a HIPAA-compliant business associate agreement dated 4 January 2025 forbidding further disclosure and requiring deletion within 30 days of contract end.",
      disclosure_bases: ["Subject consent to the disclosure", "Necessary to provide a product or service the subject requested", "Third party contractually promises no further disclosure"],
      approved_by_name: "Dr. Priya Nagarajan-Ford",
      approved_by_title: "Chief Medical Information Officer",
      approval_date: "2025-01-04",
      next_review_due: "2027-01-04",
    },
  },
  {
    id: "biometric-p09-sterling-voice-finance",
    tool: "biometric",
    label: "UK fintech, Texas call-centre voiceprint authentication, clickwrap consent, vendor involved",
    company: "Sterling Voice Finance Ltd",
    sector: "Consumer lending fintech",
    geo: "eu",
    summary: "A UK-headquartered consumer-lending fintech authenticates borrowers calling its Texas servicing centre using voiceprint matching from a named US vendor, with consent captured as clickwrap acceptance in the mobile app before the borrower's first call. Exercises the single-state Texas CUBI branch for a financial institution, alongside UK GDPR scope.",
    intake: {
      orgName: "Sterling Voice Finance Ltd",
      biometricTypes: ["Voiceprint / speaker recognition"],
      orgType: "Financial institution / fintech",
      purpose: "Customer authentication",
      jurisdictions: ["Texas, USA (CUBI)", "United Kingdom (UK GDPR)"],
      data_source_description: "Borrowers calling Sterling's Austin, Texas servicing centre are enrolled by repeating a passphrase during their first call; VoicePrint Analytics LLC's IVR-integrated engine generates a voiceprint used to authenticate the borrower on subsequent calls without a security-question challenge.",
      healthcare_tpo_context: "No",
      entity_is_government: "No",
      glba_financial_institution: "Yes",
      notice_before_collection: "Written notice given before collection",
      consent_artifact_type: "Clickwrap or in-product acceptance",
      release_artifact_description: "Before the borrower's first authenticated call, the Sterling mobile app presents a dedicated voice-biometric consent screen naming the identifier, the authentication purpose, VoicePrint Analytics as the vendor, and the retention period; the borrower taps \"I Agree\" and the acceptance is timestamped in Sterling's consent-management system.",
      biometric_consent_withdrawal: "A borrower can opt out via the app or by asking a servicing agent; the voiceprint is flagged inactive immediately and VoicePrint Analytics deletes it within 15 days, with a deletion receipt logged against the loan account.",
      retention_schedule_text: "Voiceprints are retained for the life of the loan and deleted no later than 90 days after the loan is paid in full or charged off, per the published Voice Authentication Policy at sterlingvoicefinance.example/privacy/voice, last updated 2 February 2026.",
      retention_policy_public: "Yes",
      protection_parity: "Yes",
      destruction_trigger: "Loan payoff or charge-off date recorded in the servicing system, plus the 90-day grace period; VoicePrint Analytics' scheduled job deletes the voiceprint and returns a deletion receipt.",
      sells_or_profits: "No",
      security_measures_description: "Voiceprints are encrypted at rest with AES-256 at VoicePrint Analytics' Austin data centre and in transit via TLS 1.3 from the IVR platform; access is limited to Sterling's servicing-operations team under MFA-gated SSO reviewed quarterly.",
      disclosure_recipients: "VoicePrint Analytics LLC (Texas, voice-matching processor) receives the voiceprint for authentication under a data-processing agreement dated 9 September 2025 forbidding further disclosure and requiring deletion within 30 days of contract end.",
      disclosure_bases: ["Subject consent to the disclosure", "Necessary to provide a product or service the subject requested", "Third party contractually promises no further disclosure"],
      tx_destruction_within_one_year: "No",
      tx_longer_retention_required_by_law: "Yes",
      tx_employer_security_collection: "No",
      tx_ai_training_use: "No",
      approved_by_name: "Oliver Fairbrass-Kent",
      approved_by_title: "Head of Regulatory Compliance",
      approval_date: "2026-02-02",
      next_review_due: "2027-02-02",
    },
  },
  {
    id: "biometric-p10-cascade-university-movement-lab",
    tool: "biometric",
    label: "Washington-only university gait-analysis research study, in-house (no vendor), health-inference MHMDA branch triggered",
    company: "Cascade University Movement Sciences Lab",
    sector: "Academic biomechanics research",
    geo: "us",
    summary: "A Washington-state university research lab studies gait patterns to detect early markers of neuromuscular decline, so the study both engages the Washington biometric-privacy statute and, because it infers a health condition, the My Health My Data Act's health-inference branch. Exercises the research-organisation type, IRB-based standalone consent, and no third-party vendor.",
    intake: {
      orgName: "Cascade University Movement Sciences Lab",
      biometricTypes: ["Gait analysis"],
      orgType: "Research organisation",
      purpose: "Research or product development",
      jurisdictions: ["Washington state, USA"],
      data_source_description: "Participants walk across a pressure-sensitive gait mat and are recorded by two depth cameras in the lab's Seattle facility; the university's own analysis software computes gait-parameter templates used to flag patterns associated with early neuromuscular decline, entirely on lab-owned servers.",
      healthcare_tpo_context: "No",
      entity_is_government: "No",
      glba_financial_institution: "No",
      notice_before_collection: "Written notice given before collection",
      consent_artifact_type: "Standalone written release signed before collection",
      release_artifact_description: "The IRB-approved \"Gait Study Biometric Consent Form\" (protocol GAIT-2026-014, approved 8 January 2026) is signed by each participant before the first recording session, naming the gait-template identifier, the research purpose, the retention period, and that no data is sold or shared outside the research team. All 86 enrolled participants have a signed form on file.",
      biometric_consent_withdrawal: "A participant may withdraw at any time by notifying the study coordinator; their gait templates are deleted from the analysis server within 10 business days and excluded from any pending publication dataset.",
      retention_schedule_text: "Per the IRB protocol, gait templates are retained for the duration of the study plus five years for replication purposes, then permanently deleted; the schedule is stated in the study's public IRB registration but not separately published on a lab website.",
      retention_policy_public: "No",
      protection_parity: "Yes",
      destruction_trigger: "Five years after the study's IRB-approved closeout date; the lab's data manager runs a manual deletion pass and records it in the study's data-management log.",
      sells_or_profits: "No",
      security_measures_description: "Gait templates are stored on an access-controlled lab server behind the university's research-network firewall, encrypted at rest with AES-256; only the three study staff listed on the IRB protocol have access, logged via the university's central authentication system.",
      disclosure_recipients: "No third party receives individual gait templates; only de-identified, aggregated statistical results are shared in study publications.",
      disclosure_bases: ["No disclosures are made"],
      wa_enrolls_in_database: "Yes",
      wa_commercial_purpose: "No",
      wa_security_purpose_only: "No",
      wa_mhmda_health_inference: "Yes",
      wa_mhmda_privacy_policy_published: "No",
      wa_mhmda_collection_consent: "Yes",
      wa_mhmda_share_consent_separate: "Yes",
      wa_mhmda_geofence_health_facility: "No",
      approved_by_name: "Dr. Helena Marchetti-Wu",
      approved_by_title: "Principal Investigator",
      approval_date: "2026-01-08",
      next_review_due: "2027-01-08",
    },
  },
  {
    id: "biometric-p11-ferrotech-industrial",
    tool: "biometric",
    label: "German multinational, Illinois/Texas/Washington plus a named Colorado site, employer fingerprint access control, vendor involved",
    company: "Ferrotech Industrial GmbH",
    sector: "Heavy industrial manufacturing",
    geo: "eu",
    summary: "A German industrial manufacturer runs fingerprint physical-access control across US plants in Illinois, Texas, Washington and a fourth site in Colorado (named via the 'Other US state' field), alongside its EU home operations. Exercises the broadest multi-state combination in the panel plus the named-other-state branch and a single access-control vendor spanning every site.",
    intake: {
      orgName: "Ferrotech Industrial GmbH",
      biometricTypes: ["Fingerprint / palm print"],
      orgType: "Employer (employee biometrics)",
      purpose: "Physical access control",
      jurisdictions: ["Illinois, USA (BIPA)", "Texas, USA (CUBI)", "Washington state, USA", "Other US state", "EU / EEA (GDPR)"],
      other_state_names: "Colorado",
      data_source_description: "Sentinel Access Technologies readers capture fingerprint templates at restricted-area doors in Ferrotech's Peru, Illinois; Odessa, Texas; Spokane, Washington; and Loveland, Colorado plants, syncing to Sentinel's US regional cloud tenant shared across all four sites.",
      healthcare_tpo_context: "No",
      entity_is_government: "No",
      glba_financial_institution: "No",
      notice_before_collection: "Written notice given before collection",
      notice_purpose_and_term: "Yes",
      consent_artifact_type: "Standalone written release signed before collection",
      release_artifact_description: "The \"US Plants Biometric Access Consent and Release\" (Rev. 1, adopted 18 March 2025) is a standalone document signed at each plant's enrolment kiosk, naming the identifier, the physical-access purpose, Sentinel as the vendor, and the retention period. As of July 2026, all 2,260 enrolled employees across the four US plants have a signed release on file.",
      biometric_consent_withdrawal: "An employee submits a Biometric Withdrawal Request to plant HR; access reverts to badge-only within one business day and Sentinel deletes the template within 30 days, with a destruction certificate logged centrally.",
      retention_schedule_text: "Policy SEC-GL-07 \"US Biometric Access Retention\", version 1.2, approved 18 March 2025 and posted at each plant's notice board, provides templates are destroyed no later than 30 days after termination or reassignment away from restricted areas, enforced by Sentinel's automated deprovisioning job across all four sites.",
      retention_policy_public: "Yes",
      retention_policy_predates_possession: "Yes",
      protection_parity: "Yes",
      destruction_trigger: "Termination or reassignment recorded in the group HR system, triggering a Sentinel deprovisioning webhook that purges the template at whichever site it was enrolled and logs a destruction certificate.",
      sells_or_profits: "No",
      security_measures_description: "Templates are encrypted at rest with AES-256 in Sentinel's regional tenant and in transit via TLS 1.3; access is limited to twelve named plant and regional security administrators under MFA-gated SSO recertified quarterly by the Group Director of Security.",
      disclosure_recipients: "Sentinel Access Technologies, Inc. (access-control vendor) receives the fingerprint template for all four US plants under a single data-processing addendum dated 18 March 2025 forbidding further disclosure and requiring deletion within 30 days of contract end.",
      disclosure_bases: ["Necessary to provide a product or service the subject requested", "Third party contractually promises no further disclosure"],
      tx_destruction_within_one_year: "Yes",
      tx_longer_retention_required_by_law: "No",
      tx_employer_security_collection: "Yes",
      tx_ai_training_use: "No",
      wa_enrolls_in_database: "Yes",
      wa_commercial_purpose: "No",
      wa_security_purpose_only: "Yes",
      wa_mhmda_health_inference: "No",
      wa_mhmda_privacy_policy_published: "Yes",
      wa_mhmda_collection_consent: "Yes",
      wa_mhmda_share_consent_separate: "Yes",
      wa_mhmda_geofence_health_facility: "No",
      approved_by_name: "Dr. Reinhard Ostmann-Voelker",
      approved_by_title: "Global Director of Security",
      approval_date: "2025-03-18",
      next_review_due: "2027-03-18",
    },
  },
  {
    id: "biometric-p12-zeegat-toegangssystemen",
    tool: "biometric",
    label: "Dutch security vendor, EU-only facial-geometry physical access control, no US jurisdiction and no Stage-3 practice questions",
    company: "Zeegat Toegangssystemen B.V.",
    sector: "Physical security and access-control systems",
    geo: "eu",
    summary: "A Dutch access-control-systems provider deploys its own facial-geometry readers at client office buildings entirely within the EU/EEA, with no Illinois, Texas or Washington exposure, so none of the contract's US-practices conditional questions are triggered — an honestly-empty Stage 3 rather than a degraded record, contrasted with the multi-state US fixtures elsewhere in this panel.",
    intake: {
      orgName: "Zeegat Toegangssystemen B.V.",
      biometricTypes: ["Facial geometry / facial recognition"],
      orgType: "Security / access control provider",
      purpose: "Physical access control",
      jurisdictions: ["EU / EEA (GDPR)"],
      approved_by_name: "Willem Overmars-Steenkamp",
      approved_by_title: "Managing Director",
      approval_date: "2026-04-20",
      next_review_due: "2027-04-20",
    },
  },
  {
    id: "biometric-p13-lumen-face-auth",
    tool: "biometric",
    label: "US consumer facial-authentication app, California and Colorado scope, no Illinois/Texas/Washington exposure",
    company: "Lumen Face Auth, Inc.",
    sector: "Consumer identity-verification app",
    geo: "us",
    summary: "A US consumer identity-verification app authenticates users by facial geometry for customers in California and Colorado only, with no Illinois, Texas or Washington users, so the record correctly leaves every BIPA/CUBI/RCW-19.375 conditional field absent rather than answering questions the form never asked.",
    intake: {
      orgName: "Lumen Face Auth, Inc.",
      biometricTypes: ["Facial geometry / facial recognition"],
      orgType: "Consumer app or platform",
      purpose: "Customer authentication",
      jurisdictions: ["California, USA (CCPA/CPRA)", "Colorado, USA (CPA)"],
      approved_by_name: "Janelle Fitzsimmons-Okafor",
      approved_by_title: "Chief Privacy Officer",
      approval_date: "2026-06-15",
      next_review_due: "2027-06-15",
    },
  },
  {
    id: "biometric-p14-briarcliff-hardware",
    tool: "biometric",
    label: "Small US employer, Illinois plus a named out-of-registry state, verbal consent only, unpublished retention — risk-flagged small-business record",
    company: "Briarcliff Hardware & Supply LLC",
    sector: "Retail hardware store",
    geo: "us",
    summary: "A small Illinois hardware store chain with a second location in Ohio (named via the 'Other US state' field) installs a fingerprint time clock without formal paperwork, relying only on a verbal explanation at hiring and never publishing a retention policy — a small-business risk-flagged record distinct from the panel's larger, better-documented employer fixtures.",
    intake: {
      orgName: "Briarcliff Hardware & Supply LLC",
      biometricTypes: ["Fingerprint / palm print"],
      orgType: "Employer (employee biometrics)",
      purpose: "Time & attendance / workforce management",
      jurisdictions: ["Illinois, USA (BIPA)", "Other US state"],
      other_state_names: "Ohio",
      data_source_description: "A single off-the-shelf fingerprint time clock at each of the two store locations (Aurora, Illinois and Toledo, Ohio) stores templates locally on the clock's internal memory; no network connection or vendor cloud service is involved.",
      healthcare_tpo_context: "No",
      entity_is_government: "No",
      glba_financial_institution: "No",
      notice_before_collection: "Notice given before collection, but not in writing",
      notice_purpose_and_term: "No",
      consent_artifact_type: "Verbal consent only",
      release_artifact_description: "The store manager explains the fingerprint clock to each new hire verbally during their first shift; no written notice, consent form, or release has been prepared or signed by any employee.",
      biometric_consent_withdrawal: "Not offered as a defined process; an employee who objects would need to raise the issue with the store manager directly, and no written withdrawal procedure exists.",
      retention_schedule_text: "No written retention schedule exists; templates remain on the clock's internal memory indefinitely and are only removed if an employee is manually deleted from the device by the store manager after termination, a step that is not consistently performed.",
      retention_policy_public: "No",
      retention_policy_predates_possession: "No",
      protection_parity: "Not known",
      destruction_trigger: "Manual deletion by the store manager from the clock's device menu after an employee's termination, performed inconsistently and with no logging.",
      sells_or_profits: "No",
      security_measures_description: "The clock is password-protected for administrative functions but the template store itself is not separately encrypted, and no access log exists beyond the device's built-in event history.",
      disclosure_recipients: "No third party receives the fingerprint data; the clock is a standalone device with no network or cloud connection.",
      disclosure_bases: ["No disclosures are made"],
      approved_by_name: "",
      approved_by_title: "",
      approval_date: "",
      next_review_due: "",
    },
  },
  {
    id: "biometric-p15-nordisk-sakerhetsteknik",
    tool: "biometric",
    label: "Swedish security vendor, Singapore and Australia deployments of an 'Other' biometric identifier, no EU or US practice-state exposure",
    company: "Nordisk Säkerhetsteknik AB",
    sector: "Physical security systems vendor",
    geo: "eu",
    summary: "A Swedish security-systems vendor deploys an ear-shape recognition access-control product exclusively for clients in Singapore and Australia, with no EU, UK or US jurisdiction in scope for this deployment, so the record answers only the always-required Stage 1/2 fields plus a description that the modality falls under the contract's 'Other biometric identifier' option.",
    intake: {
      orgName: "Nordisk Säkerhetsteknik AB",
      biometricTypes: ["Other biometric identifier"],
      orgType: "Security / access control provider",
      purpose: "Physical access control",
      jurisdictions: ["Singapore (PDPA)", "Australia (Privacy Act)"],
      approved_by_name: "Astrid Lindqvist-Berggren",
      approved_by_title: "Head of Compliance",
      approval_date: "2026-05-19",
      next_review_due: "2027-05-19",
    },
  },
];
