// /all-ptest fixture panel — dpa. Fifteen complete, internally consistent
// intakes authored 2026-09-14 (see ./types.ts and scripts/ptest/PANEL-BRIEF.md).
// Validated by tests/edge/ptest/panels.test.ts.

import type { PanelFixture } from "./types.ts";

export const PANEL_DPA: PanelFixture[] = [
  {
    id: "dpa-p01-vindobona-medtech",
    tool: "dpa",
    label: "EU controller→processor, EU-only, general sub-processor authorisation",
    company: "Vindobona MedTech GmbH",
    sector: "Pharmaceutical analytics",
    geo: "eu",
    summary: "German controller-processor DPA for a clinical-analytics hosting arrangement kept entirely inside the EU. Exercises the controller→processor branch, the general sub-processor authorisation model with a 30-day advance-notice window, documentation-review audit rights and duration-based retention, with no cross-border transfer clause needed.",
    intake: {
      entityName: "Vindobona MedTech GmbH",
      controllerName: "Vindobona MedTech GmbH",
      controllerJurisdiction: "Germany",
      processorName: "Solera Analytics S.A.",
      processorJurisdiction: "France",
      services: "Solera Analytics S.A. hosts and operates the clinical-trial recruitment analytics platform used by Vindobona MedTech GmbH's research division, processing candidate contact details and enrolment eligibility data for phase II/III trial matching from its Paris (eu-west-3) data centre. The platform ingests referral lists from participating hospital networks and returns eligibility scores to Vindobona's trial coordinators; no data leaves the EU at any stage of the pipeline.",
      dataCategories: ["General personal data", "Health / medical data"],
      retention: "For the duration of the principal agreement, then delete or return",
      hasSubProcessors: true,
      subProcessorList: "OVHcloud SAS (infrastructure hosting, Roubaix, France); Mailjet SAS (transactional email for coordinator notifications, Paris, France).",
      auditRights: "Documentation review — Processor provides audit reports/certifications on request",
      includeTransferClause: false,
      legalFramework: "GDPR",
      documentType: "gdpr",
      subprocessorAuthorizationModel: "general",
      subprocessorChangeNoticePeriod: "30",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "access_control", "mfa",
        "logging_monitoring", "incident_response", "personnel_confidentiality",
      ],
      securityMeasuresDetails: "Trial data is encrypted at rest with AES-256 (customer-managed keys rotated quarterly) and TLS 1.3 in transit; access to the recruitment database is limited to eleven named analysts under role-based provisioning reviewed monthly by the Solera Data Protection Officer. All administrative access requires FIDO2 MFA. A documented incident-response runbook was last tested in a tabletop exercise on 3 March 2026, and every analyst completes annual clinical-data confidentiality training.",
    },
  },
  {
    id: "dpa-p02-cobalt-ridge-analytics",
    tool: "dpa",
    label: "US domestic controller→processor, annual audit, general sub-processor authorisation",
    company: "Cobalt Ridge Analytics, Inc.",
    sector: "Marketing analytics",
    geo: "us",
    summary: "California controller engaging a Delaware processor for marketing-analytics hosting entirely within the United States. Exercises the controller→processor branch with an annual third-party audit right, named US-based sub-processors under the general authorisation model, and a US-state document type with no transfer clause.",
    intake: {
      entityName: "Cobalt Ridge Analytics, Inc.",
      controllerName: "Cobalt Ridge Analytics, Inc.",
      controllerJurisdiction: "California",
      processorName: "Northstar Data Services LLC",
      processorJurisdiction: "Delaware",
      services: "Northstar Data Services LLC operates the customer segmentation and email-campaign analytics platform for Cobalt Ridge Analytics, Inc., ingesting purchase history and marketing-consent records from Cobalt Ridge's e-commerce clients and returning audience segments for campaign targeting. All processing occurs in Northstar's us-east-1 and us-west-2 regions; no data is processed or stored outside the United States.",
      dataCategories: ["General personal data", "Financial / payment data"],
      retention: "For the duration of the principal agreement, then delete or return",
      hasSubProcessors: true,
      subProcessorList: "Amazon Web Services, Inc. (cloud infrastructure hosting); Twilio Inc. (SMS campaign delivery).",
      auditRights: "Annual audit — third-party audit summary plus right of on-site inspection on reasonable notice",
      includeTransferClause: false,
      legalFramework: "US",
      documentType: "us-state",
      subprocessorAuthorizationModel: "general",
      subprocessorChangeNoticePeriod: "30",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "access_control", "mfa",
        "vulnerability_mgmt", "security_testing", "backup_resilience",
      ],
      securityMeasuresDetails: "Segmentation data is encrypted at rest with AWS KMS-managed keys and in transit via TLS 1.2+. Northstar runs quarterly vulnerability scans and an annual third-party penetration test (most recently 14 April 2026, no critical findings outstanding), enforces MFA for all console access, and maintains nightly encrypted backups retained for 35 days with semi-annual restore testing.",
    },
  },
  {
    id: "dpa-p03-alamo-fleet-solutions",
    tool: "dpa",
    label: "US domestic, no sub-processors, fixed-period retention, enhanced audit",
    company: "Alamo Fleet Solutions LLC",
    sector: "Commercial fleet logistics",
    geo: "us",
    summary: "Texas fleet-logistics controller engaging an Illinois payment processor with no sub-processors in the chain. Exercises the enhanced on-site audit-rights option, a fixed-period retention answer with the form's fold-in free text, and a location-plus-financial data category mix, entirely domestic.",
    intake: {
      entityName: "Alamo Fleet Solutions LLC",
      controllerName: "Alamo Fleet Solutions LLC",
      controllerJurisdiction: "Texas",
      processorName: "Meridian Payment Processing Corp.",
      processorJurisdiction: "Illinois",
      services: "Meridian Payment Processing Corp. processes fuel-card transactions and driver-location telemetry for Alamo Fleet Solutions LLC's 340-truck fleet, matching each transaction to a GPS waypoint from the in-cab telematics unit to flag fuel-card misuse. Meridian performs all matching and settlement in its Chicago data center; Alamo receives only exception reports.",
      dataCategories: ["Financial / payment data", "Location data"],
      retention: "Fixed period — specify",
      hasSubProcessors: false,
      auditRights: "Enhanced — on-site inspection on 30 days' notice plus continuous evidence access",
      includeTransferClause: false,
      legalFramework: "US",
      documentType: "us-state",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "access_control",
        "logging_monitoring", "data_segregation", "secure_deletion",
      ],
      securityMeasuresDetails: "Transaction and telemetry records are held in a segregated schema encrypted at rest with AES-256, transmitted over TLS 1.3 from each telematics gateway, and access-logged to a SIEM reviewed weekly by Meridian's fraud-operations team. Retained records are purged by an automated job that cryptographically shreds the encryption key set for records past the five-year window, matching the retention answer below of \"Fixed period: five years after contract termination, then secure deletion.\"",
    },
  },
  {
    id: "dpa-p04-ile-de-rhone-diagnostics",
    tool: "dpa",
    label: "EU-only, genetic and health data, custom audit rights, specific sub-processor authorisation",
    company: "Île-de-Rhône Diagnostics SAS",
    sector: "Clinical diagnostics laboratory",
    geo: "eu",
    summary: "French diagnostics-lab controller engaging a Dutch genomics-cloud processor for sequencing compute, kept EU-only. Exercises special-category data (health and genetic), a custom audit-rights answer using the form's fold-in convention, and the specific (per-instance) sub-processor authorisation model rather than general advance notice.",
    intake: {
      entityName: "Île-de-Rhône Diagnostics SAS",
      controllerName: "Île-de-Rhône Diagnostics SAS",
      controllerJurisdiction: "France",
      processorName: "Zeeland BioCloud B.V.",
      processorJurisdiction: "Netherlands",
      services: "Zeeland BioCloud B.V. provides the sequencing-compute pipeline that processes whole-exome sequencing output for Île-de-Rhône Diagnostics SAS's oncology panel, converting raw FASTQ files into annotated variant-call reports returned to the ordering clinician. All compute runs in Zeeland's Amsterdam facility; source samples never leave France and only de-identified sequence data crosses into the Netherlands.",
      dataCategories: ["Health / medical data", "Genetic data"],
      retention: "As directed by the Controller's documented instructions",
      hasSubProcessors: true,
      subProcessorList: "Genomics Cloud Compute B.V. (variant-calling compute cluster, Netherlands).",
      auditRights: "Custom — describe",
      includeTransferClause: false,
      legalFramework: "GDPR",
      documentType: "gdpr",
      subprocessorAuthorizationModel: "specific",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "pseudonymisation",
        "access_control", "data_segregation", "personnel_confidentiality",
      ],
      securityMeasuresDetails: "Sequence data is pseudonymised at ingestion (patient identifiers replaced with a one-way study code held only by Île-de-Rhône), encrypted at rest with AES-256 and in transit with TLS 1.3, and processed in a logically segregated compute enclave dedicated to this contract. All Zeeland genomics staff sign confidentiality undertakings specific to clinical genetic data and complete annual GDPR Article 9 training. The custom audit answer reads: \"Custom: Processor provides an ISO 27001 certificate and a SOC 2 Type II report annually and permits a joint on-site inspection of the compute enclave every two years with 60 days' written notice.\"",
    },
  },
  {
    id: "dpa-p05-noordzee-cloud-services",
    tool: "dpa",
    label: "Processor perspective, EU-only, processor→sub-processor authorisation with short notice window",
    company: "Noordzee Cloud Services B.V.",
    sector: "Cloud hosting services",
    geo: "eu",
    summary: "Dutch cloud-hosting company drafting the DPA from the Processor's own seat for a UK retail controller, exercising the processor→sub-processor branch: the entity naming its own downstream infrastructure vendor under the general authorisation model with a short 14-day notice window, EU-only with documentation-review audit rights.",
    intake: {
      entityName: "Noordzee Cloud Services B.V.",
      controllerName: "Bellhaven Retail Ltd",
      controllerJurisdiction: "United Kingdom",
      processorName: "Noordzee Cloud Services B.V.",
      processorJurisdiction: "Netherlands",
      services: "Noordzee Cloud Services B.V. hosts Bellhaven Retail Ltd's e-commerce order-management platform, storing customer order history, delivery addresses and loyalty-account identifiers in Noordzee's Amsterdam facility, and handling nightly reconciliation feeds to Bellhaven's UK warehouse-management system.",
      dataCategories: ["General personal data"],
      retention: "As directed by the Controller's documented instructions",
      hasSubProcessors: true,
      subProcessorList: "Hetzner Online GmbH (infrastructure hosting, Falkenstein, Germany).",
      auditRights: "Annual audit — third-party audit summary plus right of on-site inspection on reasonable notice",
      includeTransferClause: false,
      legalFramework: "GDPR",
      documentType: "gdpr",
      subprocessorAuthorizationModel: "general",
      subprocessorChangeNoticePeriod: "14",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "access_control",
        "backup_resilience", "physical_security", "logging_monitoring",
      ],
      securityMeasuresDetails: "Order data is encrypted at rest with AES-256 and in transit via TLS 1.3 between Noordzee and Bellhaven's warehouse system. Hetzner's Falkenstein facility carries ISO 27001 physical-security certification, which Noordzee reviews annually as part of its sub-processor due-diligence file. Database access logs are retained 13 months and reviewed monthly by Noordzee's platform security lead, and encrypted backups are taken nightly with a 30-day retention window.",
    },
  },
  {
    id: "dpa-p06-gramercy-park-wealth",
    tool: "dpa",
    label: "US controller, EU processor, dual document type, no restricted transfer",
    company: "Gramercy Park Wealth Advisors, Inc.",
    sector: "Wealth management",
    geo: "us",
    summary: "New York registered investment adviser engaging an Irish fintech processor for portfolio-reporting support, exercising the dual EU/US document type because processing sits entirely inside Ireland (so no restricted transfer clause is triggered) while both regimes still govern the record. Uses documentation-review audit rights and duration-based retention with no sub-processors.",
    intake: {
      entityName: "Gramercy Park Wealth Advisors, Inc.",
      controllerName: "Gramercy Park Wealth Advisors, Inc.",
      controllerJurisdiction: "New York",
      processorName: "Emerald Fintech Services Ltd",
      processorJurisdiction: "Ireland",
      services: "Emerald Fintech Services Ltd operates the client portfolio-reporting portal for Gramercy Park Wealth Advisors, Inc., generating quarterly statements and performance dashboards for the adviser's US and EU-resident clients. All statement generation and data storage occurs in Emerald's Dublin data center; no client record leaves Ireland.",
      dataCategories: ["Financial / payment data", "General personal data"],
      retention: "For the duration of the principal agreement, then delete or return",
      hasSubProcessors: false,
      auditRights: "Documentation review — Processor provides audit reports/certifications on request",
      includeTransferClause: false,
      legalFramework: "Dual — GDPR and US state law",
      documentType: "dual-eu-us",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "access_control", "mfa", "logging_monitoring",
      ],
      securityMeasuresDetails: "Client statements are encrypted at rest with AES-256 and in transit via TLS 1.3. Access to the reporting database is limited to Emerald's seven-person reporting-operations team under MFA-gated SSO, and all access is logged to a SIEM reviewed weekly by Emerald's compliance manager.",
    },
  },
  {
    id: "dpa-p07-thameswood-retail",
    tool: "dpa",
    label: "UK controller→processor, EU-only (UK plus Ireland), enhanced audit rights",
    company: "Thameswood Retail Ltd",
    sector: "Retail and order fulfilment",
    geo: "eu",
    summary: "UK retail controller engaging an Irish fulfilment processor, both inside the contract's EU jurisdiction list so no cross-border transfer clause applies. Exercises enhanced on-site audit rights, duration-based retention, no sub-processors, and a straightforward general-plus-financial data category mix.",
    intake: {
      entityName: "Thameswood Retail Ltd",
      controllerName: "Thameswood Retail Ltd",
      controllerJurisdiction: "United Kingdom",
      processorName: "Bramford Fulfilment Services Ltd",
      processorJurisdiction: "Ireland",
      services: "Bramford Fulfilment Services Ltd manages warehousing, pick-and-pack and last-mile courier handoff for Thameswood Retail Ltd's online orders, processing customer names, delivery addresses and card-authorisation tokens (never full card numbers) at its Dublin distribution centre for orders shipped into the Republic of Ireland and Northern Ireland.",
      dataCategories: ["General personal data", "Financial / payment data"],
      retention: "For the duration of the principal agreement, then delete or return",
      hasSubProcessors: false,
      auditRights: "Enhanced — on-site inspection on 30 days' notice plus continuous evidence access",
      includeTransferClause: false,
      legalFramework: "GDPR",
      documentType: "gdpr",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "access_control",
        "physical_security", "logging_monitoring", "incident_response",
      ],
      securityMeasuresDetails: "Order and delivery data is encrypted at rest with AES-256 and in transit via TLS 1.3. The Dublin distribution centre uses badge-and-biometric physical access control at the data-room level, warehouse-floor terminal access is logged and reviewed weekly, and Bramford's incident-response plan was last exercised in a simulated courier-data-loss drill on 22 January 2026.",
    },
  },
  {
    id: "dpa-p08-summit-peak-manufacturing",
    tool: "dpa",
    label: "US domestic, employee biometric time-clock with a clear identifying purpose, fixed-period retention",
    company: "Summit Peak Manufacturing, Inc.",
    sector: "Industrial manufacturing",
    geo: "us",
    summary: "Colorado manufacturer engaging a Utah biometrics vendor for a fingerprint shift-floor time-clock system, so the biometric data category is selected alongside a purpose that is unambiguously uniquely-identifying (unlike a photo-storage scenario). Exercises fixed-period retention with the form's fold-in free text and an annual audit right, entirely domestic.",
    intake: {
      entityName: "Summit Peak Manufacturing, Inc.",
      controllerName: "Summit Peak Manufacturing, Inc.",
      controllerJurisdiction: "Colorado",
      processorName: "TimeGuard Biometrics LLC",
      processorJurisdiction: "Utah",
      services: "TimeGuard Biometrics LLC supplies and operates the fingerprint-scan time-clock system at Summit Peak Manufacturing, Inc.'s Pueblo assembly plant, matching each shift-floor worker's fingerprint template against an enrolment database to record clock-in and clock-out events for payroll. The fingerprint template is the sole means of identifying the worker at the clock — there is no badge fallback — so the identification purpose is direct and uniquely-identifying.",
      dataCategories: ["Employee / HR data", "Biometric data"],
      retention: "Fixed period — specify",
      hasSubProcessors: false,
      auditRights: "Annual audit — third-party audit summary plus right of on-site inspection on reasonable notice",
      includeTransferClause: false,
      legalFramework: "US",
      documentType: "us-state",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "access_control",
        "secure_deletion", "personnel_confidentiality", "logging_monitoring",
      ],
      securityMeasuresDetails: "Fingerprint templates are stored as irreversible mathematical hashes, encrypted at rest with AES-256 and in transit via TLS 1.3 between clock hardware and the enrolment server. Access to the enrolment database is limited to two named HR administrators, and every template is cryptographically shredded on termination or, absent an earlier trigger, after the fixed retention period stated as \"Fixed period: three years after employment ends, then destroyed under a BIPA-aligned destruction schedule with the destruction event logged.\"",
    },
  },
  {
    id: "dpa-p09-kilkenny-healthtech",
    tool: "dpa",
    label: "EU controller to US processor, SCC transfer mechanism, special-category health and genetic data",
    company: "Kilkenny HealthTech Ltd",
    sector: "Digital health platform",
    geo: "eu",
    summary: "Irish digital-health controller engaging a California sequencing-analytics processor, so a restricted transfer occurs and is covered by the EU Standard Contractual Clauses. Exercises the international-transfer branch with a named mechanism, special-category health and genetic data, a named US sub-processor under the general authorisation model, and documentation-review audit rights.",
    intake: {
      entityName: "Kilkenny HealthTech Ltd",
      controllerName: "Kilkenny HealthTech Ltd",
      controllerJurisdiction: "Ireland",
      processorName: "Meridian Cloud Solutions, Inc.",
      processorJurisdiction: "California",
      services: "Meridian Cloud Solutions, Inc. runs the variant-interpretation analytics pipeline for Kilkenny HealthTech Ltd's hereditary-cancer-risk screening app, receiving de-identified sequencing output from Kilkenny's Irish-hosted patient database and returning a risk-classification score. Processing occurs in Meridian's California data centre, which is why the transfer clause and mechanism below apply.",
      dataCategories: ["Health / medical data", "Genetic data"],
      retention: "As directed by the Controller's documented instructions",
      hasSubProcessors: true,
      subProcessorList: "CloudGenomics Inc. (variant-interpretation compute sub-processor, California, USA).",
      auditRights: "Documentation review — Processor provides audit reports/certifications on request",
      includeTransferClause: true,
      transferMechanism: "EU Standard Contractual Clauses (SCCs)",
      legalFramework: "GDPR",
      documentType: "dual-eu-us",
      subprocessorAuthorizationModel: "general",
      subprocessorChangeNoticePeriod: "30",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "pseudonymisation",
        "access_control", "mfa", "logging_monitoring", "data_segregation",
      ],
      securityMeasuresDetails: "Sequencing output is pseudonymised before it crosses to California, encrypted at rest with AES-256 and in transit with TLS 1.3, and processed in a segregated compute environment dedicated to Kilkenny's contract. Meridian enforces MFA for all engineering access, logs every query against the variant database to a SIEM retained 13 months, and completed a transfer-impact assessment alongside the SCCs confirming no conflicting US government-access order has been received to date.",
    },
  },
  {
    id: "dpa-p10-heartland-logistics",
    tool: "dpa",
    label: "US domestic, minimal general-category data, no sub-processors",
    company: "Heartland Logistics Holdings, Inc.",
    sector: "Freight logistics",
    geo: "us",
    summary: "Indiana freight-logistics controller engaging a Montana data-services processor for a small, general-purpose customer-contact database, a deliberately plain domestic scenario with no special categories, no sub-processors and documentation-review audit rights, contrasting with the more elaborate special-category fixtures elsewhere in this panel.",
    intake: {
      entityName: "Heartland Logistics Holdings, Inc.",
      controllerName: "Heartland Logistics Holdings, Inc.",
      controllerJurisdiction: "Indiana",
      processorName: "Frostbyte Data Systems LLC",
      processorJurisdiction: "Montana",
      services: "Frostbyte Data Systems LLC hosts the shipper and receiver contact directory used by Heartland Logistics Holdings, Inc.'s dispatch team to coordinate freight pickups, storing names, phone numbers and dock-scheduling notes for approximately 4,200 shipping-partner contacts in Frostbyte's Billings, Montana data centre.",
      dataCategories: ["General personal data"],
      retention: "For the duration of the principal agreement, then delete or return",
      hasSubProcessors: false,
      auditRights: "Documentation review — Processor provides audit reports/certifications on request",
      includeTransferClause: false,
      legalFramework: "US",
      documentType: "us-state",
      securityMeasuresSelected: ["encryption_at_rest", "encryption_in_transit", "access_control", "backup_resilience"],
      securityMeasuresDetails: "The contact directory is encrypted at rest with AES-256 and in transit via TLS 1.2+, access is limited to Frostbyte's four-person operations team under least-privilege provisioning, and nightly backups are retained for 30 days with quarterly restore testing.",
    },
  },
  {
    id: "dpa-p11-nordkap-analytics",
    tool: "dpa",
    label: "EU controller to Canadian processor, adequacy-decision transfer mechanism, dual EU/Canada document type",
    company: "Nordkap Analytics AB",
    sector: "Market research analytics",
    geo: "eu",
    summary: "Swedish market-research controller engaging a Canadian survey-analytics processor, exercising the international-transfer branch under an adequacy-decision mechanism (Canada's PIPEDA adequacy finding for commercial organisations) rather than SCCs. Names a Canadian sub-processor under the general authorisation model with a 45-day notice window and an annual audit right.",
    intake: {
      entityName: "Nordkap Analytics AB",
      controllerName: "Nordkap Analytics AB",
      controllerJurisdiction: "Sweden",
      processorName: "Maple Grove Data Services Inc.",
      processorJurisdiction: "Canada (federal / PIPEDA)",
      services: "Maple Grove Data Services Inc. runs the panel-management and survey-fielding platform for Nordkap Analytics AB's Nordic consumer-sentiment research, recruiting and compensating survey respondents and returning aggregated, weighted results. Respondent contact details and payment records are processed at Maple Grove's Toronto facility.",
      dataCategories: ["General personal data", "Financial / payment data"],
      retention: "For the duration of the principal agreement, then delete or return",
      hasSubProcessors: true,
      subProcessorList: "Vancouver Cloud Systems Ltd. (backup hosting, Canada).",
      auditRights: "Annual audit — third-party audit summary plus right of on-site inspection on reasonable notice",
      includeTransferClause: true,
      transferMechanism: "Adequacy decision or regulations",
      legalFramework: "GDPR",
      documentType: "dual-eu-ca",
      subprocessorAuthorizationModel: "general",
      subprocessorChangeNoticePeriod: "45",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "access_control",
        "mfa", "backup_resilience", "vulnerability_mgmt",
      ],
      securityMeasuresDetails: "Respondent records are encrypted at rest with AES-256 and in transit via TLS 1.3. Maple Grove enforces MFA for all panel-management console access, runs quarterly vulnerability scans across both the Toronto primary and Vancouver backup environments, and retains encrypted backups for 30 days with semi-annual restore testing.",
    },
  },
  {
    id: "dpa-p12-westbrook-financial",
    tool: "dpa",
    label: "US domestic, criminal-records category for KYC screening, custom audit rights",
    company: "Westbrook Financial Group Corp.",
    sector: "Retail banking and lending",
    geo: "us",
    summary: "Connecticut lender engaging an Oregon analytics processor for know-your-customer background screening, selecting the criminal-records data category alongside financial data. Exercises a custom audit-rights answer using the form's fold-in convention, controller-directed retention, and no sub-processors, entirely domestic.",
    intake: {
      entityName: "Westbrook Financial Group Corp.",
      controllerName: "Westbrook Financial Group Corp.",
      controllerJurisdiction: "Connecticut",
      processorName: "Ridgeline Analytics LLC",
      processorJurisdiction: "Oregon",
      services: "Ridgeline Analytics LLC performs know-your-customer and adverse-media screening for Westbrook Financial Group Corp.'s personal-loan underwriting, matching applicant identity data against sanctions lists and public criminal-record indices and returning a risk flag to Westbrook's underwriting team. All screening runs in Ridgeline's Portland data centre.",
      dataCategories: ["Financial / payment data", "Criminal records"],
      retention: "As directed by the Controller's documented instructions",
      hasSubProcessors: false,
      auditRights: "Custom — describe",
      includeTransferClause: false,
      legalFramework: "US",
      documentType: "us-state",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "access_control",
        "logging_monitoring", "personnel_confidentiality",
      ],
      securityMeasuresDetails: "Screening results are encrypted at rest with AES-256 and in transit via TLS 1.3, access to adverse-media match records is limited to six named compliance analysts, and every query is logged and retained for seven years to satisfy Westbrook's regulatory examination requirements. The custom audit answer reads: \"Custom: Processor completes Westbrook's annual third-party risk questionnaire and permits regulator-requested inspections within 10 business days of a request.\"",
    },
  },
  {
    id: "dpa-p13-aventura-biometrics",
    tool: "dpa",
    label: "Processor perspective, EU-only, biometric access-control data, specific sub-processor authorisation",
    company: "Aventura Biometrics GmbH",
    sector: "Physical access-control systems",
    geo: "eu",
    summary: "German biometric access-control vendor drafting the DPA from the Processor's own seat for a UK secure-facilities controller, both inside the contract's EU jurisdiction list. Exercises the biometric data category with a clear identifying purpose, enhanced on-site audit rights, fixed-period retention, and the specific (per-instance) sub-processor authorisation model.",
    intake: {
      entityName: "Aventura Biometrics GmbH",
      controllerName: "Bramwell Secure Access Ltd",
      controllerJurisdiction: "United Kingdom",
      processorName: "Aventura Biometrics GmbH",
      processorJurisdiction: "Germany",
      services: "Aventura Biometrics GmbH supplies and operates the facial-recognition secure-door access system for Bramwell Secure Access Ltd's client sites, matching each employee's enrolled facial template against a live camera feed to unlock restricted server-room doors. The facial template is the sole access credential at these doors — there is no badge fallback — so the identification purpose is direct and uniquely-identifying.",
      dataCategories: ["Biometric data", "Employee / HR data"],
      retention: "Fixed period — specify",
      hasSubProcessors: false,
      auditRights: "Enhanced — on-site inspection on 30 days' notice plus continuous evidence access",
      includeTransferClause: false,
      legalFramework: "GDPR",
      documentType: "gdpr",
      subprocessorAuthorizationModel: "specific",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "access_control",
        "secure_deletion", "physical_security", "logging_monitoring",
      ],
      securityMeasuresDetails: "Facial templates are stored as irreversible mathematical vectors, encrypted at rest with AES-256 and in transit via TLS 1.3 between the door reader and the enrolment server. Enrolment-database access is limited to three named Aventura engineers under badge-and-PIN physical control at the Munich data room, and every template is cryptographically shredded within the retention answer's window, stated as \"Fixed period: 90 days after access is revoked, then irreversibly deleted with the deletion event logged.\"",
    },
  },
  {
    id: "dpa-p14-prairie-crest-insurance",
    tool: "dpa",
    label: "US domestic, health and financial data mix for claims processing, general sub-processor authorisation",
    company: "Prairie Crest Insurance Group, Inc.",
    sector: "Health and casualty insurance",
    geo: "us",
    summary: "Minnesota insurer engaging a Washington-state claims-technology processor, mixing health and financial data categories for medical-claims adjudication. Exercises documentation-review audit rights, duration-based retention, a named claims-platform sub-processor under the general authorisation model with a 30-day notice window, entirely domestic.",
    intake: {
      entityName: "Prairie Crest Insurance Group, Inc.",
      controllerName: "Prairie Crest Insurance Group, Inc.",
      controllerJurisdiction: "Minnesota",
      processorName: "Bluewater Systems Corp.",
      processorJurisdiction: "Washington",
      services: "Bluewater Systems Corp. operates the medical-claims adjudication platform for Prairie Crest Insurance Group, Inc., ingesting itemised provider claims (diagnosis codes, treatment dates and billed amounts) and returning adjudication decisions and payment instructions. All claims data is processed in Bluewater's Seattle data centre.",
      dataCategories: ["Health / medical data", "Financial / payment data"],
      retention: "For the duration of the principal agreement, then delete or return",
      hasSubProcessors: true,
      subProcessorList: "ClaimsFlow Software, Inc. (claims-adjudication rules engine, Washington, USA).",
      auditRights: "Documentation review — Processor provides audit reports/certifications on request",
      includeTransferClause: false,
      legalFramework: "US",
      documentType: "us-state",
      subprocessorAuthorizationModel: "general",
      subprocessorChangeNoticePeriod: "30",
      securityMeasuresSelected: [
        "encryption_at_rest", "encryption_in_transit", "access_control",
        "mfa", "logging_monitoring", "data_segregation",
      ],
      securityMeasuresDetails: "Claims records are encrypted at rest with AES-256 and in transit via TLS 1.3, held in a schema logically segregated from Bluewater's other insurer clients, and accessible only to adjudication staff under MFA-gated SSO. All claims-database queries are logged and retained for six years to align with Prairie Crest's regulatory record-keeping obligations.",
    },
  },
  {
    id: "dpa-p15-lindqvist-fraud-analytics",
    tool: "dpa",
    label: "EU controller to US processor, no transfer mechanism yet in place",
    company: "Lindqvist Fraud Analytics AB",
    sector: "Payment fraud analytics",
    geo: "eu",
    summary: "Swedish fraud-analytics controller engaging a Florida payments processor while the transfer-mechanism review is still in progress, so the record honestly answers \"None in place yet\" rather than asserting a mechanism that does not exist. Exercises the transfer-gap branch alongside financial and general data categories and documentation-review audit rights.",
    intake: {
      entityName: "Lindqvist Fraud Analytics AB",
      controllerName: "Lindqvist Fraud Analytics AB",
      controllerJurisdiction: "Sweden",
      processorName: "Solaris Payments, Inc.",
      processorJurisdiction: "Florida",
      services: "Solaris Payments, Inc. provides transaction-risk scoring for Lindqvist Fraud Analytics AB's Nordic merchant clients, receiving card-transaction metadata and returning a fraud-risk score within 200 milliseconds. Scoring computation occurs in Solaris's Miami data centre; the parties' legal team is finalising the appropriate Article 46 transfer mechanism and none has been executed as of this record, which the intake states plainly rather than assuming SCCs are already in place.",
      dataCategories: ["Financial / payment data", "General personal data"],
      retention: "As directed by the Controller's documented instructions",
      hasSubProcessors: false,
      auditRights: "Documentation review — Processor provides audit reports/certifications on request",
      includeTransferClause: true,
      transferMechanism: "None in place yet",
      legalFramework: "GDPR",
      documentType: "dual-eu-us",
      securityMeasuresSelected: ["encryption_at_rest", "encryption_in_transit", "access_control", "logging_monitoring"],
      securityMeasuresDetails: "Transaction metadata is encrypted at rest with AES-256 and in transit via TLS 1.3 pending finalisation of the transfer mechanism; access to the scoring model's training data is limited to four named Solaris data scientists, and all access is logged and reviewed monthly by Lindqvist's data protection officer as an interim compensating control while the mechanism review is completed.",
    },
  },
];
