// /all-ptest fixture panel — governance. Fifteen complete, internally consistent
// intakes authored 2026-09-14 (see ./types.ts and scripts/ptest/PANEL-BRIEF.md).
// Validated by tests/edge/ptest/panels.test.ts.

import type { PanelFixture } from "./types.ts";

export const PANEL_GOVERNANCE: PanelFixture[] = [
  {
    id: "governance-p01-saas-mature-nl",
    tool: "governance",
    label: "Mature privacy programme at a Dutch project-management SaaS vendor",
    company: "Solara Cloudworks B.V.",
    sector: "Technology/SaaS",
    geo: "eu",
    summary: "Solara serves EU and UK customers with a mature privacy programme: formal DPO, verified processor DPAs, tested DSR runbook and DLP enforcement. Exercises the high-maturity branch with EU+UK jurisdictions and no special-category data.",
    intake: {
      organization_name: "Solara Cloudworks B.V.",
      sector: "Technology/SaaS",
      org_size: "51-250",
      jurisdictions: ["EU (GDPR)", "United Kingdom (UK GDPR)"],
      eu_uk_data: "Yes",
      tools: ["Microsoft 365 / Copilot", "Slack + AI features", "HubSpot"],
      data_categories: ["Contact details", "Employee records", "Customer records"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, current (reviewed in last 12 months)",
      privacy_notice_coverage: "Yes — notice covers all current activities, transfers, retention, and rights",
      dpo_status: "Yes, formal DPO",
      dpia_status: "Yes, multiple DPIAs completed",
      dpia_ai_coverage: "Yes — all AI/high-risk tools assessed",
      incident_response: "Yes, tested in last 12 months",
      training_status: "Yes, formal onboarding + annual refresh",
      training_ai_coverage: "Yes — explicitly covers AI tools",
      tool_instruction: "Yes, written policy with specific prohibitions",
      dpa_status: "Yes, all vendors",
      dpa_art28_verified: "Yes — verified",
      transfer_status: "Yes, US-based tools",
      transfer_mechanism: "EU Standard Contractual Clauses (SCCs)",
      technical_controls: "Yes — DLP/content filtering actively enforced",
      technical_controls_list: ["DLP rules", "Content filtering", "Approval workflow"],
      dsr_capability: "Yes — documented and tested across all vendors",
      dsr_rights_tested: ["Access", "Erasure", "Portability", "Rectification"],
      inventory_audit: "Yes — audited + formal approval process",
      retention_schedule_status: "Yes — retention periods documented for each category of data",
      additional_context: "The main open item is confirming the UK Addendum is countersigned for the two vendors added since the last DPA audit; that verification is scheduled for October 2026.",
      measures_review_cadence: "Annually or more often",
      measures_last_review_date: "2026-03-04",
      processing_nature: "Solara hosts a project-management SaaS product; customer records and employee records are held in its own EU-region database, with Microsoft 365/Copilot for internal documents, Slack for team communication with the AI summary feature disabled by policy, and HubSpot for sales and support under a signed Art. 28 DPA with the 2021 EU SCCs.",
      processing_scope: "Approximately 4,200 customer accounts and 140 employee records, refreshed continuously; customer records retained for 3 years after account closure and employee records for 6 years after employment ends.",
      processing_context: "Customers are business subscribers who can close their account at any time; employees cannot decline the employer's own record-keeping, so the employee-records processing carries the more material power imbalance.",
      processing_purposes: "Service delivery and billing for the SaaS product, customer support, workforce administration, and security monitoring of the platform; no secondary research use and no data sale.",
      remediation_default_owner: "Head of Compliance",
      remediation_default_target_date: "2026-11-30",
      remediation_default_priority: "Medium — remediate this year",
      remediation_default_validation_method: "Documentary evidence review",
    },
  },
  {
    id: "governance-p02-occupational-clinics-de",
    tool: "governance",
    label: "Occupational-health clinic group with Art. 37(1)(c) special-category processing",
    company: "Vindonissa Klinikgruppe GmbH",
    sector: "Healthcare/Life Sciences",
    geo: "eu",
    summary: "Vindonissa runs seven occupational-health clinics processing clinical records as a core activity at scale. Exercises the special-category and Art. 37(1)(c) branch fully, with a formal DPO mandatory under Art. 37(1)(c), and a mid-maturity technical-controls posture.",
    intake: {
      organization_name: "Vindonissa Klinikgruppe GmbH",
      sector: "Healthcare/Life Sciences",
      org_size: "251-1000",
      jurisdictions: ["EU (GDPR)"],
      eu_uk_data: "Yes",
      tools: ["Microsoft 365 / Copilot", "Zoom + AI features"],
      data_categories: ["Health or medical data", "Employee records", "Contact details"],
      special_category: "Yes",
      special_categories_list: ["Health data"],
      sc_core_activity: "Yes — a primary activity, or inextricably part of delivering our principal products or services",
      sc_core_activity_explanation: "Occupational-health assessment and treatment is the clinic group's principal service; every patient engagement produces and relies on clinical findings.",
      sc_data_subjects_count: "52,000",
      sc_population_proportion: "No",
      sc_data_volume: "Full clinical records — history, examination findings, and fitness determinations — for every patient assessed across seven clinics.",
      sc_duration: "Continuous or ongoing",
      sc_geographic_scope: "National",
      privacy_policy: "Yes, current (reviewed in last 12 months)",
      privacy_notice_coverage: "Partially — some activities or tools not yet reflected",
      dpo_status: "Yes, formal DPO",
      dpia_status: "Yes, multiple DPIAs completed",
      dpia_ai_coverage: "Some covered",
      incident_response: "Yes, tested in last 12 months",
      training_status: "Yes, formal onboarding + annual refresh",
      training_ai_coverage: "Generally covers data handling",
      tool_instruction: "Yes, written policy with specific prohibitions",
      dpa_status: "Yes, all vendors",
      dpa_art28_verified: "Partially",
      transfer_status: "All tools store data in EU/UK",
      transfer_mechanism: "n/a",
      technical_controls: "Partial — some tools or categories",
      technical_controls_list: ["DLP rules", "Endpoint upload restrictions"],
      dsr_capability: "Documented but not tested",
      inventory_audit: "Inventory exists, no formal audit/approval",
      retention_schedule_status: "Partially — documented for some categories only",
      additional_context: "The privacy notice gap concerns the newly added tele-consultation module, which is scheduled to be reflected in the notice by the end of Q4 2026 alongside its own DPIA addendum.",
      measures_review_cadence: "Annually or more often",
      measures_last_review_date: "2026-01-20",
      processing_nature: "Clinical records are held in the clinic group's on-premises patient-management system across seven sites; Microsoft 365/Copilot handles internal administrative documents with clinical content excluded by policy, and Zoom supports remote follow-up consultations with the AI companion feature disabled for clinical use.",
      processing_scope: "Approximately 52,000 patient records across seven clinics, with roughly 1,800 new assessments each month; clinical records retained 10 years from the last assessment per German medical-record retention rules.",
      processing_context: "Patients are referred by employer clients or attend directly for occupational-health assessment; clinical findings are held under physician confidentiality and only a fitness verdict is released to the referring employer.",
      processing_purposes: "Occupational-health assessment, fitness-for-work determinations, and statutory health surveillance for exposed-worker cohorts; no secondary research use without separate ethics approval.",
      remediation_default_owner: "Dr. Petra Lindholm, Data Protection Officer",
      remediation_default_target_date: "2026-12-15",
      remediation_default_priority: "High — remediate this quarter",
      remediation_default_validation_method: "Internal audit sample",
    },
  },
  {
    id: "governance-p03-investment-bank-multistate-gb",
    tool: "governance",
    label: "Large UK investment-management firm with EU, UK and US-federal jurisdiction mix",
    company: "Castleforth Capital Partners Ltd",
    sector: "Financial services",
    geo: "eu",
    summary: "Castleforth manages assets for EU, UK and US clients with a mature, formally governed privacy programme. Exercises the largest org-size band, a three-jurisdiction mix, and verified Art. 28 DPAs with SCC-based transfers to US-based tools.",
    intake: {
      organization_name: "Castleforth Capital Partners Ltd",
      sector: "Financial services",
      org_size: "1001+",
      jurisdictions: ["EU (GDPR)", "United Kingdom (UK GDPR)", "United States — Federal"],
      eu_uk_data: "Yes",
      tools: ["Microsoft 365 / Copilot", "Salesforce + Einstein", "GitHub Copilot"],
      data_categories: ["Contact details", "Financial data", "Employee records", "Communications content"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, current (reviewed in last 12 months)",
      privacy_notice_coverage: "Yes — notice covers all current activities, transfers, retention, and rights",
      dpo_status: "Yes, formal DPO",
      dpia_status: "Yes, multiple DPIAs completed",
      dpia_ai_coverage: "Yes — all AI/high-risk tools assessed",
      incident_response: "Yes, tested in last 12 months",
      training_status: "Yes, formal onboarding + annual refresh",
      training_ai_coverage: "Yes — explicitly covers AI tools",
      tool_instruction: "Yes, written policy with specific prohibitions",
      dpa_status: "Yes, all vendors",
      dpa_art28_verified: "Yes — verified",
      transfer_status: "Yes, US-based tools",
      transfer_mechanism: "EU Standard Contractual Clauses (SCCs)",
      technical_controls: "Yes — DLP/content filtering actively enforced",
      technical_controls_list: ["DLP rules", "Content filtering", "Endpoint upload restrictions", "Approval workflow"],
      dsr_capability: "Yes — documented and tested across all vendors",
      dsr_rights_tested: ["Access", "Erasure", "Portability", "Rectification"],
      inventory_audit: "Yes — audited + formal approval process",
      retention_schedule_status: "Yes — retention periods documented for each category of data",
      additional_context: "The Data Protection Officer reports directly to the Chief Risk Officer and holds no conflicting operational role, satisfying Art. 38(6); the compliance committee reviews the DPO's report quarterly.",
      measures_review_cadence: "Annually or more often",
      measures_last_review_date: "2026-02-18",
      processing_nature: "Client onboarding and portfolio records are held in Salesforce + Einstein under a signed Art. 28 DPA with the 2021 EU SCCs and the UK Addendum; Microsoft 365/Copilot supports internal document drafting with client data excluded from Copilot indexing by policy; GitHub Copilot is used by the engineering team on internal tooling only, never on client-data repositories.",
      processing_scope: "Approximately 38,000 client relationships and 1,650 employees across EU, UK and US offices; client records retained 7 years after relationship end under FCA and SEC record-keeping rules.",
      processing_context: "Clients are sophisticated investors who engage the firm under a negotiated advisory agreement; employees are subject to enhanced financial-conduct monitoring obligations that are disclosed at onboarding.",
      processing_purposes: "Investment advisory service delivery, regulatory reporting to the FCA and SEC, and fraud/market-abuse monitoring; no client data is used for unrelated marketing.",
      remediation_default_owner: "Group Data Protection Officer",
      remediation_default_target_date: "2026-12-01",
      remediation_default_priority: "Medium — remediate this year",
      remediation_default_validation_method: "External audit or assurance report",
    },
  },
  {
    id: "governance-p04-provencal-grocer-developing-fr",
    tool: "governance",
    label: "Small French regional grocer with a developing, informally-led privacy programme",
    company: "Petit Marché Provençal SAS",
    sector: "Retail/ecommerce",
    geo: "eu",
    summary: "Petit Marché runs a loyalty-card programme across 14 stores with no DPIA and ad-hoc training. Exercises the developing-maturity branch with an informal privacy lead and an undocumented processor-contract posture.",
    intake: {
      organization_name: "Petit Marché Provençal SAS",
      sector: "Retail/ecommerce",
      org_size: "11-50",
      jurisdictions: ["EU (GDPR)"],
      eu_uk_data: "Yes",
      tools: ["HubSpot"],
      data_categories: ["Contact details", "Customer records", "Financial data"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, but outdated",
      privacy_notice_coverage: "No — notice not updated for current tools",
      dpo_status: "Yes, informal privacy lead",
      dpia_status: "No, none conducted",
      incident_response: "Documented but informal",
      training_status: "Ad hoc only",
      tool_instruction: "Verbal guidance only",
      dpa_status: "Some vendors",
      dpa_art28_verified: "Not verified",
      transfer_status: "Unsure",
      transfer_mechanism: "n/a",
      technical_controls: "No — policy and training only",
      dsr_capability: "Ad hoc / not documented",
      inventory_audit: "No formal inventory",
      retention_schedule_status: "No — no documented retention periods",
      additional_context: "The owner-manager acts as the informal privacy contact alongside running store operations; no formal DPO appointment has been made because the business does not consider its processing to meet the Art. 37(1) large-scale or core-activity thresholds, though this has not been formally assessed.",
      measures_review_cadence: "No defined cadence",
      measures_last_review_date: "",
      processing_nature: "The loyalty-card programme records customer contact details and purchase totals at the till in HubSpot; no automated decision or profiling is applied to loyalty data beyond a simple points balance.",
      processing_scope: "Approximately 6,400 loyalty-card holders across 14 stores; till and loyalty records are currently kept indefinitely pending the retention-schedule work identified above.",
      processing_context: "Customers join the loyalty programme voluntarily at the till and can decline at any time with no effect on their ability to shop.",
      processing_purposes: "Operating the loyalty-points programme and sending occasional promotional offers to enrolled members.",
      remediation_default_owner: "Owner-Manager",
      remediation_default_target_date: "2027-03-31",
      remediation_default_priority: "Low — monitor",
      remediation_default_validation_method: "Management sign-off against the artifact",
    },
  },
  {
    id: "governance-p05-adtech-media-moderate-gb",
    tool: "governance",
    label: "UK media-and-advertising group with moderate maturity and heavy ad-tech tooling",
    company: "Brightline Media Group Ltd",
    sector: "Media/advertising",
    geo: "eu",
    summary: "Brightline runs programmatic advertising campaigns for UK brands with an informal privacy lead and partial technical controls. Exercises the UK-only jurisdiction branch, moderate DSR maturity, and untested transfer status for its US ad-tech stack.",
    intake: {
      organization_name: "Brightline Media Group Ltd",
      sector: "Media/advertising",
      org_size: "51-250",
      jurisdictions: ["United Kingdom (UK GDPR)"],
      eu_uk_data: "Yes",
      tools: ["Google Workspace / Gemini", "HubSpot", "Adobe Creative Cloud"],
      data_categories: ["Contact details", "Location data", "Communications content"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, but outdated",
      privacy_notice_coverage: "Partially — some activities or tools not yet reflected",
      dpo_status: "Yes, informal privacy lead",
      dpia_status: "Yes, one DPIA completed",
      dpia_ai_coverage: "No — not for AI tools",
      incident_response: "Yes, but not tested",
      training_status: "Yes, onboarding only",
      training_ai_coverage: "No — not AI-specific",
      tool_instruction: "Verbal guidance only",
      dpa_status: "Most vendors",
      dpa_art28_verified: "Unsure",
      transfer_status: "Yes, US-based tools",
      transfer_mechanism: "EU Standard Contractual Clauses (SCCs)",
      technical_controls: "Partial — some tools or categories",
      technical_controls_list: ["Content filtering"],
      dsr_capability: "Documented but not tested",
      inventory_audit: "Inventory exists, no formal audit/approval",
      retention_schedule_status: "Unsure",
      additional_context: "The informal privacy lead is the Head of Legal, who also owns commercial contracting; the firm has not assessed whether this creates an Art. 38(6) conflict for the ad-tech vendor contracts they also negotiate.",
      measures_review_cadence: "Every 1–2 years",
      measures_last_review_date: "2025-06-10",
      processing_nature: "Campaign audience data (contact and approximate location) is processed through a mix of Google Workspace/Gemini for planning documents, HubSpot for client and prospect management, and Adobe Creative Cloud for creative production; several third-party ad-tech platforms outside this list also process campaign data under separate contracts.",
      processing_scope: "Approximately 40 active client campaigns at any time, each targeting audience segments in the low hundreds of thousands; campaign data is currently retained for the life of the client relationship with no fixed deletion point.",
      processing_context: "Individuals in campaign audiences are members of the public targeted through advertising platforms, with no direct relationship to Brightline and limited practical ability to be informed of the specific processing.",
      processing_purposes: "Planning, delivering and measuring advertising campaigns for client brands; no data is retained for Brightline's own marketing beyond the client relationship.",
      remediation_default_owner: "Head of Legal",
      remediation_default_target_date: "2026-12-31",
      remediation_default_priority: "High — remediate this quarter",
      remediation_default_validation_method: "Control re-test by a second reviewer",
    },
  },
  {
    id: "governance-p06-solo-law-firm-no-dpo-ie",
    tool: "governance",
    label: "Small Irish law firm with no DPO appointed and a stated Art. 37 rationale",
    company: "Kilbride Vance Legal Services Ltd",
    sector: "Legal services",
    geo: "eu",
    summary: "Kilbride Vance is a small conveyancing and probate practice with no DPO, on the stated ground that its processing does not meet the Art. 37(1) thresholds. Exercises the DPO 'No' branch with an explicit reasoning narrative and a developing technical posture.",
    intake: {
      organization_name: "Kilbride Vance Legal Services Ltd",
      sector: "Legal services",
      org_size: "11-50",
      jurisdictions: ["EU (GDPR)"],
      eu_uk_data: "Yes",
      tools: ["Microsoft 365 / Copilot"],
      data_categories: ["Contact details", "Financial data", "Other"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, current (reviewed in last 12 months)",
      privacy_notice_coverage: "Yes — notice covers all current activities, transfers, retention, and rights",
      dpo_status: "No",
      dpia_status: "No, none conducted",
      incident_response: "Documented but informal",
      training_status: "Yes, onboarding only",
      tool_instruction: "Yes, written policy with specific prohibitions",
      dpa_status: "Yes, all vendors",
      dpa_art28_verified: "Yes — verified",
      transfer_status: "All tools store data in EU/UK",
      transfer_mechanism: "n/a",
      technical_controls: "No — policy and training only",
      dsr_capability: "Documented but not tested",
      inventory_audit: "Inventory exists, no formal audit/approval",
      retention_schedule_status: "Yes — retention periods documented for each category of data",
      additional_context: "The partners assessed Art. 37(1) against WP243 rev.01 and concluded that conveyancing and probate case files are neither large-scale nor core regular-and-systematic monitoring, so no DPO is appointed; the managing partner acts as the named privacy contact and completed the ICO's data-protection practitioner course in 2025 to support that role.",
      measures_review_cadence: "Every 1–2 years",
      measures_last_review_date: "2025-09-30",
      processing_nature: "Client case files, held in Microsoft 365 under a signed Art. 28 DPA with the 2021 EU SCCs, contain identity, financial and property-transaction details needed for conveyancing and probate matters; Copilot is restricted by policy from indexing client-matter folders.",
      processing_scope: "Approximately 30 active matters at any time across a client base of roughly 400 individuals per year; case files are retained 7 years after matter closure under the Law Society of Ireland's record-keeping guidance.",
      processing_context: "Clients engage the firm voluntarily for a specific legal matter and can choose another firm; the relationship is time-limited to the matter's duration.",
      processing_purposes: "Providing conveyancing and probate legal services and complying with anti-money-laundering identity-verification obligations; no client data is used for marketing without separate consent.",
      remediation_default_owner: "Managing Partner",
      remediation_default_target_date: "2027-06-30",
      remediation_default_priority: "Low — monitor",
      remediation_default_validation_method: "Management sign-off against the artifact",
    },
  },
  {
    id: "governance-p07-education-group-formal-dpo-nl",
    tool: "governance",
    label: "Dutch further-education group with a formal DPO under Art. 37(1)(b)",
    company: "Universiteit Steenwijk Onderwijsgroep B.V.",
    sector: "Education",
    geo: "eu",
    summary: "Steenwijk operates four further-education campuses with a formally appointed DPO reflecting its public-task-adjacent monitoring of students. Exercises the education sector, a mid-large org size, and mixed maturity across DSR and technical controls.",
    intake: {
      organization_name: "Universiteit Steenwijk Onderwijsgroep B.V.",
      sector: "Education",
      org_size: "251-1000",
      jurisdictions: ["EU (GDPR)"],
      eu_uk_data: "Yes",
      tools: ["Google Workspace / Gemini", "Zoom + AI features", "Grammarly"],
      data_categories: ["Contact details", "Employee records", "Children's data", "Communications content"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, current (reviewed in last 12 months)",
      privacy_notice_coverage: "Partially — some activities or tools not yet reflected",
      dpo_status: "Yes, formal DPO",
      dpia_status: "Yes, one DPIA completed",
      dpia_ai_coverage: "Some covered",
      incident_response: "Yes, tested in last 12 months",
      training_status: "Yes, formal onboarding + annual refresh",
      training_ai_coverage: "Generally covers data handling",
      tool_instruction: "Yes, written policy with specific prohibitions",
      dpa_status: "Most vendors",
      dpa_art28_verified: "Partially",
      transfer_status: "Yes, US-based tools",
      transfer_mechanism: "EU Standard Contractual Clauses (SCCs)",
      technical_controls: "Partial — some tools or categories",
      technical_controls_list: ["DLP rules", "Endpoint upload restrictions"],
      dsr_capability: "Documented but not tested",
      inventory_audit: "Yes — audited + formal approval process",
      retention_schedule_status: "Partially — documented for some categories only",
      additional_context: "The DPO was appointed because the institution regularly and systematically monitors students (attendance, assessment, and some under-18 learners in its vocational stream) at scale across four campuses, which the board treated as squarely within Art. 37(1)(b).",
      measures_review_cadence: "Annually or more often",
      measures_last_review_date: "2026-02-27",
      processing_nature: "Student and staff records are held across Google Workspace (with Gemini restricted from student-record documents by administrative-console policy), Zoom for remote and hybrid classes, and Grammarly for staff correspondence drafting with student-record content excluded.",
      processing_scope: "Approximately 6,800 students and 540 staff across four campuses; student records retained 7 years after programme completion under Dutch education-sector retention guidance.",
      processing_context: "Students are enrolled voluntarily but cannot decline the institution's core administrative and assessment record-keeping while enrolled; a subset of vocational-stream learners are under 18.",
      processing_purposes: "Enrolment administration, teaching delivery, assessment record-keeping, and safeguarding of under-18 learners; no student data is used for third-party marketing.",
      remediation_default_owner: "Data Protection Officer",
      remediation_default_target_date: "2026-12-20",
      remediation_default_priority: "High — remediate this quarter",
      remediation_default_validation_method: "Internal audit sample",
    },
  },
  {
    id: "governance-p08-municipal-utility-mature-de",
    tool: "governance",
    label: "German municipal utility company with a mandatory formal DPO",
    company: "Stadtwerke Lindenau GmbH",
    sector: "Government/public sector",
    geo: "eu",
    summary: "Stadtwerke Lindenau is a municipally-owned utility with a formal DPO mandatory under Art. 37(1)(a) as a public authority. Exercises the largest org-size band in the government/public-sector branch with a mature, fully-verified posture.",
    intake: {
      organization_name: "Stadtwerke Lindenau GmbH",
      sector: "Government/public sector",
      org_size: "1001+",
      jurisdictions: ["EU (GDPR)"],
      eu_uk_data: "Yes",
      tools: ["Microsoft 365 / Copilot", "Salesforce + Einstein"],
      data_categories: ["Contact details", "Financial data", "Employee records", "Location data"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, current (reviewed in last 12 months)",
      privacy_notice_coverage: "Yes — notice covers all current activities, transfers, retention, and rights",
      dpo_status: "Yes, formal DPO",
      dpia_status: "Yes, multiple DPIAs completed",
      dpia_ai_coverage: "Yes — all AI/high-risk tools assessed",
      incident_response: "Yes, tested in last 12 months",
      training_status: "Yes, formal onboarding + annual refresh",
      training_ai_coverage: "Yes — explicitly covers AI tools",
      tool_instruction: "Yes, written policy with specific prohibitions",
      dpa_status: "Yes, all vendors",
      dpa_art28_verified: "Yes — verified",
      transfer_status: "All tools store data in EU/UK",
      transfer_mechanism: "n/a",
      technical_controls: "Yes — DLP/content filtering actively enforced",
      technical_controls_list: ["DLP rules", "Content filtering", "Endpoint upload restrictions", "Approval workflow"],
      dsr_capability: "Yes — documented and tested across all vendors",
      dsr_rights_tested: ["Access", "Erasure", "Rectification"],
      inventory_audit: "Yes — audited + formal approval process",
      retention_schedule_status: "Yes — retention periods documented for each category of data",
      additional_context: "As a municipally-owned public utility, Stadtwerke Lindenau appointed a formal DPO under Art. 37(1)(a) as a body carrying out tasks in the public interest, independent of its size; both Salesforce + Einstein and Microsoft 365 are hosted in the EU region with no US transfer.",
      measures_review_cadence: "Annually or more often",
      measures_last_review_date: "2026-04-11",
      processing_nature: "Customer billing and meter data are held in Salesforce + Einstein under an EU-only hosting configuration and a signed Art. 28 DPA; Microsoft 365/Copilot handles internal administrative documents with Copilot restricted from customer-account records by policy.",
      processing_scope: "Approximately 210,000 household and business utility accounts and 1,900 employees; billing records retained 10 years under German commercial-code accounting-record rules.",
      processing_context: "Customers are households and businesses within the municipal service area who cannot readily switch utility provider for the regulated network service, which the utility recognises as a factor weighing toward stronger transparency obligations.",
      processing_purposes: "Utility billing and metering, network-fault management, and statutory regulatory reporting; no customer data is used for unrelated marketing.",
      remediation_default_owner: "Data Protection Officer",
      remediation_default_target_date: "2026-12-31",
      remediation_default_priority: "Medium — remediate this year",
      remediation_default_validation_method: "External audit or assurance report",
    },
  },
  {
    id: "governance-p09-law-studio-developing-it",
    tool: "governance",
    label: "Italian legal-services studio with an informal privacy lead and developing controls",
    company: "Studio Legale Bellavista S.r.l.",
    sector: "Legal services",
    geo: "eu",
    summary: "Studio Legale Bellavista provides corporate and litigation services with an informal privacy lead and partially documented processor contracts. Exercises the legal-services sector at mid size with an 'Unsure' transfer-status branch and no retention schedule.",
    intake: {
      organization_name: "Studio Legale Bellavista S.r.l.",
      sector: "Legal services",
      org_size: "51-250",
      jurisdictions: ["EU (GDPR)"],
      eu_uk_data: "Yes",
      tools: ["Microsoft 365 / Copilot", "Otter.ai / Fireflies"],
      data_categories: ["Contact details", "Financial data", "Communications content"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, but outdated",
      privacy_notice_coverage: "Unsure",
      dpo_status: "Yes, informal privacy lead",
      dpia_status: "Unsure",
      incident_response: "Documented but informal",
      training_status: "Ad hoc only",
      tool_instruction: "Verbal guidance only",
      dpa_status: "Some vendors",
      dpa_art28_verified: "Unsure",
      transfer_status: "Unsure",
      transfer_mechanism: "n/a",
      technical_controls: "No — policy and training only",
      dsr_capability: "Ad hoc / not documented",
      inventory_audit: "No formal inventory",
      retention_schedule_status: "Unsure",
      additional_context: "The firm uses Otter.ai / Fireflies to transcribe client-strategy calls without a reviewed Art. 28 agreement in place; the managing partner has flagged this as the most urgent open item pending outside privacy counsel's review.",
      measures_review_cadence: "Unsure",
      measures_last_review_date: "",
      processing_nature: "Client matter files and correspondence are held in Microsoft 365 with no confirmed restriction on Copilot indexing of client-matter folders; call transcription for strategy calls runs through Otter.ai / Fireflies under an unreviewed standard vendor agreement.",
      processing_scope: "Approximately 60 active corporate and litigation matters at any time, serving roughly 140 corporate clients; retention periods for matter files are not currently documented.",
      processing_context: "Clients are corporate entities engaging the firm for specific matters; individual data subjects within those matters (counterparties, witnesses) have no direct relationship with the firm.",
      processing_purposes: "Providing corporate advisory and litigation legal services; call transcription supports internal note-taking for the assigned legal team only.",
      remediation_default_owner: "Managing Partner",
      remediation_default_target_date: "2026-12-31",
      remediation_default_priority: "Critical — remediate now",
      remediation_default_validation_method: "External audit or assurance report",
    },
  },
  {
    id: "governance-p10-manufacturing-mature-se",
    tool: "governance",
    label: "Large Swedish industrial manufacturer with a mature cross-border governance posture",
    company: "Storfors Industriverk AB",
    sector: "Manufacturing",
    geo: "eu",
    summary: "Storfors operates EU and UK manufacturing sites with a formal DPO, verified Art. 28 DPAs, and SCC-based transfers for its US-hosted engineering tools. Exercises the manufacturing sector at the largest org-size band with EU+UK jurisdictions.",
    intake: {
      organization_name: "Storfors Industriverk AB",
      sector: "Manufacturing",
      org_size: "1001+",
      jurisdictions: ["EU (GDPR)", "United Kingdom (UK GDPR)"],
      eu_uk_data: "Yes",
      tools: ["Microsoft 365 / Copilot", "GitHub Copilot", "Slack + AI features"],
      data_categories: ["Contact details", "Employee records", "Location data"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, current (reviewed in last 12 months)",
      privacy_notice_coverage: "Yes — notice covers all current activities, transfers, retention, and rights",
      dpo_status: "Yes, formal DPO",
      dpia_status: "Yes, multiple DPIAs completed",
      dpia_ai_coverage: "Yes — all AI/high-risk tools assessed",
      incident_response: "Yes, tested in last 12 months",
      training_status: "Yes, formal onboarding + annual refresh",
      training_ai_coverage: "Yes — explicitly covers AI tools",
      tool_instruction: "Yes, written policy with specific prohibitions",
      dpa_status: "Yes, all vendors",
      dpa_art28_verified: "Yes — verified",
      transfer_status: "Yes, US-based tools",
      transfer_mechanism: "EU Standard Contractual Clauses (SCCs)",
      technical_controls: "Yes — DLP/content filtering actively enforced",
      technical_controls_list: ["DLP rules", "Endpoint upload restrictions", "Approval workflow"],
      dsr_capability: "Yes — documented and tested across all vendors",
      dsr_rights_tested: ["Access", "Erasure", "Portability", "Rectification"],
      inventory_audit: "Yes — audited + formal approval process",
      retention_schedule_status: "Yes — retention periods documented for each category of data",
      additional_context: "Badge-entry location data at the two production sites is logged for safety and site-access purposes only and is excluded from any performance-management use under the works-council agreement.",
      measures_review_cadence: "Annually or more often",
      measures_last_review_date: "2026-05-06",
      processing_nature: "Employee and site-access records are held in Microsoft 365 with Copilot restricted from HR and site-security folders by administrative policy; GitHub Copilot is used by the engineering team on internal codebases only, and Slack's AI summary feature is disabled for HR and works-council channels.",
      processing_scope: "Approximately 3,400 employees across two production sites in Sweden and one in the UK; employee records retained 7 years after employment ends under Swedish and UK record-keeping rules.",
      processing_context: "Employees cannot decline core employment record-keeping or site-access badge logging, and the works-council agreement expressly limits badge data to safety and access purposes.",
      processing_purposes: "Workforce administration, site safety and access control, and engineering-tool support for product development; no employee data is used for marketing.",
      remediation_default_owner: "Group Data Protection Officer",
      remediation_default_target_date: "2026-11-15",
      remediation_default_priority: "Medium — remediate this year",
      remediation_default_validation_method: "Internal audit sample",
    },
  },
  {
    id: "governance-p11-startup-no-dpo-ie",
    tool: "governance",
    label: "Ten-person Irish SaaS startup with no DPO and a stated Art. 37 rationale",
    company: "NanoLoop Systems Ltd",
    sector: "Technology/SaaS",
    geo: "eu",
    summary: "NanoLoop is a nine-employee developer-tools startup with no DPO, on the stated ground that its processing does not meet Art. 37(1) thresholds at its current scale. Exercises the smallest org-size band with a minimal but honestly documented governance baseline.",
    intake: {
      organization_name: "NanoLoop Systems Ltd",
      sector: "Technology/SaaS",
      org_size: "1-10",
      jurisdictions: ["EU (GDPR)"],
      eu_uk_data: "Yes",
      tools: ["Google Workspace / Gemini", "GitHub Copilot", "Notion + AI"],
      data_categories: ["Contact details", "Customer records"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, current (reviewed in last 12 months)",
      privacy_notice_coverage: "Yes — notice covers all current activities, transfers, retention, and rights",
      dpo_status: "No",
      dpia_status: "No, none conducted",
      incident_response: "Documented but informal",
      training_status: "Yes, onboarding only",
      tool_instruction: "Yes, written policy with specific prohibitions",
      dpa_status: "Most vendors",
      dpa_art28_verified: "Unsure",
      transfer_status: "Yes, US-based tools",
      transfer_mechanism: "EU Standard Contractual Clauses (SCCs)",
      technical_controls: "No — policy and training only",
      dsr_capability: "Ad hoc / not documented",
      inventory_audit: "No formal inventory",
      retention_schedule_status: "No — no documented retention periods",
      additional_context: "The founders assessed Art. 37(1) at their current scale of roughly 1,100 customer contacts and concluded neither the core-activity nor large-scale threshold is met, so no DPO is appointed; the CTO acts as the named privacy contact pending growth that would revisit this assessment.",
      measures_review_cadence: "On material change only",
      measures_last_review_date: "2026-01-05",
      processing_nature: "Customer contact and account records are held in Google Workspace, with Gemini's workspace-wide indexing left at its default setting; GitHub Copilot is used on the product codebase, which contains no customer personal data; Notion + AI is used for internal product documentation.",
      processing_scope: "Approximately 1,100 customer contacts for the developer-tools product; account records are currently kept without a defined deletion point.",
      processing_context: "Customers are individual developers or small teams who sign up directly and can close their account and request deletion at any time through support.",
      processing_purposes: "Operating the developer-tools SaaS product, billing, and customer support; no customer data is used to train any model.",
      remediation_default_owner: "Chief Technology Officer",
      remediation_default_target_date: "2027-01-31",
      remediation_default_priority: "Medium — remediate this year",
      remediation_default_validation_method: "Management sign-off against the artifact",
    },
  },
  {
    id: "governance-p12-wealth-management-developing-gb",
    tool: "governance",
    label: "UK wealth-management firm with a developing posture and an informal privacy lead",
    company: "Hallcross Wealth Management Ltd",
    sector: "Financial services",
    geo: "eu",
    summary: "Hallcross advises UK clients with an informal privacy lead, one completed DPIA, and partially verified processor DPAs. Exercises the financial-services sector under UK-only jurisdiction at the 251-1000 size band with mixed maturity.",
    intake: {
      organization_name: "Hallcross Wealth Management Ltd",
      sector: "Financial services",
      org_size: "251-1000",
      jurisdictions: ["United Kingdom (UK GDPR)"],
      eu_uk_data: "Yes",
      tools: ["Microsoft 365 / Copilot", "Salesforce + Einstein"],
      data_categories: ["Contact details", "Financial data", "Employee records"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, but outdated",
      privacy_notice_coverage: "Partially — some activities or tools not yet reflected",
      dpo_status: "Yes, informal privacy lead",
      dpia_status: "Yes, one DPIA completed",
      dpia_ai_coverage: "No — not for AI tools",
      incident_response: "Yes, but not tested",
      training_status: "Yes, onboarding only",
      training_ai_coverage: "No — not AI-specific",
      tool_instruction: "Verbal guidance only",
      dpa_status: "Most vendors",
      dpa_art28_verified: "Partially",
      transfer_status: "Yes, US-based tools",
      transfer_mechanism: "UK IDTA",
      technical_controls: "Partial — some tools or categories",
      technical_controls_list: ["DLP rules"],
      dsr_capability: "Documented but not tested",
      inventory_audit: "Inventory exists, no formal audit/approval",
      retention_schedule_status: "Partially — documented for some categories only",
      additional_context: "The informal privacy lead is the Head of Compliance, who is currently completing a formal data-protection practitioner qualification; the board has budgeted for a review of whether a formal DPO appointment is warranted once assets under advice pass the GBP 2 billion threshold expected in 2027.",
      measures_review_cadence: "Every 1–2 years",
      measures_last_review_date: "2025-05-14",
      processing_nature: "Client financial and identity records are held in Salesforce + Einstein under a partially verified Art. 28 arrangement; Microsoft 365/Copilot is used for internal advisory-note drafting with client financial detail excluded from Copilot indexing by policy, though this restriction has not yet been independently tested.",
      processing_scope: "Approximately 9,200 client relationships and 640 employees; client records are retained 6 years after relationship end under FCA record-keeping rules.",
      processing_context: "Clients engage the firm under a negotiated advisory agreement and can transfer to another adviser; the firm has an enhanced duty of care given the financial-advice relationship.",
      processing_purposes: "Wealth-management advisory service delivery, regulatory reporting to the FCA, and anti-money-laundering identity verification.",
      remediation_default_owner: "Head of Compliance",
      remediation_default_target_date: "2026-12-31",
      remediation_default_priority: "High — remediate this quarter",
      remediation_default_validation_method: "Control re-test by a second reviewer",
    },
  },
  {
    id: "governance-p13-retail-group-mature-nl",
    tool: "governance",
    label: "Large Dutch retail group with a mature, fully-tooled privacy programme",
    company: "Meervolk Retail Groep B.V.",
    sector: "Retail/ecommerce",
    geo: "eu",
    summary: "Meervolk operates online and in-store retail across the EU and UK with a formal DPO, verified DPAs, and tested DSR handling across a large vendor estate. Exercises the largest retail org-size band with EU+UK jurisdictions and heavy tooling.",
    intake: {
      organization_name: "Meervolk Retail Groep B.V.",
      sector: "Retail/ecommerce",
      org_size: "1001+",
      jurisdictions: ["EU (GDPR)", "United Kingdom (UK GDPR)"],
      eu_uk_data: "Yes",
      tools: ["Microsoft 365 / Copilot", "Salesforce + Einstein", "HubSpot", "Adobe Creative Cloud"],
      data_categories: ["Contact details", "Customer records", "Financial data", "Employee records"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, current (reviewed in last 12 months)",
      privacy_notice_coverage: "Yes — notice covers all current activities, transfers, retention, and rights",
      dpo_status: "Yes, formal DPO",
      dpia_status: "Yes, multiple DPIAs completed",
      dpia_ai_coverage: "Yes — all AI/high-risk tools assessed",
      incident_response: "Yes, tested in last 12 months",
      training_status: "Yes, formal onboarding + annual refresh",
      training_ai_coverage: "Yes — explicitly covers AI tools",
      tool_instruction: "Yes, written policy with specific prohibitions",
      dpa_status: "Yes, all vendors",
      dpa_art28_verified: "Yes — verified",
      transfer_status: "Yes, US-based tools",
      transfer_mechanism: "EU Standard Contractual Clauses (SCCs)",
      technical_controls: "Yes — DLP/content filtering actively enforced",
      technical_controls_list: ["DLP rules", "Content filtering", "Endpoint upload restrictions", "Approval workflow"],
      dsr_capability: "Yes — documented and tested across all vendors",
      dsr_rights_tested: ["Access", "Erasure", "Portability", "Rectification"],
      inventory_audit: "Yes — audited + formal approval process",
      retention_schedule_status: "Yes — retention periods documented for each category of data",
      additional_context: "The DPO chairs a cross-functional privacy committee that meets monthly with representatives from IT security, marketing and HR; the last independent external audit (2026-01) found no material gaps and two minor observations, both closed by March 2026.",
      measures_review_cadence: "Annually or more often",
      measures_last_review_date: "2026-01-30",
      processing_nature: "Customer and transaction records are held in Salesforce + Einstein under a signed Art. 28 DPA with the 2021 EU SCCs and UK Addendum; Microsoft 365/Copilot and HubSpot support internal operations and marketing respectively, each under its own verified Art. 28 agreement; Adobe Creative Cloud is used for campaign creative production with no customer personal data.",
      processing_scope: "Approximately 2.1 million customer accounts and 4,800 employees across EU and UK stores and online; customer records retained 3 years after last activity and employee records 7 years after employment ends.",
      processing_context: "Customers are retail shoppers who can close their account or object to marketing at any time; employees are subject to standard retail-sector employment record-keeping.",
      processing_purposes: "Retail sales and order fulfilment, customer service, marketing to consenting customers, and workforce administration; no customer data is sold to third parties.",
      remediation_default_owner: "Group Data Protection Officer",
      remediation_default_target_date: "2026-10-31",
      remediation_default_priority: "Medium — remediate this year",
      remediation_default_validation_method: "External audit or assurance report",
    },
  },
  {
    id: "governance-p14-logistics-other-sector-fr",
    tool: "governance",
    label: "French alpine logistics operator classified under the 'Other' sector option",
    company: "Fret Alpin Logistique SAS",
    sector: "Other",
    geo: "eu",
    summary: "Fret Alpin runs freight logistics across the French Alps region with a moderate governance posture and an informal privacy lead. Exercises the 'Other' sector option, mid org size, and a driver-location data category distinct from the vehicle-telematics LIA scenario.",
    intake: {
      organization_name: "Fret Alpin Logistique SAS",
      sector: "Other",
      org_size: "51-250",
      jurisdictions: ["EU (GDPR)"],
      eu_uk_data: "Yes",
      tools: ["Microsoft 365 / Copilot", "HubSpot"],
      data_categories: ["Contact details", "Employee records", "Location data"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, current (reviewed in last 12 months)",
      privacy_notice_coverage: "Partially — some activities or tools not yet reflected",
      dpo_status: "Yes, informal privacy lead",
      dpia_status: "Yes, one DPIA completed",
      dpia_ai_coverage: "Yes — all AI/high-risk tools assessed",
      incident_response: "Documented but informal",
      training_status: "Yes, onboarding only",
      training_ai_coverage: "Generally covers data handling",
      tool_instruction: "Yes, written policy with specific prohibitions",
      dpa_status: "Yes, all vendors",
      dpa_art28_verified: "Partially",
      transfer_status: "All tools store data in EU/UK",
      transfer_mechanism: "n/a",
      technical_controls: "Partial — some tools or categories",
      technical_controls_list: ["Endpoint upload restrictions"],
      dsr_capability: "Documented but not tested",
      inventory_audit: "Yes — audited + formal approval process",
      retention_schedule_status: "Partially — documented for some categories only",
      additional_context: "Fret Alpin selected 'Other' because freight logistics is not separately listed; the informal privacy lead is the Head of Fleet Operations, supported by outside counsel retained for the DPIA covering the driver-location system completed in 2025.",
      measures_review_cadence: "Every 1–2 years",
      measures_last_review_date: "2025-11-19",
      processing_nature: "Driver location during working hours is logged by an EU-hosted fleet-management system; Microsoft 365/Copilot supports internal administration and HubSpot manages client shipment bookings, both under signed Art. 28 agreements.",
      processing_scope: "Approximately 95 drivers and 40 office staff; location data is retained 6 months and shipment booking records 5 years under French commercial-record rules.",
      processing_context: "Drivers cannot decline working-hours location tracking as it is a condition of the role disclosed at hiring; the system is disabled outside rostered hours.",
      processing_purposes: "Route planning, delivery-time-window commitments to clients, and driver safety monitoring; no location data is used for performance-related pay decisions.",
      remediation_default_owner: "Head of Fleet Operations",
      remediation_default_target_date: "2026-12-15",
      remediation_default_priority: "Medium — remediate this year",
      remediation_default_validation_method: "Documentary evidence review",
    },
  },
  {
    id: "governance-p15-devtools-immature-it",
    tool: "governance",
    label: "Italian developer-tools vendor with a largely unassessed, 'Unsure'-heavy governance posture",
    company: "ByteCraft Labs S.r.l.",
    sector: "Technology/SaaS",
    geo: "eu",
    summary: "ByteCraft is a small developer-tools vendor that has not yet assessed several of its own governance questions. Exercises the 'Unsure' branch across transfer status, technical controls and retention scheduling, contrasted with the mature SaaS fixture in p01.",
    intake: {
      organization_name: "ByteCraft Labs S.r.l.",
      sector: "Technology/SaaS",
      org_size: "11-50",
      jurisdictions: ["EU (GDPR)"],
      eu_uk_data: "Yes",
      tools: ["GitHub Copilot", "Notion + AI"],
      data_categories: ["Contact details", "Customer records"],
      special_category: "No",
      special_categories_list: [],
      sc_core_activity: "n/a",
      sc_core_activity_explanation: "",
      sc_data_subjects_count: "",
      sc_population_proportion: "n/a",
      sc_data_volume: "",
      sc_duration: "n/a",
      sc_geographic_scope: "n/a",
      privacy_policy: "Yes, but outdated",
      privacy_notice_coverage: "Unsure",
      dpo_status: "Yes, informal privacy lead",
      dpia_status: "Unsure",
      incident_response: "No",
      training_status: "No formal training",
      tool_instruction: "No instruction provided",
      dpa_status: "Some vendors",
      dpa_art28_verified: "Unsure",
      transfer_status: "Unsure",
      transfer_mechanism: "n/a",
      technical_controls: "Unsure",
      dsr_capability: "No process in place",
      inventory_audit: "Unsure",
      retention_schedule_status: "Unsure",
      additional_context: "ByteCraft has grown quickly since 2025 and has not yet run a formal review of its data-protection posture; the co-founder acting as informal privacy lead has flagged this governance assessment itself as the trigger for commissioning outside privacy counsel, budgeted for Q4 2026.",
      measures_review_cadence: "Unsure",
      measures_last_review_date: "",
      processing_nature: "Customer account and support-ticket data is held in the product's own EU-hosted database; GitHub Copilot is used on the product codebase and Notion + AI on internal documentation, neither configured with any specific customer-data exclusion policy at this time.",
      processing_scope: "Approximately 3,600 customer accounts for the developer-tools product; no retention schedule is currently documented for any data category.",
      processing_context: "Customers are individual developers who sign up directly online and can close their account through support, though the deletion process has not been formally tested.",
      processing_purposes: "Operating the developer-tools product, billing, and customer support.",
      remediation_default_owner: "Co-Founder (acting privacy lead)",
      remediation_default_target_date: "2026-12-31",
      remediation_default_priority: "Critical — remediate now",
      remediation_default_validation_method: "External audit or assurance report",
    },
  },
];
