// GENERATED by scripts/ptest/export-packs.ts (DOC 261) — do not edit by hand.
// Rebuild: deno run --allow-read --allow-write --allow-env scripts/ptest/export-packs.ts
// Drift guard: tests/edge/ptest/packs.test.ts
import type { BlockCatalogue } from "./types.ts";

export const ADMT_BLOCK_CATALOGUE: BlockCatalogue = {
  "product": "cppa-admt",
  "spine_version": "cppa-admt-v3.2.2-2026-08-25",
  "generated_on": "2026-09-14",
  "generated_from": [
    "admt-hr-significant-tuning",
    "admt-credit-significant-tuning",
    "admt-advertising-adversarial",
    "admt-service-eligibility-conservative",
    "admt-hr-perfect-record",
    "admt-hr-messy-record",
    "admt-full-optout-strong-compliance",
    "admt-human-appeal-exception-strong",
    "admt-hiring-admission-exception-strong",
    "admt-work-allocation-compensation-exception-strong",
    "admt-ca-tenant-screening-perfect",
    "admt-full-optout-strong-compliance",
    "admt-human-appeal-exception-strong",
    "admt-hiring-admission-exception-strong",
    "admt-work-allocation-compensation-exception-strong"
  ],
  "entries": [
    {
      "block_key": "cover:0",
      "section_id": "cover",
      "section_title": "Assessment Profile",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR §§ 7001(e)",
        "§§ 7050",
        "§§ 7150(b)(3)"
      ]
    },
    {
      "block_key": "cover#p1",
      "section_id": "cover",
      "section_title": "Assessment Profile",
      "kind": "skeleton",
      "fixed_text_prefix": "Scope of Assessment: This report evaluates the Company's reported practices against the CCPA regulations governing automated decisionmaking technology (“ADMT”) ",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary#p0",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "lead",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary#p1",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "skeleton",
      "fixed_text_prefix": "Article 11 of the CCPA regulations (Cal. Code Regs. tit. 11, §§ 7200–7222) requires a business to determine whether it uses ADMT for a significant decision and,",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§§ 7200"
      ]
    },
    {
      "block_key": "executive_summary#p2",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "skeleton",
      "fixed_text_prefix": "The Company uses TalentRank in Hiring or admission decisions. This assessment addresses four questions: whether Article 11 applies to that use; whether the requ",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary:2",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary#p4",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "skeleton",
      "fixed_text_prefix": "Record sufficiency is graded Qualified because one or more supporting fields were not provided. The record-quality table in the Governance section identifies th",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary#p5",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "skeleton",
      "fixed_text_prefix": "Priority Matters: no conditions to proceed or required follow-up items were identified from the Company's current responses.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "system_profile#p0",
      "section_id": "system_profile",
      "section_title": "1. System and Decision Profile",
      "kind": "skeleton",
      "fixed_text_prefix": "The Company identifies the System as TalentRank, described by the Company as an ML classifier. The Company describes the System as follows: TalentRank scores ré",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7001(ddd)"
      ]
    },
    {
      "block_key": "system_profile#p1",
      "section_id": "system_profile",
      "section_title": "1. System and Decision Profile",
      "kind": "skeleton",
      "fixed_text_prefix": "The Company describes human review as follows: “Yes — reviewer knows how to interpret output, reviews it plus other info, and has authority to change the decisi",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "system_profile#p2",
      "section_id": "system_profile",
      "section_title": "1. System and Decision Profile",
      "kind": "skeleton",
      "fixed_text_prefix": "The Company did not identify a third-party ADMT in the information supplied for this assessment.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "applicability#p0",
      "section_id": "applicability",
      "section_title": "2. Applicability of the ADMT Requirements",
      "kind": "legal_requirement",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7001(ddd)",
        "11 CCR § 7001(ddd)(6)",
        "11 CCR § 7001(e)",
        "11 CCR § 7001(e)(1)",
        "11 CCR § 7200(a)"
      ]
    },
    {
      "block_key": "applicability#p1",
      "section_id": "applicability",
      "section_title": "2. Applicability of the ADMT Requirements",
      "kind": "lead",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "applicability:2",
      "section_id": "applicability",
      "section_title": "2. Applicability of the ADMT Requirements",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "applicability#p3",
      "section_id": "applicability",
      "section_title": "2. Applicability of the ADMT Requirements",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "applicability#p4",
      "section_id": "applicability",
      "section_title": "2. Applicability of the ADMT Requirements",
      "kind": "skeleton",
      "fixed_text_prefix": "Scope qualification — conditions on this determination",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "applicability#p5",
      "section_id": "applicability",
      "section_title": "2. Applicability of the ADMT Requirements",
      "kind": "skeleton",
      "fixed_text_prefix": "This determination rests on the reported human review operating in practice for every significant decision TalentRank touches. Qualifying review under 11 CCR § ",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7001(e)(1)"
      ]
    },
    {
      "block_key": "applicability#p6",
      "section_id": "applicability",
      "section_title": "2. Applicability of the ADMT Requirements",
      "kind": "skeleton",
      "fixed_text_prefix": "Regulatory Interpretation — Human involvement",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7001(ddd)(6)",
        "11 CCR § 7001(e)(1)"
      ]
    },
    {
      "block_key": "applicability#p7",
      "section_id": "applicability",
      "section_title": "2. Applicability of the ADMT Requirements",
      "kind": "skeleton",
      "fixed_text_prefix": "Regulatory interpretation of the human-involvement standard — nonbinding interpretive context from the Agency's Final Statement of Reasons; the operative test i",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7001(e)"
      ]
    },
    {
      "block_key": "applicability#p8",
      "section_id": "applicability",
      "section_title": "2. Applicability of the ADMT Requirements",
      "kind": "quoted_rulemaking",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7001(e)(1)"
      ]
    },
    {
      "block_key": "applicability#p9",
      "section_id": "applicability",
      "section_title": "2. Applicability of the ADMT Requirements",
      "kind": "quoted_rulemaking",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7001(e)"
      ]
    },
    {
      "block_key": "notice#p0",
      "section_id": "notice",
      "section_title": "3. Pre-use Notice Audit",
      "kind": "skeleton",
      "fixed_text_prefix": "Not reached. On the Company's reported facts the System is outside Article 11 for this decision (Section 2), so the Pre-use Notice requirements are not assessed",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7220(b)(2)",
        "11 CCR § 7220(b)(3)",
        "11 CCR § 7220(c)(1)",
        "11 CCR § 7220(c)(2)",
        "11 CCR § 7220(c)(3)",
        "11 CCR § 7220(c)(4)",
        "11 CCR § 7220(c)(5)(A)",
        "11 CCR § 7220(c)(5)(C)"
      ]
    },
    {
      "block_key": "optout#p0",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "skeleton",
      "fixed_text_prefix": "Not reached, for the reason stated in Section 3: the opt-out and exception requirements are not assessed in this report.",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7221(a)",
        "11 CCR § 7221(b)(1)",
        "11 CCR § 7221(b)(2)(A)",
        "11 CCR § 7221(b)(3)(A)"
      ]
    },
    {
      "block_key": "access#p0",
      "section_id": "access",
      "section_title": "5. Access and Explanation Audit",
      "kind": "skeleton",
      "fixed_text_prefix": "Not reached, for the reason stated in Section 3: the access and explanation requirements are not assessed in this report.",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7222(a)",
        "11 CCR § 7222(b)(1)",
        "11 CCR § 7222(b)(2)",
        "11 CCR § 7222(b)(3)",
        "11 CCR § 7222(b)(3)(A)",
        "11 CCR § 7222(b)(4)"
      ]
    },
    {
      "block_key": "vendor#p0",
      "section_id": "vendor",
      "section_title": "6. Third-Party and Vendor Dependency",
      "kind": "skeleton",
      "fixed_text_prefix": "Not reached, for the reason stated in Section 3: no vendor-dependency analysis is performed in this report.",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7050(h)",
        "11 CCR § 7221(n)(2)",
        "11 CCR § 7222(i)",
        "§ 7051(a)(6)"
      ]
    },
    {
      "block_key": "governance#p0",
      "section_id": "governance",
      "section_title": "7. Governance, Record Sufficiency, and Related Risk-Assessment Obligations",
      "kind": "legal_requirement",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7150(b)(3)",
        "11 CCR § 7155(a)(2)",
        "11 CCR § 7155(a)(3)",
        "11 CCR § 7155(b)",
        "11 CCR § 7200(b)",
        "11 CCR §§ 7150(a)"
      ]
    },
    {
      "block_key": "governance#p1",
      "section_id": "governance",
      "section_title": "7. Governance, Record Sufficiency, and Related Risk-Assessment Obligations",
      "kind": "skeleton",
      "fixed_text_prefix": "This ADMT Compliance Assessment is not the Article 10 risk assessment. The two records should nevertheless stay aligned because changes to the system, its decis",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "governance#p2",
      "section_id": "governance",
      "section_title": "7. Governance, Record Sufficiency, and Related Risk-Assessment Obligations",
      "kind": "skeleton",
      "fixed_text_prefix": "The overall record supporting this assessment is graded qualified. The following table shows the record quality supporting each section of this assessment:",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "governance:1",
      "section_id": "governance",
      "section_title": "7. Governance, Record Sufficiency, and Related Risk-Assessment Obligations",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "actions#p0",
      "section_id": "actions",
      "section_title": "8. Conditions, Required Follow-Up, and Recommendations",
      "kind": "skeleton",
      "fixed_text_prefix": "No conditions to proceed, required follow-up items, or additional recommendations were identified from the Company's current responses.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "conclusion#p0",
      "section_id": "conclusion",
      "section_title": "9. Conclusion",
      "kind": "lead",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "conclusion#p1",
      "section_id": "conclusion",
      "section_title": "9. Conclusion",
      "kind": "skeleton",
      "fixed_text_prefix": "Review and Maintenance. Update and reissue this assessment when material changes occur to the System, its decision use, the Pre-use Notice, the opt-out or appea",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "review_of_assessment#p0",
      "section_id": "review_of_assessment",
      "section_title": "Review and Approval",
      "kind": "skeleton",
      "fixed_text_prefix": "The foregoing report records the applicability assessment of the System, and the facts supporting it, as of the date of this assessment.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "review_of_assessment:1",
      "section_id": "review_of_assessment",
      "section_title": "Review and Approval",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_a#p0",
      "section_id": "appendix_a",
      "section_title": "Appendix A — Factor, Determination, and Authority Matrix",
      "kind": "skeleton",
      "fixed_text_prefix": "This matrix restates each material factor behind the assessment in one place: the report's determination on that factor, in the report's own words, and the spec",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_a:0",
      "section_id": "appendix_a",
      "section_title": "Appendix A — Factor, Determination, and Authority Matrix",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7001(ddd)(6)",
        "11 CCR § 7001(e)(1)",
        "11 CCR § 7220(b)(2)",
        "11 CCR § 7220(c)",
        "11 CCR § 7220(c)(1)",
        "11 CCR § 7221(b)(1)",
        "11 CCR § 7221(b)(2)(A)",
        "11 CCR § 7221(b)(3)(A)",
        "11 CCR § 7221(c)",
        "11 CCR § 7222(a)",
        "11 CCR § 7222(c)",
        "11 CCR § 7222(d)",
        "11 CCR §§ 7001(ddd)",
        "11 CCR §§ 7001(e)(1)",
        "11 CCR §§ 7221(n)(2)",
        "§ 7021(a)"
      ]
    },
    {
      "block_key": "appendix_c#p0",
      "section_id": "appendix_c",
      "section_title": "Appendix B — Assessment Fact Record",
      "kind": "skeleton",
      "fixed_text_prefix": "This appendix captures the material facts the Company supplied and that the assessment used. It supports later review and updating; it does not independently ve",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_c:0",
      "section_id": "appendix_c",
      "section_title": "Appendix B — Assessment Fact Record",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7001(ddd)(2)"
      ]
    },
    {
      "block_key": "executive_summary#p6",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7220(c)",
        "§ 7220(c)(4)"
      ]
    },
    {
      "block_key": "executive_summary#p7",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7221(b)(2)(A)"
      ]
    },
    {
      "block_key": "executive_summary#p8",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "notice#p1",
      "section_id": "notice",
      "section_title": "3. Pre-use Notice Audit",
      "kind": "legal_requirement",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7220(c)(5)"
      ]
    },
    {
      "block_key": "notice#p2",
      "section_id": "notice",
      "section_title": "3. Pre-use Notice Audit",
      "kind": "lead",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "notice#p3",
      "section_id": "notice",
      "section_title": "3. Pre-use Notice Audit",
      "kind": "skeleton",
      "fixed_text_prefix": "The Company states that it provides the Pre-use Notice Included in our Notice at Collection. The following table shows whether the Company's notice covers each ",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "notice:2",
      "section_id": "notice",
      "section_title": "3. Pre-use Notice Audit",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "notice#p5",
      "section_id": "notice",
      "section_title": "3. Pre-use Notice Audit",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "optout#p1",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "lead",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "optout#p2",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "skeleton",
      "fixed_text_prefix": "The Company reports that it offers a full opt-out right rather than relying on a § 7221(b) exception.",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7221(b)",
        "§ 7221(b)(1)",
        "§ 7221(b)(2)",
        "§ 7221(b)(3)"
      ]
    },
    {
      "block_key": "optout#p3",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "skeleton",
      "fixed_text_prefix": "4.1 Full Opt-Out Pathway",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7221(b)(1)"
      ]
    },
    {
      "block_key": "optout#p4",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "legal_requirement",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7221(c)",
        "11 CCR § 7221(c)(1)",
        "11 CCR § 7221(d)",
        "11 CCR § 7221(n)(1)"
      ]
    },
    {
      "block_key": "optout#p5",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "skeleton",
      "fixed_text_prefix": "Section 7221 also contains additional handling rules concerning fraudulent requests, authorized agents, later requests for renewed consent, and non-retaliation ",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7221(b)(1)",
        "11 CCR § 7221(b)(1)(A)",
        "11 CCR § 7221(b)(1)(B)",
        "11 CCR § 7221(b)(2)(A)",
        "11 CCR § 7221(b)(3)(A)",
        "11 CCR § 7221(g)",
        "§ 7001(ddd)(3)(A)",
        "§ 7001(ddd)(4)(B)"
      ]
    },
    {
      "block_key": "optout:4.1",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "optout#p7",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "optout#p8",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "skeleton",
      "fixed_text_prefix": "4.2–4.3 Exception Pathways. Not applicable: the Company offers the ADMT opt-out and does not rely on a § 7221(b) exception.",
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7221(b)"
      ]
    },
    {
      "block_key": "access#p1",
      "section_id": "access",
      "section_title": "5. Access and Explanation Audit",
      "kind": "legal_requirement",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7222(c)",
        "11 CCR § 7222(d)",
        "11 CCR § 7222(i)"
      ]
    },
    {
      "block_key": "access#p2",
      "section_id": "access",
      "section_title": "5. Access and Explanation Audit",
      "kind": "lead",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "access#p3",
      "section_id": "access",
      "section_title": "5. Access and Explanation Audit",
      "kind": "skeleton",
      "fixed_text_prefix": "The following tables show the Company's access-request process and its readiness to produce each element of the required explanation:",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "access:2",
      "section_id": "access",
      "section_title": "5. Access and Explanation Audit",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "access:3",
      "section_id": "access",
      "section_title": "5. Access and Explanation Audit",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "access#p6",
      "section_id": "access",
      "section_title": "5. Access and Explanation Audit",
      "kind": "skeleton",
      "fixed_text_prefix": "Withholding and Security: The Company has not described a trade-secret or security withholding policy.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "access#p7",
      "section_id": "access",
      "section_title": "5. Access and Explanation Audit",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "11 CCR § 7222(c)"
      ]
    },
    {
      "block_key": "actions#p1",
      "section_id": "actions",
      "section_title": "8. Conditions, Required Follow-Up, and Recommendations",
      "kind": "skeleton",
      "fixed_text_prefix": "8.1 Conditions to Proceed",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "actions:8.1",
      "section_id": "actions",
      "section_title": "8. Conditions, Required Follow-Up, and Recommendations",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7220(c)",
        "§ 7220(c)(4)",
        "§ 7221(b)(2)(A)"
      ]
    },
    {
      "block_key": "actions#p3",
      "section_id": "actions",
      "section_title": "8. Conditions, Required Follow-Up, and Recommendations",
      "kind": "skeleton",
      "fixed_text_prefix": "8.2 Required Assessment Follow-Up",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "actions:8.2",
      "section_id": "actions",
      "section_title": "8. Conditions, Required Follow-Up, and Recommendations",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": [
        "§ 7222(f)"
      ]
    },
    {
      "block_key": "actions#p5",
      "section_id": "actions",
      "section_title": "8. Conditions, Required Follow-Up, and Recommendations",
      "kind": "skeleton",
      "fixed_text_prefix": "8.3 Recommendations",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "actions:8.3",
      "section_id": "actions",
      "section_title": "8. Conditions, Required Follow-Up, and Recommendations",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_b#p0",
      "section_id": "appendix_b",
      "section_title": "Appendix B — Persuasive Authority (Analogous Enforcement)",
      "kind": "skeleton",
      "fixed_text_prefix": "This appendix collects enforcement decisions issued under analogous data-protection law that bear on factors assessed in this report. These decisions were issue",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_b:1",
      "section_id": "appendix_b",
      "section_title": "Appendix B — Persuasive Authority (Analogous Enforcement)",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary#p9",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary#p10",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "optout#p6",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "skeleton",
      "fixed_text_prefix": "The current intake tests the sole-use condition and asks about non-discrimination testing and supporting fairness documentation. Those materials are evidence re",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "optout:4.3",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "vendor#p1",
      "section_id": "vendor",
      "section_title": "6. Third-Party and Vendor Dependency",
      "kind": "skeleton",
      "fixed_text_prefix": "The Company identifies the third-party ADMT as: Vendor tool, contract not on file.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "vendor#p2",
      "section_id": "vendor",
      "section_title": "6. Third-Party and Vendor Dependency",
      "kind": "skeleton",
      "fixed_text_prefix": "The following table shows which vendor controls are relevant to the Company's selected pathway and whether the vendor supports each one:",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "vendor:0",
      "section_id": "vendor",
      "section_title": "6. Third-Party and Vendor Dependency",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "vendor#p4",
      "section_id": "vendor",
      "section_title": "6. Third-Party and Vendor Dependency",
      "kind": "skeleton",
      "fixed_text_prefix": "On the pathway the Company selected (Hiring/admission exception), the Company's reported vendor controls are:",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "vendor:1",
      "section_id": "vendor",
      "section_title": "6. Third-Party and Vendor Dependency",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "vendor#p6",
      "section_id": "vendor",
      "section_title": "6. Third-Party and Vendor Dependency",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "optout:4.2",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "optout#p9",
      "section_id": "optout",
      "section_title": "4. Opt-Out and Exception Audit",
      "kind": "skeleton",
      "fixed_text_prefix": "4.3 Employment and Education Exceptions. Not applicable: the Company does not rely on the hiring/admission or work-allocation exception.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    }
  ]
};
