// GENERATED by scripts/ptest/export-packs.ts (DOC 261) — do not edit by hand.
// Rebuild: deno run --allow-read --allow-write --allow-env scripts/ptest/export-packs.ts
// Drift guard: tests/edge/ptest/packs.test.ts
import type { RegistryPack } from "./types.ts";

export const GOVERNANCE_REGISTRY_PACK: RegistryPack = {
  "product": "governance",
  "registry_version": "governance-va-w2-2026-08-01-item327+governance-accountability-item313-2026-07-31+governance-dpa2018-wp243-doc164-2026-09-04",
  "generated_on": "2026-09-14",
  "rows": [
    {
      "proposition_key": "principle_lawfulness_fairness_transparency",
      "citation": "GDPR Art. 5",
      "subsection": "GDPR Art. 5(1)(a)",
      "verbatim_quote": "processed lawfully, fairly and in a transparent manner in relation to the data subject ('lawfulness, fairness and transparency');"
    },
    {
      "proposition_key": "principle_purpose_limitation",
      "citation": "GDPR Art. 5",
      "subsection": "GDPR Art. 5(1)(b)",
      "verbatim_quote": "collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes;"
    },
    {
      "proposition_key": "principle_data_minimisation",
      "citation": "GDPR Art. 5",
      "subsection": "GDPR Art. 5(1)(c)",
      "verbatim_quote": "adequate, relevant and limited to what is necessary in relation to the purposes for which they are processed ('data minimisation');"
    },
    {
      "proposition_key": "lawful_basis_legitimate_interests",
      "citation": "GDPR Art. 6",
      "subsection": "GDPR Art. 6(1)(f)",
      "verbatim_quote": "processing is necessary for the purposes of the legitimate interests pursued by the controller or by a third party, except where such interests are overridden by the interests or fundamental rights and freedoms of the data subject which require protection of personal data, in particular where the data subject is a child."
    },
    {
      "proposition_key": "special_categories_prohibition",
      "citation": "GDPR Art. 9",
      "subsection": "GDPR Art. 9(1)",
      "verbatim_quote": "Processing of personal data revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, or trade union membership, and the processing of genetic data, biometric data for the purpose of uniquely identifying a natural person, data concerning health or data concerning a natural person's sex life or sexual orientation shall be prohibited."
    },
    {
      "proposition_key": "art_13_controller_identity",
      "citation": "GDPR Art. 13",
      "subsection": "GDPR Art. 13(1)(a)",
      "verbatim_quote": "the identity and the contact details of the controller and, where applicable, of the controller's representative;"
    },
    {
      "proposition_key": "art_13_rights_information",
      "citation": "GDPR Art. 13",
      "subsection": "GDPR Art. 13(2)(b)",
      "verbatim_quote": "the existence of the right to request from the controller access to and rectification or erasure of personal data or restriction of processing concerning the data subject or to object to processing as well as the right to data portability;"
    },
    {
      "proposition_key": "art_14_rights_information",
      "citation": "GDPR Art. 14",
      "subsection": "GDPR Art. 14(2)(c)",
      "verbatim_quote": "the existence of the right to request from the controller access to and rectification or erasure of personal data or restriction of processing concerning the data subject and to object to processing as well as the right to data portability;"
    },
    {
      "proposition_key": "art_22_admt_right",
      "citation": "GDPR Art. 22",
      "subsection": "GDPR Art. 22(1)",
      "verbatim_quote": "The data subject shall have the right not to be subject to a decision based solely on automated processing, including profiling, which produces legal effects concerning him or her or similarly significantly affects him or her."
    },
    {
      "proposition_key": "data_protection_by_design",
      "citation": "GDPR Art. 25",
      "subsection": "GDPR Art. 25(1)",
      "verbatim_quote": "the controller shall, both at the time of the determination of the means for processing and at the time of the processing itself, implement appropriate technical and organisational measures, such as pseudonymisation, which are designed to implement data-protection principles, such as data minimisation, in an effective manner and to integrate the necessary safeguards into the processing in order to meet the requirements of this Regulation and protect the rights of data subjects."
    },
    {
      "proposition_key": "processor_sufficient_guarantees",
      "citation": "GDPR Art. 28",
      "subsection": "GDPR Art. 28(1)",
      "verbatim_quote": "Where processing is to be carried out on behalf of a controller, the controller shall use only processors providing sufficient guarantees to implement appropriate technical and organisational measures in such a manner that processing will meet the requirements of this Regulation and ensure the protection of the rights of the data subject."
    },
    {
      "proposition_key": "processor_sub_processor_authorisation",
      "citation": "GDPR Art. 28",
      "subsection": "GDPR Art. 28(2)",
      "verbatim_quote": "The processor shall not engage another processor without prior specific or general written authorisation of the controller."
    },
    {
      "proposition_key": "processor_documented_instructions",
      "citation": "GDPR Art. 28",
      "subsection": "GDPR Art. 28(3)(a)",
      "verbatim_quote": "processes the personal data only on documented instructions from the controller, including with regard to transfers of personal data to a third country or an international organisation, unless required to do so by Union or Member State law to which the processor is subject"
    },
    {
      "proposition_key": "processor_confidentiality",
      "citation": "GDPR Art. 28",
      "subsection": "GDPR Art. 28(3)(b)",
      "verbatim_quote": "ensures that persons authorised to process the personal data have committed themselves to confidentiality or are under an appropriate statutory obligation of confidentiality;"
    },
    {
      "proposition_key": "processor_return_or_delete",
      "citation": "GDPR Art. 28",
      "subsection": "GDPR Art. 28(3)(g)",
      "verbatim_quote": "at the choice of the controller, deletes or returns all the personal data to the controller after the end of the provision of services relating to processing, and deletes existing copies unless Union or Member State law requires storage of the personal data;"
    },
    {
      "proposition_key": "processor_audit_rights",
      "citation": "GDPR Art. 28",
      "subsection": "GDPR Art. 28(3)(h)",
      "verbatim_quote": "makes available to the controller all information necessary to demonstrate compliance with the obligations laid down in this Article and allow for and contribute to audits, including inspections, conducted by the controller or another auditor mandated by the controller."
    },
    {
      "proposition_key": "ropa_controller_record",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(1)",
      "verbatim_quote": "Each controller and, where applicable, the controller's representative, shall maintain a record of processing activities under its responsibility."
    },
    {
      "proposition_key": "ropa_processor_record",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(2)",
      "verbatim_quote": "Each processor and, where applicable, the processor's representative shall maintain a record of all categories of processing activities carried out on behalf of a controller"
    },
    {
      "proposition_key": "ropa_small_enterprise_carveout",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(5)",
      "verbatim_quote": "The obligations referred to in paragraphs 1 and 2 shall not apply to an enterprise or an organisation employing fewer than 250 persons unless the processing it carries out is likely to result in a risk to the rights and freedoms of data subjects, the processing is not occasional, or the processing includes special categories of data as referred to in Article 9(1) or personal data relating to criminal convictions and offences referred to in Article 10."
    },
    {
      "proposition_key": "security_appropriate_measures",
      "citation": "GDPR Art. 32",
      "subsection": "GDPR Art. 32(1)",
      "verbatim_quote": "the controller and the processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk"
    },
    {
      "proposition_key": "security_staff_instructions",
      "citation": "GDPR Art. 32",
      "subsection": "GDPR Art. 32(4)",
      "verbatim_quote": "The controller and processor shall take steps to ensure that any natural person acting under the authority of the controller or the processor who has access to personal data does not process them except on instructions from the controller, unless he or she is required to do so by Union or Member State law."
    },
    {
      "proposition_key": "breach_notify_sa_72h",
      "citation": "GDPR Art. 33",
      "subsection": "GDPR Art. 33(1)",
      "verbatim_quote": "In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the supervisory authority competent in accordance with Article 55, unless the personal data breach is unlikely to result in a risk to the rights and freedoms of natural persons."
    },
    {
      "proposition_key": "breach_processor_notify_controller",
      "citation": "GDPR Art. 33",
      "subsection": "GDPR Art. 33(2)",
      "verbatim_quote": "The processor shall notify the controller without undue delay after becoming aware of a personal data breach."
    },
    {
      "proposition_key": "breach_notify_data_subject_high_risk",
      "citation": "GDPR Art. 34",
      "subsection": "GDPR Art. 34(1)",
      "verbatim_quote": "When the personal data breach is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall communicate the personal data breach to the data subject without undue delay."
    },
    {
      "proposition_key": "dpia_when_required",
      "citation": "GDPR Art. 35",
      "subsection": "GDPR Art. 35(1)",
      "verbatim_quote": "Where a type of processing in particular using new technologies, and taking into account the nature, scope, context and purposes of the processing, is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall, prior to the processing, carry out an assessment of the impact of the envisaged processing operations on the protection of personal data."
    },
    {
      "proposition_key": "dpia_trigger_automated_profiling",
      "citation": "GDPR Art. 35",
      "subsection": "GDPR Art. 35(3)(a)",
      "verbatim_quote": "a systematic and extensive evaluation of personal aspects relating to natural persons which is based on automated processing, including profiling, and on which decisions are based that produce legal effects concerning the natural person or similarly significantly affect the natural person;"
    },
    {
      "proposition_key": "dpia_trigger_special_categories_large_scale",
      "citation": "GDPR Art. 35",
      "subsection": "GDPR Art. 35(3)(b)",
      "verbatim_quote": "processing on a large scale of special categories of data referred to in Article 9(1), or of personal data relating to criminal convictions and offences referred to in Article 10;"
    },
    {
      "proposition_key": "dpia_trigger_public_area_monitoring",
      "citation": "GDPR Art. 35",
      "subsection": "GDPR Art. 35(3)(c)",
      "verbatim_quote": "a systematic monitoring of a publicly accessible area on a large scale."
    },
    {
      "proposition_key": "transfers_general_principle",
      "citation": "GDPR Art. 44",
      "subsection": "GDPR Art. 44",
      "verbatim_quote": "Any transfer of personal data which are undergoing processing or are intended for processing after transfer to a third country or to an international organisation shall take place only if, subject to the other provisions of this Regulation, the conditions laid down in this Chapter are complied with by the controller and processor"
    },
    {
      "proposition_key": "transfers_appropriate_safeguards",
      "citation": "GDPR Art. 46",
      "subsection": "GDPR Art. 46(1)",
      "verbatim_quote": "a controller or processor may transfer personal data to a third country or an international organisation only if the controller or processor has provided appropriate safeguards, and on condition that enforceable data subject rights and effective legal remedies for data subjects are available."
    },
    {
      "proposition_key": "transfers_scc_mechanism",
      "citation": "GDPR Art. 46",
      "subsection": "GDPR Art. 46(2)(c)",
      "verbatim_quote": "standard data protection clauses adopted by the Commission in accordance with the examination procedure referred to in Article 93(2);"
    },
    {
      "proposition_key": "transfers_bcr_mechanism",
      "citation": "GDPR Art. 46",
      "subsection": "GDPR Art. 46(2)(b)",
      "verbatim_quote": "binding corporate rules in accordance with Article 47;"
    },
    {
      "proposition_key": "uk_art_44_not_in_force",
      "citation": "UK GDPR Art. 44",
      "subsection": "UK GDPR Art. 44 (omitted)",
      "verbatim_quote": "There is no UK GDPR Article 44 in force; the UK Chapter V general principle must not be cited to Art. 44."
    },
    {
      "proposition_key": "uk_transfers_general_principle",
      "citation": "UK GDPR Art. 44A",
      "subsection": "UK GDPR Art. 44A(1)",
      "verbatim_quote": "A controller or processor may transfer personal data to a third country or an international organisation only if"
    },
    {
      "proposition_key": "uk_transfers_adequacy_route",
      "citation": "UK GDPR Art. 44A",
      "subsection": "UK GDPR Art. 44A(2)(a)",
      "verbatim_quote": "is approved by regulations under Article 45A that are in force at the time of the transfer,"
    },
    {
      "proposition_key": "uk_transfers_safeguards_route",
      "citation": "UK GDPR Art. 44A",
      "subsection": "UK GDPR Art. 44A(2)(b)",
      "verbatim_quote": "is made subject to appropriate safeguards (see Article 46), or"
    },
    {
      "proposition_key": "uk_transfers_art_49a_restriction",
      "citation": "UK GDPR Art. 44A",
      "subsection": "UK GDPR Art. 44A(3)",
      "verbatim_quote": "A transfer may not be made in reliance on paragraph 2(b) or (c) if, or to the extent that, it would breach a restriction in regulations under Article 49A."
    },
    {
      "proposition_key": "uk_adequacy_regulations_power",
      "citation": "UK GDPR Art. 45A",
      "subsection": "UK GDPR Art. 45A(2)",
      "verbatim_quote": "The Secretary of State may only make regulations under this Article approving transfers to a third country or international organisation if the Secretary of State considers that the data protection test is met in relation to the transfers (see Article 45B)."
    },
    {
      "proposition_key": "uk_adequacy_data_protection_test",
      "citation": "UK GDPR Art. 45B",
      "subsection": "UK GDPR Art. 45B(1)",
      "verbatim_quote": "the data protection test is met in relation to transfers of personal data to a third country or international organisation if the standard of the protection provided for data subjects with regard to general processing of personal data in the country or by the organisation is not materially lower than the standard of the protection provided for data subjects by or under"
    },
    {
      "proposition_key": "uk_adequacy_test_factors",
      "citation": "UK GDPR Art. 45B",
      "subsection": "UK GDPR Art. 45B(2)",
      "verbatim_quote": "In considering whether the data protection test is met in relation to transfers of personal data to a third country or international organisation, the Secretary of State must consider, among other things"
    },
    {
      "proposition_key": "uk_transfers_appropriate_safeguards",
      "citation": "UK GDPR Art. 46",
      "subsection": "UK GDPR Art. 46(1A)",
      "verbatim_quote": "A transfer of personal data to a third country or an international organisation by a controller or processor is made subject to appropriate safeguards only"
    },
    {
      "proposition_key": "uk_transfers_exporter_own_assessment",
      "citation": "UK GDPR Art. 46",
      "subsection": "UK GDPR Art. 46(1A)(a)(ii)",
      "verbatim_quote": "the controller or processor, acting reasonably and proportionately, considers that the data protection test is met in relation to the transfer or that type of transfer (see paragraph 6), or"
    },
    {
      "proposition_key": "uk_transfers_sos_clauses",
      "citation": "UK GDPR Art. 46",
      "subsection": "UK GDPR Art. 46(2)(c)",
      "verbatim_quote": "standard data protection clauses specified in regulations made by the Secretary of State under Article 47A(1) and for the time being in force;"
    },
    {
      "proposition_key": "uk_transfers_commissioner_clauses",
      "citation": "UK GDPR Art. 46",
      "subsection": "UK GDPR Art. 46(2)(d)",
      "verbatim_quote": "standard data protection clauses specified in a document issued (and not withdrawn) by the Commissioner for the purposes of this Article under section 119A of the 2018 Act and for the time being in force;"
    },
    {
      "proposition_key": "uk_transfers_bcr_mechanism",
      "citation": "UK GDPR Art. 46",
      "subsection": "UK GDPR Art. 46(2)(b)",
      "verbatim_quote": "binding corporate rules approved in accordance with Article 47;"
    },
    {
      "proposition_key": "uk_transfers_data_protection_test",
      "citation": "UK GDPR Art. 46",
      "subsection": "UK GDPR Art. 46(6)",
      "verbatim_quote": "the data protection test is met in relation to a transfer, or a type of transfer, of personal data if, after the transfer, the standard of the protection provided for the data subject with regard to that personal data by the safeguards required under paragraph 1A, and (where relevant) by other means, would not be materially lower than the standard of the protection provided for the data subject with regard to the personal data by or under"
    },
    {
      "proposition_key": "uk_transfers_reasonable_and_proportionate",
      "citation": "UK GDPR Art. 46",
      "subsection": "UK GDPR Art. 46(7)",
      "verbatim_quote": "what is reasonable and proportionate is to be determined by reference to all the circumstances, or likely circumstances, of the transfer or type of transfer, including the nature and volume of the personal data transferred."
    },
    {
      "proposition_key": "uk_bcr_commissioner_approval",
      "citation": "UK GDPR Art. 47",
      "subsection": "UK GDPR Art. 47(1)",
      "verbatim_quote": "The Commissioner shall approve binding corporate rules"
    },
    {
      "proposition_key": "uk_standard_clauses_secretary_of_state",
      "citation": "UK GDPR Art. 47A",
      "subsection": "UK GDPR Art. 47A(1)",
      "verbatim_quote": "The Secretary of State may by regulations specify standard data protection clauses which the Secretary of State considers are capable of securing that the data protection test set out in Article 46 is met in relation to transfers of personal data generally or in relation to a type of transfer specified in the regulations."
    },
    {
      "proposition_key": "necessity_less_intrusive_alternatives",
      "citation": "EDPB Guidelines 2/2019, § 2.4 (Necessity)",
      "subsection": "EDPB Guidelines 2/2019, § 2.4",
      "verbatim_quote": "If there are realistic, less intrusive alternatives, the processing is not ‘necessary’."
    },
    {
      "proposition_key": "accountability_demonstrate_compliance",
      "citation": "GDPR Art. 5",
      "subsection": "GDPR Art. 5(2)",
      "verbatim_quote": "The controller shall be responsible for, and be able to demonstrate compliance with, paragraph 1 (‘accountability’)."
    },
    {
      "proposition_key": "art_24_1_appropriate_measures",
      "citation": "GDPR Art. 24",
      "subsection": "GDPR Art. 24(1)",
      "verbatim_quote": "Taking into account the nature, scope, context and purposes of processing as well as the risks of varying likelihood and severity for the rights and freedoms of natural persons, the controller shall implement appropriate technical and organisational measures to ensure and to be able to demonstrate that processing is performed in accordance with this Regulation."
    },
    {
      "proposition_key": "art_24_1_review_and_update",
      "citation": "GDPR Art. 24",
      "subsection": "GDPR Art. 24(1) (second sentence)",
      "verbatim_quote": "Those measures shall be reviewed and updated where necessary."
    },
    {
      "proposition_key": "art_24_2_data_protection_policies",
      "citation": "GDPR Art. 24",
      "subsection": "GDPR Art. 24(2)",
      "verbatim_quote": "Where proportionate in relation to processing activities, the measures referred to in paragraph 1 shall include the implementation of appropriate data protection policies by the controller."
    },
    {
      "proposition_key": "art_24_3_codes_and_certification",
      "citation": "GDPR Art. 24",
      "subsection": "GDPR Art. 24(3)",
      "verbatim_quote": "Adherence to approved codes of conduct as referred to in Article 40 or approved certification mechanisms as referred to in Article 42 may be used as an element by which to demonstrate compliance with the obligations of the controller."
    },
    {
      "proposition_key": "art_30_1_record_duty",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(1)",
      "verbatim_quote": "Each controller and, where applicable, the controller's representative, shall maintain a record of processing activities under its responsibility. That record shall contain all of the following information:"
    },
    {
      "proposition_key": "art_30_1_a_controller_contact",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(1)(a)",
      "verbatim_quote": "the name and contact details of the controller and, where applicable, the joint controller, the controller's representative and the data protection officer;"
    },
    {
      "proposition_key": "art_30_1_b_purposes",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(1)(b)",
      "verbatim_quote": "the purposes of the processing;"
    },
    {
      "proposition_key": "art_30_1_c_categories",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(1)(c)",
      "verbatim_quote": "a description of the categories of data subjects and of the categories of personal data;"
    },
    {
      "proposition_key": "art_30_1_d_recipients",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(1)(d)",
      "verbatim_quote": "the categories of recipients to whom the personal data have been or will be disclosed including recipients in third countries or international organisations;"
    },
    {
      "proposition_key": "art_30_1_e_transfers",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(1)(e)",
      "verbatim_quote": "where applicable, transfers of personal data to a third country or an international organisation, including the identification of that third country or international organisation and, in the case of transfers referred to in the second subparagraph of Article 49(1), the documentation of suitable safeguards;"
    },
    {
      "proposition_key": "art_30_1_f_retention",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(1)(f)",
      "verbatim_quote": "where possible, the envisaged time limits for erasure of the different categories of data;"
    },
    {
      "proposition_key": "art_30_1_g_security_measures",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(1)(g)",
      "verbatim_quote": "where possible, a general description of the technical and organisational security measures referred to in Article 32(1)."
    },
    {
      "proposition_key": "art_30_3_in_writing",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(3)",
      "verbatim_quote": "The records referred to in paragraphs 1 and 2 shall be in writing, including in electronic form."
    },
    {
      "proposition_key": "art_30_4_available_to_sa",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(4)",
      "verbatim_quote": "The controller or the processor and, where applicable, the controller's or the processor's representative, shall make the record available to the supervisory authority on request."
    },
    {
      "proposition_key": "art_30_5_small_enterprise_exemption",
      "citation": "GDPR Art. 30",
      "subsection": "GDPR Art. 30(5)",
      "verbatim_quote": "The obligations referred to in paragraphs 1 and 2 shall not apply to an enterprise or an organisation employing fewer than 250 persons unless the processing it carries out is likely to result in a risk to the rights and freedoms of data subjects, the processing is not occasional, or the processing includes special categories of data as referred to in Article 9(1) or personal data relating to criminal convictions and offences referred to in Article 10."
    },
    {
      "proposition_key": "art_37_1_designation_trigger",
      "citation": "GDPR Art. 37",
      "subsection": "GDPR Art. 37(1)",
      "verbatim_quote": "The controller and the processor shall designate a data protection officer in any case where:"
    },
    {
      "proposition_key": "art_37_1_a_public_authority",
      "citation": "GDPR Art. 37",
      "subsection": "GDPR Art. 37(1)(a)",
      "verbatim_quote": "the processing is carried out by a public authority or body, except for courts acting in their judicial capacity;"
    },
    {
      "proposition_key": "art_37_1_b_regular_systematic_monitoring",
      "citation": "GDPR Art. 37",
      "subsection": "GDPR Art. 37(1)(b)",
      "verbatim_quote": "the core activities of the controller or the processor consist of processing operations which, by virtue of their nature, their scope and/or their purposes, require regular and systematic monitoring of data subjects on a large scale; or"
    },
    {
      "proposition_key": "art_37_1_c_large_scale_special_category",
      "citation": "GDPR Art. 37",
      "subsection": "GDPR Art. 37(1)(c)",
      "verbatim_quote": "the core activities of the controller or the processor consist of processing on a large scale of special categories of data pursuant to Article 9 and personal data relating to criminal convictions and offences referred to in Article 10."
    },
    {
      "proposition_key": "art_37_5_professional_qualities",
      "citation": "GDPR Art. 37",
      "subsection": "GDPR Art. 37(5)",
      "verbatim_quote": "The data protection officer shall be designated on the basis of professional qualities and, in particular, expert knowledge of data protection law and practices and the ability to fulfil the tasks referred to in Article 39."
    },
    {
      "proposition_key": "art_37_7_publish_contact_details",
      "citation": "GDPR Art. 37",
      "subsection": "GDPR Art. 37(7)",
      "verbatim_quote": "The controller or the processor shall publish the contact details of the data protection officer and communicate them to the supervisory authority."
    },
    {
      "proposition_key": "art_38_1_timely_involvement",
      "citation": "GDPR Art. 38",
      "subsection": "GDPR Art. 38(1)",
      "verbatim_quote": "The controller and the processor shall ensure that the data protection officer is involved, properly and in a timely manner, in all issues which relate to the protection of personal data."
    },
    {
      "proposition_key": "art_38_2_resources_and_access",
      "citation": "GDPR Art. 38",
      "subsection": "GDPR Art. 38(2)",
      "verbatim_quote": "The controller and processor shall support the data protection officer in performing the tasks referred to in Article 39 by providing resources necessary to carry out those tasks and access to personal data and processing operations, and to maintain his or her expert knowledge."
    },
    {
      "proposition_key": "art_38_3_independence",
      "citation": "GDPR Art. 38",
      "subsection": "GDPR Art. 38(3)",
      "verbatim_quote": "The controller and processor shall ensure that the data protection officer does not receive any instructions regarding the exercise of those tasks. He or she shall not be dismissed or penalised by the controller or the processor for performing his tasks. The data protection officer shall directly report to the highest management level of the controller or the processor."
    },
    {
      "proposition_key": "art_38_6_conflict_of_interests",
      "citation": "GDPR Art. 38",
      "subsection": "GDPR Art. 38(6)",
      "verbatim_quote": "The data protection officer may fulfil other tasks and duties. The controller or processor shall ensure that any such tasks and duties do not result in a conflict of interests."
    },
    {
      "proposition_key": "art_39_1_dpo_tasks",
      "citation": "GDPR Art. 39",
      "subsection": "GDPR Art. 39(1)",
      "verbatim_quote": "The data protection officer shall have at least the following tasks:"
    },
    {
      "proposition_key": "art_39_1_a_inform_and_advise",
      "citation": "GDPR Art. 39",
      "subsection": "GDPR Art. 39(1)(a)",
      "verbatim_quote": "to inform and advise the controller or the processor and the employees who carry out processing of their obligations pursuant to this Regulation and to other Union or Member State data protection provisions;"
    },
    {
      "proposition_key": "art_39_1_b_monitor_compliance",
      "citation": "GDPR Art. 39",
      "subsection": "GDPR Art. 39(1)(b)",
      "verbatim_quote": "to monitor compliance with this Regulation, with other Union or Member State data protection provisions and with the policies of the controller or processor in relation to the protection of personal data, including the assignment of responsibilities, awareness-raising and training of staff involved in processing operations, and the related audits;"
    },
    {
      "proposition_key": "art_39_1_c_dpia_advice",
      "citation": "GDPR Art. 39",
      "subsection": "GDPR Art. 39(1)(c)",
      "verbatim_quote": "to provide advice where requested as regards the data protection impact assessment and monitor its performance pursuant to Article 35;"
    },
    {
      "proposition_key": "art_39_1_d_cooperate_with_sa",
      "citation": "GDPR Art. 39",
      "subsection": "GDPR Art. 39(1)(d)",
      "verbatim_quote": "to cooperate with the supervisory authority;"
    },
    {
      "proposition_key": "art_39_1_e_contact_point",
      "citation": "GDPR Art. 39",
      "subsection": "GDPR Art. 39(1)(e)",
      "verbatim_quote": "to act as the contact point for the supervisory authority on issues relating to processing, including the prior consultation referred to in Article 36, and to consult, where appropriate, with regard to any other matter."
    },
    {
      "proposition_key": "art_39_2_risk_based_tasks",
      "citation": "GDPR Art. 39",
      "subsection": "GDPR Art. 39(2)",
      "verbatim_quote": "The data protection officer shall in the performance of his or her tasks have due regard to the risk associated with processing operations, taking into account the nature, scope, context and purposes of processing."
    },
    {
      "proposition_key": "dpa2018_s119a_power",
      "citation": "Data Protection Act 2018",
      "subsection": "Data Protection Act 2018, s. 119A(1)",
      "verbatim_quote": "The Commissioner may issue a document specifying standard data protection clauses which the Commissioner considers are capable of securing that the data protection test set out in Article 46 of the UK GDPR or section 75 of this Act (or both) is met in relation to transfers of personal data."
    },
    {
      "proposition_key": "dpa2018_s119a_consultation",
      "citation": "Data Protection Act 2018",
      "subsection": "Data Protection Act 2018, s. 119A(4)",
      "verbatim_quote": "Before issuing a document under this section, the Commissioner must consult the Secretary of State and such of the following as the Commissioner considers appropriate"
    },
    {
      "proposition_key": "dpa2018_sch1_para5",
      "citation": "Data Protection Act 2018",
      "subsection": "Data Protection Act 2018, Sch. 1, para. 5(1)",
      "verbatim_quote": "Except as otherwise provided, a condition in this Part of this Schedule is met only if, when the processing is carried out, the controller has an appropriate policy document in place (see paragraph 39 in Part 4 of this Schedule)."
    },
    {
      "proposition_key": "dpa2018_sch1_para39",
      "citation": "Data Protection Act 2018",
      "subsection": "Data Protection Act 2018, Sch. 1, para. 39",
      "verbatim_quote": "the controller has produced a document which—\n(a) explains the controller's procedures for securing compliance with the principles in Article 5 of the UK GDPR (principles relating to processing of personal data) in connection with the processing of personal data in reliance on the condition in question, and\n(b) explains the controller's policies as regards the retention and erasure of personal data processed in reliance on the condition, giving an indication of how long such personal data is likely to be retained."
    },
    {
      "proposition_key": "dpa2018_sch1_para40",
      "citation": "Data Protection Act 2018",
      "subsection": "Data Protection Act 2018, Sch. 1, para. 40(1)",
      "verbatim_quote": "the controller must during the relevant period—\n(a) retain the appropriate policy document,\n(b) review and (if appropriate) update it from time to time, and\n(c) make it available to the Commissioner, on request, without charge."
    },
    {
      "proposition_key": "dpa2018_sch1_para41",
      "citation": "Data Protection Act 2018",
      "subsection": "Data Protection Act 2018, Sch. 1, para. 41",
      "verbatim_quote": "A record maintained by the controller, or the controller's representative, under Article 30 of the UK GDPR in respect of the processing of personal data in reliance on a condition described in paragraph 38 must include the following information—\n(a) which condition is relied on,\n(b) how the processing satisfies Article 6 of the UK GDPR (lawfulness of processing), and\n(c) whether the personal data is retained and erased in accordance with the policies described in paragraph 39(b) and, if it is not, the reasons for not following those policies."
    },
    {
      "proposition_key": "wp243_large_scale_factors",
      "citation": "Article 29 Working Party Guidelines on Data Protection Officers ('DPOs'), WP243 rev.01 (endorsed by the EDPB)",
      "subsection": "WP243 rev.01, §2.1.3 ('Large scale')",
      "verbatim_quote": "The GDPR does not define what constitutes large-scale processing. The WP29 recommends that the\nfollowing factors, in particular, be considered when determining whether the processing is carried out\non a large scale:\n the number of data subjects concerned - either as a specific number or as a proportion of the\nrelevant population\n the volume of data and/or the range of different data items being processed\n the duration, or permanence, of the data processing activity\n the geographical extent of the processing activity"
    },
    {
      "proposition_key": "wp243_core_activities",
      "citation": "Article 29 Working Party Guidelines on Data Protection Officers ('DPOs'), WP243 rev.01 (endorsed by the EDPB)",
      "subsection": "WP243 rev.01, §2.1.2 ('Core activities')",
      "verbatim_quote": "Article 37(1)(b) and (c) of the GDPR refers to the ‘core activities of the controller or processor’. Recital 97 specifies that the core activities of a controller relate to ‘primary activities and do not relate\nto the processing of personal data as ancillary activities’. ‘Core activities’ can be considered as the\nkey operations necessary to achieve the controller’s or processor’s goals."
    }
  ]
};
