// GENERATED by scripts/ptest/export-packs.ts (DOC 261) — do not edit by hand.
// Rebuild: deno run --allow-read --allow-write --allow-env scripts/ptest/export-packs.ts
// Drift guard: tests/edge/ptest/packs.test.ts
import type { RegistryPack } from "./types.ts";

export const RISK_REGISTRY_PACK: RegistryPack = {
  "product": "cppa-risk",
  "registry_version": "risk-va-w1-2026-09-17",
  "generated_on": "2026-09-14",
  "rows": [
    {
      "proposition_key": "ra_when_required",
      "citation": "11 CCR § 7150",
      "subsection": "11 CCR § 7150(a)",
      "verbatim_quote": "Every business whose processing of consumers' personal information presents significant risk to consumers' privacy as set forth in subsection (b) must conduct a risk assessment before initiating that processing."
    },
    {
      "proposition_key": "ra_triggers_intro",
      "citation": "11 CCR § 7150",
      "subsection": "11 CCR § 7150(b)",
      "verbatim_quote": "Each of the following processing activities presents significant risk to consumers' privacy:"
    },
    {
      "proposition_key": "ra_trigger_sell_share",
      "citation": "11 CCR § 7150",
      "subsection": "11 CCR § 7150(b)(1)",
      "verbatim_quote": "Selling or sharing personal information."
    },
    {
      "proposition_key": "ra_trigger_sensitive",
      "citation": "11 CCR § 7150",
      "subsection": "11 CCR § 7150(b)(2)",
      "verbatim_quote": "Processing sensitive personal information."
    },
    {
      "proposition_key": "ra_trigger_sensitive_hr_exclusion",
      "citation": "11 CCR § 7150",
      "subsection": "11 CCR § 7150(b)(2)(A)",
      "verbatim_quote": "A business that processes the sensitive personal information of its employees or independent contractors solely and specifically for purposes of administering compensation payments, determining and storing employment authorization, administering employment benefits, providing reasonable accommodation as required by law, or wage reporting as required by law, is not required to conduct a risk assessment for the processing of sensitive personal information for these purposes."
    },
    {
      "proposition_key": "ra_trigger_admt",
      "citation": "11 CCR § 7150",
      "subsection": "11 CCR § 7150(b)(3)",
      "verbatim_quote": "Using ADMT for a significant decision concerning a consumer."
    },
    {
      "proposition_key": "ra_trigger_infer_context",
      "citation": "11 CCR § 7150",
      "subsection": "11 CCR § 7150(b)(4)",
      "verbatim_quote": "Using automated processing to infer or extrapolate a consumer's intelligence, ability, aptitude, performance at work, economic situation, health (including mental health), personal preferences, interests, reliability, predispositions, behavior, location, or movements, based upon systematic observation of that consumer when they are acting in their capacity as an educational program applicant, job applicant, student, employee, or independent contractor for the business."
    },
    {
      "proposition_key": "ra_trigger_infer_sensitive_location",
      "citation": "11 CCR § 7150",
      "subsection": "11 CCR § 7150(b)(5)",
      "verbatim_quote": "Using automated processing to infer or extrapolate a consumer's intelligence, ability, aptitude, performance at work, economic situation, health (including mental health), personal preferences, interests, reliability, predispositions, behavior, or movements, based upon that"
    },
    {
      "proposition_key": "ra_trigger_train",
      "citation": "11 CCR § 7150",
      "subsection": "11 CCR § 7150(b)(6)",
      "verbatim_quote": "Processing the personal information of consumers, which the business intends to use to train an ADMT for a significant decision concerning a consumer; or train a facial-recognition, emotion-recognition, or other technology that verifies a consumer's identity, or conducts physical or biological identification or profiling of a consumer."
    },
    {
      "proposition_key": "ra_stakeholder_internal",
      "citation": "11 CCR § 7151",
      "subsection": "11 CCR § 7151(a)",
      "verbatim_quote": "A business's employees whose job duties include participating in the processing of personal information that would be subject to a risk assessment must be included in the business's risk assessment process for that processing activity."
    },
    {
      "proposition_key": "ra_stakeholder_external",
      "citation": "11 CCR § 7151",
      "subsection": "11 CCR § 7151(b)",
      "verbatim_quote": "In conducting the risk assessment, a business may include external parties in the process."
    },
    {
      "proposition_key": "ra_content_intro",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)",
      "verbatim_quote": "A business must conduct a risk assessment to determine whether the risks to consumers' privacy from the processing of personal information outweigh the benefits to the consumer, the business, other stakeholders, and the public from that same processing."
    },
    {
      "proposition_key": "ra_content_purpose",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(1)",
      "verbatim_quote": "Identify and document in a risk assessment report the business's purpose for processing consumers' personal information. The purpose must not be identified or described in generic terms, such as \"to improve our services\" or for \"security purposes.\""
    },
    {
      "proposition_key": "ra_content_categories",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(2)",
      "verbatim_quote": "Identify and document in a risk assessment report the categories of personal information to be processed, including any categories of sensitive personal information. This must include the minimum personal information that is necessary to achieve the purpose of processing consumers' personal information."
    },
    {
      "proposition_key": "ra_content_operational",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(3)",
      "verbatim_quote": "Identify and document in a risk assessment report the following operational elements of the processing:"
    },
    {
      "proposition_key": "ra_content_op_method",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(3)(A)",
      "verbatim_quote": "The business's planned method for collecting, using, disclosing, retaining, or otherwise processing personal information, and the sources of the personal information."
    },
    {
      "proposition_key": "ra_content_op_retention",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(3)(B)",
      "verbatim_quote": "How long the business plans to retain each category of personal information, or if unknown, the criteria the business plans to use to determine that retention period."
    },
    {
      "proposition_key": "ra_content_op_disclosures",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(3)(E)",
      "verbatim_quote": "What disclosures the business has made or plans to make to the consumer about the processing of their personal information and how these disclosures were or will be made"
    },
    {
      "proposition_key": "ra_content_op_recipients",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(3)(F)",
      "verbatim_quote": "The names or categories of the service providers, contractors, or third parties to whom the business discloses or makes available the consumers' personal information for the processing; and the purpose for which the business discloses or makes the consumers' personal information available to them."
    },
    {
      "proposition_key": "ra_content_benefits",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(4)",
      "verbatim_quote": "Identify the benefits to the business, the consumer, other stakeholders, and the public from the processing of the personal information, as applicable. The benefits must not be identified in generic terms, such as \"improving our service.\""
    },
    {
      "proposition_key": "ra_content_negative_impacts",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(5)",
      "verbatim_quote": "Identify the negative impacts to consumers' privacy associated with the processing. The business must identify the sources and causes of these negative impacts."
    },
    {
      "proposition_key": "ra_content_safeguards",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(6)",
      "verbatim_quote": "Identify and document in a risk assessment report any safeguards that the business plans to implement for the processing, such as safeguards to address the negative impacts identified in subsection (a)(5)."
    },
    {
      "proposition_key": "ra_content_initiate",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(7)",
      "verbatim_quote": "Identify and document in a risk assessment report whether it will initiate the processing subject to the risk assessment."
    },
    {
      "proposition_key": "ra_content_contributors",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(8)",
      "verbatim_quote": "Identify and document in a risk assessment report the individuals who provided the information for the risk assessment, except for legal counsel who provided legal advice."
    },
    {
      "proposition_key": "ra_content_approval",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(9)",
      "verbatim_quote": "Identify and document in a risk assessment report the date the assessment was reviewed and approved, and the names and positions of the individuals who reviewed or approved the assessment, except for legal counsel who provided legal advice."
    },
    {
      "proposition_key": "ra_train_recipient_facts",
      "citation": "11 CCR § 7153",
      "subsection": "11 CCR § 7153(a)",
      "verbatim_quote": "A business that makes ADMT available to another business (\"recipient-"
    },
    {
      "proposition_key": "ra_train_scope",
      "citation": "11 CCR § 7153",
      "subsection": "11 CCR § 7153(b)",
      "verbatim_quote": "The requirements of this section apply only to ADMT trained using personal information."
    },
    {
      "proposition_key": "ra_goal",
      "citation": "11 CCR § 7154",
      "subsection": "11 CCR § 7154(a)",
      "verbatim_quote": "The goal of a risk assessment is restricting or prohibiting the processing of personal information if the risks to privacy of the consumer outweigh the benefits resulting from processing to the consumer, the business, other stakeholders, and the public."
    },
    {
      "proposition_key": "ra_timing_new",
      "citation": "11 CCR § 7155",
      "subsection": "11 CCR § 7155(a)(1)",
      "verbatim_quote": "A business must conduct and document a risk assessment in accordance with the requirements of this Article before initiating any processing activity identified in section 7150, subsection (b)."
    },
    {
      "proposition_key": "ra_timing_review_3yr",
      "citation": "11 CCR § 7155",
      "subsection": "11 CCR § 7155(a)(2)",
      "verbatim_quote": "At least once every three years, a business must review, and update as necessary, its risk assessments to ensure that they remain accurate in accordance with the requirements of this Article."
    },
    {
      "proposition_key": "ra_timing_material_change",
      "citation": "11 CCR § 7155",
      "subsection": "11 CCR § 7155(a)(3)",
      "verbatim_quote": "a business must update a risk assessment whenever there is a material change relating to the processing activity, as soon as feasibly possible, but no later than 45 calendar days from the date of the material change."
    },
    {
      "proposition_key": "ra_timing_material_change_definition",
      "citation": "11 CCR § 7155",
      "subsection": "11 CCR § 7155(a)(3)",
      "verbatim_quote": "A change relating to the processing activity is material if it creates new negative impacts or increases the magnitude or likelihood of previously identified negative impacts as set forth in section 7152, subsection (a)(5), or diminishes the effectiveness of the safeguards as set forth in section 7152, subsection (a)(6)."
    },
    {
      "proposition_key": "ra_timing_existing",
      "citation": "11 CCR § 7155",
      "subsection": "11 CCR § 7155(b)",
      "verbatim_quote": "For any processing activity identified in section 7150, subsection (b), that the business initiated prior to January 1, 2026 and that continues after January 1, 2026, the business must conduct, and document as set forth in section 7152, a risk assessment in accordance with the requirements of this Article no later than December 31, 2027."
    },
    {
      "proposition_key": "ra_retention",
      "citation": "11 CCR § 7155",
      "subsection": "11 CCR § 7155(c)",
      "verbatim_quote": "A business must retain its risk assessments, including original and updated versions, for as long as the processing continues or for five years after the completion of the risk assessment, whichever is later."
    },
    {
      "proposition_key": "ra_comparable_set",
      "citation": "11 CCR § 7156",
      "subsection": "11 CCR § 7156(a)",
      "verbatim_quote": "A business may conduct a single risk assessment for a comparable set of processing activities. A \"comparable set of processing activities\" that can be addressed by a single risk assessment is a set of similar processing activities that present similar risks to consumers' privacy."
    },
    {
      "proposition_key": "ra_other_law_reuse",
      "citation": "11 CCR § 7156",
      "subsection": "11 CCR § 7156(b)",
      "verbatim_quote": "A business may utilize a risk assessment that it has prepared for another purpose to meet the requirements in section 7152, provided that the risk assessment contains the information that must be included in, or is paired with the outstanding information necessary for, compliance with section 7152."
    },
    {
      "proposition_key": "ra_submit_2026_2027",
      "citation": "11 CCR § 7157",
      "subsection": "11 CCR § 7157(a)(1)",
      "verbatim_quote": "For risk assessments conducted in 2026 and 2027, the business must submit to the Agency the information required by subsection (b) no later than April 1, 2028."
    },
    {
      "proposition_key": "ra_submit_ongoing",
      "citation": "11 CCR § 7157",
      "subsection": "11 CCR § 7157(a)(2)",
      "verbatim_quote": "For risk assessments conducted after 2027, the business must submit to the Agency the information required by subsection (b) no later than April 1 following any year during which the business conducted the risk assessments."
    },
    {
      "proposition_key": "ra_submit_content_intro",
      "citation": "11 CCR § 7157",
      "subsection": "11 CCR § 7157(b)",
      "verbatim_quote": "A business must submit to the Agency the following risk assessment information:"
    },
    {
      "proposition_key": "ra_submit_attestation",
      "citation": "11 CCR § 7157",
      "subsection": "11 CCR § 7157(b)(5)",
      "verbatim_quote": "Attestation to the following statement: \"I attest that the business has conducted a risk assessment for the processing activities set forth in California Code of Regulations, Title 11, section 7150, subsection (b), during the time period covered by this submission, and that I meet the requirements of section 7157, subsection (c). Under penalty of perjury under the laws of the state of California, I hereby declare that the risk assessment information submitted is true and correct.\""
    },
    {
      "proposition_key": "ra_submit_signer",
      "citation": "11 CCR § 7157",
      "subsection": "11 CCR § 7157(c)",
      "verbatim_quote": "The individual submitting the information set forth in subsection (b) must be a member of the business's executive management team who:"
    },
    {
      "proposition_key": "ra_submit_portal",
      "citation": "11 CCR § 7157",
      "subsection": "11 CCR § 7157(d)",
      "verbatim_quote": "The risk assessment information must be submitted to the Agency via the Agency's website at https://cppa.ca.gov/."
    },
    {
      "proposition_key": "ra_submit_ondemand",
      "citation": "11 CCR § 7157",
      "subsection": "11 CCR § 7157(e)",
      "verbatim_quote": "The Agency or the Attorney General may require a business to submit its risk assessment reports to the Agency or to the Attorney General at any time. A business must submit its risk assessment reports within 30 calendar days of the Agency's or the Attorney General's request."
    },
    {
      "proposition_key": "ra_admt_def",
      "citation": "11 CCR § 7001",
      "subsection": "11 CCR § 7001(e)",
      "verbatim_quote": "\"Automated decisionmaking technology\" or \"ADMT\" means any technology that processes personal information and uses computation to replace human decisionmaking or substantially replace human decisionmaking."
    },
    {
      "proposition_key": "ra_human_involvement",
      "citation": "11 CCR § 7001",
      "subsection": "11 CCR § 7001(e)(1)",
      "verbatim_quote": "For purposes of this definition, to \"substantially replace human decisionmaking\" means a business uses the technology's output to make a decision without human involvement."
    },
    {
      "proposition_key": "ra_human_involvement_elements",
      "citation": "11 CCR § 7001",
      "subsection": "11 CCR § 7001(e)(1)",
      "verbatim_quote": "(A) Know how to interpret and use the technology's output to make the decision; (B) Review and analyze the output of the technology, and any other information that is relevant to make or change the decision; and (C) Have the authority to make or change the decision based on their analysis in subsection (B)."
    },
    {
      "proposition_key": "ra_significant_decision_def",
      "citation": "11 CCR § 7001",
      "subsection": "11 CCR § 7001(ddd)",
      "verbatim_quote": "\"Significant decision\" means a decision that results in the provision or denial of financial or lending services, housing, education enrollment or opportunities, employment or independent contracting opportunities or compensation, or healthcare services."
    },
    {
      "proposition_key": "ra_content_admt_logic_output",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(3)(G)",
      "verbatim_quote": "For the uses of ADMT set forth in section 7150, subsections (b)(3), the business must identify: (i) The logic of the ADMT, including any assumptions or limitations of the logic; and (ii) The output of the ADMT, and how the business will use the output to make a significant decision."
    },
    {
      "proposition_key": "ra_negative_impact_unauthorized_access",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(5)(A)",
      "verbatim_quote": "Unauthorized access, destruction, use, modification, or disclosure of personal information; and unauthorized activity resulting in the loss of availability of personal information."
    },
    {
      "proposition_key": "ra_negative_impact_discrimination",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(5)(B)",
      "verbatim_quote": "Discrimination upon the basis of protected characteristics that would violate federal or state law."
    },
    {
      "proposition_key": "ra_negative_impact_control",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(5)(C)",
      "verbatim_quote": "Impairing consumers' control over their personal information, such as by providing insufficient information for consumers to make an informed decision regarding the processing of their personal information, or by interfering with consumers' ability to make choices consistent with their reasonable expectations."
    },
    {
      "proposition_key": "ra_negative_impact_coercion",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(5)(D)",
      "verbatim_quote": "Coercing or compelling consumers into allowing the processing of their personal information, such as by conditioning consumers' acquisition or use of an online service upon their disclosure of"
    },
    {
      "proposition_key": "ra_negative_impact_coercion_cont",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(5)(D)",
      "verbatim_quote": "personal information that is unnecessary to the expected functionality of the service, or requiring consumers to consent to processing when such consent cannot be freely given (e.g., because it was obtained through the use of a dark pattern)."
    },
    {
      "proposition_key": "ra_negative_impact_economic",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(5)(E)",
      "verbatim_quote": "Economic harms, including limiting or depriving consumers of economic opportunities, charging consumers higher prices, or compensating consumers at lower rates based upon profiling; or imposing additional costs upon consumers, including costs associated with the unauthorized access to consumers' personal information."
    },
    {
      "proposition_key": "ra_negative_impact_physical",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(5)(F)",
      "verbatim_quote": "Physical harms to consumers or to property, including processing that creates the opportunity for physical or sexual violence."
    },
    {
      "proposition_key": "ra_negative_impact_reputational",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(5)(G)",
      "verbatim_quote": "Reputational harms, including stigmatization, that could negatively impact an average consumer, such as stigmatization of a consumer as a result of a mobile dating application's disclosure of the consumer's sexual or other preferences in a partner outside of the dating application."
    },
    {
      "proposition_key": "ra_negative_impact_psychological",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(5)(H)",
      "verbatim_quote": "Psychological harms, including emotional distress, stress, anxiety, embarrassment, fear, frustration, shame, and feelings of violation, that could negatively impact an average consumer."
    },
    {
      "proposition_key": "ra_safeguard_admt_policies",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(6)(A)(iv)",
      "verbatim_quote": "Implementing policies, procedures, and training to ensure that the business's ADMT works for the business's purpose and does not unlawfully discriminate based upon protected characteristics."
    },
    {
      "proposition_key": "ra_submit_point_of_contact",
      "citation": "11 CCR § 7157",
      "subsection": "11 CCR § 7157(b)(1)",
      "verbatim_quote": "The business's name and a point of contact for the business, including the contact's name, phone number, and email address."
    },
    {
      "proposition_key": "ra_submit_signer_qualifications",
      "citation": "11 CCR § 7157",
      "subsection": "11 CCR § 7157(c)(1)-(2)",
      "verbatim_quote": "(1) Is directly responsible for the business's risk-assessment compliance; (2) Has sufficient knowledge of the business's risk assessment to provide accurate information; and"
    },
    {
      "proposition_key": "ra_submit_signer_authority",
      "citation": "11 CCR § 7157",
      "subsection": "11 CCR § 7157(c)(3)",
      "verbatim_quote": "Has the authority to submit the risk assessment information to the Agency."
    },
    {
      "proposition_key": "ccpa_dns_link",
      "citation": "Cal. Civ. Code § 1798.135",
      "subsection": "Cal. Civ. Code § 1798.135(a)(1)",
      "verbatim_quote": "Provide a clear and conspicuous link on the business' internet homepages, titled \"Do Not Sell or Share My Personal Information,\" to an internet web page that enables a consumer, or a person authorized by the consumer, to opt out of the sale or sharing of the consumer's personal information."
    },
    {
      "proposition_key": "ra_content_interaction_method",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(3)(C)",
      "verbatim_quote": "The business's method of interacting with the consumers whose personal information the business plans to process (e.g., via websites, applications, or offline) and the purpose of the interaction (e.g., to provide a good or service)."
    },
    {
      "proposition_key": "ra_content_consumer_count",
      "citation": "11 CCR § 7152",
      "subsection": "11 CCR § 7152(a)(3)(D)",
      "verbatim_quote": "The approximate number of consumers whose personal information the business plans to process."
    },
    {
      "proposition_key": "ccpa_third_party_def",
      "citation": "Cal. Civ. Code § 1798.140",
      "subsection": "Cal. Civ. Code § 1798.140(ai)",
      "verbatim_quote": "\"Third party\" means a person who is not any of the following:"
    },
    {
      "proposition_key": "ccpa_rulemaking",
      "citation": "Cal. Civ. Code § 1798.185",
      "subsection": "Cal. Civ. Code § 1798.185(a)(15)",
      "verbatim_quote": "Issuing regulations governing access and opt-out rights with respect to a business' use of automated decisionmaking technology, including profiling and requiring a business' response to access requests to include meaningful information about the logic involved in those decisionmaking processes, as well as a description of the likely outcome of the process with respect to the consumer."
    }
  ]
};
