// GENERATED by scripts/ptest/export-packs.ts (DOC 261) — do not edit by hand.
// Rebuild: deno run --allow-read --allow-write --allow-env scripts/ptest/export-packs.ts
// Drift guard: tests/edge/ptest/packs.test.ts
import type { BlockCatalogue } from "./types.ts";

export const RISK_BLOCK_CATALOGUE: BlockCatalogue = {
  "product": "cppa-risk",
  "spine_version": "cppa-risk-v5.3-2026-09-02",
  "generated_on": "2026-09-14",
  "generated_from": [
    "risk-saas-clean-tuning",
    "risk-adtech-sell-tuning",
    "risk-consumer-boundary-adversarial",
    "risk-v3-ics-timing-hook-agreed",
    "risk-v3-admt-fraud-scoring-hook-disagreed",
    "risk-perfect-complete",
    "risk-perfect-seller-geolocation",
    "batch-ee860fd0-verilink"
  ],
  "entries": [
    {
      "block_key": "cover:0",
      "section_id": "cover",
      "section_title": "Assessment Profile",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "cover:1",
      "section_id": "cover",
      "section_title": "Assessment Profile",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "cover:2",
      "section_id": "cover",
      "section_title": "Assessment Profile",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary:0",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "skeleton",
      "fixed_text_prefix": "A. Activity Assessed. The activity assessed is identified by the Company as follows: “{activityName}” (the “Activity”). The Company identifies the subject of th",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary:1",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "skeleton",
      "fixed_text_prefix": "B. Why a Risk Assessment Is Required. California requires a risk assessment before a business begins processing that falls within a significant-risk category en",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary:2",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "exec_trigger_lines"
      ],
      "sources": [
        "DERIVED:applicable_7150_triggers"
      ],
      "authorities": [
        "11 CCR § 7150(b)"
      ]
    },
    {
      "block_key": "executive_summary:3",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary:4",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "skeleton",
      "fixed_text_prefix": "C. The Balancing Test. Where a trigger is engaged, 11 CCR §§ 7152 and 7154 require the Company to evaluate whether the privacy risks the Activity creates for co",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary:5",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [
        "exec_ledger_intro"
      ],
      "sources": [
        "INTAKE:a5_harm_pathways"
      ],
      "authorities": [
        "11 CCR § 7152",
        "11 CCR § 7154"
      ]
    },
    {
      "block_key": "executive_summary:6",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "executive_summary:7",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "benefit_strip"
      ],
      "sources": [
        "FACTOR:benefit_weight_table"
      ],
      "authorities": [
        "11 CCR § 7152(a)(4)"
      ]
    },
    {
      "block_key": "executive_summary:8",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "lead",
      "fixed_text_prefix": null,
      "factor_ids": [
        "exec_determination"
      ],
      "sources": [
        "FACTOR:balancing_table"
      ],
      "authorities": [
        "11 CCR § 7154"
      ]
    },
    {
      "block_key": "executive_summary:9",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "recommended_outcome"
      ],
      "sources": [
        "FACTOR:balancing_table",
        "INTAKE:processing_status"
      ],
      "authorities": [
        "11 CCR § 7152(a)(7)",
        "11 CCR § 7154"
      ]
    },
    {
      "block_key": "executive_summary:10",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "conditions_compact"
      ],
      "sources": [
        "FACTOR:conditions_to_proceed"
      ],
      "authorities": []
    },
    {
      "block_key": "executive_summary:11",
      "section_id": "executive_summary",
      "section_title": "Executive Summary",
      "kind": "skeleton",
      "fixed_text_prefix": "The appendices to this report preserve the complete supporting record behind this summary — the data inventory, the full risk and safeguard register, the automa",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "i_method:0",
      "section_id": "i_method",
      "section_title": "1. How This Assessment Decides",
      "kind": "skeleton",
      "fixed_text_prefix": "A. The Question. Sections 7152 and 7154 of 11 CCR frame a single question: do the privacy risks that this processing creates for consumers outweigh the benefits",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "i_method:1",
      "section_id": "i_method",
      "section_title": "1. How This Assessment Decides",
      "kind": "skeleton",
      "fixed_text_prefix": "B. The EndUserPrivacy (EUP) Decision Logic. This assessment follows a five-step process to analyze whether the benefits of the Activity outweigh the risks it po",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "i_method:2",
      "section_id": "i_method",
      "section_title": "1. How This Assessment Decides",
      "kind": "skeleton",
      "fixed_text_prefix": "Step 1 — Triggers. The Activity is tested against the significant-risk categories of § 7150(b); if none applies, no assessment is required and the analysis ends",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "i_method:3",
      "section_id": "i_method",
      "section_title": "1. How This Assessment Decides",
      "kind": "skeleton",
      "fixed_text_prefix": "Step 2 — Necessity. Each element of personal information is measured for its processing necessity for the Activity (§ 7152(a)(2)).",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "i_method:4",
      "section_id": "i_method",
      "section_title": "1. How This Assessment Decides",
      "kind": "skeleton",
      "fixed_text_prefix": "Step 3 — Inherent risk. Each risk the Company identifies is weighted in terms of likelihood and severity.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "i_method:5",
      "section_id": "i_method",
      "section_title": "1. How This Assessment Decides",
      "kind": "skeleton",
      "fixed_text_prefix": "Step 4 — Safeguard mitigation. The type and implementation status of the safeguards identified by the Company are assessed against the corresponding risks.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "i_method:6",
      "section_id": "i_method",
      "section_title": "1. How This Assessment Decides",
      "kind": "skeleton",
      "fixed_text_prefix": "Step 5 — The balance. The strongest benefit established is weighed against the most serious risk remaining after safeguards; every benefit and every remaining r",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "i_method:7",
      "section_id": "i_method",
      "section_title": "1. How This Assessment Decides",
      "kind": "skeleton",
      "fixed_text_prefix": "C. Qualitative Refinement. The assessment also considers any additional information supplied by the Company to refine the conclusions reached through the steps ",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:0",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "skeleton",
      "fixed_text_prefix": "[Q] What is being processed, about whom, and why — in the Company’s own words.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:1",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "skeleton",
      "fixed_text_prefix": "A. Purpose and Scope. The Purpose, as the Company states it in the Executive Summary, governs every analysis that follows. {customerVoiceIntro}",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:2",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "customer_voice",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:3",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "skeleton",
      "fixed_text_prefix": "Governing requirement. Section 7152(a)(1) requires the assessment to state the Company’s purpose with enough specificity to evaluate the processing; generic pur",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:4",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "purpose_specificity_analysis"
      ],
      "sources": [
        "INTAKE:purpose_specificity_facts"
      ],
      "authorities": [
        "11 CCR § 7152(a)(1)"
      ]
    },
    {
      "block_key": "ii_information:5",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "skeleton",
      "fixed_text_prefix": "This assessment covers processing undertaken for the Purpose. Section 7156 permits one assessment to cover a comparable set of activities only when they are sim",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:6",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:7",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "skeleton",
      "fixed_text_prefix": "B. How the Processing Operates. This part records the processing end to end, as the Company itself describes it.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:8",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "skeleton",
      "fixed_text_prefix": "Governing requirement. Section 7152(a)(3)(A) requires the report to identify how the Company collects, uses, discloses, retains, and otherwise processes the inf",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:9",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "operational_sequence"
      ],
      "sources": [
        "INTAKE:processing_entry_point",
        "INTAKE:processing_methods",
        "INTAKE:processing_result"
      ],
      "authorities": [
        "11 CCR § 7152(a)(3)(A)"
      ]
    },
    {
      "block_key": "ii_information:10",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "consumer_context"
      ],
      "sources": [
        "INTAKE:approximate_ca_consumers",
        "INTAKE:bought_sold_shared_count",
        "INTAKE:consumer_interaction_method",
        "INTAKE:consumer_interaction_purpose",
        "INTAKE:consumer_relationship_context",
        "INTAKE:i3_ca_consumer_band",
        "INTAKE:i4b_sources"
      ],
      "authorities": [
        "11 CCR § 7152(a)(3)(C)",
        "11 CCR § 7152(a)(3)(D)"
      ]
    },
    {
      "block_key": "ii_information:11",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "information_profile"
      ],
      "sources": [
        "INTAKE:q15_sensitive_pi",
        "INTAKE:q15b_under16_knowledge",
        "INTAKE:q15c_spi_volume",
        "INTAKE:q17_sensitive_basis",
        "INTAKE:q4_pi_categories"
      ],
      "authorities": [
        "11 CCR § 7152(a)(2)"
      ]
    },
    {
      "block_key": "ii_information:12",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "skeleton",
      "fixed_text_prefix": "For reference against the statutory taxonomy, each personal-information category the Company identifies is mapped to its canonical California category as follow",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:13",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "sources_analysis"
      ],
      "sources": [
        "INTAKE:i4b_sources",
        "INTAKE:source_categories"
      ],
      "authorities": [
        "11 CCR § 7152(a)(3)(A)"
      ]
    },
    {
      "block_key": "ii_information:14",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "skeleton",
      "fixed_text_prefix": "F. Recipients and Disclosures. A disclosure can change the risk profile because another organization may use, secure, retain, or further disclose the informatio",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:15",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "skeleton",
      "fixed_text_prefix": "Governing requirement. Section 7152(a)(3)(F) requires the report to identify the service providers, contractors, and third parties that receive or can access th",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:16",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [
        "recipients_summary"
      ],
      "sources": [
        "INTAKE:recipients"
      ],
      "authorities": [
        "11 CCR § 7152(a)(3)(F)"
      ]
    },
    {
      "block_key": "ii_information:17",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:18",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "recipient_consequences"
      ],
      "sources": [
        "INTAKE:essential_vendors",
        "INTAKE:q5_sell_share",
        "INTAKE:recipients",
        "INTAKE:vendor_dependency"
      ],
      "authorities": [
        "11 CCR § 7152(a)(3)(F)"
      ]
    },
    {
      "block_key": "ii_information:19",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "skeleton",
      "fixed_text_prefix": "G. Retention. How long the information is kept determines how long each risk this report identifies remains live.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:20",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "skeleton",
      "fixed_text_prefix": "Governing requirement. Section 7152(a)(3)(B) requires the report to identify how long each category of personal information will be retained or, if the period i",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:21",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:22",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "retention_basis"
      ],
      "sources": [
        "INTAKE:i2_retention_criteria",
        "INTAKE:i2_retention_period",
        "INTAKE:retention_by_pi_category"
      ],
      "authorities": [
        "11 CCR § 7152(a)(3)(B)"
      ]
    },
    {
      "block_key": "ii_information:23",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "prior_assessments"
      ],
      "sources": [
        "INTAKE:i9_existing_dpia_summary",
        "INTAKE:i9_has_existing_dpia"
      ],
      "authorities": [
        "11 CCR § 7156(b)"
      ]
    },
    {
      "block_key": "ii_information:24",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "skeleton",
      "fixed_text_prefix": "Sections 7151 and 7152(a)(8) require the assessment to identify the individuals who provided information for it (other than legal counsel who provided legal adv",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "ii_information:25",
      "section_id": "ii_information",
      "section_title": "2. The Information Provided",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "record_providers"
      ],
      "sources": [
        "INTAKE:a8_information_providers",
        "INTAKE:i7_external_consultees",
        "INTAKE:i7_internal_contributors",
        "INTAKE:section_7151_operational_participants"
      ],
      "authorities": [
        "11 CCR § 7151",
        "11 CCR § 7152(a)(8)"
      ]
    },
    {
      "block_key": "iii_analysis:0",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "skeleton",
      "fixed_text_prefix": "[Q] Does the Company’s account satisfy each element the regulation tests?",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iii_analysis:1",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "skeleton",
      "fixed_text_prefix": "Each part of this section applies one element of the regulatory test to the information provided by the Company: the rule first, then the facts read against the",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iii_analysis:2",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "skeleton",
      "fixed_text_prefix": "A. The Triggers, Applied. The threshold question is whether the Activity falls within a category the regulation treats as presenting significant risk to consume",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iii_analysis:3",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "skeleton",
      "fixed_text_prefix": "Governing requirement. Section 7150(b) enumerates the processing activities that present significant risk to consumers’ privacy.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iii_analysis:4",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "trigger_application"
      ],
      "sources": [
        "DERIVED:applicable_7150_triggers"
      ],
      "authorities": [
        "11 CCR § 7150(b)"
      ]
    },
    {
      "block_key": "iii_analysis:5",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "necessity_landing"
      ],
      "sources": [
        "INTAKE:a2_necessity_set"
      ],
      "authorities": [
        "11 CCR § 7152(a)(2)"
      ]
    },
    {
      "block_key": "iii_analysis:6",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iii_analysis:7",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "necessity_supported",
        "necessity_unsupported"
      ],
      "sources": [
        "INTAKE:a2_necessity_set"
      ],
      "authorities": [
        "11 CCR § 7152(a)(2)"
      ]
    },
    {
      "block_key": "iii_analysis:8",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "lead",
      "fixed_text_prefix": null,
      "factor_ids": [
        "necessity_conclusion"
      ],
      "sources": [
        "INTAKE:a2_necessity_set"
      ],
      "authorities": [
        "11 CCR § 7152(a)(2)"
      ]
    },
    {
      "block_key": "iii_analysis:9",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "skeleton",
      "fixed_text_prefix": "C. Transparency, Expectations, and Choice Architecture. What consumers are told, what they would reasonably expect, and what they can practically refuse shape t",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iii_analysis:10",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "skeleton",
      "fixed_text_prefix": "Governing requirement. Section 7152(a)(3)(E) requires the report to identify the disclosures the Company has made or plans to make; § 7152(a)(5)(C) treats insuf",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iii_analysis:11",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "notice_application"
      ],
      "sources": [
        "INTAKE:activity_disclosures",
        "INTAKE:q11_policy_review",
        "INTAKE:q12_notice_at_collection",
        "INTAKE:q13_notice_content"
      ],
      "authorities": [
        "11 CCR § 7152(a)(3)(E)",
        "11 CCR § 7152(a)(5)(C)"
      ]
    },
    {
      "block_key": "iii_analysis:12",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "expectation_application"
      ],
      "sources": [
        "INTAKE:expectation_check",
        "INTAKE:q12_notice_at_collection",
        "INTAKE:q13_notice_content"
      ],
      "authorities": [
        "11 CCR § 7152(a)(5)(C)"
      ]
    },
    {
      "block_key": "iii_analysis:13",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "choice_architecture"
      ],
      "sources": [
        "INTAKE:choice_architecture_check"
      ],
      "authorities": [
        "11 CCR § 7152(a)(5)(D)"
      ]
    },
    {
      "block_key": "iii_analysis:14",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "skeleton",
      "fixed_text_prefix": "D. Practical Consumer Control. A consumer right reduces risk only where the consumer can use it in practice and exercising it meaningfully changes the processin",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iii_analysis:15",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iii_analysis:16",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "controls_application"
      ],
      "sources": [
        "INTAKE:q10_id_verification",
        "INTAKE:q16_sensitive_limit",
        "INTAKE:q20_admt_opt_out",
        "INTAKE:q6_right_know",
        "INTAKE:q7_right_delete",
        "INTAKE:q8_right_correct",
        "INTAKE:q9_opt_out"
      ],
      "authorities": [
        "11 CCR § 7152(a)(5)(C)"
      ]
    },
    {
      "block_key": "iii_analysis:17",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [
        "admt_intro"
      ],
      "sources": [
        "INTAKE:q18_admt_use"
      ],
      "authorities": [
        "11 CCR § 7152(a)(3)(G)"
      ]
    },
    {
      "block_key": "iii_analysis:18",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "admt_role"
      ],
      "sources": [
        "INTAKE:admt_operational_role",
        "INTAKE:admt_role_type",
        "INTAKE:q19_admt_description"
      ],
      "authorities": [
        "11 CCR § 7152(a)(3)(G)"
      ]
    },
    {
      "block_key": "iii_analysis:19",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "admt_human_review"
      ],
      "sources": [
        "INTAKE:human_review_facts",
        "INTAKE:i5_admt_human_review"
      ],
      "authorities": [
        "11 CCR § 7001(e)",
        "11 CCR § 7150(b)(3)"
      ]
    },
    {
      "block_key": "iii_analysis:20",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "admt_logic_note",
        "admt_testing_analysis",
        "admt_training_note"
      ],
      "sources": [
        "INTAKE:admt_logic_documented",
        "INTAKE:admt_testing_facts",
        "INTAKE:i5_admt_training_source"
      ],
      "authorities": [
        "11 CCR § 7150(b)(6)",
        "11 CCR § 7152(a)(3)(G)(i)",
        "11 CCR § 7152(a)(5)(B)",
        "11 CCR § 7152(a)(6)(A)(iv)",
        "11 CCR § 7153"
      ]
    },
    {
      "block_key": "iii_analysis:21",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "lead",
      "fixed_text_prefix": null,
      "factor_ids": [
        "admt_conclusion"
      ],
      "sources": [
        "FACTOR:admt_human_review",
        "FACTOR:admt_testing_analysis",
        "INTAKE:q19_admt_description"
      ],
      "authorities": [
        "11 CCR § 7152(a)(3)(G)"
      ]
    },
    {
      "block_key": "iii_analysis:22",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "skeleton",
      "fixed_text_prefix": "F. Benefits. Section 7152(a)(4) requires the assessment to identify the benefits the processing produces for the consumer, the business, other stakeholders, and",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iii_analysis:23",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "benefit_paragraphs"
      ],
      "sources": [
        "FACTOR:benefit_weight_table",
        "INTAKE:a4_benefit_business",
        "INTAKE:a4_benefit_consumer",
        "INTAKE:a4_benefit_other_stakeholders",
        "INTAKE:a4_benefit_public"
      ],
      "authorities": [
        "11 CCR § 7152(a)(4)"
      ]
    },
    {
      "block_key": "iii_analysis:24",
      "section_id": "iii_analysis",
      "section_title": "3. Analysis",
      "kind": "lead",
      "fixed_text_prefix": null,
      "factor_ids": [
        "benefits_conclusion"
      ],
      "sources": [
        "FACTOR:benefit_weight_table"
      ],
      "authorities": [
        "11 CCR § 7152(a)(4)"
      ]
    },
    {
      "block_key": "iv_determination:0",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "risk_ledger_landing"
      ],
      "sources": [
        "INTAKE:a5_harm_pathways"
      ],
      "authorities": [
        "11 CCR § 7152(a)(5)",
        "11 CCR § 7152(a)(6)"
      ]
    },
    {
      "block_key": "iv_determination:1",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iv_determination:2",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "risk_paragraphs"
      ],
      "sources": [
        "INTAKE:a5_harm_pathways",
        "INTAKE:a6_safeguards",
        "INTAKE:risk_interdependency_check"
      ],
      "authorities": [
        "11 CCR § 7152(a)(5)",
        "11 CCR § 7152(a)(6)"
      ]
    },
    {
      "block_key": "iv_determination:3",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "risk_rollup"
      ],
      "sources": [
        "INTAKE:a5_harm_pathways",
        "INTAKE:a6_safeguards"
      ],
      "authorities": [
        "11 CCR § 7152(a)(5)",
        "11 CCR § 7152(a)(6)"
      ]
    },
    {
      "block_key": "iv_determination:4",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "skeleton",
      "fixed_text_prefix": "B. What Weighs For, and What Weighs Against. The considerations below are those reached in Sections 2 and 3 and the ledger above — stated here by reference, in ",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iv_determination:5",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "factors_for"
      ],
      "sources": [
        "FACTOR:benefit_weight_table",
        "FACTOR:necessity_conclusion"
      ],
      "authorities": [
        "11 CCR § 7154"
      ]
    },
    {
      "block_key": "iv_determination:6",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "factors_against"
      ],
      "sources": [
        "FACTOR:necessity_conclusion",
        "FACTOR:residual_rule"
      ],
      "authorities": [
        "11 CCR § 7154"
      ]
    },
    {
      "block_key": "iv_determination:7",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "skeleton",
      "fixed_text_prefix": "C. The Determination. The determination weighs the strongest benefit established (§ 3.F) against the most serious risk remaining (§ 4.A), on the information pro",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iv_determination:8",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iv_determination:9",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "determination_text"
      ],
      "sources": [
        "FACTOR:balancing_table",
        "FACTOR:benefit_weight_table",
        "FACTOR:residual_rule",
        "INTAKE:final_processing_decision",
        "INTAKE:impact_intake.benefitsOutweigh"
      ],
      "authorities": [
        "11 CCR § 7152(a)(7)",
        "11 CCR § 7154"
      ]
    },
    {
      "block_key": "iv_determination:10",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iv_determination:11",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "skeleton",
      "fixed_text_prefix": "D. Conditions, Follow-Ups, and Recommendations. The determination above depends on the conditions stated here; the follow-ups complete the information provided;",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iv_determination:12",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "conditions_to_proceed"
      ],
      "sources": [
        "FACTOR:balancing_table",
        "FACTOR:necessity_conclusion",
        "FACTOR:planned_safeguards",
        "FACTOR:safeguard_gaps"
      ],
      "authorities": [
        "11 CCR § 7154"
      ]
    },
    {
      "block_key": "iv_determination:13",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "required_assessment_follow_up"
      ],
      "sources": [
        "DERIVED:record_complete",
        "FACTOR:uncertain_elements"
      ],
      "authorities": []
    },
    {
      "block_key": "iv_determination:14",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "iv_determination:15",
      "section_id": "iv_determination",
      "section_title": "4. The Balance and the Determination",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:0",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "skeleton",
      "fixed_text_prefix": "[Q] Who approved this assessment, when must it be revisited, and what must be submitted to the regulator?",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:1",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:2",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "approval_follow_up",
        "approval_sufficiency_conclusion"
      ],
      "sources": [
        "FINAL:approver_authority_confirmed",
        "FINAL:assessment_reviewers_approvers"
      ],
      "authorities": [
        "11 CCR § 7152(a)(9)"
      ]
    },
    {
      "block_key": "v_governance:3",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "skeleton",
      "fixed_text_prefix": "B. Timing and the Applicable Deadline. Whether this assessment is timely depends on when the covered processing began or will begin. Processing status: {process",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:4",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "skeleton",
      "fixed_text_prefix": "Governing requirement. Section 7155(a)(1) requires a risk assessment before the Company initiates processing that falls within § 7150(b). Section 7155(b) gives ",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:5",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:6",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "skeleton",
      "fixed_text_prefix": "C. Review Cadence and Material Changes. An assessment is not static: it must be revisited on a schedule, and sooner where the processing materially changes. Mat",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:7",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "skeleton",
      "fixed_text_prefix": "Governing requirement. Section 7155(a)(2) requires review at least once every three years. Section 7155(a)(3) requires an earlier update whenever a material cha",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:8",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:9",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [
        "review_cadence"
      ],
      "sources": [
        "INTAKE:i9_has_existing_dpia",
        "INTAKE:material_change_date",
        "INTAKE:material_change_since_prior",
        "SYSTEM:assessment_date"
      ],
      "authorities": [
        "11 CCR § 7155"
      ]
    },
    {
      "block_key": "v_governance:10",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "skeleton",
      "fixed_text_prefix": "D. Retention of the Assessment Record. This report and its supporting materials are themselves records the Company must keep.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:11",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "skeleton",
      "fixed_text_prefix": "Governing requirement. Section 7155(c) requires the Company to retain original and updated risk assessments for as long as the processing continues or for five ",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:12",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "skeleton",
      "fixed_text_prefix": "{retentionEndRule}. Supporting materials should be retained with the assessment where they are material to a finding, safeguard, or decision.",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:13",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "skeleton",
      "fixed_text_prefix": "E. CPPA Submission Support (§ 7157). Section 7157 requires businesses to submit specified risk-assessment information to the Agency on the regulatory schedule r",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:14",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "v_governance:15",
      "section_id": "v_governance",
      "section_title": "5. Governance, Review, and Submission",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "review_and_approval:0",
      "section_id": "review_and_approval",
      "section_title": "Review and Approval",
      "kind": "skeleton",
      "fixed_text_prefix": "This risk assessment was prepared from the information the Company supplied and is retained in accordance with 11 CCR § 7155(c). The individuals below record th",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "review_and_approval:1",
      "section_id": "review_and_approval",
      "section_title": "Review and Approval",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "agency_submission_checklist:0",
      "section_id": "agency_submission_checklist",
      "section_title": "Agency Submission Checklist (11 CCR § 7157)",
      "kind": "skeleton",
      "fixed_text_prefix": "If this risk assessment is subject to the submission requirement under 11 CCR § 7157(a), a member of the Company’s executive management team who meets the quali",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "agency_submission_checklist:1",
      "section_id": "agency_submission_checklist",
      "section_title": "Agency Submission Checklist (11 CCR § 7157)",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "agency_submission_checklist:2",
      "section_id": "agency_submission_checklist",
      "section_title": "Agency Submission Checklist (11 CCR § 7157)",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "agency_submission_checklist:3",
      "section_id": "agency_submission_checklist",
      "section_title": "Agency Submission Checklist (11 CCR § 7157)",
      "kind": "skeleton",
      "fixed_text_prefix": "The submitting executive must additionally attest, on the Agency’s portal, to the following statement required by § 7157(b)(5): \"I attest that the business has ",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "table_of_authorities:0",
      "section_id": "table_of_authorities",
      "section_title": "Appendix A — Factor, Determination, and Authority Matrix",
      "kind": "skeleton",
      "fixed_text_prefix": "The table below identifies the factors analyzed in this assessment, the determinations made for each factor based on the information provided, and the correspon",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "table_of_authorities:1",
      "section_id": "table_of_authorities",
      "section_title": "Appendix A — Factor, Determination, and Authority Matrix",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_i:0",
      "section_id": "appendix_i",
      "section_title": "Appendix B — Persuasive Authority (Analogous Enforcement)",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_i:1",
      "section_id": "appendix_i",
      "section_title": "Appendix B — Persuasive Authority (Analogous Enforcement)",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_i:2",
      "section_id": "appendix_i",
      "section_title": "Appendix B — Persuasive Authority (Analogous Enforcement)",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_i:3",
      "section_id": "appendix_i",
      "section_title": "Appendix B — Persuasive Authority (Analogous Enforcement)",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_i:4",
      "section_id": "appendix_i",
      "section_title": "Appendix B — Persuasive Authority (Analogous Enforcement)",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_a:0",
      "section_id": "appendix_a",
      "section_title": "Appendix C — Processing and Data Inventory",
      "kind": "skeleton",
      "fixed_text_prefix": "This appendix contains the detailed factual inventory supporting Section 2, including personal-information and sensitive-personal-information categories, source",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_a:1",
      "section_id": "appendix_a",
      "section_title": "Appendix C — Processing and Data Inventory",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_c:0",
      "section_id": "appendix_c",
      "section_title": "Appendix D — Privacy Risk Register and Safeguard Mapping",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_c:1",
      "section_id": "appendix_c",
      "section_title": "Appendix D — Privacy Risk Register and Safeguard Mapping",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_d:0",
      "section_id": "appendix_d",
      "section_title": "Appendix E — ADMT Technical and Decision Record",
      "kind": "conditional",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_d:1",
      "section_id": "appendix_d",
      "section_title": "Appendix E — ADMT Technical and Decision Record",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_d:2",
      "section_id": "appendix_d",
      "section_title": "Appendix E — ADMT Technical and Decision Record",
      "kind": "generated",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_f:0",
      "section_id": "appendix_f",
      "section_title": "Appendix F — Materials Considered",
      "kind": "skeleton",
      "fixed_text_prefix": "This appendix lists the documents, technical materials, policies, contracts, assessments, and other factual materials identified or relied on for this assessmen",
      "factor_ids": [],
      "sources": [],
      "authorities": []
    },
    {
      "block_key": "appendix_f:1",
      "section_id": "appendix_f",
      "section_title": "Appendix F — Materials Considered",
      "kind": "table",
      "fixed_text_prefix": null,
      "factor_ids": [],
      "sources": [],
      "authorities": []
    }
  ]
};
