import PillarPage from "@/components/PillarPage";

const GlobalPrivacyLaws = () => (
  <PillarPage
    updateCategory="global"
    title="Global Privacy Laws"
    subtitle="Comparative guide to privacy regulation outside the U.S. and EU, covering APAC, Latin America, Middle East, and Africa frameworks."
    icon="🌐"
    lastUpdated="March 7, 2026"
    intro="Data protection and privacy regulation has become a global phenomenon, with over 140 countries having enacted some form of data protection legislation. While the EU's GDPR remains the most influential framework, jurisdictions across Asia-Pacific, Latin America, the Middle East, and Africa have developed their own approaches — some closely aligned with GDPR, others reflecting distinct regulatory philosophies. This guide provides a comparative overview of major privacy frameworks outside the United States and European Union."
    sections={[
      {
        heading: "Asia-Pacific Privacy Frameworks",
        content: `The APAC region presents the most diverse privacy regulatory landscape. Japan's <a href="https://www.ppc.go.jp/en/legal/" target="_blank" rel="noopener noreferrer">Act on Protection of Personal Information (APPI)</a>, amended in 2022, includes cross-border transfer restrictions and an adequacy arrangement with the EU. South Korea's <a href="https://www.pipc.go.kr/eng/user/lgp/law/personalInfoProtectionAct.do" target="_blank" rel="noopener noreferrer">Personal Information Protection Act (PIPA)</a> is among the strictest globally, with the <a href="https://www.pipc.go.kr/eng/" target="_blank" rel="noopener noreferrer">Personal Information Protection Commission (PIPC)</a> imposing significant fines, including a ₩5.6 billion penalty against Kakao Corp in 2026. Singapore's <a href="https://www.pdpc.gov.sg/Overview-of-PDPA/The-Legislation/Personal-Data-Protection-Act" target="_blank" rel="noopener noreferrer">Personal Data Protection Act (PDPA)</a> takes a consent-based approach with mandatory breach notification. Australia's <a href="https://www.legislation.gov.au/C2004A03712/latest" target="_blank" rel="noopener noreferrer">Privacy Act 1988</a> is undergoing significant reform following a 2023 review recommending stronger individual rights. India's <a href="https://www.meity.gov.in/static/uploads/2024/06/2bf1f0e9f04e6fb4f8fef35e82c42aa5.pdf" target="_blank" rel="noopener noreferrer">Digital Personal Data Protection Act (2023)</a> establishes a consent-based framework with a new Data Protection Board. China's <a href="http://en.npc.gov.cn.cdurl.cn/2021-12/29/c_694559.htm" target="_blank" rel="noopener noreferrer">Personal Information Protection Law (PIPL)</a> imposes strict data localization and cross-border transfer requirements.`
      },
      {
        heading: "Latin American Frameworks",
        content: `Latin America's privacy landscape is anchored by Brazil's <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" target="_blank" rel="noopener noreferrer">LGPD (Lei Geral de Proteção de Dados)</a>, which closely mirrors the GDPR in structure and rights. Brazil's <a href="https://www.gov.br/anpd/pt-br" target="_blank" rel="noopener noreferrer">ANPD</a> issued guidance in March 2026 establishing standard contractual clauses for international data transfers. Argentina's <a href="https://servicios.infoleg.gob.ar/infolegInternet/anexos/60000-64999/64790/norma.htm" target="_blank" rel="noopener noreferrer">Personal Data Protection Law (Ley 25.326)</a> predates GDPR and maintains an EU adequacy determination. Mexico's <a href="https://www.diputados.gob.mx/LeyesBiblio/pdf/LFPDPPP.pdf" target="_blank" rel="noopener noreferrer">Federal Law on Protection of Personal Data Held by Private Parties</a> is enforced by <a href="https://home.inai.org.mx/" target="_blank" rel="noopener noreferrer">INAI</a>, though the agency has faced institutional challenges. <a href="https://www.sic.gov.co/proteccion-de-datos-personales" target="_blank" rel="noopener noreferrer">Colombia</a>, <a href="https://www.bcn.cl/leychile/navegar?idNorma=141599" target="_blank" rel="noopener noreferrer">Chile</a>, and <a href="https://www.gob.pe/institucion/minjus/normas-legales/243470-29733" target="_blank" rel="noopener noreferrer">Peru</a> have enacted or modernized data protection laws with varying degrees of enforcement activity.`
      },
      {
        heading: "Middle East and Africa",
        content: `The Middle East and Africa represent the fastest-growing regions for privacy regulation. The UAE has multiple frameworks including the <a href="https://u.ae/en/about-the-uae/digital-uae/data/data-protection-laws" target="_blank" rel="noopener noreferrer">federal Personal Data Protection Law</a> and <a href="https://www.difc.ae/business/laws-regulations/legal-database/data-protection-law-difc-law-no-5-2020" target="_blank" rel="noopener noreferrer">DIFC</a>/<a href="https://en.adgm.thomsonreuters.com/rulebook/data-protection-regulations-2021" target="_blank" rel="noopener noreferrer">ADGM</a> regulations in financial free zones. Saudi Arabia's <a href="https://sdaia.gov.sa/en/SDAIA/about/Files/PersonalDataEnglish.pdf" target="_blank" rel="noopener noreferrer">Personal Data Protection Law</a>, enforced by <a href="https://sdaia.gov.sa/en/" target="_blank" rel="noopener noreferrer">SDAIA</a>, applies broadly to data processing within the Kingdom. South Africa's <a href="https://www.gov.za/documents/protection-personal-information-act" target="_blank" rel="noopener noreferrer">Protection of Personal Information Act (POPIA)</a>, enforced by the <a href="https://inforegulator.org.za/" target="_blank" rel="noopener noreferrer">Information Regulator</a>, has been in full effect since 2021 with increasing enforcement activity. <a href="https://ndpc.gov.ng/" target="_blank" rel="noopener noreferrer">Nigeria</a>, <a href="https://www.odpc.go.ke/" target="_blank" rel="noopener noreferrer">Kenya</a>, <a href="https://www.dpc.gov.eg/" target="_blank" rel="noopener noreferrer">Egypt</a>, and <a href="https://www.dataprotection.org.gh/" target="_blank" rel="noopener noreferrer">Ghana</a> have enacted data protection laws, though enforcement capacity varies significantly across the continent.`
      },
      {
        heading: "Cross-Border Data Transfers",
        content: `International data transfers remain one of the most challenging compliance areas. Approaches vary from the EU's <a href="https://commission.europa.eu/law/law-topic/data-protection/international-dimension-data-protection/adequacy-decisions_en" target="_blank" rel="noopener noreferrer">adequacy decisions</a> and <a href="https://commission.europa.eu/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en" target="_blank" rel="noopener noreferrer">standard contractual clauses</a>, to <a href="https://www.apec.org/groups/committee-on-trade-and-investment/digital-economy-steering-group/cross-border-privacy-rules-system" target="_blank" rel="noopener noreferrer">APEC's Cross-Border Privacy Rules (CBPR)</a>, to data localization requirements in jurisdictions like China, India, and Russia. The proliferation of national data protection laws has created a complex web of transfer requirements. Key developments include: Brazil's SCC framework (March 2026), <a href="https://www.ppc.go.jp/en/enforcement/cooperation/EU/" target="_blank" rel="noopener noreferrer">Japan-EU mutual adequacy</a>, the <a href="https://www.dataprivacyframework.gov/" target="_blank" rel="noopener noreferrer">EU-US Data Privacy Framework</a>, and increasing use of <a href="https://www.edpb.europa.eu/our-work-tools/our-documents/recommendations/recommendations-12022-application-article-25-3-and_en" target="_blank" rel="noopener noreferrer">binding corporate rules</a> for multinational organizations.`
      },
      {
        heading: "Trends in Global Privacy Regulation",
        content: "Several trends are shaping the global privacy landscape: the global spread of GDPR-style legislation continues with new laws in the Middle East and Africa; AI-specific provisions are being integrated into privacy frameworks worldwide; children's privacy is receiving heightened attention across jurisdictions; enforcement activity is accelerating in previously low-activity jurisdictions; cross-border cooperation between DPAs is increasing; and data localization requirements are expanding, particularly in Asia and the Middle East. Organizations operating globally must maintain awareness of this rapidly evolving regulatory environment."
      },
    ]}
    relatedLinks={[
      { label: "Global Privacy Authority Directory", href: "/global-privacy-authorities" },
      { label: "GDPR Enforcement", href: "/gdpr-enforcement" },
      { label: "AI Privacy Regulations", href: "/ai-privacy-regulations" },
      { label: "Enforcement Tracker", href: "/enforcement-tracker" },
    ]}
    directoryLink={{ label: "Browse All Global Authorities", href: "/global-privacy-authorities" }}
  />
);

export default GlobalPrivacyLaws;
