// Public /samples hub — lists every tool with published sample reports.
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { FileText } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { TOOL_ROUTE } from "@/lib/sampleToolRoutes";
import { useConversionEvent } from "@/hooks/useConversionEvent";

type SampleRow = {
  id: string;
  tool_slug: string;
  variant: string;
  title: string;
  scenario_summary: string | null;
};

const TOOL_DISPLAY: Record<string, string> = {
  li_assessment: "Legitimate Interests Assessment",
  dpia: "Impact Assessment Builder",
  dpa: "Data Processing Agreement",
  governance: "Governance Assessment",
  ir_playbook: "Incident Response Playbook",
  biometric: "Biometric Compliance Check",
  cppa_risk: "CPPA Risk Assessment",
  cppa_cyber: "CPPA Cybersecurity Audit",
  ropa: "Record of Processing Activities (RoPA)",
  us_notice: "US State Privacy Notice",
  eu_notice: "EU / Global Privacy Notice",
};

type Grouped = {
  toolSlug: string;
  displayName: string;
  toolRoute?: string;
  firstScenario: string | null;
  variants: SampleRow[];
};

export default function SamplesHub() {
  const [rows, setRows] = useState<SampleRow[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [selectedTool, setSelectedTool] = useState<string | null>(null);
  const [selectedVariant, setSelectedVariant] = useState<string | null>(null);
  const fireConversion = useConversionEvent();

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const { data, error } = await supabase
        .from("sample_reports")
        .select("id, tool_slug, variant, title, scenario_summary")
        .eq("status", "published")
        .order("tool_slug")
        .order("variant");
      if (cancelled) return;
      if (error) {
        setError(error.message);
        setRows([]);
        return;
      }
      setRows((data ?? []) as SampleRow[]);
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  // Distinct chip options derived from the already-loaded rows.
  const toolOptions = useMemo(() => {
    if (!rows) return [] as { slug: string; label: string }[];
    const seen = new Map<string, string>();
    for (const r of rows) {
      if (!seen.has(r.tool_slug)) {
        seen.set(r.tool_slug, TOOL_DISPLAY[r.tool_slug] ?? r.tool_slug);
      }
    }
    return Array.from(seen, ([slug, label]) => ({ slug, label })).sort((a, b) =>
      a.label.localeCompare(b.label),
    );
  }, [rows]);

  const variantOptions = useMemo(() => {
    if (!rows) return [] as string[];
    return Array.from(new Set(rows.map((r) => r.variant))).sort();
  }, [rows]);

  const filteredRows = useMemo(() => {
    if (!rows) return [] as SampleRow[];
    return rows.filter(
      (r) =>
        (!selectedTool || r.tool_slug === selectedTool) &&
        (!selectedVariant || r.variant === selectedVariant),
    );
  }, [rows, selectedTool, selectedVariant]);

  const grouped: Grouped[] = useMemo(() => {
    if (!rows) return [];
    const map = new Map<string, Grouped>();
    for (const r of filteredRows) {
      const existing = map.get(r.tool_slug);
      if (existing) {
        existing.variants.push(r);
      } else {
        map.set(r.tool_slug, {
          toolSlug: r.tool_slug,
          displayName: TOOL_DISPLAY[r.tool_slug] ?? r.tool_slug,
          toolRoute: TOOL_ROUTE[r.tool_slug],
          firstScenario: r.scenario_summary,
          variants: [r],
        });
      }
    }
    return Array.from(map.values()).sort((a, b) => a.displayName.localeCompare(b.displayName));
  }, [rows, filteredRows]);

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Helmet>
        <title>Sample Reports — See what you'll get | EndUserPrivacy</title>
        <meta
          name="description"
          content="Full-length sample reports generated by the same engines you'll use. Realistic fictional scenarios, unedited output. Browse before you run your own."
        />
        <link rel="canonical" href="https://enduserprivacy.com/samples" />
        <meta property="og:title" content="Sample Reports | EndUserPrivacy" />
        <meta property="og:url" content="https://enduserprivacy.com/samples" />
        <meta property="og:type" content="website" />
      </Helmet>

      <Navbar />

      {/* Hero */}
      <header className="bg-brand-navy text-white">
        <div className="max-w-[1280px] mx-auto px-4 sm:px-6 lg:px-8 py-14 md:py-20">
          <p className="text-xs uppercase tracking-[0.18em] text-brand-cloud mb-3">
            Sample Reports
          </p>
          <h1 className="font-display text-4xl md:text-5xl text-white mb-4 leading-tight">
            See exactly what you&apos;ll get
          </h1>
          <p className="text-slate-300 text-lg max-w-3xl leading-relaxed">
            Every report below was generated by the same engines you&apos;ll use — full-length,
            unedited, and built from realistic fictional scenarios. Open any sample, then start
            your own.
          </p>
          <div className="mt-6">
            <Link
              to="/tools"
              className="inline-flex items-center gap-2 rounded-md bg-amber-400 text-brand-navy px-5 py-2.5 text-sm font-bold hover:opacity-90 no-underline"
            >
              Generate your own report →
            </Link>
          </div>
        </div>
      </header>

      <main className="flex-1 max-w-[1280px] w-full mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {error && (
          <div className="rounded-md border border-destructive/40 bg-destructive/5 text-sm p-4 mb-6">
            Could not load samples: {error}
          </div>
        )}

        {rows === null && (
          <>
            {/* Filter row placeholder — reserves height to prevent CLS */}
            <div className="mb-6 space-y-3" aria-hidden>
              <div className="h-4 w-32 bg-muted/40 rounded mb-2" />
              <div className="h-8 w-full bg-muted/30 rounded" style={{ minHeight: 32 }} />
              <div className="h-4 w-40 bg-muted/40 rounded mb-2 mt-3" />
              <div className="h-8 w-full bg-muted/30 rounded" style={{ minHeight: 32 }} />
            </div>
            <div
              className="grid grid-cols-1 lg:grid-cols-2 gap-6"
              aria-label="Loading samples"
              aria-busy="true"
            >
              {Array.from({ length: 6 }).map((_, i) => (
                <div
                  key={i}
                  className="rounded-xl border border-brand-cloud bg-card p-6 md:p-7 shadow-sm animate-pulse"
                  style={{ minHeight: 220 }}
                >
                  <div className="h-6 w-2/3 bg-muted/50 rounded mb-3" />
                  <div className="h-4 w-full bg-muted/40 rounded mb-2" />
                  <div className="h-4 w-4/5 bg-muted/40 rounded mb-6" />
                  <div className="h-4 w-1/3 bg-muted/30 rounded" />
                </div>
              ))}
            </div>
          </>
        )}

        {rows !== null && grouped.length === 0 && (
          <div className="rounded-lg border border-brand-cloud bg-muted/30 p-8 text-center">
            <FileText className="h-8 w-8 mx-auto mb-3 text-muted-foreground" aria-hidden />
            <p className="font-medium text-brand-navy">Samples are being finalized. Check back shortly.</p>
          </div>
        )}

        {rows !== null && rows.length > 0 && (
          <div className="mb-6 space-y-3" aria-label="Sample filters">
            <div>
              <p className="text-body-tiny uppercase tracking-wider text-muted-foreground mb-2">Filter by tool</p>
              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={() => setSelectedTool(null)}
                  aria-pressed={selectedTool === null}
                  className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-medium transition-colors ${selectedTool === null ? "bg-brand-navy text-white border-brand-navy" : "border-brand-cloud bg-muted/40 text-brand-navy hover:bg-brand-cloud/60"}`}
                >
                  All tools
                </button>
                {toolOptions.map((t) => (
                  <button
                    key={t.slug}
                    type="button"
                    onClick={() => setSelectedTool(t.slug === selectedTool ? null : t.slug)}
                    aria-pressed={selectedTool === t.slug}
                    className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-medium transition-colors ${selectedTool === t.slug ? "bg-brand-navy text-white border-brand-navy" : "border-brand-cloud bg-muted/40 text-brand-navy hover:bg-brand-cloud/60"}`}
                  >
                    {t.label}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <p className="text-body-tiny uppercase tracking-wider text-muted-foreground mb-2">Filter by jurisdiction</p>
              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={() => setSelectedVariant(null)}
                  aria-pressed={selectedVariant === null}
                  className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-medium transition-colors ${selectedVariant === null ? "bg-brand-navy text-white border-brand-navy" : "border-brand-cloud bg-muted/40 text-brand-navy hover:bg-brand-cloud/60"}`}
                >
                  All types
                </button>
                {variantOptions.map((v) => (
                  <button
                    key={v}
                    type="button"
                    onClick={() => setSelectedVariant(v === selectedVariant ? null : v)}
                    aria-pressed={selectedVariant === v}
                    className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-medium uppercase transition-colors ${selectedVariant === v ? "bg-brand-navy text-white border-brand-navy" : "border-brand-cloud bg-muted/40 text-brand-navy hover:bg-brand-cloud/60"}`}
                  >
                    {v}
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}

        {rows !== null && rows.length > 0 && grouped.length === 0 && (
          <div className="rounded-lg border border-brand-cloud bg-muted/30 p-6 text-center text-sm text-muted-foreground mb-6">
            No samples match the selected filters.
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {grouped.map((g) => (
            <article
              key={g.toolSlug}
              className="rounded-xl border border-brand-cloud bg-card p-6 md:p-7 shadow-sm flex flex-col"
            >
              <header className="mb-3">
                <h2 className="font-display text-xl md:text-2xl text-brand-navy mb-1">
                  {g.displayName}
                </h2>
                {g.firstScenario && (
                  <p className="text-sm text-muted-foreground leading-6 line-clamp-2">
                    {g.firstScenario}
                  </p>
                )}
              </header>

              {g.variants.length > 0 && (
                <div className="mt-2 mb-4">
                  <p className="text-body-tiny uppercase tracking-wider text-muted-foreground mb-2">
                    Jurisdiction variants
                  </p>
                  <div className="flex flex-wrap gap-2">
                    {g.variants.map((v) => (
                      <Link
                        key={v.id}
                        to={`/samples/${g.toolSlug}/${v.variant}`}
                        className="inline-flex items-center rounded-full border border-brand-cloud bg-muted/40 px-3 py-1 text-xs font-medium text-brand-navy hover:bg-brand-cloud/60 no-underline"
                      >
                        {v.variant}
                      </Link>
                    ))}
                  </div>
                </div>
              )}

              <div className="mt-auto flex flex-wrap gap-4 items-center pt-4 border-t border-brand-cloud/60">
                <Link
                  to={`/samples/${g.toolSlug}`}
                  className="inline-flex items-center gap-1.5 text-sm font-semibold text-brand-teal-text hover:underline no-underline"
                >
                  <FileText className="h-4 w-4" aria-hidden /> View sample
                </Link>
                {g.toolRoute && (
                  <Link
                    to={g.toolRoute}
                    className="text-sm font-medium text-muted-foreground hover:text-brand-navy no-underline"
                  >
                    Start your own →
                  </Link>
                )}
              </div>
            </article>
          ))}
        </div>
      </main>

      <Footer />
    </div>
  );
}
