// /all-ptest fixture panel — eu-notice. Fifteen complete, internally consistent
// intakes authored 2026-09-14 (see ./types.ts and scripts/ptest/PANEL-BRIEF.md).
// Validated by tests/edge/ptest/panels.test.ts.
//
// Contract: supabase/functions/run-stress-job/_local/intake-contracts/eu-notice.ts
// (euNoticeContract). The intake is flat — run-stress-job writes one
// eu_notice_answers row per top-level key. `establishment_jurisdiction` drives
// whether run-stress-job also selects the UK GDPR framework (only "uk" does),
// so the panel is split between "eea"-established and "uk"-established
// controllers to exercise both. Every legal-entity suffix matches its
// country: GmbH -> Germany, B.V. -> Netherlands, Ltd -> Great Britain or
// Ireland, S.A./SAS -> France, AB -> Sweden, S.r.l. -> Italy, SE (Societas
// Europaea) -> any EU member state (here, Austria).

import type { PanelFixture } from "./types.ts";

export const PANEL_EU_NOTICE: PanelFixture[] = [
  {
    id: "eu-notice-p01-alpenklar-medtech-gmbh",
    tool: "eu-notice",
    label: "German remote patient-monitoring SaaS with human-reviewed alerts",
    company: "Alpenklar MedTech GmbH",
    sector: "Healthcare technology (remote patient monitoring)",
    geo: "eu",
    summary:
      "Alpenklar MedTech runs a remote patient-monitoring dashboard for Bavarian hospitals, mixing direct patient enrollment with device data from partner clinics. Exercises EU establishment, special-category health data on explicit consent, human-reviewed automated anomaly alerts, a mixed collection source, and a US cloud transfer under SCCs.",
    intake: {
      controller_name: "Alpenklar MedTech GmbH",
      entity_name: "Alpenklar MedTech GmbH",
      company_name: "Alpenklar MedTech GmbH",
      controller_address: "Leopoldstraße 244, 80807 München, Germany",
      contact_email: "privacy@alpenklarmedtech.example",
      dpo_details: "yes",
      dpo_name: "Dr. Insa Vogt",
      dpo_email: "dpo@alpenklarmedtech.example",
      processing_purposes: ["service_delivery", "security", "legal_compliance", "research"],
      data_categories: ["identifiers", "health_medical", "internet_activity"],
      special_category_basis: ["explicit_consent", "health_medicine"],
      lawful_basis: ["consent", "contract", "legal_obligation"],
      third_party_recipients: ["service_providers", "regulators"],
      transfer_outside_eea: "yes",
      transfer_safeguards: ["sccs"],
      transfer_destinations: "United States (cloud hosting subprocessor for encrypted vital-signs storage)",
      adequacy_status: "No adequacy decision covers the United States; the transfer relies on the EU Standard Contractual Clauses with supplementary encryption-at-rest measures.",
      retention_period: "Patient monitoring records are retained for 10 years after the last recorded reading, matching German medical-record retention rules (§ 630f BGB).",
      automated_decisions: "human_review",
      automated_decisions_detail: "The monitoring algorithm flags vital-sign readings outside a clinician-configured threshold as an urgent alert candidate, but a ward nurse or physician reviews every flagged reading and decides whether to contact the patient before any action is taken.",
      collection_source: "mixed",
      data_source_categories: ["partners"],
      establishment_jurisdiction: "eea",
      gdpr_dpo_mandatory: "mandatory_large_scale_special",
      gdpr_right_to_withdraw: "Where monitoring relies on consent, patients may withdraw it at any time by contacting their care team or dpo@alpenklarmedtech.example, without affecting readings already processed.",
      gdpr_right_to_object: "Patients may object to processing for research purposes at any time; opting out does not affect their ongoing clinical monitoring.",
      gdpr_dpa_contact: "Bayerisches Landesamt für Datenschutzaufsicht (BayLDA)",
      gdpr_profiling: "no",
    },
  },
  {
    id: "eu-notice-p02-nieuwpoort-logistics-bv",
    tool: "eu-notice",
    label: "Dutch freight-forwarder notice covering cross-border customs transfers",
    company: "Nieuwpoort Logistics B.V.",
    sector: "Freight forwarding and logistics",
    geo: "eu",
    summary:
      "Nieuwpoort Logistics coordinates cross-border freight for EU exporters and shares shipment data with UK and US customs brokers. Exercises EU establishment, no special-category data, no automated decisions, and a transfer outside the EEA under SCCs and the UK Addendum.",
    intake: {
      controller_name: "Nieuwpoort Logistics B.V.",
      entity_name: "Nieuwpoort Logistics B.V.",
      company_name: "Nieuwpoort Logistics B.V.",
      controller_address: "Keizersgracht 482, 1017 EG Amsterdam, Netherlands",
      contact_email: "privacy@nieuwpoortlogistics.example",
      dpo_details: "yes",
      dpo_name: "Femke Aalders",
      dpo_email: "dpo@nieuwpoortlogistics.example",
      processing_purposes: ["service_delivery", "legal_compliance", "security"],
      data_categories: ["identifiers", "commercial", "professional"],
      lawful_basis: ["contract", "legitimate_interests", "legal_obligation"],
      third_party_recipients: ["service_providers", "regulators", "affiliates"],
      transfer_outside_eea: "yes",
      transfer_safeguards: ["sccs", "uk_addendum"],
      transfer_destinations: "United Kingdom (customs broker) and United States (freight-tracking software vendor)",
      retention_period: "Shipment and customs records are retained for 7 years to satisfy EU and member-state customs-recordkeeping rules.",
      automated_decisions: "no",
      collection_source: "direct",
      establishment_jurisdiction: "eea",
      gdpr_dpo_mandatory: "voluntary",
      gdpr_right_to_withdraw: "Not applicable to consent-based processing, as Nieuwpoort's processing of shipment data relies on contract and legal obligation rather than consent.",
      gdpr_right_to_object: "Customers may object to processing based on legitimate interests, such as shipment-analytics reporting, by contacting dpo@nieuwpoortlogistics.example.",
      gdpr_dpa_contact: "Autoriteit Persoonsgegevens",
      gdpr_profiling: "no",
    },
  },
  {
    id: "eu-notice-p03-harrow-community-trust",
    tool: "eu-notice",
    label: "UK food-bank charity with no designated DPO and no overseas transfers",
    company: "Harrow Community Trust Ltd",
    sector: "Charity / community food-bank services",
    geo: "eu",
    summary:
      "Harrow Community Trust is a small registered charity running a UK food bank that has not designated a DPO because it is not legally required to. Exercises UK establishment (no overseas transfers), the non-profit-body and health special-category grounds for safeguarding referrals, and the dpo_details = no branch.",
    intake: {
      controller_name: "Harrow Community Trust Ltd",
      entity_name: "Harrow Community Trust Ltd",
      company_name: "Harrow Community Trust Ltd",
      controller_address: "14 Greenford Road, Harrow, London HA1 3QN, United Kingdom",
      contact_email: "privacy@harrowcommunitytrust.example",
      dpo_details: "no",
      processing_purposes: ["service_delivery", "legal_compliance"],
      data_categories: ["identifiers", "health_medical", "financial"],
      special_category_basis: ["non_profit", "health_medicine"],
      lawful_basis: ["consent", "legitimate_interests", "vital_interests"],
      third_party_recipients: ["service_providers", "regulators"],
      transfer_outside_eea: "no",
      retention_period: "Beneficiary referral and food-parcel records are retained for 2 years after the last visit, then anonymized for annual impact reporting.",
      automated_decisions: "no",
      collection_source: "direct",
      establishment_jurisdiction: "uk",
      gdpr_dpo_mandatory: "not_applicable",
      gdpr_right_to_withdraw: "Beneficiaries who consented to a safeguarding referral may withdraw that consent at any time by telling a volunteer coordinator, without affecting continued access to food-bank support.",
      gdpr_right_to_object: "Beneficiaries may object to being included in anonymized impact reporting by contacting privacy@harrowcommunitytrust.example.",
      gdpr_dpa_contact: "Information Commissioner's Office (ICO)",
      gdpr_profiling: "no",
      uk_lawful_basis_schedule: "DPA 2018 Schedule 1, Part 2, condition for the provision of support to individuals with a particular health need, alongside the Article 9(2)(d) not-for-profit-body ground.",
      uk_ico_complaint: "Beneficiaries and volunteers may complain to the Information Commissioner's Office (ico.org.uk) if they believe their data has been mishandled.",
    },
  },
  {
    id: "eu-notice-p04-kestrel-insurance-ireland",
    tool: "eu-notice",
    label: "Irish life and health insurer with automated underwriting scoring",
    company: "Kestrel Insurance Ireland Ltd",
    sector: "Life and health insurance",
    geo: "eu",
    summary:
      "Kestrel Insurance Ireland underwrites life and critical-illness policies using an automated risk-scoring model that sets the initial premium without a human in the loop, subject to an appeal right. Exercises EU establishment, special-category health data, a solely automated decision, a mixed collection source, and reinsurance transfers to the United States under SCCs and BCRs.",
    intake: {
      controller_name: "Kestrel Insurance Ireland Ltd",
      entity_name: "Kestrel Insurance Ireland Ltd",
      company_name: "Kestrel Insurance Ireland Ltd",
      controller_address: "32 Fitzwilliam Square, Dublin 2, D02 XY45, Ireland",
      contact_email: "privacy@kestrelinsurance.example",
      dpo_details: "yes",
      dpo_name: "Roisin Ahern",
      dpo_email: "dpo@kestrelinsurance.example",
      processing_purposes: ["service_delivery", "payment", "legal_compliance", "security"],
      data_categories: ["identifiers", "health_medical", "financial"],
      special_category_basis: ["health_medicine"],
      lawful_basis: ["contract", "legal_obligation", "legitimate_interests"],
      third_party_recipients: ["service_providers", "regulators", "affiliates"],
      transfer_outside_eea: "yes",
      transfer_safeguards: ["sccs", "bcrs"],
      transfer_destinations: "United States (reinsurance partner group, intra-group transfer of underwriting files)",
      retention_period: "Policy and underwriting records are retained for the policy term plus 7 years, matching the Central Bank of Ireland's insurance-recordkeeping requirements.",
      automated_decisions: "yes",
      automated_decisions_detail: "The initial premium quote is set solely by an automated risk-scoring model applied to the medical questionnaire and GP report; applicants can request a human underwriter to review and, where warranted, revise the automated quote before accepting the policy.",
      collection_source: "mixed",
      data_source_categories: ["partners", "public_sources"],
      establishment_jurisdiction: "eea",
      gdpr_dpo_mandatory: "mandatory_large_scale_special",
      gdpr_right_to_withdraw: "Not applicable to consent-based processing, as Kestrel's underwriting processing relies on contract, legal obligation, and legitimate interests rather than consent.",
      gdpr_right_to_object: "Applicants may object to the legitimate-interests fraud-screening check by contacting dpo@kestrelinsurance.example; this does not affect the contractual underwriting assessment.",
      gdpr_dpa_contact: "Data Protection Commission (Ireland)",
      gdpr_profiling: "yes",
      gdpr_profiling_info: "Applicants are profiled against actuarial risk factors derived from their medical questionnaire and GP report to produce the automated premium quote described above.",
    },
  },
  {
    id: "eu-notice-p05-bellerive-assurance-vie",
    tool: "eu-notice",
    label: "French life-insurance SA with human-finalised underwriting scores",
    company: "Bellerive Assurance Vie SA",
    sector: "Life insurance",
    geo: "eu",
    summary:
      "Bellerive Assurance Vie sells life-insurance and savings products underwritten with an automated pre-score that a licensed underwriter always finalises before any policy is issued or declined. Exercises EU establishment, special-category health data, human-reviewed automated decisions, and EEA-only data processing with no third-country transfer.",
    intake: {
      controller_name: "Bellerive Assurance Vie SA",
      entity_name: "Bellerive Assurance Vie SA",
      company_name: "Bellerive Assurance Vie SA",
      controller_address: "45 Rue de Rivoli, 75004 Paris, France",
      contact_email: "confidentialite@belleriveassurancevie.example",
      dpo_details: "yes",
      dpo_name: "Amandine Roche",
      dpo_email: "dpo@belleriveassurancevie.example",
      processing_purposes: ["service_delivery", "payment", "legal_compliance"],
      data_categories: ["identifiers", "health_medical", "financial"],
      special_category_basis: ["health_medicine"],
      lawful_basis: ["contract", "consent", "legal_obligation"],
      third_party_recipients: ["service_providers", "regulators"],
      transfer_outside_eea: "no",
      retention_period: "Policy files are retained for the policy term plus 10 years after termination, matching the French Code des assurances recordkeeping rule.",
      automated_decisions: "human_review",
      automated_decisions_detail: "A statistical pre-score derived from the medical questionnaire suggests a premium band, but a licensed underwriter reviews the medical file and pre-score together and makes the final underwriting decision in every case.",
      collection_source: "direct",
      establishment_jurisdiction: "eea",
      gdpr_dpo_mandatory: "mandatory_large_scale_special",
      gdpr_right_to_withdraw: "Where medical data is collected with explicit consent for a supplementary health questionnaire, applicants may withdraw that consent before the policy is issued, though this may prevent Bellerive from offering the requested cover.",
      gdpr_right_to_object: "Policyholders may object to marketing communications about new savings products at any time by contacting confidentialite@belleriveassurancevie.example.",
      gdpr_dpa_contact: "Commission Nationale de l'Informatique et des Libertés (CNIL)",
      gdpr_profiling: "no",
    },
  },
  {
    id: "eu-notice-p06-nordkyla-digital-ab",
    tool: "eu-notice",
    label: "Swedish B2B marketing-analytics SaaS with ad-partner profiling",
    company: "Nordkyla Digital AB",
    sector: "Marketing analytics software",
    geo: "eu",
    summary:
      "Nordkyla Digital sells a marketing-analytics dashboard that profiles website visitors for audience segmentation, mixing data collected directly with pixel data received from advertising and social partners. Exercises EU establishment, general profiling short of an Article 22 decision, a mixed collection source, and a transfer to a US ad-tech vendor under SCCs.",
    intake: {
      controller_name: "Nordkyla Digital AB",
      entity_name: "Nordkyla Digital AB",
      company_name: "Nordkyla Digital AB",
      controller_address: "Kungsgatan 30, 111 35 Stockholm, Sweden",
      contact_email: "privacy@nordkyladigital.example",
      dpo_details: "yes",
      dpo_name: "Erik Sandström",
      dpo_email: "dpo@nordkyladigital.example",
      processing_purposes: ["marketing", "analytics", "advertising"],
      data_categories: ["identifiers", "internet_activity", "commercial"],
      lawful_basis: ["legitimate_interests", "consent"],
      third_party_recipients: ["service_providers", "analytics", "advertising"],
      transfer_outside_eea: "yes",
      transfer_safeguards: ["sccs"],
      transfer_destinations: "United States (advertising-technology subprocessor for pixel and conversion data)",
      retention_period: "Visitor-segment data is retained 13 months on a rolling basis, matching Nordkyla's cookie-consent commitment.",
      automated_decisions: "no",
      collection_source: "mixed",
      data_source_categories: ["partners", "social_web"],
      establishment_jurisdiction: "eea",
      gdpr_dpo_mandatory: "voluntary",
      gdpr_right_to_withdraw: "Visitors who consented to marketing cookies may withdraw consent at any time through the cookie-preference banner on any Nordkyla-monitored site.",
      gdpr_right_to_object: "Visitors may object to profiling based on legitimate interests by contacting privacy@nordkyladigital.example or using the opt-out link in any marketing email.",
      gdpr_dpa_contact: "Integritetsskyddsmyndigheten (IMY)",
      gdpr_profiling: "yes",
      gdpr_profiling_info: "Website visitors are grouped into audience segments based on browsing behaviour and advertising-partner pixel data for use in Nordkyla's customers' ad campaigns; segments do not produce any decision with legal or similarly significant effect on the visitor.",
    },
  },
  {
    id: "eu-notice-p07-falkenrath-energie-gmbh",
    tool: "eu-notice",
    label: "German smart-meter energy utility with disputable automated billing",
    company: "Falkenrath Energie GmbH",
    sector: "Energy utility (smart-meter billing)",
    geo: "eu",
    summary:
      "Falkenrath Energie bills residential customers in Hesse using automated dynamic-tariff calculations from smart-meter readings, with a customer right to request human recalculation on dispute. Exercises EU establishment, large-scale systematic monitoring via smart meters, a human-review automated decision, and no third-country transfer.",
    intake: {
      controller_name: "Falkenrath Energie GmbH",
      entity_name: "Falkenrath Energie GmbH",
      company_name: "Falkenrath Energie GmbH",
      controller_address: "Mainzer Landstraße 55, 60329 Frankfurt am Main, Germany",
      contact_email: "datenschutz@falkenrathenergie.example",
      dpo_details: "yes",
      dpo_name: "Jonas Brandt",
      dpo_email: "dpo@falkenrathenergie.example",
      processing_purposes: ["service_delivery", "payment", "legal_compliance"],
      data_categories: ["identifiers", "commercial", "financial"],
      lawful_basis: ["contract", "legal_obligation"],
      third_party_recipients: ["service_providers", "regulators"],
      transfer_outside_eea: "no",
      retention_period: "Smart-meter consumption and billing records are retained for 10 years after the end of the supply contract, matching German commercial and tax-recordkeeping rules.",
      automated_decisions: "human_review",
      automated_decisions_detail: "The dynamic tariff amount on each bill is calculated automatically from half-hourly smart-meter readings; a customer who disputes a bill can request that a billing analyst manually recalculate the tariff from the raw meter data before the disputed amount is confirmed.",
      collection_source: "direct",
      establishment_jurisdiction: "eea",
      gdpr_dpo_mandatory: "mandatory_large_scale_monitoring",
      gdpr_right_to_withdraw: "Not applicable to consent-based processing, as Falkenrath's smart-meter billing relies on contract and legal obligation rather than consent.",
      gdpr_right_to_object: "Customers may object to having their consumption profile used for the optional load-forecasting research programme by contacting datenschutz@falkenrathenergie.example, without affecting core billing.",
      gdpr_dpa_contact: "Der Hessische Beauftragte für Datenschutz und Informationsfreiheit (HBDI)",
      gdpr_profiling: "no",
    },
  },
  {
    id: "eu-notice-p08-whitlock-vane-solicitors",
    tool: "eu-notice",
    label: "London solicitors' firm without a statutory DPO, cross-border e-discovery",
    company: "Whitlock & Vane Solicitors Ltd",
    sector: "Legal services",
    geo: "eu",
    summary:
      "Whitlock & Vane is a mid-size London solicitors' firm that has not designated a statutory DPO but transfers case files to a US e-discovery vendor for international litigation matters. Exercises UK establishment, the legal-claims special-category ground, no automated decisions, the dpo_details = no branch, and a transfer outside the EEA under SCCs and the UK Addendum.",
    intake: {
      controller_name: "Whitlock & Vane Solicitors Ltd",
      entity_name: "Whitlock & Vane Solicitors Ltd",
      company_name: "Whitlock & Vane Solicitors Ltd",
      controller_address: "22 Fenchurch Street, London EC3M 3BY, United Kingdom",
      contact_email: "privacy@whitlockvane.example",
      dpo_details: "no",
      processing_purposes: ["service_delivery", "legal_compliance", "security"],
      data_categories: ["identifiers", "professional", "financial", "criminal"],
      special_category_basis: ["legal_claims"],
      lawful_basis: ["contract", "legal_obligation", "legitimate_interests"],
      third_party_recipients: ["service_providers", "regulators"],
      transfer_outside_eea: "yes",
      transfer_safeguards: ["sccs", "uk_addendum"],
      transfer_destinations: "United States (e-discovery and litigation-document-review vendor for cross-border matters)",
      retention_period: "Client matter files are retained for 6 years after matter closure under the firm's professional-indemnity insurer's requirements, or longer where a limitation period has not expired.",
      automated_decisions: "no",
      collection_source: "direct",
      establishment_jurisdiction: "uk",
      gdpr_dpo_mandatory: "not_applicable",
      gdpr_right_to_withdraw: "Not applicable to consent-based processing, as the firm's processing of client and case data relies on contract, legal obligation, and legitimate interests rather than consent.",
      gdpr_right_to_object: "Clients may object to processing based on legitimate interests, such as conflict-checking against the firm's client database, by contacting privacy@whitlockvane.example.",
      gdpr_dpa_contact: "Information Commissioner's Office (ICO)",
      gdpr_profiling: "no",
      uk_lawful_basis_schedule: "DPA 2018 Schedule 1, Part 3, condition for the establishment, exercise, or defence of legal claims.",
      uk_ico_complaint: "Clients may complain to the Information Commissioner's Office (ico.org.uk) about how their personal data is handled.",
    },
  },
  {
    id: "eu-notice-p09-meridian-retail-ireland",
    tool: "eu-notice",
    label: "Irish sports-apparel e-commerce retailer using a US email vendor",
    company: "Meridian Retail Ireland Ltd",
    sector: "E-commerce / sports apparel retail",
    geo: "eu",
    summary:
      "Meridian Retail Ireland sells sports apparel online to customers across Ireland and Great Britain and uses a US email-marketing platform under Standard Contractual Clauses. Exercises EU establishment, no special-category data, no automated decisions, and a third-country transfer.",
    intake: {
      controller_name: "Meridian Retail Ireland Ltd",
      entity_name: "Meridian Retail Ireland Ltd",
      company_name: "Meridian Retail Ireland Ltd",
      controller_address: "18 Grand Canal Quay, Dublin 2, D02 KH59, Ireland",
      contact_email: "privacy@meridianretail.example",
      dpo_details: "yes",
      dpo_name: "Cian Doyle",
      dpo_email: "dpo@meridianretail.example",
      processing_purposes: ["service_delivery", "marketing", "payment", "analytics"],
      data_categories: ["identifiers", "commercial", "internet_activity", "financial"],
      lawful_basis: ["contract", "consent", "legitimate_interests"],
      third_party_recipients: ["service_providers", "analytics", "affiliates"],
      transfer_outside_eea: "yes",
      transfer_safeguards: ["sccs"],
      transfer_destinations: "United States (email-marketing and customer-analytics platform)",
      retention_period: "Order history is retained for 6 years for tax purposes; marketing-consent records are retained until consent is withdrawn.",
      automated_decisions: "no",
      collection_source: "direct",
      establishment_jurisdiction: "eea",
      gdpr_dpo_mandatory: "voluntary",
      gdpr_right_to_withdraw: "Customers who opted into marketing emails may withdraw consent at any time using the unsubscribe link in any email or by contacting dpo@meridianretail.example.",
      gdpr_right_to_object: "Customers may object to profiling for personalised product recommendations, which relies on legitimate interests, by adjusting their account preferences.",
      gdpr_dpa_contact: "Data Protection Commission (Ireland)",
      gdpr_profiling: "yes",
      gdpr_profiling_info: "Purchase history and browsing behaviour are used to generate personalised product recommendations on the storefront and in marketing emails.",
    },
  },
  {
    id: "eu-notice-p10-casarano-moda-srl",
    tool: "eu-notice",
    label: "Italian fashion retailer using a US CRM vendor for loyalty marketing",
    company: "Casarano Moda S.r.l.",
    sector: "Fashion retail",
    geo: "eu",
    summary:
      "Casarano Moda sells designer apparel from its Milan boutique and online store and uses a US customer-relationship-management vendor to run its loyalty programme. Exercises EU establishment, no special-category data, no automated decisions, and a third-country transfer under SCCs.",
    intake: {
      controller_name: "Casarano Moda S.r.l.",
      entity_name: "Casarano Moda S.r.l.",
      company_name: "Casarano Moda S.r.l.",
      controller_address: "Via Monte Napoleone 8, 20121 Milano, Italy",
      contact_email: "privacy@casaranomoda.example",
      dpo_details: "yes",
      dpo_name: "Giulia Ferrante",
      dpo_email: "dpo@casaranomoda.example",
      processing_purposes: ["service_delivery", "marketing", "payment"],
      data_categories: ["identifiers", "commercial", "internet_activity", "financial"],
      lawful_basis: ["consent", "contract", "legitimate_interests"],
      third_party_recipients: ["service_providers", "affiliates"],
      transfer_outside_eea: "yes",
      transfer_safeguards: ["sccs"],
      transfer_destinations: "United States (customer-relationship-management and loyalty-programme vendor)",
      retention_period: "Purchase and loyalty-programme records are retained for 5 years after the customer's last purchase, then deleted.",
      automated_decisions: "no",
      collection_source: "direct",
      establishment_jurisdiction: "eea",
      gdpr_dpo_mandatory: "voluntary",
      gdpr_right_to_withdraw: "Customers who joined the loyalty programme by consent may withdraw at any time in-store or by contacting privacy@casaranomoda.example.",
      gdpr_right_to_object: "Customers may object to marketing emails at any time using the unsubscribe link included in every message.",
      gdpr_dpa_contact: "Garante per la protezione dei dati personali",
      gdpr_profiling: "no",
    },
  },
  {
    id: "eu-notice-p11-vindobona-public-transport-se",
    tool: "eu-notice",
    label: "Austrian cross-border transit operator with automated fare-evasion fines",
    company: "Vindobona Public Transport SE",
    sector: "Public transport (cross-border rail and bus)",
    geo: "eu",
    summary:
      "Vindobona Public Transport, a Societas Europaea operating cross-border rail and bus services out of Vienna under a public-service concession, issues automated fare-evasion penalty notices from ticket-validator scans that a passenger can contest to a human reviewer. Exercises EU establishment, a public-task lawful basis, a mixed collection source with partner transit agencies, a mandatory-DPO public-authority branch, and a solely automated decision.",
    intake: {
      controller_name: "Vindobona Public Transport SE",
      entity_name: "Vindobona Public Transport SE",
      company_name: "Vindobona Public Transport SE",
      controller_address: "Erdbergstraße 202, 1030 Wien, Austria",
      contact_email: "datenschutz@vindobonatransport.example",
      dpo_details: "yes",
      dpo_name: "Katharina Huber",
      dpo_email: "dpo@vindobonatransport.example",
      processing_purposes: ["service_delivery", "payment", "security", "legal_compliance"],
      data_categories: ["identifiers", "geolocation", "commercial", "financial"],
      lawful_basis: ["public_task", "contract", "legal_obligation"],
      third_party_recipients: ["service_providers", "affiliates", "regulators"],
      transfer_outside_eea: "no",
      retention_period: "Ticket-validation and journey data is retained 90 days for fare reconciliation; confirmed fare-evasion penalty records are retained 3 years to support appeals and recovery.",
      automated_decisions: "yes",
      automated_decisions_detail: "A ticket validator that detects no valid ticket or pass automatically issues a provisional fare-evasion penalty notice by matching the scan to the passenger's registered travel-card account; the passenger can contest the notice to a human customer-relations officer, who can cancel it before any penalty is collected.",
      collection_source: "mixed",
      data_source_categories: ["partners", "public_authorities"],
      establishment_jurisdiction: "eea",
      gdpr_dpo_mandatory: "mandatory_public_authority",
      gdpr_right_to_withdraw: "Not applicable to consent-based processing, as Vindobona's processing of travel-card and ticketing data relies on its public-service task and contract rather than consent.",
      gdpr_right_to_object: "Passengers may object to receiving service-disruption alerts based on legitimate interests by disabling notifications in the Vindobona travel-card account settings.",
      gdpr_dpa_contact: "Österreichische Datenschutzbehörde",
      gdpr_profiling: "no",
    },
  },
  {
    id: "eu-notice-p12-solheim-marine-ab",
    tool: "eu-notice",
    label: "Swedish maritime-logistics tech firm with vessel-tracking data and an unsettled ADMT answer",
    company: "Solheim Marine AB",
    sector: "Maritime logistics technology",
    geo: "eu",
    summary:
      "Solheim Marine builds vessel-tracking and predictive-maintenance software for shipping operators and has not yet determined whether its scheduling recommendations meet the Article 22 automated-decision threshold. Exercises EU establishment, geolocation data on crew and vessels, an unsure automated-decisions answer, and transfers to both an adequate jurisdiction and the United States.",
    intake: {
      controller_name: "Solheim Marine AB",
      entity_name: "Solheim Marine AB",
      company_name: "Solheim Marine AB",
      controller_address: "Södra Hamngatan 19, 411 06 Göteborg, Sweden",
      contact_email: "privacy@solheimmarine.example",
      dpo_details: "yes",
      dpo_name: "Lina Bergqvist",
      dpo_email: "dpo@solheimmarine.example",
      processing_purposes: ["service_delivery", "security", "analytics"],
      data_categories: ["identifiers", "geolocation", "professional"],
      lawful_basis: ["contract", "legitimate_interests"],
      third_party_recipients: ["service_providers", "analytics"],
      transfer_outside_eea: "yes",
      transfer_safeguards: ["adequacy", "sccs"],
      transfer_destinations: "South Korea (AIS vessel-tracking data partner, adequacy decision) and United States (predictive-maintenance analytics subprocessor, Standard Contractual Clauses)",
      adequacy_status: "The transfer to the South Korean AIS data partner relies on the European Commission's adequacy decision for the Republic of Korea; the United States transfer relies on the EU Standard Contractual Clauses.",
      retention_period: "Vessel-position and maintenance-sensor data is retained 24 months on a rolling basis for trend analysis.",
      automated_decisions: "unsure",
      collection_source: "direct",
      establishment_jurisdiction: "eea",
      gdpr_dpo_mandatory: "voluntary",
      gdpr_right_to_withdraw: "Not applicable to consent-based processing, as Solheim's vessel-tracking processing relies on contract and legitimate interests rather than consent.",
      gdpr_right_to_object: "Crew members may object to the collection of individually-identifiable location data (as opposed to vessel-level tracking) by asking their employer's fleet manager to enable the anonymised crew-privacy mode.",
      gdpr_dpa_contact: "Integritetsskyddsmyndigheten (IMY)",
      gdpr_profiling: "unsure",
      gdpr_profiling_info: "Solheim is still assessing, with outside counsel, whether its predictive-maintenance scheduling recommendations to fleet operators constitute profiling of individual crew members or purely vessel-level analytics.",
    },
  },
  {
    id: "eu-notice-p13-kupferberg-praezisionstechnik",
    tool: "eu-notice",
    label: "German precision-manufacturing GmbH with an EU-only industrial supply chain",
    company: "Kupferberg Präzisionstechnik GmbH",
    sector: "Industrial manufacturing (precision engineering)",
    geo: "eu",
    summary:
      "Kupferberg Präzisionstechnik manufactures precision components for EU industrial customers and keeps its entire supply chain and data processing inside the EU. Exercises EU establishment, no special-category data, no automated decisions, direct collection, and no third-country transfer.",
    intake: {
      controller_name: "Kupferberg Präzisionstechnik GmbH",
      entity_name: "Kupferberg Präzisionstechnik GmbH",
      company_name: "Kupferberg Präzisionstechnik GmbH",
      controller_address: "Hohenzollernring 72, 50672 Köln, Germany",
      contact_email: "datenschutz@kupferbergpraezision.example",
      dpo_details: "yes",
      dpo_name: "Tobias Reinhardt",
      dpo_email: "dpo@kupferbergpraezision.example",
      processing_purposes: ["service_delivery", "legal_compliance", "payment"],
      data_categories: ["identifiers", "professional", "commercial", "financial"],
      lawful_basis: ["contract", "legitimate_interests", "legal_obligation"],
      third_party_recipients: ["service_providers", "regulators"],
      transfer_outside_eea: "no",
      retention_period: "Order and invoicing records are retained for 10 years to satisfy German commercial and tax recordkeeping obligations (§ 257 HGB, § 147 AO).",
      automated_decisions: "no",
      collection_source: "direct",
      establishment_jurisdiction: "eea",
      gdpr_dpo_mandatory: "voluntary",
      gdpr_right_to_withdraw: "Not applicable to consent-based processing, as Kupferberg's processing of customer-contact data relies on contract, legitimate interests, and legal obligation rather than consent.",
      gdpr_right_to_object: "Business contacts may object to receiving Kupferberg's quarterly product-catalogue mailing, which relies on legitimate interests, by emailing datenschutz@kupferbergpraezision.example.",
      gdpr_dpa_contact: "Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen (LDI NRW)",
      gdpr_profiling: "no",
    },
  },
  {
    id: "eu-notice-p14-ondelette-cosmetiques-sas",
    tool: "eu-notice",
    label: "French cosmetics e-commerce brand with a skincare-quiz profiling feature",
    company: "Ondelette Cosmétiques SAS",
    sector: "Cosmetics e-commerce retail",
    geo: "eu",
    summary:
      "Ondelette Cosmétiques sells skincare products online and profiles quiz responses to personalise product recommendations, without any decision that produces a legal or similarly significant effect. Exercises EU establishment, general profiling short of Article 22, no special-category data, and a third-country transfer to a US CRM vendor.",
    intake: {
      controller_name: "Ondelette Cosmétiques SAS",
      entity_name: "Ondelette Cosmétiques SAS",
      company_name: "Ondelette Cosmétiques SAS",
      controller_address: "12 Rue Saint-Honoré, 75001 Paris, France",
      contact_email: "confidentialite@ondelettecosmetiques.example",
      dpo_details: "yes",
      dpo_name: "Camille Fontaine",
      dpo_email: "dpo@ondelettecosmetiques.example",
      processing_purposes: ["service_delivery", "marketing", "payment", "analytics"],
      data_categories: ["identifiers", "commercial", "internet_activity", "financial"],
      lawful_basis: ["consent", "contract", "legitimate_interests"],
      third_party_recipients: ["service_providers", "analytics", "affiliates"],
      transfer_outside_eea: "yes",
      transfer_safeguards: ["sccs"],
      transfer_destinations: "United States (customer-relationship-management and email-marketing vendor)",
      retention_period: "Order records are retained for 5 years for consumer-protection purposes; skincare-quiz responses are retained until the customer's account is deleted.",
      automated_decisions: "no",
      collection_source: "direct",
      establishment_jurisdiction: "eea",
      gdpr_dpo_mandatory: "voluntary",
      gdpr_right_to_withdraw: "Customers who completed the skincare quiz by consent may delete their quiz responses at any time from their account settings.",
      gdpr_right_to_object: "Customers may object to marketing emails at any time using the unsubscribe link in every message, and to product-recommendation profiling by disabling personalisation in account settings.",
      gdpr_dpa_contact: "Commission Nationale de l'Informatique et des Libertés (CNIL)",
      gdpr_profiling: "yes",
      gdpr_profiling_info: "Skincare-quiz answers (skin type, concerns, routine preferences) are used to generate personalised product recommendations; the recommendation does not restrict or determine any purchase and has no legal or similarly significant effect on the customer.",
    },
  },
  {
    id: "eu-notice-p15-ardglass-community-housing",
    tool: "eu-notice",
    label: "Northern Ireland social housing association handling accessibility needs",
    company: "Ardglass Community Housing Ltd",
    sector: "Social housing",
    geo: "eu",
    summary:
      "Ardglass Community Housing is a Belfast-based registered social landlord that records tenants' health information only where needed to arrange accessibility adaptations. Exercises UK establishment, special-category health data on the non-profit-body and welfare grounds, no automated decisions, and no overseas transfers.",
    intake: {
      controller_name: "Ardglass Community Housing Ltd",
      entity_name: "Ardglass Community Housing Ltd",
      company_name: "Ardglass Community Housing Ltd",
      controller_address: "9 Cathedral Quarter, Belfast BT1 2LA, United Kingdom",
      contact_email: "privacy@ardglasscommunityhousing.example",
      dpo_details: "yes",
      dpo_name: "Niamh Quigley",
      dpo_email: "dpo@ardglasscommunityhousing.example",
      processing_purposes: ["service_delivery", "legal_compliance", "security"],
      data_categories: ["identifiers", "financial", "health_medical"],
      special_category_basis: ["non_profit", "health_medicine"],
      lawful_basis: ["contract", "legal_obligation", "legitimate_interests", "vital_interests"],
      third_party_recipients: ["service_providers", "regulators"],
      transfer_outside_eea: "no",
      retention_period: "Tenancy files are retained for 6 years after the tenancy ends; accessibility-adaptation health records are retained only for the duration of the adaptation works plus 12 months.",
      automated_decisions: "no",
      collection_source: "direct",
      establishment_jurisdiction: "uk",
      gdpr_dpo_mandatory: "voluntary",
      gdpr_right_to_withdraw: "Tenants who consented to share additional medical detail to support an urgent repair request may withdraw that consent at any time without affecting their tenancy.",
      gdpr_right_to_object: "Tenants may object to being contacted for the annual tenant-satisfaction survey, which relies on legitimate interests, by contacting privacy@ardglasscommunityhousing.example.",
      gdpr_dpa_contact: "Information Commissioner's Office (ICO)",
      gdpr_profiling: "no",
      uk_lawful_basis_schedule: "DPA 2018 Schedule 1, Part 1, condition for the exercise of a statutory function connected with the provision of social housing.",
      uk_ico_complaint: "Tenants may complain to the Information Commissioner's Office (ico.org.uk) about how their personal data is handled.",
    },
  },
];
