// ITEM 371 / ITEM 4(a) — CORPUS PIN FOR THE CYBER INTAKE RAIL.
//
// Every `regulationText` in CPPA_CYBER_RAIL must be a BYTE-EXACT contiguous
// substring of the approved `public.provision_texts` excerpt for the provision
// named in its `citation` (after the resolver's normalization). The rail is
// generated by `scripts/item371/gen-cyber-rail.ts`; this test is the guard that
// keeps it conformed to the corpus rather than the other way round.
//
// Runs against the live corpus over the Data API. Skipped when the sandbox has
// no network/credentials — corpus-pin is a CI/dev-only guard.

import { describe, it, expect, beforeAll } from "vitest";
import { CPPA_CYBER_RAIL } from "@/components/cppa/CPPACyberRailEntries";
import { normalizeCorpusText } from "../../../supabase/functions/run-cppa-cybersecurity/_local/registry/cyber-verified-authorities.ts";
import { loadCyberProvisionRows, type ProvisionRow } from "./corpus-client";

let rows: Record<string, ProvisionRow> | null = null;

beforeAll(async () => {
  rows = await loadCyberProvisionRows();
}, 60_000);

function provisionKey(citation: string): string | null {
  const m = /§\s*7(\d{3})/.exec(citation);
  return m ? `cppa-7${m[1]}` : null;
}

describe("CPPA cyber intake rail — corpus pin", () => {
  it("every regulationText is verbatim in its cited corpus row", () => {
    if (!rows) return; // corpus unreachable — guard skipped
    const failures: string[] = [];
    for (const [key, entry] of Object.entries(CPPA_CYBER_RAIL)) {
      const pk = provisionKey(entry.citation);
      if (!pk) {
        failures.push(`${key}: citation "${entry.citation}" names no cppa-7NNN provision`);
        continue;
      }
      const row = rows[pk];
      if (!row) {
        failures.push(`${key}: no corpus row for ${pk}`);
        continue;
      }
      if (row.status !== "approved") {
        failures.push(`${key}: corpus row ${pk} is "${row.status}", not approved`);
        continue;
      }
      const corpus = normalizeCorpusText(String(row.verbatim_excerpt ?? ""));
      if (!corpus.includes(entry.regulationText)) failures.push(`${key} (${entry.citation})`);
    }
    expect(
      failures,
      `Rail regulationText not found verbatim in the corpus:\n  ${failures.join("\n  ")}`,
    ).toEqual([]);
  });

  it("covers the § 7124 certification requirements", () => {
    const e = CPPA_CYBER_RAIL["cyber_certification"];
    expect(e).toBeTruthy();
    expect(e.citation).toContain("7124");
    expect(e.plainSummary).toMatch(/April 1/);
  });

  it("every entry carries actionable coaching", () => {
    const missing = Object.entries(CPPA_CYBER_RAIL)
      .filter(([, e]) => !e.coachLead?.trim() || !e.coachBody?.trim())
      .map(([k]) => k);
    expect(missing).toEqual([]);
  });

  it("coachLead is differentiated per field (no shared boilerplate)", () => {
    const leads = Object.values(CPPA_CYBER_RAIL).map((e) => e.coachLead);
    expect(new Set(leads).size).toBe(leads.length);
  });
});
