-- DOC 191 §7.3 migration verification. Returns ONE ROW PER MISMATCH;
-- an empty result means every migrated row matches the hand-authored source
-- byte for byte. Generated by scripts/doc191-lia-profile-backfill.ts --verify.
with expected(cam_row_id, md5_expected) as (values
  ('lia/f04-balancing/ap-01', '2bc3b4c68823be9d3e03dbaec69780ae'),
  ('lia/f03-necessity/ap-01', 'fcd11d8279bcfaffa02d1df8d816a21c'),
  ('lia/f01-interest-legitimacy/ap-02', '7f46a6b563502a35a57f6871f93669a1'),
  ('lia/f05-reasonable-expectations/ap-01', '78af0b4b3e224e32a14fa51c21476f4b'),
  ('lia/f06-relationship/ap-01', 'aabe62071d72bf936c686b4a2f718dbc'),
  ('lia/f05-reasonable-expectations/ap-02', '0a26ab1c5ce2f36c353984098d221535'),
  ('lia/f01-interest-legitimacy/ap-w5-01', '616f1d34f801180472b85d4522b343a8'),
  ('lia/f05-expectations/ap-w5-02', 'ab32e3b7b2ac8829e00747ecfe150e24'),
  ('lia/f11-eprivacy/ap-w5-03', '2a837b9802e4187c26283ffc59c0176d'),
  ('lia/f07-harms/ap-w5-04', '3fb132fd987e2300e7d1cc5fc4106af5'),
  ('lia/f11-eprivacy/ap-w5-05', '8333cdc25c648128751ad6453ba46732'),
  ('lia/f03-necessity/ap-w5-06', '5e43d4d77370c7b13c3653307e61b8a0'),
  ('lia/f05-expectations/ap-w5-07', 'b93466312feafc538ed77ecc052ad8e7'),
  ('lia/f07-harms/ap-w5-08', '6cef78d1c7386f66150d80d4d99f2ddd'),
  ('lia/f01-interest-legitimacy/ap-w5-09', '703cf5258d76d178a5e71d2d66f38fc0'),
  ('lia/f08-safeguards/ap-w5-10', '914574eb6d950bb46440f25b8187eb9c'),
  ('lia/f04-balancing/ap-w5-11', '8e86e3faff93b6be1a8009a16da3eb5c'),
  ('lia/f01-interest-legitimacy/ap-w5-12', 'cdfeb54fb1370c43ef83748d601913b3'),
  ('lia/f06-relationship/ap-w5-13', '52951e6530f24f31cb6098bfb6d150a3'),
  ('lia/f05-expectations/ap-w5-14', '3364b90ce996fc51bc3bfcc58223819a'),
  ('lia/f06-relationship/ap-w5-15', '94201223bcabd72c2a35e7d1b62211f4'),
  ('lia/f11-eprivacy/ap-w5-16', 'c18c2ed70aaba30886282faddc6ac3ca'),
  ('lia/f01-interest-legitimacy/ap-w5-17', 'ba6d7fd6481b4b0176ead0d332dbc8d9'),
  ('lia/f03-necessity/ap-w6-01', '692850ebb238cb5ea9ecf5de070fcaed'),
  ('lia/f01-interest-legitimacy/ap-w6-02', '9d97a24ee4a53d39bde0fd01aa6c935b'),
  ('lia/f08-safeguards/ap-w6-03', '2b0ba2a0a6d1c7f187639d5f7dddfe83'),
  ('lia/f04-balancing/ap-w6-04', '24d2b6a48beb7f8db847a78eaaabf221'),
  ('lia/f05-reasonable-expectations/ap-w6-05', '57f1e51fc882a8c5a4668008a8133a38'),
  ('lia/f06-relationship/ap-w6-06', '5d2a204c319697c829ed25e698dd4720'),
  ('lia/f04-balancing/ap-w6-07', '3bcf903810ed733c96a387384c1ed419'),
  ('lia/f01-interest-legitimacy/ap-w6-08', '9b4bc7abc236556409d94bcd614f768d'),
  ('lia/f11-eprivacy/ap-w6-09', '4d91bce6d341ecd1204f12e510019c1b'),
  ('lia/f01-interest-legitimacy/ap-w6-10', '77e1f3728178a62f3638e31755b4753d'),
  ('lia/f06-relationship/ap-w6-11', '2a758cfd16d42f75e32a6956ad607c58'),
  ('lia/f01-interest-legitimacy/ap-w6-12', '73c1d0be00024d4bd56bcfe25058f9dd')
)
select e.cam_row_id,
       md5(a.product || '|' || a.source_table || '|' || a.source_row_id::text || '|' || coalesce(a.cam_row_id,'∅') || '|' || a.country || '|' || a.instrument || '|' || array_to_string(a.factor_ids,'~') || '|' || coalesce(a.use_case_class,'∅') || '|' || a.outcome_posture || '|' || coalesce(a.relationship,'∅') || '|' || array_to_string(a.data_categories,'~') || '|' || array_to_string(a.flags,'~') || '|' || a.rule_or_pattern || '|' || coalesce(a.rule_statement,'∅') || '|' || a.curation_note || '|' || a.curated_by || '|' || a.pipeline_stage || '|' || coalesce(a.extracted_quote,'∅') || '|' || a.quote_verified::text || '|' || a.confidence_tier || '|' || a.pipeline_version) as md5_actual,
       e.md5_expected,
       case when a.cam_row_id is null then 'MISSING FROM DB' else 'CONTENT MISMATCH' end as problem
from expected e
left join public.authority_relevance_profiles a
  on a.product = 'lia' and a.cam_row_id = e.cam_row_id
where a.cam_row_id is null or md5(a.product || '|' || a.source_table || '|' || a.source_row_id::text || '|' || coalesce(a.cam_row_id,'∅') || '|' || a.country || '|' || a.instrument || '|' || array_to_string(a.factor_ids,'~') || '|' || coalesce(a.use_case_class,'∅') || '|' || a.outcome_posture || '|' || coalesce(a.relationship,'∅') || '|' || array_to_string(a.data_categories,'~') || '|' || array_to_string(a.flags,'~') || '|' || a.rule_or_pattern || '|' || coalesce(a.rule_statement,'∅') || '|' || a.curation_note || '|' || a.curated_by || '|' || a.pipeline_stage || '|' || coalesce(a.extracted_quote,'∅') || '|' || a.quote_verified::text || '|' || a.confidence_tier || '|' || a.pipeline_version) <> e.md5_expected;
