/**
 * ITEM 313 — verbatim corpus snapshot for the governance registry pin tests.
 *
 * GENERATED from public.gdpr_articles (jurisdiction='eu'), not typed by hand.
 *
 * CORPUS CHECK (dispatch-confirmed, re-run this turn — no ingestion required):
 *   Art. 5 = 1977 chars (ends "...paragraph 1 (‘accountability’).")
 *   Art. 24 = 861 · Art. 30 = 2907 · Art. 37 = 1989 · Art. 38 = 1390 · Art. 39 = 1278
 *
 * Every verbatim_quote in governance-verified-authorities.ts that the
 * governance deliverables cite MUST appear as an exact substring of one of
 * these snapshots. Do NOT edit by hand.
 */

export const GOVERNANCE_CORPUS_SNAPSHOT: Record<string, string> = {
  "eu-art-5": "1. Personal data shall be:\n\n(a)\n\nprocessed lawfully, fairly and in a transparent manner in relation to the data subject (‘lawfulness, fairness and transparency’);\n\n(b)\n\ncollected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes; further processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes shall, in accordance with Article 89(1), not be considered to be incompatible with the initial purposes (‘purpose limitation’);\n\n(c)\n\nadequate, relevant and limited to what is necessary in relation to the purposes for which they are processed (‘data minimisation’);\n\n(d)\n\naccurate and, where necessary, kept up to date; every reasonable step must be taken to ensure that personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’);\n\n(e)\n\nkept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with Article 89(1) subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’);\n\n(f)\n\nprocessed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (‘integrity and confidentiality’).\n\n2. The controller shall be responsible for, and be able to demonstrate compliance with, paragraph 1 (‘accountability’).",
  "eu-art-24": "1. Taking into account the nature, scope, context and purposes of processing as well as the risks of varying likelihood and severity for the rights and freedoms of natural persons, the controller shall implement appropriate technical and organisational measures to ensure and to be able to demonstrate that processing is performed in accordance with this Regulation. Those measures shall be reviewed and updated where necessary.\n\n2. Where proportionate in relation to processing activities, the measures referred to in paragraph 1 shall include the implementation of appropriate data protection policies by the controller.\n\n3. Adherence to approved codes of conduct as referred to in Article 40 or approved certification mechanisms as referred to in Article 42 may be used as an element by which to demonstrate compliance with the obligations of the controller.",
  "eu-art-30": "1. Each controller and, where applicable, the controller's representative, shall maintain a record of processing activities under its responsibility. That record shall contain all of the following information:\n\n(a)\n\nthe name and contact details of the controller and, where applicable, the joint controller, the controller's representative and the data protection officer;\n\n(b)\n\nthe purposes of the processing;\n\n(c)\n\na description of the categories of data subjects and of the categories of personal data;\n\n(d)\n\nthe categories of recipients to whom the personal data have been or will be disclosed including recipients in third countries or international organisations;\n\n(e)\n\nwhere applicable, transfers of personal data to a third country or an international organisation, including the identification of that third country or international organisation and, in the case of transfers referred to in the second subparagraph of Article 49(1), the documentation of suitable safeguards;\n\n(f)\n\nwhere possible, the envisaged time limits for erasure of the different categories of data;\n\n(g)\n\nwhere possible, a general description of the technical and organisational security measures referred to in Article 32(1).\n\n2. Each processor and, where applicable, the processor's representative shall maintain a record of all categories of processing activities carried out on behalf of a controller, containing:\n\n(a)\n\nthe name and contact details of the processor or processors and of each controller on behalf of which the processor is acting, and, where applicable, of the controller's or the processor's representative, and the data protection officer;\n\n(b)\n\nthe categories of processing carried out on behalf of each controller;\n\n(c)\n\nwhere applicable, transfers of personal data to a third country or an international organisation, including the identification of that third country or international organisation and, in the case of transfers referred to in the second subparagraph of Article 49(1), the documentation of suitable safeguards;\n\n(d)\n\nwhere possible, a general description of the technical and organisational security measures referred to in Article 32(1).\n\n3. The records referred to in paragraphs 1 and 2 shall be in writing, including in electronic form.\n\n4. The controller or the processor and, where applicable, the controller's or the processor's representative, shall make the record available to the supervisory authority on request.\n\n5. The obligations referred to in paragraphs 1 and 2 shall not apply to an enterprise or an organisation employing fewer than 250 persons unless the processing it carries out is likely to result in a risk to the rights and freedoms of data subjects, the processing is not occasional, or the processing includes special categories of data as referred to in Article 9(1) or personal data relating to criminal convictions and offences referred to in Article 10.",
  "eu-art-37": "1. The controller and the processor shall designate a data protection officer in any case where:\n\n(a)\n\nthe processing is carried out by a public authority or body, except for courts acting in their judicial capacity;\n\n(b)\n\nthe core activities of the controller or the processor consist of processing operations which, by virtue of their nature, their scope and/or their purposes, require regular and systematic monitoring of data subjects on a large scale; or\n\n(c)\n\nthe core activities of the controller or the processor consist of processing on a large scale of special categories of data pursuant to Article 9 and personal data relating to criminal convictions and offences referred to in Article 10.\n\n2. A group of undertakings may appoint a single data protection officer provided that a data protection officer is easily accessible from each establishment.\n\n3. Where the controller or the processor is a public authority or body, a single data protection officer may be designated for several such authorities or bodies, taking account of their organisational structure and size.\n\n4. In cases other than those referred to in paragraph 1, the controller or processor or associations and other bodies representing categories of controllers or processors may or, where required by Union or Member State law shall, designate a data protection officer. The data protection officer may act for such associations and other bodies representing controllers or processors.\n\n5. The data protection officer shall be designated on the basis of professional qualities and, in particular, expert knowledge of data protection law and practices and the ability to fulfil the tasks referred to in Article 39.\n\n6. The data protection officer may be a staff member of the controller or processor, or fulfil the tasks on the basis of a service contract.\n\n7. The controller or the processor shall publish the contact details of the data protection officer and communicate them to the supervisory authority.",
  "eu-art-38": "1. The controller and the processor shall ensure that the data protection officer is involved, properly and in a timely manner, in all issues which relate to the protection of personal data.\n\n2. The controller and processor shall support the data protection officer in performing the tasks referred to in Article 39 by providing resources necessary to carry out those tasks and access to personal data and processing operations, and to maintain his or her expert knowledge.\n\n3. The controller and processor shall ensure that the data protection officer does not receive any instructions regarding the exercise of those tasks. He or she shall not be dismissed or penalised by the controller or the processor for performing his tasks. The data protection officer shall directly report to the highest management level of the controller or the processor.\n\n4. Data subjects may contact the data protection officer with regard to all issues related to processing of their personal data and to the exercise of their rights under this Regulation.\n\n5. The data protection officer shall be bound by secrecy or confidentiality concerning the performance of his or her tasks, in accordance with Union or Member State law.\n\n6. The data protection officer may fulfil other tasks and duties. The controller or processor shall ensure that any such tasks and duties do not result in a conflict of interests.",
  "eu-art-39": "1. The data protection officer shall have at least the following tasks:\n\n(a)\n\nto inform and advise the controller or the processor and the employees who carry out processing of their obligations pursuant to this Regulation and to other Union or Member State data protection provisions;\n\n(b)\n\nto monitor compliance with this Regulation, with other Union or Member State data protection provisions and with the policies of the controller or processor in relation to the protection of personal data, including the assignment of responsibilities, awareness-raising and training of staff involved in processing operations, and the related audits;\n\n(c)\n\nto provide advice where requested as regards the data protection impact assessment and monitor its performance pursuant to Article 35;\n\n(d)\n\nto cooperate with the supervisory authority;\n\n(e)\n\nto act as the contact point for the supervisory authority on issues relating to processing, including the prior consultation referred to in Article 36, and to consult, where appropriate, with regard to any other matter.\n\n2. The data protection officer shall in the performance of his or her tasks have due regard to the risk associated with processing operations, taking into account the nature, scope, context and purposes of processing."
};
