/**
 * ITEM 312 — verbatim corpus snapshot for the ir-playbook registry pin tests.
 *
 * GENERATED from the approved corpus, not typed by hand:
 *   * public.gdpr_articles rows (jurisdiction='eu', articles 32/33/34).
 *   * public.provision_texts rows ukgdpr-art-33 / ukgdpr-art-34 (status='approved').
 *
 * CORPUS CHECK (dispatch-confirmed, re-run this turn):
 *   gdpr_articles(eu,'33') = 1734 chars; gdpr_articles(eu,'34') = 1649 chars,
 *   ending "...may decide that any of the conditions referred to in paragraph 3
 *   are met." Item 291's "Art. 34 truncated" P0 flag is WITHDRAWN (Item 300 /
 *   304 Fix C) and is not a blocker.
 *
 * Every verbatim_quote in ir-playbook-verified-authorities.ts that this module
 * cites MUST appear as an exact substring of one of these snapshots.
 * Do NOT edit by hand.
 */

export const IR_CORPUS_SNAPSHOT: Record<string, string> = {
  "eu-art-32": "1. Taking into account the state of the art, the costs of implementation and the nature, scope, context and purposes of processing as well as the risk of varying likelihood and severity for the rights and freedoms of natural persons, the controller and the processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including inter alia as appropriate:\n\n(a)\n\nthe pseudonymisation and encryption of personal data;\n\n(b)\n\nthe ability to ensure the ongoing confidentiality, integrity, availability and resilience of processing systems and services;\n\n(c)\n\nthe ability to restore the availability and access to personal data in a timely manner in the event of a physical or technical incident;\n\n(d)\n\na process for regularly testing, assessing and evaluating the effectiveness of technical and organisational measures for ensuring the security of the processing.\n\n2. In assessing the appropriate level of security account shall be taken in particular of the risks that are presented by processing, in particular from accidental or unlawful destruction, loss, alteration, unauthorised disclosure of, or access to personal data transmitted, stored or otherwise processed.\n\n3. Adherence to an approved code of conduct as referred to in Article 40 or an approved certification mechanism as referred to in Article 42 may be used as an element by which to demonstrate compliance with the requirements set out in paragraph 1 of this Article.\n\n4. The controller and processor shall take steps to ensure that any natural person acting under the authority of the controller or the processor who has access to personal data does not process them except on instructions from the controller, unless he or she is required to do so by Union or Member State law.",
  "eu-art-33": "1. In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the supervisory authority competent in accordance with Article 55, unless the personal data breach is unlikely to result in a risk to the rights and freedoms of natural persons. Where the notification to the supervisory authority is not made within 72 hours, it shall be accompanied by reasons for the delay.\n\n2. The processor shall notify the controller without undue delay after becoming aware of a personal data breach.\n\n3. The notification referred to in paragraph 1 shall at least:\n\n(a)\n\ndescribe the nature of the personal data breach including where possible, the categories and approximate number of data subjects concerned and the categories and approximate number of personal data records concerned;\n\n(b)\n\ncommunicate the name and contact details of the data protection officer or other contact point where more information can be obtained;\n\n(c)\n\ndescribe the likely consequences of the personal data breach;\n\n(d)\n\ndescribe the measures taken or proposed to be taken by the controller to address the personal data breach, including, where appropriate, measures to mitigate its possible adverse effects.\n\n4. Where, and in so far as, it is not possible to provide the information at the same time, the information may be provided in phases without undue further delay.\n\n5. The controller shall document any personal data breaches, comprising the facts relating to the personal data breach, its effects and the remedial action taken. That documentation shall enable the supervisory authority to verify compliance with this Article.",
  "eu-art-34": "1. When the personal data breach is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall communicate the personal data breach to the data subject without undue delay.\n\n2. The communication to the data subject referred to in paragraph 1 of this Article shall describe in clear and plain language the nature of the personal data breach and contain at least the information and measures referred to in points (b), (c) and (d) of Article 33(3).\n\n3. The communication to the data subject referred to in paragraph 1 shall not be required if any of the following conditions are met:\n\n(a)\n\nthe controller has implemented appropriate technical and organisational protection measures, and those measures were applied to the personal data affected by the personal data breach, in particular those that render the personal data unintelligible to any person who is not authorised to access it, such as encryption;\n\n(b)\n\nthe controller has taken subsequent measures which ensure that the high risk to the rights and freedoms of data subjects referred to in paragraph 1 is no longer likely to materialise;\n\n(c)\n\nit would involve disproportionate effort. In such a case, there shall instead be a public communication or similar measure whereby the data subjects are informed in an equally effective manner.\n\n4. If the controller has not already communicated the personal data breach to the data subject, the supervisory authority, having considered the likelihood of the personal data breach resulting in a high risk, may require it to do so or may decide that any of the conditions referred to in paragraph 3 are met.",
  "ukgdpr-art-33": "In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the Commissioner , unless the personal data breach is unlikely to result in a risk to the rights and freedoms of natural persons. Where the notification under this paragraph is not made within 72 hours, it shall be accompanied by reasons for the delay. The processor shall notify the controller without undue delay after becoming aware of a personal data breach. The notification referred to in paragraph 1 shall at least: describe the nature of the personal data breach including where possible, the categories and approximate number of data subjects concerned and the categories and approximate number of personal data records concerned; communicate the name and contact details of the data protection officer or other contact point where more information can be obtained; describe the likely consequences of the personal data breach; describe the measures taken or proposed to be taken by the controller to address the personal data breach, including, where appropriate, measures to mitigate its possible adverse effects. Where, and in so far as, it is not possible to provide the information at the same time, the information may be provided in phases without undue further delay. The controller shall document any personal data breaches, comprising the facts relating to the personal data breach, its effects and the remedial action taken. That documentation shall enable the Commissioner to verify compliance with this Article.",
  "ukgdpr-art-34": "When the personal data breach is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall communicate the personal data breach to the data subject without undue delay. The communication to the data subject referred to in paragraph 1 of this Article shall describe in clear and plain language the nature of the personal data breach and contain at least the information and measures referred to in points (b), (c) and (d) of Article 33(3). The communication to the data subject referred to in paragraph 1 shall not be required if any of the following conditions are met: the controller has implemented appropriate technical and organisational protection measures, and those measures were applied to the personal data affected by the personal data breach, in particular those that render the personal data unintelligible to any person who is not authorised to access it, such as encryption; the controller has taken subsequent measures which ensure that the high risk to the rights and freedoms of data subjects referred to in paragraph 1 is no longer likely to materialise; it would involve disproportionate effort. In such a case, there shall instead be a public communication or similar measure whereby the data subjects are informed in an equally effective manner. If the controller has not already communicated the personal data breach to the data subject, the Commissioner , having considered the likelihood of the personal data breach resulting in a high risk, may require it to do so or may decide that any of the conditions referred to in paragraph 3 are met."
};
