/**
 * ITEM 316 — corpus snapshot for the registration duty registry.
 *
 * Whitespace-normalized copies of the APPROVED `public.provision_texts` rows
 * (and the approved `public.gdpr_articles` bodies for Arts. 27 and 37) that
 * the registration duty registry quotes from, taken 2026-07-31.
 *
 * The pin tests assert that every `verbatim_quote` in the registry is an exact
 * substring of the row named by its `corpus_key`. That is what makes the
 * quotes checkable offline: if someone edits a quote by hand, the pin fails.
 */
export const REGISTRATION_CORPUS_SNAPSHOT: Record<string, string> = {
  "ca-delete-act-1798-99-80":
    "For purposes of this title: (a) The definitions in Section 1798.140 shall apply unless otherwise specified in this title. (b) \"Authorized agent\" has the same meaning as used in Chapter 1 (commencing with Section 7000) of Division 6 of Title 11 of the California Code of Regulations. (c) \"Data broker\" means a business that knowingly collects and sells to third parties the personal information of a consumer with whom the business does not have a direct relationship. \"Data broker\" does not include any of the following: (1) An entity to the extent that it is covered by the federal Fair Credit Reporting Act (15 U.S.C. Sec. 1681 et seq.). (2) An entity to the extent that it is covered by the Gramm-Leach-Bliley Act (Public Law 106-102) and implementing regulations. (3) An entity to the extent that it is covered by the Insurance Information and Privacy Protection Act (Article 6.6 (commencing with Section 791) of Chapter 1 of Part 2 of Division 1 of the Insurance Code). (4) An entity, or a business associate of a covered entity, to the extent their processing of personal information is exempt under Section 1798.146. For purposes of this paragraph, \"business associate\" and \"covered entity\" have the same meanings as defined in Section 1798.146.",
  "ca-delete-act-1798-99-82":
    "(a) On or before January 31 following each year in which a business meets the definition of data broker as provided in this title, the business shall register with the California Privacy Protection Agency pursuant to the requirements of this section. (b) In registering with the California Privacy Protection Agency, as described in subdivision (a), a data broker shall do all of the following: (1) Pay a registration fee in an amount determined by the California Privacy Protection Agency, not to exceed the reasonable costs of establishing and maintaining the informational internet website described in Section 1798.99.84 and the reasonable costs of establishing, maintaining, and providing access to the accessible deletion mechanism described in Section 1798.99.86. Registration fees shall be deposited in the Data Brokers' Registry Fund, created within the State Treasury pursuant to Section 1798.99.81, and used for the purposes outlined in this paragraph. (2) Provide the following information: (A) The name of the data broker and its primary physical, email, and internet website addresses. (B) The metrics compiled pursuant to paragraphs (1) and (2) of subdivision (a) of Section 1798.99.85. (C) Whether the data broker collects the personal information of minors.",
  "or-ors-646a-593":
    "(1) As used in this section: ... (c)(A) \"Data broker\" means a business entity or part of a business entity that collects and sells or licenses brokered personal data to another person. ... (2)(a) Except as provided in paragraph (b) of this subsection, a data broker may not collect, sell or license brokered personal data within this state unless the data broker first registers with the Department of Consumer and Business Services as provided in subsection (3) of this section. ... (3) To register with the department, a data broker shall: (a) Submit on a form and in a format the department specifies: (A) The name of the data broker; (B) The street address and telephone number of the data broker; and (C) The data broker's primary website and electronic mail address. (b) Pay a fee in an amount the department specifies by rule. The department shall set the fee in an amount that is sufficient, when aggregated, to pay the costs of administering the registration program. ... (4) If a data broker complies with the requirements set forth in subsection (3) of this section, the department shall approve the registration. A registration under this section is valid until December 31 of the year in which the department approves the registration.",
  "tx-bc-510-001":
    "Sec. 510.001. DEFINITIONS. In this chapter: ... (4) \"Data broker\" means a business entity that collects, processes, or transfers personal data that the business entity did not collect directly from the individual linked or linkable to the data. ... (11) \"Personal data\" means any information, including sensitive data, that is linked or reasonably linkable to an identified or identifiable individual. The term includes pseudonymous data when the information is used by a controller or processor in conjunction with additional information that reasonably links the information to an identified or identifiable individual. The term does not include deidentified data, employee data, or publicly available information. ... (17) \"Transfer,\" in the context of data, means to disclose, release, share, disseminate, make available, sell, or license the data by any means or medium.",
  "tx-bc-510-003":
    "(a) Except as provided by Subsection (b), this chapter applies only to a data broker that, in a 12-month period, derives: (1) more than 50 percent of the data broker's revenue directly from processing or transferring personal data not collected by the data broker directly from the individuals to whom the data pertains; or (2) revenue directly from processing or transferring the personal data of more than 50,000 individuals not collected by the data broker directly from the individuals to whom the data pertains. (b) This chapter does not apply to: (1) a service provider, including a service provider that engages in the business of processing employee data for a third-party employer for the sole purpose of providing benefits to the third-party employer's employees; (2) a person or entity that collects personal data from another person or entity to which the person or entity is related by common ownership or corporate control, provided a reasonable consumer would expect the persons or entities to share data; (3) a federal, state, tribal, territorial, or local governmental entity, including a body, authority, board, bureau, commission, district, agency, or political subdivision of a governmental entity; ... (5) a consumer reporting agency or other person or entity that furnishes information for inclusion in a consumer credit report or obtains a consumer credit report, but only to the extent the person or entity engages in activity regulated or authorized by the Fair Credit Reporting Act (15 U.S.C. Section 1681 et seq.) ...; or (6) a financial institution subject to Title V, Gramm-Leach-Bliley Act (15 U.S.C. Section 6801 et seq.).",
  "tx-bc-510-005":
    "(a) To conduct business in this state, a data broker to which this chapter applies shall register with the secretary of state by filing a registration statement and paying a registration fee of $300. (b) The registration statement must include: (1) the legal name of the data broker; (2) a contact person and the primary physical address, e-mail address, telephone number, and Internet website address for the data broker; (2-a) a link to a page on the data broker's Internet website that provides consumers with specific instructions, which must be prominently displayed, on how to exercise their consumer rights under Section 541.051, and any other applicable data privacy rights under Chapter 541; (3) a description of the categories of data the data broker processes and transfers; (4) a statement of whether or not the data broker implements a purchaser credentialing process; (5) if the data broker has actual knowledge that the data broker possesses personal data of a known child: (A) a statement detailing the data collection practices, databases, sales activities, and opt-out policies that are applicable to the personal data of a known child; and (B) a statement on how the data broker complies with applicable federal and state law regarding the collection, use, or disclosure of personal data from and about a child on the Internet; and (6) the number of security breaches the data broker has experienced during the year immediately preceding the year in which the registration is filed, and if known, the total number of consumers affected by each breach. ... (d) A registration certificate expires on the first anniversary of its date of issuance. A data broker may renew a registration certificate by filing a renewal application, in the form prescribed by the secretary of state, and paying a renewal fee in the amount of $300.",
  "vt-9vsa-2430":
    "(4)(A) \"Data broker\" means a business, or unit or units of a business, separately or together, that knowingly collects and sells or licenses to third parties the brokered personal information of a consumer with whom the business does not have a direct relationship. (B) Examples of a direct relationship with a business include if the consumer is a past or present: (i) customer, client, subscriber, user, or registered user of the business's goods or services; (ii) employee, contractor, or agent of the business; (iii) investor in the business; or (iv) donor to the business. (C) The following activities conducted by a business, and the collection and sale or licensing of brokered personal information incidental to conducting these activities, do not qualify the business as a data broker: (i) developing or maintaining third-party e-commerce or application platforms; (ii) providing 411 directory assistance or directory information services, including name, address, and telephone number, on behalf of or as a function of a telecommunications carrier; (iii) providing publicly available information related to a consumer's business or profession; or (iv) providing publicly available information via real-time or near-real-time alert services for health or safety purposes. (D) The phrase \"sells or licenses\" does not include: (i) a one-time or occasional sale of assets of a business as part of a transfer of control of those assets that is not part of the ordinary conduct of the business;",
  "vt-9vsa-2446":
    "(a) Annually, on or before January 31 following a year in which a person meets the definition of data broker as provided in section 2430 of this title, a data broker shall: (1) register with the Secretary of State; (2) pay a registration fee of $100.00; and (3) provide the following information: (A) the name and primary physical, e-mail, and Internet addresses of the data broker; (B) if the data broker permits a consumer to opt out of the data broker's collection of brokered personal information, opt out of its databases, or opt out of certain sales of data: (i) the method for requesting an opt-out; (ii) if the opt-out applies to only certain activities or sales, which ones; and (iii) whether the data broker permits a consumer to authorize a third party to perform the opt-out on the consumer's behalf.",
  "gdpr-articles:eu:27":
    "1. Where Article 3(2) applies, the controller or the processor shall designate in writing a representative in the Union. 2. The obligation laid down in paragraph 1 of this Article shall not apply to: (a) processing which is occasional, does not include, on a large scale, processing of special categories of data as referred to in Article 9(1) or processing of personal data relating to criminal convictions and offences referred to in Article 10, and is unlikely to result in a risk to the rights and freedoms of natural persons, taking into account the nature, context, scope and purposes of the processing; or (b) a public authority or body. 3. The representative shall be established in one of the Member States where the data subjects, whose personal data are processed in relation to the offering of goods or services to them, or whose behaviour is monitored, are. 4. The representative shall be mandated by the controller or processor to be addressed in addition to or instead of the controller or the processor by, in particular, supervisory authorities and data subjects, on all issues related to processing, for the purposes of ensuring compliance with this Regulation. 5. The designation of a representative by the controller or processor shall be without prejudice to legal actions which could be initiated against the controller or the processor themselves.",
  "gdpr-articles:uk:27":
    "Where Article 3(2) applies, the controller or the processor shall designate in writing a representative in the United Kingdom . The obligation laid down in paragraph 1 of this Article shall not apply to: processing which is occasional, does not include, on a large scale, processing of special categories of data as referred to in Article 9(1) or processing of personal data relating to criminal convictions and offences referred to in Article 10, and is unlikely to result in a risk to the rights and freedoms of natural persons, taking into account the nature, context, scope and purposes of the processing; or a public authority or body … The representative shall be mandated by the controller or processor to be addressed in addition to or instead of the controller or the processor by, in particular, the Commissioner and data subjects, on all issues related to processing, for the purposes of ensuring compliance with this Regulation. The designation of a representative by the controller or processor shall be without prejudice to legal actions which could be initiated against the controller or the processor themselves.",
  "gdpr-articles:eu:37":
    "1. The controller and the processor shall designate a data protection officer in any case where: (a) the processing is carried out by a public authority or body, except for courts acting in their judicial capacity; (b) the core activities of the controller or the processor consist of processing operations which, by virtue of their nature, their scope and/or their purposes, require regular and systematic monitoring of data subjects on a large scale; or (c) the core activities of the controller or the processor consist of processing on a large scale of special categories of data pursuant to Article 9 and personal data relating to criminal convictions and offences referred to in Article 10. 2. A group of undertakings may appoint a single data protection officer provided that a data protection officer is easily accessible from each establishment. 3. Where the controller or the processor is a public authority or body, a single data protection officer may be designated for several such authorities or bodies, taking account of their organisational structure and size. 4. In cases other than those referred to in paragraph 1, the controller or processor or associations and other bodies representing categories of controllers or processors may or, where required by Union or Member State law shall, designate a data protection officer. The data protection officer may act for such associations and other bodies representing controllers or processors. 5. The data protection officer shall be designated on the basis of professional qualities and, in particular, expert knowledge of data protection law and practices and the ability to fulfil the tasks referred to in Article 39. 6. The data protection officer may be a staff member of the controller or processor, or fulfil the tasks on the basis of a service contract. 7. The controller or the processor shall publish the contact details of the data protection officer and communicate them to the supervisory authority.",
};
