// /all-ptest fixture panel — ir-playbook. Fifteen complete, internally consistent
// intakes authored 2026-09-14 (see ./types.ts and scripts/ptest/PANEL-BRIEF.md).
// Validated by tests/edge/ptest/panels.test.ts.

import type { PanelFixture } from "./types.ts";

export const PANEL_IR_PLAYBOOK: PanelFixture[] = [
  {
    id: "ir-playbook-p01-harborview-retail",
    tool: "ir-playbook",
    label: "US retailer, contained cyberattack, live 72-hour-scale clock, full standing playbook",
    company: "Harborview Retail Corp.",
    sector: "Retail e-commerce",
    geo: "us",
    summary: "California retailer discovers and contains a credential-stuffing attack against its admin console within a day, with all affected payment data encrypted. Exercises a single-state California jurisdiction, a live notification clock, contained-Yes, and every ITEM 369-IR standing-playbook field answered.",
    intake: {
      organizationName: "Harborview Retail Corp.",
      discoveryDateTime: "2026-09-13T14:20:00Z",
      cause: "Unauthorized external access / cyberattack",
      dataTypes: ["Names and contact details", "Financial / payment data"],
      affectedCount: "100–1,000",
      jurisdictions: ["California"],
      processorInvolved: true,
      processorName: "Stripe, Inc.",
      contained: "Yes",
      organisationType: "Company",
      encryptionStatus: "All affected data encrypted / rendered unintelligible",
      encryptionKeyStatus: "Keys not compromised",
      affectedRecordCount: "approx. 640 customer order records",
      affectedDataSubjectCount: "approx. 610 California customers",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any successful login to the Harborview POS Cloud admin console from an IP address outside the corporate VPN range.",
        "Any alert from the managed security provider naming customer order or payment data.",
        "More than 50 failed admin-console login attempts within a 10-minute window.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "Confirmed unauthorized access to the admin console with evidence of data export.", escalation: "Incident Lead notifies the CEO and General Counsel within 60 minutes." },
        { level: "SEV-2", definition: "Suspicious admin-console access without confirmed export.", escalation: "Incident Lead notifies the Head of Engineering within 2 hours." },
      ],
      severityThresholds: ["SEV-1: any confirmed export of customer payment or order data.", "SEV-2: anomalous access with no confirmed export within 4 hours of detection."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "R. Okafor-Blythe (VP Engineering)", alternate: "S. Vance (Director of IT)" },
        { role: "Legal", primary: "M. Castellano (General Counsel)", alternate: "outside counsel on call" },
        { role: "Communications", primary: "J. Petrakis (Head of Customer Experience)", alternate: "D. Nakamura (PR agency lead)" },
      ],
      outsideCounselName: "Ferris Whitlock LLP (Privacy & Data Security)",
      outsideCounselContact: "24-hour line (415) 555-0148; incident@ferriswhitlock.example",
      privilegeProtocol: true,
      insurerContact: "Anchor Point Cyber Insurance, policy AP-CY-2291, claims (800) 555-0173",
      forensicVendorContact: "Redline Forensics, retainer RF-2026-0087, dispatch (888) 555-0119",
      lawEnforcementContact: "FBI IC3 and the San Jose field office cyber squad, (408) 555-0102",
      keySystems: ["Harborview POS Cloud (Shopify Plus admin)", "Stripe payment gateway integration", "Loyalty-account database (PostgreSQL, AWS us-west-2)"],
      logSources: ["Shopify admin audit log (12-month retention)", "AWS CloudTrail for us-west-2 (12-month retention)", "Okta SSO sign-in logs (18-month retention)"],
      itIsolationAuthority: "The Director of IT may revoke any admin-console session or API key without further approval on the Incident Lead's instruction.",
      breachNoticeContracts: [
        { counterparty: "Stripe, Inc. (payment processor)", deadline: "Within 24 hours of awareness of any incident affecting cardholder data", clause: "Stripe Services Agreement §9" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve", "fh_isolate", "fh_counsel", "fh_scope", "fh_insurer"],
      nextTabletopDate: "2026-12-04",
    },
  },
  {
    id: "ir-playbook-p02-kestrel-point-systems",
    tool: "ir-playbook",
    label: "US SaaS provider, uncontained ransomware, multi-state and EU jurisdictions, processor involved",
    company: "Kestrel Point Systems Inc.",
    sector: "Project-management SaaS",
    geo: "us",
    summary: "A project-management SaaS vendor is hit by ransomware affecting a legacy unencrypted database of over 100,000 accounts across California, Texas, New York and EU customers, with containment still in progress. Exercises the uncontained branch, an unencrypted-data limb, an assumed (not yet confirmed) awareness timestamp, and a named processor.",
    intake: {
      organizationName: "Kestrel Point Systems Inc.",
      discoveryDateTime: "2026-09-12T03:45:00Z",
      cause: "Ransomware or malware",
      dataTypes: ["Names and contact details", "Passwords / credentials", "Financial / payment data"],
      affectedCount: "More than 100,000",
      jurisdictions: ["California", "Texas", "New York", "EU/EEA"],
      processorInvolved: true,
      processorName: "Vantage Billing Solutions LLC",
      contained: "No",
      organisationType: "Company",
      encryptionStatus: "No affected data encrypted",
      encryptionKeyStatus: "Not applicable — no encryption",
      affectedRecordCount: "at least 118,000 account records identified so far, count still climbing as forensics proceeds",
      affectedDataSubjectCount: "at least 112,000 individual account holders",
      awarenessConfirmed: "Assumed — detection timestamp treated as awareness pending confirmation",
      activationCriteria: [
        "Any ransomware note, mass-encryption event, or unexplained service outage across production databases.",
        "Any report from Vantage Billing Solutions of anomalous activity touching Kestrel Point customer records.",
        "Detection of unauthorized lateral movement inside the production VPC.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "Confirmed ransomware encryption of a production database containing customer credentials.", escalation: "Incident Lead notifies the CEO and board within 30 minutes; outside counsel engaged immediately." },
        { level: "SEV-2", definition: "Suspected compromise pending confirmation of scope.", escalation: "Incident Lead notifies the CTO within 1 hour." },
      ],
      severityThresholds: ["SEV-1: confirmed encryption or exfiltration of the legacy account database.", "SEV-2: anomalous access without confirmed impact."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "A. Demir (CTO)", alternate: "L. Whitcombe (VP Infrastructure)" },
        { role: "Security / Forensics Lead", primary: "P. Renwick (Head of Security)", alternate: "external forensics lead" },
        { role: "Legal", primary: "outside counsel", alternate: "H. Iwu (Associate General Counsel)" },
        { role: "Communications Lead", primary: "T. Okonjo (VP Marketing)", alternate: "N/A" },
      ],
      outsideCounselName: "Bramwell Sackett LLP (Cyber Incident Response)",
      outsideCounselContact: "24-hour hotline (650) 555-0166; ir@bramwellsackett.example",
      privilegeProtocol: true,
      insurerContact: "Pinnacle Cyber Underwriters, policy PCU-9284, claims (877) 555-0141",
      forensicVendorContact: "Ashcombe Digital Forensics, retainer ADF-2026-0055, dispatch (855) 555-0177",
      lawEnforcementContact: "FBI IC3; case referred to the San Francisco field office",
      keySystems: ["Legacy accounts database (self-hosted MySQL, us-east-1)", "Vantage Billing Solutions integration", "Production Kubernetes cluster"],
      logSources: ["VPC flow logs (90-day retention)", "Kubernetes audit logs (30-day retention)", "Vantage Billing Solutions API access logs"],
      itIsolationAuthority: "The VP Infrastructure may isolate any production node or revoke any service credential immediately, notifying the Incident Lead within 15 minutes.",
      breachNoticeContracts: [
        { counterparty: "Vantage Billing Solutions LLC (processor)", deadline: "Without undue delay and in any event within 48 hours of awareness", clause: "Data Processing Addendum §7.2" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve", "fh_counsel", "fh_insurer"],
      nextTabletopDate: "2026-10-20",
    },
  },
  {
    id: "ir-playbook-p03-alderbrook-health-network",
    tool: "ir-playbook",
    label: "US healthcare provider, insider snooping discovered late, HIPAA clock already elapsed",
    company: "Alderbrook Health Network LLC",
    sector: "Multi-clinic healthcare provider",
    geo: "us",
    summary: "A healthcare network discovers, during a routine compliance audit months after the fact, that a clinic scheduler had been browsing patient records without a treatment reason. Because discovery came so late, the HIPAA 60-day notification clock has already elapsed by the time the record is assessed — an already-elapsed clock scenario, contrasted with the live-clock fixtures elsewhere in this panel.",
    intake: {
      organizationName: "Alderbrook Health Network LLC",
      discoveryDateTime: "2026-06-02T16:00:00Z",
      cause: "Insider threat",
      dataTypes: ["Health / medical records", "Names and contact details", "Government IDs / SSN"],
      affectedCount: "10,000–100,000",
      jurisdictions: ["United States (HIPAA)", "California"],
      processorInvolved: true,
      processorName: "Veridian Health IT Hosting, Inc.",
      contained: "Yes",
      organisationType: "Healthcare provider",
      encryptionStatus: "Some affected data encrypted",
      encryptionKeyStatus: "Keys compromised or possibly compromised",
      affectedRecordCount: "approx. 14,300 patient chart records accessed without a treatment reason",
      affectedDataSubjectCount: "approx. 14,300 patients across three clinic sites",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any EHR audit-log alert flagging chart access with no corresponding appointment or referral.",
        "Any employee report of a colleague viewing a chart for a patient they do not treat.",
        "Any law-enforcement or media inquiry naming a specific patient's record.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "Confirmed unauthorized access to patient charts by an employee with no treatment relationship, affecting more than 500 patients.", escalation: "Incident Lead notifies the Compliance Officer and CEO within 4 hours." },
        { level: "SEV-2", definition: "A single-patient snooping complaint under investigation.", escalation: "Logged by the Privacy Officer and reviewed at the monthly compliance meeting." },
      ],
      severityThresholds: ["SEV-1: more than 500 patients affected by confirmed unauthorized chart access.", "SEV-2: fewer than 500 patients, or an unconfirmed complaint."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "C. Whitfield (Chief Compliance Officer)", alternate: "R. Adeyemi (Privacy Officer)" },
        { role: "Legal", primary: "outside healthcare counsel", alternate: "in-house counsel" },
        { role: "HR", primary: "K. Bellweather (Director of HR)", alternate: "N/A" },
      ],
      outsideCounselName: "Marchetti Vance LLP (Health Care Privacy)",
      outsideCounselContact: "(312) 555-0134; healthir@marchettivance.example",
      privilegeProtocol: true,
      insurerContact: "Sentinel Health Liability Trust, policy SHLT-6612, claims (866) 555-0198",
      forensicVendorContact: "Not engaged — internal EHR audit-log review was sufficient to bound the incident",
      lawEnforcementContact: "Not contacted — no evidence of external criminal conduct",
      keySystems: ["Epic EHR (hosted by Veridian Health IT Hosting, three-clinic instance)", "Clinic scheduling system (athenahealth)"],
      logSources: ["Epic chart-access audit log (7-year retention, HIPAA-mandated)", "Active Directory sign-in logs (12-month retention)"],
      itIsolationAuthority: "The IT Director may suspend any EHR user account on the Compliance Officer's instruction; the affected employee's access was suspended the same day as discovery.",
      breachNoticeContracts: [
        { counterparty: "Veridian Health IT Hosting, Inc. (Epic hosting processor)", deadline: "Within 10 business days of awareness", clause: "Business Associate Agreement §5.2" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve", "fh_dpo"],
      nextTabletopDate: "2026-11-10",
    },
  },
  {
    id: "ir-playbook-p04-meridian-trust-bank",
    tool: "ir-playbook",
    label: "US bank, contained phishing/credential compromise, live clock, processor involved",
    company: "Meridian Trust Bank Corp.",
    sector: "Retail banking",
    geo: "us",
    summary: "A bank contains a phishing campaign that compromised several employee credentials before any fraudulent transfer completed, engaging its FTC-regulated notification track alongside New York and Connecticut state duties. Exercises the processor-involved branch (a wire-processing vendor), a live clock, and full recovery detail.",
    intake: {
      organizationName: "Meridian Trust Bank Corp.",
      discoveryDateTime: "2026-09-13T08:10:00Z",
      cause: "Phishing / credential compromise",
      dataTypes: ["Financial / payment data", "Passwords / credentials", "Names and contact details"],
      affectedCount: "1,000–10,000",
      jurisdictions: ["United States (FTC)", "New York", "Connecticut"],
      processorInvolved: true,
      processorName: "Cordant Wire Processing Corp.",
      contained: "Yes",
      organisationType: "Financial institution",
      encryptionStatus: "Some affected data encrypted",
      encryptionKeyStatus: "Keys not compromised",
      affectedRecordCount: "approx. 2,850 customer account records queried by the compromised credentials",
      affectedDataSubjectCount: "approx. 2,850 retail banking customers",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any employee report of a suspicious email requesting Meridian Online Banking credentials.",
        "Any anomalous wire-initiation pattern flagged by Cordant Wire Processing's fraud-scoring engine.",
        "More than three failed multi-factor challenges on a single employee account within 10 minutes.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "Confirmed fraudulent wire initiated using compromised employee credentials.", escalation: "Incident Lead notifies the Chief Risk Officer and General Counsel within 30 minutes." },
        { level: "SEV-2", definition: "Compromised credentials confirmed but no fraudulent transaction initiated.", escalation: "Incident Lead notifies the CISO within 1 hour." },
      ],
      severityThresholds: ["SEV-1: any confirmed fraudulent wire or account takeover.", "SEV-2: credential compromise contained before any transaction."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "V. Ostrowski (CISO)", alternate: "F. Callaghan (Deputy CISO)" },
        { role: "Legal", primary: "G. Nakashima (General Counsel)", alternate: "outside banking counsel" },
        { role: "Fraud Operations", primary: "B. Sorensen (Fraud Operations Manager)", alternate: "Cordant fraud desk" },
      ],
      outsideCounselName: "Halloway Prescott LLP (Banking & Financial Services)",
      outsideCounselContact: "(212) 555-0187; bankingir@hallowayprescott.example",
      privilegeProtocol: true,
      insurerContact: "Fidelis Financial Institution Bond, policy FFIB-3387, claims (800) 555-0122",
      forensicVendorContact: "Northgate Cyber Forensics, retainer NCF-2026-0041, dispatch (877) 555-0155",
      lawEnforcementContact: "FBI Financial Crimes Section and the US Secret Service field office",
      keySystems: ["Meridian Online Banking platform", "Cordant Wire Processing integration", "Employee email (Microsoft 365)"],
      logSources: ["Microsoft 365 sign-in and mailbox audit logs (12-month retention)", "Cordant wire-initiation audit trail", "Core banking system transaction log (7-year retention)"],
      itIsolationAuthority: "The Deputy CISO may force-reset any employee credential and disable wire-initiation rights immediately on the Incident Lead's instruction.",
      breachNoticeContracts: [
        { counterparty: "Cordant Wire Processing Corp. (processor)", deadline: "Within 24 hours of awareness", clause: "Master Services Agreement §12.3" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve", "fh_isolate", "fh_counsel", "fh_scope", "fh_insurer"],
      nextTabletopDate: "2026-12-15",
    },
  },
  {
    id: "ir-playbook-p05-riverside-county-transit",
    tool: "ir-playbook",
    label: "US public authority, small-scale lost device, contained, live clock",
    company: "Riverside County Transit Authority",
    sector: "Public transit authority",
    geo: "us",
    summary: "A public transit authority's paratransit coordinator loses an unencrypted laptop containing a small registration roster, recovered and contained the same day it goes missing. Exercises the public-authority organisation type, the smallest affected-count band, and an unencrypted-device fact pattern distinct from the panel's larger cyberattack scenarios.",
    intake: {
      organizationName: "Riverside County Transit Authority",
      discoveryDateTime: "2026-09-13T17:30:00Z",
      cause: "Lost or stolen device",
      dataTypes: ["Names and contact details", "Location data"],
      affectedCount: "Fewer than 100",
      jurisdictions: ["California"],
      processorInvolved: true,
      processorName: "TransitReg Cloud Systems, Inc.",
      contained: "Yes",
      organisationType: "Public authority",
      encryptionStatus: "No affected data encrypted",
      encryptionKeyStatus: "Not applicable — no encryption",
      affectedRecordCount: "78 paratransit registration records",
      affectedDataSubjectCount: "78 registered paratransit riders",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any report of a lost or stolen Authority-issued laptop, tablet, or removable drive.",
        "Any inventory-audit discrepancy involving a device known to hold rider registration data.",
      ],
      severityMatrix: [
        { level: "SEV-2", definition: "A single device holding fewer than 500 rider records is lost or stolen.", escalation: "Incident Lead notifies the Deputy Director within 4 hours." },
        { level: "SEV-3", definition: "A device holding no personal data is lost.", escalation: "Logged by IT; no executive escalation." },
      ],
      severityThresholds: ["SEV-2: any lost device confirmed to hold rider personal data.", "SEV-3: a device confirmed to hold no personal data."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "D. Faraday (IT Manager)", alternate: "M. Ibarra (Deputy Director of Operations)" },
        { role: "Legal", primary: "County Counsel's office", alternate: "N/A" },
      ],
      outsideCounselName: "County Counsel's office handles this matter in-house",
      outsideCounselContact: "(951) 555-0110",
      privilegeProtocol: false,
      insurerContact: "Riverside County joint-powers risk pool, claims (951) 555-0177",
      forensicVendorContact: "Not engaged — device was password-protected local storage only, no network exposure",
      lawEnforcementContact: "Riverside County Sheriff's Department, incident report filed the day of loss",
      keySystems: ["Paratransit registration roster (migrated from a local spreadsheet to TransitReg Cloud Systems' managed database)"],
      logSources: ["Device asset-tracking log", "Building access-control log for the last known location"],
      itIsolationAuthority: "The IT Manager may remotely wipe any lost Authority device once mobile-device management confirms last check-in.",
      breachNoticeContracts: [
        { counterparty: "TransitReg Cloud Systems, Inc. (registration-database processor)", deadline: "Within 5 business days of awareness", clause: "Hosting and Support Agreement §8" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_scope"],
      nextTabletopDate: "2027-01-15",
    },
  },
  {
    id: "ir-playbook-p06-cascadia-biolabs",
    tool: "ir-playbook",
    label: "US research organisation, accidental disclosure of special-category and biometric data, contained",
    company: "Cascadia BioLabs, Inc.",
    sector: "Biotechnology research",
    geo: "us",
    summary: "A biotech research organisation accidentally emails a participant roster containing health status and gait-analysis biometric identifiers to an incorrect internal distribution list, caught and recalled within hours. Exercises the accidental-disclosure cause, the 'Other' organisation type, and a special-category-plus-biometric data mix across three West Coast states.",
    intake: {
      organizationName: "Cascadia BioLabs, Inc.",
      discoveryDateTime: "2026-09-12T11:00:00Z",
      cause: "Accidental disclosure",
      dataTypes: ["Health / medical records", "Biometric data", "Special category data"],
      affectedCount: "100–1,000",
      jurisdictions: ["California", "Washington", "Oregon"],
      processorInvolved: true,
      processorName: "ClinCloud Research Systems, Inc.",
      contained: "Yes",
      organisationType: "Other",
      encryptionStatus: "No affected data encrypted",
      encryptionKeyStatus: "Not applicable — no encryption",
      affectedRecordCount: "212 clinical-trial participant records",
      affectedDataSubjectCount: "212 gait-analysis study participants",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any email or file share containing participant health or biometric data sent outside the approved study-team distribution list.",
        "Any IRB or participant complaint alleging unauthorized disclosure of study data.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "Study data reaches a recipient outside the organisation.", escalation: "Incident Lead notifies the IRB liaison and General Counsel within 4 hours." },
        { level: "SEV-2", definition: "Study data reaches an internal recipient outside the approved study team, but not outside the organisation.", escalation: "Incident Lead notifies the Principal Investigator within 24 hours." },
      ],
      severityThresholds: ["SEV-1: disclosure to any recipient outside Cascadia BioLabs.", "SEV-2: disclosure limited to internal staff outside the study team, recalled within 24 hours."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "E. Solheim (Director of Research Compliance)", alternate: "T. Marchand (IT Security Lead)" },
        { role: "Principal Investigator", primary: "Dr. N. Osei-Prempeh", alternate: "Dr. L. Fontaine" },
        { role: "Legal", primary: "outside counsel", alternate: "N/A" },
      ],
      outsideCounselName: "Corrigan Blakely LLP (Life Sciences Privacy)",
      outsideCounselContact: "(206) 555-0161; ir@corriganblakely.example",
      privilegeProtocol: true,
      insurerContact: "BioShield Research Liability, policy BSR-7710, claims (888) 555-0133",
      forensicVendorContact: "Not engaged — internal email-recall and read-receipt review bounded the incident",
      lawEnforcementContact: "Not applicable",
      keySystems: ["Study participant roster (REDCap, hosted by ClinCloud Research Systems)", "Corporate email (Google Workspace)"],
      logSources: ["Google Workspace email audit log (6-month retention)", "REDCap access log"],
      itIsolationAuthority: "The IT Security Lead may recall or block any outbound message containing study-data attachments once a disclosure is reported.",
      breachNoticeContracts: [
        { counterparty: "ClinCloud Research Systems, Inc. (REDCap hosting processor)", deadline: "Within 5 business days of awareness", clause: "Data Hosting Agreement §6" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve", "fh_scope"],
      nextTabletopDate: "2026-11-05",
    },
  },
  {
    id: "ir-playbook-p07-thornbury-municipal-water",
    tool: "ir-playbook",
    label: "US public authority, cause and scope still under investigation, unknown containment",
    company: "Thornbury Municipal Water District",
    sector: "Public water utility",
    geo: "us",
    summary: "A municipal water district detects unusual outbound traffic from its billing server but has not yet determined the cause, scope, or whether the intrusion is contained. Exercises the unknown-cause branch, the unknown-affected-count and unknown-containment options together, and a partially-executed first-hour checklist reflecting a genuinely open investigation.",
    intake: {
      organizationName: "Thornbury Municipal Water District",
      discoveryDateTime: "2026-09-13T22:15:00Z",
      cause: "Unknown / still investigating",
      dataTypes: ["Names and contact details", "Financial / payment data"],
      affectedCount: "Unknown",
      jurisdictions: ["Texas"],
      processorInvolved: true,
      processorName: "AquaBill Municipal Systems, Inc.",
      contained: "Unknown",
      organisationType: "Public authority",
      encryptionStatus: "Unknown",
      encryptionKeyStatus: "Unknown",
      affectedRecordCount: "Not yet determined — forensic scoping is in progress",
      affectedDataSubjectCount: "Not yet determined — forensic scoping is in progress",
      awarenessConfirmed: "Unknown",
      activationCriteria: [
        "Any unexplained outbound network connection from the billing server to an unrecognised external address.",
        "Any unusual after-hours administrative login to the billing or customer-service systems.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "Confirmed exfiltration of ratepayer billing data.", escalation: "Incident Lead notifies the General Manager and District Board Chair within 2 hours." },
        { level: "SEV-2", definition: "Anomalous activity under investigation with no confirmed exfiltration.", escalation: "Incident Lead notifies the IT Supervisor within 4 hours." },
      ],
      severityThresholds: ["SEV-1: confirmed data exfiltration.", "SEV-2: anomalous activity, scope not yet confirmed."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "W. Halstrom (IT Supervisor)", alternate: "contracted MSP on-call engineer" },
        { role: "General Manager", primary: "P. Renaud", alternate: "Deputy General Manager" },
      ],
      outsideCounselName: "Not yet engaged — pending scoping results",
      outsideCounselContact: "District's standing municipal counsel, (432) 555-0119",
      privilegeProtocol: false,
      insurerContact: "Texas Municipal League Intergovernmental Risk Pool, claims (800) 555-0144",
      forensicVendorContact: "Praxis Municipal Forensics engaged on a scoping-only basis, (855) 555-0188",
      lawEnforcementContact: "Not yet contacted — pending confirmation of criminal activity",
      keySystems: ["Billing and customer-service system (AquaBill Municipal Systems SaaS platform)", "SCADA network (segregated, not implicated to date)"],
      logSources: ["Billing-server firewall logs (30-day retention)", "VPN gateway logs"],
      itIsolationAuthority: "The IT Supervisor may isolate the billing server from the wider network immediately; the SCADA network's isolation requires General Manager sign-off given operational-continuity risk.",
      breachNoticeContracts: [
        { counterparty: "AquaBill Municipal Systems, Inc. (billing-platform processor)", deadline: "Within 72 hours of awareness, per the hosting agreement", clause: "Municipal Billing Platform Agreement §11" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve"],
      nextTabletopDate: "2026-10-30",
    },
  },
  {
    id: "ir-playbook-p08-fenwick-sons-logistics",
    tool: "ir-playbook",
    label: "US logistics company, uncontained cyberattack via VPN vulnerability, notification decision overdue",
    company: "Fenwick & Sons Logistics LLC",
    sector: "Freight logistics",
    geo: "us",
    summary: "A freight logistics company discovers, sixty days after the fact, that an unpatched VPN appliance was exploited to reach driver and payroll data across three states, and containment work is still ongoing. Exercises the already-elapsed clock, an uncontained incident, and a payroll-processor involvement together with a multi-state jurisdiction mix.",
    intake: {
      organizationName: "Fenwick & Sons Logistics LLC",
      discoveryDateTime: "2026-07-16T09:00:00Z",
      cause: "Unauthorized external access / cyberattack",
      dataTypes: ["Names and contact details", "Location data", "Financial / payment data"],
      affectedCount: "10,000–100,000",
      jurisdictions: ["Texas", "Illinois", "Massachusetts"],
      processorInvolved: true,
      processorName: "Halbrook Payroll Services Inc.",
      contained: "No",
      organisationType: "Company",
      encryptionStatus: "Some affected data encrypted",
      encryptionKeyStatus: "Keys compromised or possibly compromised",
      affectedRecordCount: "approx. 22,400 driver and dispatch records identified, scoping still underway",
      affectedDataSubjectCount: "approx. 19,600 current and former drivers",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any alert from the VPN appliance vendor naming an actively exploited vulnerability in Fenwick's model.",
        "Any report from Halbrook Payroll Services of anomalous access to driver payroll records.",
        "Any dispatcher report of GPS or routing data behaving unexpectedly.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "Confirmed exploitation of the VPN appliance with access to driver or payroll data.", escalation: "Incident Lead notifies the COO and outside counsel within 1 hour." },
        { level: "SEV-2", definition: "Vulnerability confirmed present but exploitation unconfirmed.", escalation: "Incident Lead notifies the IT Director within 4 hours." },
      ],
      severityThresholds: ["SEV-1: confirmed exploitation with data access.", "SEV-2: vulnerability present, exploitation unconfirmed."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "G. Fenwick III (COO)", alternate: "R. Delacroix (IT Director)" },
        { role: "Legal", primary: "outside counsel", alternate: "N/A" },
        { role: "Payroll Liaison", primary: "Halbrook Payroll Services account manager", alternate: "N/A" },
      ],
      outsideCounselName: "Ashworth Greer LLP (Data Security)",
      outsideCounselContact: "(312) 555-0192; ir@ashworthgreer.example",
      privilegeProtocol: true,
      insurerContact: "Continental Freight Cyber Program, policy CFCP-4482, claims (877) 555-0166",
      forensicVendorContact: "Ironclad Digital Forensics, retainer ICDF-2026-0073, dispatch (866) 555-0129",
      lawEnforcementContact: "FBI Chicago field office, cyber squad",
      keySystems: ["VPN appliance (remote-site connectivity)", "Halbrook Payroll Services integration", "Dispatch and GPS routing platform"],
      logSources: ["VPN appliance connection logs (limited to 30 days, a known gap now being remediated)", "Halbrook Payroll access logs", "Dispatch platform audit trail"],
      itIsolationAuthority: "The IT Director may take the VPN appliance offline immediately; doing so was authorised and executed the day scoping began, forcing dispatchers onto a temporary manual routing process.",
      breachNoticeContracts: [
        { counterparty: "Halbrook Payroll Services Inc. (processor)", deadline: "Within 72 hours of awareness", clause: "Service Agreement §8.4" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve", "fh_isolate", "fh_counsel"],
      nextTabletopDate: "2026-10-09",
    },
  },
  {
    id: "ir-playbook-p09-alderney-data-systems",
    tool: "ir-playbook",
    label: "German SaaS company, contained cyberattack, live GDPR 72-hour clock",
    company: "Alderney Data Systems GmbH",
    sector: "Developer-tools SaaS",
    geo: "eu",
    summary: "A German developer-tools vendor discovers an exposed API key that allowed limited unauthorized access to a customer database, contained within hours of discovery. Exercises a live GDPR Article 33 72-hour clock, a single EU jurisdiction pairing (Germany plus the broader EU/EEA), and a fully answered standing playbook.",
    intake: {
      organizationName: "Alderney Data Systems GmbH",
      discoveryDateTime: "2026-09-13T06:40:00Z",
      cause: "Unauthorized external access / cyberattack",
      dataTypes: ["Names and contact details", "Passwords / credentials"],
      affectedCount: "1,000–10,000",
      jurisdictions: ["Germany", "EU/EEA"],
      processorInvolved: true,
      processorName: "Amazon Web Services EMEA SARL",
      contained: "Yes",
      organisationType: "Company",
      encryptionStatus: "Some affected data encrypted",
      encryptionKeyStatus: "Keys not compromised",
      affectedRecordCount: "approx. 3,100 customer account records",
      affectedDataSubjectCount: "approx. 3,100 registered developer accounts",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any API key or service-account credential found exposed in a public code repository or log output.",
        "Any anomalous query volume against the customer database from an unrecognised service account.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "Confirmed unauthorized database access using an exposed credential.", escalation: "Incident Lead notifies the Geschäftsführer and Datenschutzbeauftragter within 1 hour." },
        { level: "SEV-2", definition: "Exposed credential found with no confirmed unauthorized use.", escalation: "Incident Lead notifies the engineering on-call lead within 4 hours." },
      ],
      severityThresholds: ["SEV-1: confirmed unauthorized use of the exposed credential.", "SEV-2: exposure detected and revoked before confirmed use."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "J. Brandt (Head of Engineering)", alternate: "S. Lindqvist-Meyer (Site Reliability Lead)" },
        { role: "Datenschutzbeauftragter (DPO)", primary: "F. Wachsmuth", alternate: "external DPO service" },
        { role: "Legal", primary: "outside counsel", alternate: "N/A" },
      ],
      outsideCounselName: "Reuter Falkenberg Rechtsanwälte (Datenschutzrecht)",
      outsideCounselContact: "+49 30 555 0142; ir@reuterfalkenberg.example",
      privilegeProtocol: true,
      insurerContact: "Kontinent Cyberversicherung, Police KC-5521, Schadensmeldung +49 30 555 0177",
      forensicVendorContact: "Nordwind Digitalforensik, Rahmenvertrag NDF-2026-0038, +49 30 555 0163",
      lawEnforcementContact: "Bundeskriminalamt Cybercrime-Meldestelle",
      keySystems: ["Customer database (managed PostgreSQL, AWS eu-central-1)", "CI/CD pipeline (GitHub Actions)"],
      logSources: ["GitHub audit log (12-month retention)", "Database query audit log (90-day retention)", "AWS CloudTrail for eu-central-1"],
      itIsolationAuthority: "The Site Reliability Lead may revoke any API key or service-account credential immediately on suspicion, notifying the Incident Lead within 15 minutes.",
      breachNoticeContracts: [
        { counterparty: "Amazon Web Services EMEA SARL (cloud hosting processor)", deadline: "Communicated without undue delay, per AWS's incident notification provisions", clause: "AWS Data Processing Addendum" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve", "fh_isolate", "fh_dpo", "fh_counsel"],
      nextTabletopDate: "2026-12-02",
    },
  },
  {
    id: "ir-playbook-p10-kesselring-retail",
    tool: "ir-playbook",
    label: "Dutch retailer, large-scale exposed storage bucket, GDPR clock already elapsed",
    company: "Kesselring Retail B.V.",
    sector: "Online retail",
    geo: "eu",
    summary: "A Dutch online retailer learns from an external security researcher, ten days after the underlying misconfiguration occurred, that a cloud storage bucket exposed over a hundred thousand customer records across the Netherlands, Belgium and the wider EU. Exercises an already-elapsed GDPR clock, a processor-involved branch, and the largest affected-count band.",
    intake: {
      organizationName: "Kesselring Retail B.V.",
      discoveryDateTime: "2026-09-04T13:25:00Z",
      cause: "Phishing / credential compromise",
      dataTypes: ["Financial / payment data", "Names and contact details"],
      affectedCount: "More than 100,000",
      jurisdictions: ["Netherlands", "Belgium", "EU/EEA"],
      processorInvolved: true,
      processorName: "Delta Fulfilment Cloud B.V.",
      contained: "Yes",
      organisationType: "Company",
      encryptionStatus: "No affected data encrypted",
      encryptionKeyStatus: "Not applicable — no encryption",
      affectedRecordCount: "approx. 134,000 order and payment-reference records",
      affectedDataSubjectCount: "approx. 128,500 customers across the Netherlands and Belgium",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any external report of an exposed or misconfigured Kesselring cloud storage resource.",
        "Any finance-team report of a payment-redirection or invoice-fraud attempt referencing internal order data.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "Confirmed public exposure of customer order or payment data.", escalation: "Incident Lead notifies the Directie and the Functionaris Gegevensbescherming within 1 hour." },
        { level: "SEV-2", definition: "Suspected misconfiguration under verification.", escalation: "Incident Lead notifies the Head of Platform Engineering within 4 hours." },
      ],
      severityThresholds: ["SEV-1: confirmed public exposure of customer data.", "SEV-2: suspected misconfiguration, exposure unconfirmed."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "H. van der Berg (Head of Platform Engineering)", alternate: "M. Devos (Security Lead)" },
        { role: "Functionaris Gegevensbescherming (DPO)", primary: "L. Tijhuis", alternate: "external DPO service" },
        { role: "Communications", primary: "R. Aerts (Head of Communications)", alternate: "N/A" },
      ],
      outsideCounselName: "Van Riemsdijk Bosman Advocaten (Privacyrecht)",
      outsideCounselContact: "+31 20 555 0148; ir@vanriemsdijkbosman.example",
      privilegeProtocol: true,
      insurerContact: "Benelux Cyber Assurantiën, polis BCA-3391, schademelding +31 20 555 0177",
      forensicVendorContact: "Polderlicht Digital Forensics, raamovereenkomst PDF-2026-0061, +31 20 555 0122",
      lawEnforcementContact: "Politie Landelijke Eenheid, Cybercrimeteam",
      keySystems: ["Customer order database (cloud object storage, eu-west-1)", "Delta Fulfilment Cloud integration"],
      logSources: ["Cloud storage access logs (90-day retention, the gap that let the exposure run undetected for 10 days)", "Delta Fulfilment Cloud API logs"],
      itIsolationAuthority: "The Security Lead may restrict or revoke public access to any cloud storage bucket immediately upon report, without further approval.",
      breachNoticeContracts: [
        { counterparty: "Delta Fulfilment Cloud B.V. (processor)", deadline: "Without undue delay and in any event within 48 hours of awareness", clause: "Verwerkersovereenkomst art. 6" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve", "fh_isolate", "fh_dpo", "fh_counsel", "fh_scope"],
      nextTabletopDate: "2026-11-27",
    },
  },
  {
    id: "ir-playbook-p11-bracknell-financial-services",
    tool: "ir-playbook",
    label: "UK financial institution, uncontained ransomware, UK and Ireland jurisdictions",
    company: "Bracknell Financial Services Ltd",
    sector: "Wealth management and insurance",
    geo: "eu",
    summary: "A UK wealth-management firm's policy-administration system is hit by ransomware, encrypting core records with recovery still underway. Exercises the uncontained branch under UK GDPR and the ICO's separate 72-hour duty alongside an Irish subsidiary's Data Protection Commission notice, with a live clock and a compromised-key encryption posture.",
    intake: {
      organizationName: "Bracknell Financial Services Ltd",
      discoveryDateTime: "2026-09-13T05:20:00Z",
      cause: "Ransomware or malware",
      dataTypes: ["Financial / payment data", "Passwords / credentials", "Government IDs / SSN"],
      affectedCount: "10,000–100,000",
      jurisdictions: ["United Kingdom", "Ireland"],
      processorInvolved: true,
      processorName: "Helios Managed SOC Services Ltd",
      contained: "No",
      organisationType: "Financial institution",
      encryptionStatus: "Some affected data encrypted",
      encryptionKeyStatus: "Keys compromised or possibly compromised",
      affectedRecordCount: "approx. 41,000 policyholder records identified so far",
      affectedDataSubjectCount: "approx. 38,700 UK and Irish policyholders",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any ransomware note or mass-encryption event on the policy-administration system.",
        "Any unexplained failure of the nightly policy-data backup job.",
        "Any alert from Helios Managed SOC Services naming the policy database.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "Confirmed ransomware encryption of the policy-administration system.", escalation: "Incident Lead notifies the Chief Executive and the Senior Independent Director within 30 minutes; outside counsel engaged immediately." },
        { level: "SEV-2", definition: "Suspected compromise pending scope confirmation.", escalation: "Incident Lead notifies the Chief Risk Officer within 1 hour." },
      ],
      severityThresholds: ["SEV-1: confirmed encryption of policyholder records.", "SEV-2: suspected compromise, scope unconfirmed."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "H. Fairweather-Cole (Chief Risk Officer)", alternate: "D. Okonkwo-Barrett (Head of IT)" },
        { role: "Data Protection Officer", primary: "S. Ainsley (DPO, covering both the UK and Irish entities)", alternate: "external DPO service" },
        { role: "Legal", primary: "outside counsel", alternate: "N/A" },
      ],
      outsideCounselName: "Thackeray Voss LLP (Data Protection and Financial Regulation)",
      outsideCounselContact: "+44 20 7946 0155; ir@thackerayvoss.example",
      privilegeProtocol: true,
      insurerContact: "Britannia Specialty Cyber, policy BSC-6603, claims +44 20 7946 0188",
      forensicVendorContact: "Redcliffe Digital Forensics, retainer RDF-2026-0092, +44 161 496 0071",
      lawEnforcementContact: "Action Fraud and the National Crime Agency's cyber unit",
      keySystems: ["Policy-administration platform (on-premises, Reading data centre)", "Client-facing policyholder portal"],
      logSources: ["Windows Server event logs (90-day retention)", "Backup-job monitoring system alerts", "Firewall and VPN logs"],
      itIsolationAuthority: "The Head of IT may isolate any affected server segment immediately on the Incident Lead's instruction, with the policyholder portal taken offline as a precaution the same day.",
      breachNoticeContracts: [
        { counterparty: "Helios Managed SOC Services Ltd (managed security services processor)", deadline: "Within 24 hours of awareness", clause: "Managed Security Services Agreement §7" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve", "fh_isolate", "fh_dpo", "fh_counsel"],
      nextTabletopDate: "2026-10-14",
    },
  },
  {
    id: "ir-playbook-p12-solstice-sante",
    tool: "ir-playbook",
    label: "French healthcare provider, insider access after termination discovered late, elapsed clock",
    company: "Solstice Santé SAS",
    sector: "Telemedicine provider",
    geo: "eu",
    summary: "A French telemedicine provider discovers, during a quarterly access-rights audit three months after the fact, that a departed contractor's VPN credentials were never revoked and were used to download patient records. Exercises the already-elapsed clock, the insider-threat cause with a former (not current) worker, and special-category health data under a single EU jurisdiction.",
    intake: {
      organizationName: "Solstice Santé SAS",
      discoveryDateTime: "2026-06-10T10:00:00Z",
      cause: "Insider threat",
      dataTypes: ["Health / medical records", "Special category data", "Names and contact details"],
      affectedCount: "100–1,000",
      jurisdictions: ["France", "EU/EEA"],
      processorInvolved: true,
      processorName: "MedCloud France SAS",
      contained: "Yes",
      organisationType: "Healthcare provider",
      encryptionStatus: "Some affected data encrypted",
      encryptionKeyStatus: "Keys not compromised",
      affectedRecordCount: "approx. 340 patient consultation records",
      affectedDataSubjectCount: "approx. 340 telemedicine patients",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any quarterly access-rights audit finding an active credential belonging to a departed worker.",
        "Any VPN or EHR access event attributed to an account that should have been deprovisioned.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "Confirmed use of a departed worker's still-active credential to access patient records.", escalation: "Incident Lead notifies the Directeur Général and the Délégué à la protection des données within 4 hours." },
        { level: "SEV-2", definition: "A stale credential is found active but no access is confirmed.", escalation: "Logged by IT Security and reviewed at the monthly compliance meeting." },
      ],
      severityThresholds: ["SEV-1: confirmed unauthorized access using a stale credential.", "SEV-2: stale credential found, no confirmed access."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "C. Delaroche (Responsable IT Sécurité)", alternate: "M. Guillemot (Directrice des Opérations)" },
        { role: "Délégué à la protection des données (DPO)", primary: "A. Bertheaux", alternate: "external DPO service" },
        { role: "Legal", primary: "outside counsel", alternate: "N/A" },
      ],
      outsideCounselName: "Cabinet Larchevêque (Droit de la santé et données personnelles)",
      outsideCounselContact: "+33 1 84 55 0142; ir@larcheveque-avocats.example",
      privilegeProtocol: true,
      insurerContact: "Assurances Santé Numérique, police ASN-4471, sinistres +33 1 84 55 0177",
      forensicVendorContact: "Vigilance Numérique Forensique, contrat-cadre VNF-2026-0029, +33 1 84 55 0163",
      lawEnforcementContact: "Not contacted — internal audit trail was sufficient to bound the incident and no ongoing threat was identified",
      keySystems: ["Téléconsultation EHR platform (hosted by MedCloud France, HDS-certified)", "VPN remote-access gateway"],
      logSources: ["VPN authentication log (12-month retention)", "EHR access audit log (required under HDS certification, 10-year retention)"],
      itIsolationAuthority: "The Responsable IT Sécurité may revoke any credential immediately upon an audit finding; the contractor's VPN and EHR access were revoked the same day the audit finding was confirmed.",
      breachNoticeContracts: [
        { counterparty: "MedCloud France SAS (HDS-certified hosting processor)", deadline: "Within 48 hours of awareness", clause: "Contrat d'hébergement de données de santé, art. 6" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve", "fh_dpo"],
      nextTabletopDate: "2026-12-08",
    },
  },
  {
    id: "ir-playbook-p13-nordlicht-energi",
    tool: "ir-playbook",
    label: "Swedish utility, contained cyberattack on customer portal, live clock, processor involved",
    company: "Nordlicht Energi AB",
    sector: "Energy utility",
    geo: "eu",
    summary: "A Swedish energy utility contains a credential-stuffing attack against its smart-meter customer portal within hours, with its metering-data vendor also engaged as processor. Exercises a live clock, an EU-plus-Norway jurisdiction mix, and processor involvement in a utility-sector setting distinct from the panel's retail and financial scenarios.",
    intake: {
      organizationName: "Nordlicht Energi AB",
      discoveryDateTime: "2026-09-13T19:05:00Z",
      cause: "Unauthorized external access / cyberattack",
      dataTypes: ["Names and contact details", "Financial / payment data", "Location data"],
      affectedCount: "1,000–10,000",
      jurisdictions: ["Sweden", "EU/EEA", "Norway"],
      processorInvolved: true,
      processorName: "Fjordkraft Metering Data AS",
      contained: "Yes",
      organisationType: "Company",
      encryptionStatus: "All affected data encrypted / rendered unintelligible",
      encryptionKeyStatus: "Keys not compromised",
      affectedRecordCount: "approx. 4,600 customer portal accounts",
      affectedDataSubjectCount: "approx. 4,600 residential customers",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any spike in failed login attempts against the smart-meter customer portal exceeding the automated threshold.",
        "Any report from Fjordkraft Metering Data of anomalous access to shared metering records.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "Confirmed account takeover with access to billing or consumption data.", escalation: "Incident Lead notifies the VD (CEO) and Dataskyddsombud within 2 hours." },
        { level: "SEV-2", definition: "Elevated failed-login volume without confirmed takeover.", escalation: "Incident Lead notifies the IT-chef within 4 hours." },
      ],
      severityThresholds: ["SEV-1: confirmed account takeover.", "SEV-2: elevated failed-login volume, no confirmed takeover."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "E. Lindqvist (IT-chef)", alternate: "K. Sandström (Säkerhetsansvarig)" },
        { role: "Dataskyddsombud (DPO)", primary: "M. Öhrström", alternate: "external DPO service" },
      ],
      outsideCounselName: "Advokatfirman Norrsken (Dataskydd)",
      outsideCounselContact: "+46 8 555 0142; ir@norrsken-advokat.example",
      privilegeProtocol: true,
      insurerContact: "Nordisk Cyberförsäkring, försäkring NCF-8814, skadeanmälan +46 8 555 0177",
      forensicVendorContact: "Polarnatt Digital Forensik, ramavtal PDF-2026-0047, +46 8 555 0163",
      lawEnforcementContact: "Polisen, IT-brottsenheten",
      keySystems: ["Smart-meter customer portal", "Fjordkraft Metering Data integration", "Billing system"],
      logSources: ["Customer-portal authentication log (12-month retention)", "Fjordkraft metering-access log", "WAF and CDN request logs"],
      itIsolationAuthority: "The Säkerhetsansvarig may force a password reset across the customer portal and enable step-up authentication immediately upon detecting an attack pattern.",
      breachNoticeContracts: [
        { counterparty: "Fjordkraft Metering Data AS (processor)", deadline: "Without undue delay and in any event within 48 hours of awareness", clause: "Personuppgiftsbiträdesavtal §6" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve", "fh_isolate", "fh_dpo"],
      nextTabletopDate: "2026-11-19",
    },
  },
  {
    id: "ir-playbook-p14-clontarf-insurance",
    tool: "ir-playbook",
    label: "Irish insurer, small-scale accidental disclosure via mail-merge error, contained, live clock",
    company: "Clontarf Insurance Ltd",
    sector: "Personal lines insurance",
    geo: "eu",
    summary: "An Irish insurer's renewal mailing run misattaches a handful of policyholders' medical-underwriting attachments to the wrong recipients due to a mail-merge error, caught the same afternoon. Exercises the smallest affected-count band alongside health and financial data together, a live clock, and a UK-plus-Ireland-plus-EU jurisdiction spread reflecting the insurer's cross-border book.",
    intake: {
      organizationName: "Clontarf Insurance Ltd",
      discoveryDateTime: "2026-09-13T15:50:00Z",
      cause: "Accidental disclosure",
      dataTypes: ["Financial / payment data", "Health / medical records", "Names and contact details"],
      affectedCount: "Fewer than 100",
      jurisdictions: ["Ireland", "EU/EEA", "United Kingdom"],
      processorInvolved: true,
      processorName: "Emerald Isle Print & Mail Services Ltd",
      contained: "Yes",
      organisationType: "Financial institution",
      encryptionStatus: "No affected data encrypted",
      encryptionKeyStatus: "Not applicable — no encryption",
      affectedRecordCount: "17 policy-renewal letters with a mismatched medical-underwriting attachment",
      affectedDataSubjectCount: "17 policyholders",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any policyholder report of receiving another customer's renewal documentation.",
        "Any mail-merge or print-run reconciliation discrepancy identified before dispatch is complete.",
      ],
      severityMatrix: [
        { level: "SEV-2", definition: "A mail-merge error sends fewer than 100 policyholders' documents to the wrong recipient.", escalation: "Incident Lead notifies the Head of Compliance within 4 hours." },
        { level: "SEV-1", definition: "A mail-merge or system error sends documents to 100 or more incorrect recipients.", escalation: "Incident Lead notifies the Chief Executive within 2 hours." },
      ],
      severityThresholds: ["SEV-1: 100 or more policyholders affected.", "SEV-2: fewer than 100 policyholders affected."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "N. Fitzsimons (Head of Compliance)", alternate: "O. Brennan-Doyle (Operations Manager)" },
        { role: "Data Protection Officer", primary: "R. Casey", alternate: "external DPO service" },
      ],
      outsideCounselName: "Handled in-house; outside counsel on standby retainer",
      outsideCounselContact: "Mallon Geoghegan LLP, +353 1 555 0148",
      privilegeProtocol: false,
      insurerContact: "Emerald Mutual Assurance E&O cover, policy EMA-2291, claims +353 1 555 0177",
      forensicVendorContact: "Not engaged — a print-vendor reconciliation report was sufficient to identify the 17 affected letters",
      lawEnforcementContact: "Not applicable",
      keySystems: ["Policy-renewal mail-merge system", "Emerald Isle Print & Mail Services vendor portal"],
      logSources: ["Print-vendor dispatch reconciliation report", "Policy administration system change log"],
      itIsolationAuthority: "The Operations Manager may halt any in-progress mail-merge run immediately on discovery of a mismatch; the remaining un-dispatched batch was held the same afternoon.",
      breachNoticeContracts: [
        { counterparty: "Emerald Isle Print & Mail Services Ltd (print and mailing processor)", deadline: "Within 5 business days of awareness", clause: "Print and Fulfilment Services Agreement §9" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_preserve", "fh_dpo"],
      nextTabletopDate: "2027-02-03",
    },
  },
  {
    id: "ir-playbook-p15-wexford-county-council",
    tool: "ir-playbook",
    label: "Irish public authority, children's-services device loss discovered late during asset audit",
    company: "Wexford County Council",
    sector: "Local government / children's services",
    geo: "eu",
    summary: "An Irish county council discovers, weeks after the fact during a routine asset audit, that a children's-services caseworker's laptop containing case files went missing. Exercises the already-elapsed clock, the public-authority organisation type, children's data, and a single-jurisdiction Irish record distinct from the panel's corporate scenarios.",
    intake: {
      organizationName: "Wexford County Council",
      discoveryDateTime: "2026-08-11T09:30:00Z",
      cause: "Lost or stolen device",
      dataTypes: ["Names and contact details", "Children's data"],
      affectedCount: "Fewer than 100",
      jurisdictions: ["Ireland"],
      processorInvolved: true,
      processorName: "Sceim Case Management Solutions Ltd",
      contained: "Yes",
      organisationType: "Public authority",
      encryptionStatus: "No affected data encrypted",
      encryptionKeyStatus: "Not applicable — no encryption",
      affectedRecordCount: "23 children's-services case files",
      affectedDataSubjectCount: "23 children and their guardians named in the case files",
      awarenessConfirmed: "Confirmed — discovery timestamp verified as the moment of awareness",
      activationCriteria: [
        "Any asset-audit discrepancy involving a device known to hold children's-services case files.",
        "Any caseworker report of a lost or stolen Council device.",
      ],
      severityMatrix: [
        { level: "SEV-1", definition: "A lost or stolen device is confirmed to hold children's-services case files.", escalation: "Incident Lead notifies the Director of Services and the Data Protection Officer within 4 hours." },
        { level: "SEV-2", definition: "A lost device is confirmed to hold no case-file data.", escalation: "Logged by IT; reviewed at the monthly asset-management meeting." },
      ],
      severityThresholds: ["SEV-1: confirmed case-file data on the lost device.", "SEV-2: no case-file data confirmed on the device."],
      responseTeamRoster: [
        { role: "Incident Lead", primary: "B. Kinsella (Director of Children and Family Services)", alternate: "N. Whelan (IT Officer)" },
        { role: "Data Protection Officer", primary: "C. Prendergast", alternate: "N/A" },
      ],
      outsideCounselName: "County Solicitor's office handles this matter in-house",
      outsideCounselContact: "+353 53 555 0119",
      privilegeProtocol: false,
      insurerContact: "Local Government Management Agency risk pool, claims +353 1 555 0166",
      forensicVendorContact: "Not engaged — device held local encrypted-container storage only for unrelated files; the case-file access was via an unencrypted local cache, per the IT Officer's device audit",
      lawEnforcementContact: "An Garda Síochána, incident report filed on the day of discovery",
      keySystems: ["Children's-services case-management system (hosted by Sceim Case Management Solutions)", "Caseworker mobile device fleet"],
      logSources: ["Mobile device management asset log", "Case-management system access log (7-year retention)"],
      itIsolationAuthority: "The IT Officer may remotely wipe any lost Council device once mobile-device management confirms the device's last check-in; the missing laptop's wipe command was issued the day it was reported missing during the audit.",
      breachNoticeContracts: [
        { counterparty: "Sceim Case Management Solutions Ltd (case-management hosting processor)", deadline: "Within 5 business days of awareness", clause: "Hosting and Support Agreement §7" },
      ],
      firstHourConfirmations: ["fh_activate", "fh_clock", "fh_dpo"],
      nextTabletopDate: "2026-12-19",
    },
  },
];
