// /all-ptest fixture panel — registration. Fifteen complete, internally consistent
// intakes authored 2026-09-14 (see ./types.ts and scripts/ptest/PANEL-BRIEF.md).
// Validated by tests/edge/ptest/panels.test.ts.
//
// Contract: supabase/functions/run-stress-job/_local/intake-contracts/registration-assessment.ts
// (registrationContract). run-stress-job passes the intake straight through
// as run-registration-assessment's `intake_data` (no reshaping), so every key
// here is one the engine (_shared/registration-engine.ts) reads directly.
// Numeric fields are emitted as JS numbers, matching the form's parsed
// submit payload. Every organisation is EU/UK (geo "eu"): legal-form suffix
// matches its country (GmbH -> Germany, B.V. -> Netherlands, Ltd -> Great
// Britain, S.r.l. -> Italy, AG -> Austria, S.L. -> Spain, SAS -> France, AB
// -> Sweden); public authorities and a public university/health service are
// named without a corporate suffix, matching how such bodies actually name
// themselves.

import type { PanelFixture } from "./types.ts";

export const PANEL_REGISTRATION: PanelFixture[] = [
  {
    id: "registration-p01-gemeente-doverbeek",
    tool: "registration",
    label: "Dutch municipality deploying an AI benefits-fraud detection tool",
    company: "Gemeente Doverbeek",
    sector: "Local government / public sector",
    geo: "eu",
    summary:
      "Gemeente Doverbeek, a Dutch municipal authority, runs youth and social-welfare services and deploys a third-party AI system to flag possible social-benefits fraud. Exercises the public-authority branch, special-category and children's data, large-scale CCTV/parking monitoring, and an AI high-risk deployer role that is not a critical-infrastructure safety component.",
    intake: {
      organization_name: "Gemeente Doverbeek",
      is_public_authority: true,
      organization_country: "NL",
      organization_size: "medium",
      industry: "Public sector",
      email: "privacy@doverbeek-gemeente.example",
      employee_count: 640,
      annual_revenue_usd: 210000000,
      data_subjects_count: 84000,
      role: "controller",
      processes_personal_data: true,
      processes_special_categories: true,
      processes_children_data: true,
      large_scale_monitoring: true,
      uses_ai_systems: true,
      ai_high_risk: true,
      ai_high_risk_role: "deployer",
      ai_annex_iii_point_2: "no",
      ai_general_purpose_provider: false,
      cross_border_transfers: false,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: false,
      has_eu_establishment: true,
      has_uk_establishment: false,
      eu_lead_member_state: "NL",
      markets_served: ["NL"],
      approved_by_name: "Marieke van Dillen",
      approved_by_title: "Chief Privacy Officer",
      approval_date: "2026-06-02",
      next_review_due: "2027-06-02",
    },
  },
  {
    id: "registration-p02-ostkuesten-technische-universitaet",
    tool: "registration",
    label: "German public university using AI-proctored exams with facial verification",
    company: "Ostküsten Technische Universität",
    sector: "Public higher education",
    geo: "eu",
    summary:
      "Ostküsten Technische Universität is a German public university whose AI-proctoring vendor performs facial verification during remote exams and whose Erasmus exchange programme sends student records to a UK partner. Exercises the public-authority branch, biometric identity verification, an AI high-risk deployer role, and a cross-border transfer to a non-EU market.",
    intake: {
      organization_name: "Ostküsten Technische Universität",
      is_public_authority: true,
      organization_country: "DE",
      organization_size: "large",
      industry: "Education",
      email: "datenschutz@ostkuesten-tu.example",
      employee_count: 3400,
      annual_revenue_usd: 410000000,
      data_subjects_count: 26000,
      role: "controller",
      processes_personal_data: true,
      processes_special_categories: true,
      processes_children_data: false,
      large_scale_monitoring: false,
      uses_ai_systems: true,
      ai_high_risk: true,
      ai_high_risk_role: "deployer",
      ai_annex_iii_point_2: "no",
      ai_general_purpose_provider: false,
      cross_border_transfers: true,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: true,
      has_eu_establishment: true,
      has_uk_establishment: false,
      eu_lead_member_state: "DE",
      markets_served: ["DE", "UK"],
      approved_by_name: "Prof. Dr. Henrike Sassen",
      approved_by_title: "Data Protection Officer",
      approval_date: "2026-05-14",
      next_review_due: "2027-05-14",
    },
  },
  {
    id: "registration-p03-vantaggio-vision",
    tool: "registration",
    label: "Italian facial-verification AI vendor selling to banks across the EU",
    company: "Vantaggio Vision S.r.l.",
    sector: "Computer-vision AI software",
    geo: "eu",
    summary:
      "Vantaggio Vision builds a facial-verification API that banks embed in their own onboarding flows, and trains its models on a licensed biometric image dataset hosted on US cloud infrastructure. Exercises a private AI-provider role for a high-risk biometric-identification system, a controller-and-processor dual role, and a cross-border transfer under contract.",
    intake: {
      organization_name: "Vantaggio Vision S.r.l.",
      is_public_authority: false,
      organization_country: "IT",
      organization_size: "small",
      industry: "SaaS / Software",
      email: "privacy@vantaggiovision.example",
      employee_count: 38,
      annual_revenue_usd: 6200000,
      data_subjects_count: 450000,
      role: "both",
      processes_personal_data: true,
      processes_special_categories: true,
      processes_children_data: false,
      large_scale_monitoring: false,
      uses_ai_systems: true,
      ai_high_risk: true,
      ai_high_risk_role: "provider",
      ai_annex_iii_point_2: "no",
      ai_general_purpose_provider: false,
      cross_border_transfers: true,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: true,
      has_eu_establishment: true,
      has_uk_establishment: false,
      eu_lead_member_state: "IT",
      markets_served: ["IT", "DE", "FR", "ES"],
      approved_by_name: "Lorenzo Basile",
      approved_by_title: "Chief Executive Officer",
      approval_date: "2026-04-20",
      next_review_due: "2027-04-20",
    },
  },
  {
    id: "registration-p04-kaerntner-stromnetz",
    tool: "registration",
    label: "Austrian electricity grid operator with an AI safety-component system",
    company: "Kärntner Stromnetz AG",
    sector: "Electricity grid utility",
    geo: "eu",
    summary:
      "Kärntner Stromnetz operates the regional electricity distribution grid and built its own AI-based automated load-shedding safety system, which registers at the national level as a critical-infrastructure safety component rather than in the EU high-risk database. Exercises the AI Annex III point 2 branch (answered yes, unlike every other fixture in this panel), a private controller with no cross-border transfer, and no data-broker or biometric activity.",
    intake: {
      organization_name: "Kärntner Stromnetz AG",
      is_public_authority: false,
      organization_country: "AT",
      organization_size: "medium",
      industry: "Other",
      email: "datenschutz@kaerntner-stromnetz.example",
      employee_count: 910,
      annual_revenue_usd: 340000000,
      data_subjects_count: 610000,
      role: "controller",
      processes_personal_data: true,
      processes_special_categories: false,
      processes_children_data: false,
      large_scale_monitoring: false,
      uses_ai_systems: true,
      ai_high_risk: true,
      ai_high_risk_role: "provider",
      ai_annex_iii_point_2: "yes",
      ai_general_purpose_provider: false,
      cross_border_transfers: false,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: false,
      has_eu_establishment: true,
      has_uk_establishment: false,
      eu_lead_member_state: "AT",
      markets_served: ["AT"],
      approved_by_name: "Dieter Falkner",
      approved_by_title: "Head of Compliance",
      approval_date: "2026-07-01",
      next_review_due: "2027-07-01",
    },
  },
  {
    id: "registration-p05-agence-emploi-numerique",
    tool: "registration",
    label: "French national employment agency deploying AI job-matching",
    company: "Agence Nationale pour l'Emploi Numérique",
    sector: "Public employment services",
    geo: "eu",
    summary:
      "Agence Nationale pour l'Emploi Numérique is a French public employment agency using an AI system to match jobseekers, including those declaring a disability status, to open roles. Exercises the public-authority branch alongside special-category data, an AI high-risk deployer role for an employment-access system, and a domestic-only, non-broker processing footprint.",
    intake: {
      organization_name: "Agence Nationale pour l'Emploi Numérique",
      is_public_authority: true,
      organization_country: "FR",
      organization_size: "large",
      industry: "Public sector",
      email: "protection-donnees@anen.example",
      employee_count: 5200,
      annual_revenue_usd: 890000000,
      data_subjects_count: 3100000,
      role: "controller",
      processes_personal_data: true,
      processes_special_categories: true,
      processes_children_data: false,
      large_scale_monitoring: false,
      uses_ai_systems: true,
      ai_high_risk: true,
      ai_high_risk_role: "deployer",
      ai_annex_iii_point_2: "no",
      ai_general_purpose_provider: false,
      cross_border_transfers: false,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: false,
      has_eu_establishment: true,
      has_uk_establishment: false,
      eu_lead_member_state: "FR",
      markets_served: ["FR"],
      approved_by_name: "Sophie Marchetti",
      approved_by_title: "Déléguée à la protection des données",
      approval_date: "2026-03-11",
      next_review_due: "2027-03-11",
    },
  },
  {
    id: "registration-p06-meridiana-audience-insights",
    tool: "registration",
    label: "Dutch audience-data broker licensing profiles into US markets",
    company: "Meridiana Audience Insights B.V.",
    sector: "Data broker / audience analytics",
    geo: "eu",
    summary:
      "Meridiana Audience Insights aggregates consumer profiles from partner websites it has no direct relationship with and licenses them to advertisers in the EU and to buyers in California, Texas, and Vermont. Exercises the data-broker branch in full (thresholds, exemption claim, and filing-readiness flags) on an EU-established controller with no AI high-risk system.",
    intake: {
      organization_name: "Meridiana Audience Insights B.V.",
      is_public_authority: false,
      organization_country: "NL",
      organization_size: "medium",
      industry: "AdTech / MarTech",
      email: "privacy@meridianainsights.example",
      employee_count: 260,
      annual_revenue_usd: 58000000,
      data_subjects_count: 9200000,
      role: "controller",
      processes_personal_data: true,
      processes_special_categories: false,
      processes_children_data: false,
      large_scale_monitoring: true,
      uses_ai_systems: true,
      ai_high_risk: false,
      ai_general_purpose_provider: false,
      cross_border_transfers: true,
      acts_as_data_broker: true,
      sells_or_shares_personal_info: true,
      processes_biometrics_for_id: false,
      collects_data_not_directly_from_individuals: true,
      has_direct_relationship_with_data_subjects: false,
      sells_or_licenses_brokered_data: true,
      brokered_data_individual_count: 2800000,
      brokered_data_revenue_share_pct: 65,
      data_broker_exemption_claimed: "none",
      filing_contact_details_ready: true,
      filing_opt_out_mechanism_documented: true,
      filing_minors_data_practices_documented: true,
      filing_metrics_documented: true,
      filing_rights_instructions_documented: true,
      filing_tx_categories_documented: true,
      filing_tx_credentialing_statement_documented: true,
      filing_tx_breach_count_documented: true,
      has_eu_establishment: true,
      has_uk_establishment: false,
      eu_lead_member_state: "NL",
      markets_served: ["NL", "DE", "US-CA", "US-TX", "US-VT"],
      approved_by_name: "Willem de Groot",
      approved_by_title: "Head of Data Governance",
      approval_date: "2026-06-25",
      next_review_due: "2027-06-25",
    },
  },
  {
    id: "registration-p07-cronwell-insurance-data",
    tool: "registration",
    label: "UK insurance-data aggregator claiming a statutory broker exemption",
    company: "Cronwell Insurance Data Services Ltd",
    sector: "Insurance data services",
    geo: "eu",
    summary:
      "Cronwell Insurance Data Services aggregates policyholder claims data across its US-affiliated insurers' UK book of business and shares it within the group for underwriting, claiming an insurance-industry statutory exemption from broker registration. Exercises the UK-establishment (no EU establishment) branch, a claimed data-broker exemption rather than a plain no, and a controller-and-processor dual role.",
    intake: {
      organization_name: "Cronwell Insurance Data Services Ltd",
      is_public_authority: false,
      organization_country: "GB",
      organization_size: "medium",
      industry: "Financial services",
      email: "privacy@cronwelldata.example",
      employee_count: 175,
      annual_revenue_usd: 41000000,
      data_subjects_count: 540000,
      role: "both",
      processes_personal_data: true,
      processes_special_categories: false,
      processes_children_data: false,
      large_scale_monitoring: false,
      uses_ai_systems: false,
      ai_high_risk: false,
      ai_general_purpose_provider: false,
      cross_border_transfers: true,
      acts_as_data_broker: true,
      sells_or_shares_personal_info: true,
      processes_biometrics_for_id: false,
      collects_data_not_directly_from_individuals: true,
      has_direct_relationship_with_data_subjects: false,
      sells_or_licenses_brokered_data: true,
      brokered_data_individual_count: 540000,
      brokered_data_revenue_share_pct: 22,
      data_broker_exemption_claimed: "insurance",
      filing_contact_details_ready: true,
      filing_opt_out_mechanism_documented: false,
      has_eu_establishment: false,
      has_uk_establishment: true,
      markets_served: ["UK", "US-CA"],
      approved_by_name: "Harriet Colby",
      approved_by_title: "Group Data Protection Lead",
      approval_date: "2026-05-05",
      next_review_due: "2027-05-05",
    },
  },
  {
    id: "registration-p08-tindaya-legal-translations",
    tool: "registration",
    label: "Micro Spanish translation agency processing client documents as a processor",
    company: "Tindaya Legal Translations S.L.",
    sector: "Legal translation services",
    geo: "eu",
    summary:
      "Tindaya Legal Translations is a six-person Spanish agency that translates litigation and contract documents supplied by law-firm clients and processes the personal data those documents contain solely on the clients' instructions. Exercises the pure-processor role branch, a micro organisation size, and a minimal, single-market, non-AI, non-broker record.",
    intake: {
      organization_name: "Tindaya Legal Translations S.L.",
      is_public_authority: false,
      organization_country: "ES",
      organization_size: "micro",
      industry: "Other",
      email: "privacidad@tindayatraducciones.example",
      employee_count: 6,
      annual_revenue_usd: 480000,
      data_subjects_count: 1200,
      role: "processor",
      processes_personal_data: true,
      processes_special_categories: false,
      processes_children_data: false,
      large_scale_monitoring: false,
      uses_ai_systems: false,
      ai_high_risk: false,
      ai_general_purpose_provider: false,
      cross_border_transfers: false,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: false,
      has_eu_establishment: true,
      has_uk_establishment: false,
      eu_lead_member_state: "ES",
      markets_served: ["ES"],
      approved_by_name: "Nuria Peralta",
      approved_by_title: "Owner / Managing Director",
      approval_date: "2026-08-02",
      next_review_due: "2027-08-02",
    },
  },
  {
    id: "registration-p09-klarwind-learning",
    tool: "registration",
    label: "Dutch edtech provider with an AI automated-assessment product",
    company: "Klarwind Learning B.V.",
    sector: "K-12 education technology",
    geo: "eu",
    summary:
      "Klarwind Learning sells an AI-based automated essay-scoring product to secondary schools across the Benelux and hosts grading infrastructure with a non-EU cloud provider. Exercises children's personal data, an AI high-risk provider role for an educational-assessment system, and a cross-border transfer on a small-company record.",
    intake: {
      organization_name: "Klarwind Learning B.V.",
      is_public_authority: false,
      organization_country: "NL",
      organization_size: "small",
      industry: "Education",
      email: "privacy@klarwindlearning.example",
      employee_count: 47,
      annual_revenue_usd: 5100000,
      data_subjects_count: 180000,
      role: "controller",
      processes_personal_data: true,
      processes_special_categories: false,
      processes_children_data: true,
      large_scale_monitoring: false,
      uses_ai_systems: true,
      ai_high_risk: true,
      ai_high_risk_role: "provider",
      ai_annex_iii_point_2: "no",
      ai_general_purpose_provider: false,
      cross_border_transfers: true,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: false,
      has_eu_establishment: true,
      has_uk_establishment: false,
      eu_lead_member_state: "NL",
      markets_served: ["NL", "DE", "BE"],
      approved_by_name: "Sanne Willemsen",
      approved_by_title: "Founder & Data Protection Lead",
      approval_date: "2026-06-18",
      next_review_due: "2027-06-18",
    },
  },
  {
    id: "registration-p10-solvane-biometrics",
    tool: "registration",
    label: "Swedish workplace biometric access-control vendor across the Nordics",
    company: "Solvane Biometrics AB",
    sector: "Physical security / biometric access control",
    geo: "eu",
    summary:
      "Solvane Biometrics builds fingerprint and facial-recognition access-control terminals that it both manufactures and operates as a managed service for Nordic corporate clients. Exercises biometric identification, special-category data, an AI high-risk provider role, and a controller-and-processor dual role across a Nordic-only, no-transfer footprint.",
    intake: {
      organization_name: "Solvane Biometrics AB",
      is_public_authority: false,
      organization_country: "SE",
      organization_size: "small",
      industry: "SaaS / Software",
      email: "privacy@solvanebiometrics.example",
      employee_count: 52,
      annual_revenue_usd: 8900000,
      data_subjects_count: 95000,
      role: "both",
      processes_personal_data: true,
      processes_special_categories: true,
      processes_children_data: false,
      large_scale_monitoring: false,
      uses_ai_systems: true,
      ai_high_risk: true,
      ai_high_risk_role: "provider",
      ai_annex_iii_point_2: "no",
      ai_general_purpose_provider: false,
      cross_border_transfers: false,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: true,
      has_eu_establishment: true,
      has_uk_establishment: false,
      eu_lead_member_state: "SE",
      markets_served: ["SE", "NO", "FI"],
      approved_by_name: "Anneli Ström",
      approved_by_title: "Chief Technology Officer",
      approval_date: "2026-04-09",
      next_review_due: "2027-04-09",
    },
  },
  {
    id: "registration-p11-cassiopee-langue-artificielle",
    tool: "registration",
    label: "French general-purpose AI language-model provider",
    company: "Cassiopée Langue Artificielle SAS",
    sector: "Artificial intelligence / foundation models",
    geo: "eu",
    summary:
      "Cassiopée Langue Artificielle trains and licenses a general-purpose French-language foundation model, using leased US GPU infrastructure for training runs. Exercises the general-purpose-AI-provider branch (distinct from an Annex III high-risk system), a controller role, and a cross-border transfer for model training.",
    intake: {
      organization_name: "Cassiopée Langue Artificielle SAS",
      is_public_authority: false,
      organization_country: "FR",
      organization_size: "medium",
      industry: "SaaS / Software",
      email: "confidentialite@cassiopee-ai.example",
      employee_count: 130,
      annual_revenue_usd: 22000000,
      data_subjects_count: 3400000,
      role: "controller",
      processes_personal_data: true,
      processes_special_categories: false,
      processes_children_data: false,
      large_scale_monitoring: false,
      uses_ai_systems: true,
      ai_high_risk: false,
      ai_general_purpose_provider: true,
      cross_border_transfers: true,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: false,
      has_eu_establishment: true,
      has_uk_establishment: false,
      eu_lead_member_state: "FR",
      markets_served: ["FR", "DE", "IE", "US"],
      approved_by_name: "Mathis Guerin",
      approved_by_title: "Head of AI Governance",
      approval_date: "2026-07-22",
      next_review_due: "2027-07-22",
    },
  },
  {
    id: "registration-p12-bramleigh-analytics",
    tool: "registration",
    label: "UK marketing-analytics firm unsure of its role on a white-labelled AI module",
    company: "Bramleigh Analytics Ltd",
    sector: "Marketing analytics",
    geo: "eu",
    summary:
      "Bramleigh Analytics recently white-labelled a third-party AI candidate-screening module into its HR-marketing product suite and has not yet determined whether it is a provider or a deployer of that high-risk system. Exercises UK establishment with no EU establishment, an unsure AI high-risk role, and a cross-border transfer.",
    intake: {
      organization_name: "Bramleigh Analytics Ltd",
      is_public_authority: false,
      organization_country: "GB",
      organization_size: "small",
      industry: "AdTech / MarTech",
      email: "privacy@bramleighanalytics.example",
      employee_count: 34,
      annual_revenue_usd: 4200000,
      data_subjects_count: 210000,
      role: "controller",
      processes_personal_data: true,
      processes_special_categories: false,
      processes_children_data: false,
      large_scale_monitoring: false,
      uses_ai_systems: true,
      ai_high_risk: true,
      ai_high_risk_role: "unsure",
      ai_annex_iii_point_2: "no",
      ai_general_purpose_provider: false,
      cross_border_transfers: true,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: false,
      has_eu_establishment: false,
      has_uk_establishment: true,
      markets_served: ["UK", "IE", "DE"],
      approved_by_name: "Oliver Fenchurch",
      approved_by_title: "Operations Director",
      approval_date: "2026-08-14",
      next_review_due: "2027-08-14",
    },
  },
  {
    id: "registration-p13-servizio-sanitario-emilia",
    tool: "registration",
    label: "Italian regional health authority using AI diagnostic triage on pediatric cases",
    company: "Servizio Sanitario Regionale Emilia — Direzione Digitale",
    sector: "Public healthcare",
    geo: "eu",
    summary:
      "Servizio Sanitario Regionale Emilia is a regional public health authority whose emergency departments, including pediatric units, use an AI triage-priority system on patient vitals. Exercises the public-authority branch, special-category health data, children's data, an AI high-risk deployer role, and a large, domestic-only enterprise record.",
    intake: {
      organization_name: "Servizio Sanitario Regionale Emilia — Direzione Digitale",
      is_public_authority: true,
      organization_country: "IT",
      organization_size: "enterprise",
      industry: "Healthcare",
      email: "protezionedati@ssr-emilia.example",
      employee_count: 24000,
      annual_revenue_usd: 3200000000,
      data_subjects_count: 4400000,
      role: "controller",
      processes_personal_data: true,
      processes_special_categories: true,
      processes_children_data: true,
      large_scale_monitoring: false,
      uses_ai_systems: true,
      ai_high_risk: true,
      ai_high_risk_role: "deployer",
      ai_annex_iii_point_2: "no",
      ai_general_purpose_provider: false,
      cross_border_transfers: false,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: false,
      has_eu_establishment: true,
      has_uk_establishment: false,
      eu_lead_member_state: "IT",
      markets_served: ["IT"],
      approved_by_name: "Dott.ssa Francesca Iovine",
      approved_by_title: "Responsabile della Protezione dei Dati",
      approval_date: "2026-02-27",
      next_review_due: "2027-02-27",
    },
  },
  {
    id: "registration-p14-fenwick-loach-bookkeeping",
    tool: "registration",
    label: "Small UK bookkeeping firm with a minimal, single-market record",
    company: "Fenwick & Loach Bookkeeping Ltd",
    sector: "Accounting and bookkeeping services",
    geo: "eu",
    summary:
      "Fenwick & Loach Bookkeeping is a nine-person UK firm serving local small-business clients with no AI systems, no cross-border transfers, and no data-broker activity. Exercises the minimal-footprint branch — a small, UK-only, controller-only record with every high-risk flag answered no.",
    intake: {
      organization_name: "Fenwick & Loach Bookkeeping Ltd",
      is_public_authority: false,
      organization_country: "GB",
      organization_size: "small",
      industry: "Other",
      email: "privacy@fenwickloach.example",
      employee_count: 9,
      annual_revenue_usd: 890000,
      data_subjects_count: 640,
      role: "controller",
      processes_personal_data: true,
      processes_special_categories: false,
      processes_children_data: false,
      large_scale_monitoring: false,
      uses_ai_systems: false,
      ai_high_risk: false,
      ai_general_purpose_provider: false,
      cross_border_transfers: false,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: false,
      has_eu_establishment: false,
      has_uk_establishment: true,
      markets_served: ["UK"],
      approved_by_name: "Rosalind Fenwick",
      approved_by_title: "Partner",
      approval_date: "2026-07-30",
      next_review_due: "2027-07-30",
    },
  },
  {
    id: "registration-p15-corvenna-people-analytics",
    tool: "registration",
    label: "German HR-tech SaaS with EU and UK establishments and a dual AI role",
    company: "Corvenna People Analytics GmbH",
    sector: "Human resources technology",
    geo: "eu",
    summary:
      "Corvenna People Analytics is a German HR-tech company with a Frankfurt headquarters and a London subsidiary that both licenses an AI hiring-screening product to enterprise clients and uses the same product for its own recruitment. Exercises the both-EU-and-UK-establishment branch, a both provider-and-deployer AI role, and a controller-and-processor dual role.",
    intake: {
      organization_name: "Corvenna People Analytics GmbH",
      is_public_authority: false,
      organization_country: "DE",
      organization_size: "large",
      industry: "SaaS / Software",
      email: "datenschutz@corvenna.example",
      employee_count: 890,
      annual_revenue_usd: 96000000,
      data_subjects_count: 1400000,
      role: "both",
      processes_personal_data: true,
      processes_special_categories: false,
      processes_children_data: false,
      large_scale_monitoring: false,
      uses_ai_systems: true,
      ai_high_risk: true,
      ai_high_risk_role: "both",
      ai_annex_iii_point_2: "no",
      ai_general_purpose_provider: false,
      cross_border_transfers: true,
      acts_as_data_broker: false,
      sells_or_shares_personal_info: false,
      processes_biometrics_for_id: false,
      has_eu_establishment: true,
      has_uk_establishment: true,
      eu_lead_member_state: "DE",
      markets_served: ["DE", "UK", "FR", "NL"],
      approved_by_name: "Katrin Lindemann",
      approved_by_title: "Global Data Protection Officer",
      approval_date: "2026-05-30",
      next_review_due: "2027-05-30",
    },
  },
];
