// DPIA ANALOGY HOOKS — pinned, generated file (doc 213 / doc 222).
//
// Generated by `generate-corpus-hooks` (action "generate") from RATIFIED
// `public.authority_hooks` rows. Do not hand-edit the hooks array:
// regenerate it. Run: dpia-hooks-v2-2026-09-09-0
//
// EXCLUDED ROWS (named, not silently dropped):
//   (none)

import type { AuthorityHook } from "../../../../_shared/corpus/hook-types.ts";


export const DPIA_HOOKS_VERSION = "dpia-hooks-v2-2026-09-09-0";

export const DPIA_HOOKS: readonly AuthorityHook[] = [
  {
    "hook_id": "enforcement_actions:0675e6a0-66ba-4173-8bce-be113e70604e:v1",
    "profile_id": "2e10ae4c-73f4-49ad-a72b-cfe2e2f25e05",
    "source_row_id": "0675e6a0-66ba-4173-8bce-be113e70604e",
    "fact_atoms": [
      "flag:children"
    ],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [
      "flag:children"
    ],
    "finding_span": "MediaLab failed to carry out a DPIA prior to engaging in a form of high risk processing, specifically, processing the personal data of children under the age of 18 where it intended to offer online services to those children, placing MediaLab in breach of Article 35(1) UK GDPR.",
    "fact_pattern_paraphrase": "an online service offered to children under 18 without a DPIA for that high-risk processing and with no way of verifying age or obtaining parental consent",
    "finding_paraphrase": "offering an online service to children without a DPIA for that high-risk processing breaches Article 35(1) UK GDPR",
    "settledness": "R3",
    "posture": "rejected",
    "factor_id": "the children's-data trigger",
    "bears_on_element": "obligation",
    "authority_label": "ICO, MediaLab.AI, Inc., decision of 4 February 2026",
    "regulator": "ICO",
    "relevance": {
      "instrument": "UK GDPR",
      "factor_ids": [
        "the children's-data trigger"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [
        "children_data"
      ],
      "outcome_posture": "rejected"
    },
    "authority_label_short": "ICO, MediaLab.AI, Inc.",
    "hook_version": 1,
    "source_status": "sa_decision",
    "status_label": "supervisory-authority decision — persuasive, non-binding outside its jurisdiction",
    "verb": "found",
    "appeal_note": null,
    "verified_as_of": null,
    "pinpoint": {
      "kind": "field",
      "ref": "source_document_text",
      "anchor_span": "MediaLab failed to carry out a DPIA prior to engaging in a form of high risk processing, specifically, processing the personal data of children under the age of 18 where it intended to offer online services to those children, placing MediaLab in breach of Article 35(1) UK GDPR."
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The record describes an online platform or service that children under 18 can access. In its decision on MediaLab.AI (operator of Imgur), the UK Information Commissioner's Office found that offering an online service to children without a DPIA for that high-risk processing breaches Article 35(1) UK GDPR. It also found that consent does not work as the lawful basis when the platform has no way of verifying a user's age or obtaining parental consent for younger users. That finding cuts against the company's position here. But the outcome depends on this company's own facts: whether age verification and parental-consent mechanisms actually exist and function, and whether a DPIA specifically addressed processing children's data before the service was offered to them. Section 1 records whether that trigger is satisfied. (ICO, MediaLab.AI, Inc., decision of 4 February 2026; supervisory-authority decision — persuasive, non-binding outside its jurisdiction.)",
    "status_in_citation": true
  },
  {
    "hook_id": "enforcement_actions:68252e3a-15a6-47ad-b3a5-40a9875f842b:v1",
    "profile_id": "61517f24-4bb4-4e99-b2ac-34a08a76a776",
    "source_row_id": "68252e3a-15a6-47ad-b3a5-40a9875f842b",
    "fact_atoms": [
      "class:innovative_technology_use"
    ],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [
      "class:innovative_technology_use"
    ],
    "finding_span": "Also, no data protection impact assessment pursuant to Art. 35 DSGVO had been carried out and the technical and organizational protection measures had not been outlined in the list of processing activities.",
    "fact_pattern_paraphrase": "a camera-based driving-assistance system tested on vehicles without a DPIA and without a data-processing agreement with the third party running the tests",
    "finding_paraphrase": "testing the camera-based system without carrying out a DPIA breaches Article 35",
    "settledness": "R3",
    "posture": "rejected",
    "factor_id": "the innovative-technology trigger",
    "bears_on_element": "obligation",
    "authority_label": "Data Protection Authority of Niedersachsen, Volkswagen, decision of 26 July 2022",
    "regulator": "Data Protection Authority of Niedersachsen",
    "relevance": {
      "instrument": "GDPR",
      "factor_ids": [
        "the innovative-technology trigger"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [
        "innovative_technology"
      ],
      "outcome_posture": "rejected"
    },
    "authority_label_short": "Data Protection Authority of Niedersachsen, Volkswagen",
    "hook_version": 1,
    "source_status": "sa_decision",
    "status_label": "supervisory-authority decision — persuasive, non-binding outside its jurisdiction",
    "verb": "found",
    "appeal_note": null,
    "verified_as_of": "2026-09-09",
    "pinpoint": {
      "kind": "field",
      "ref": "source_document_text",
      "anchor_span": "Weiterhin war keine Datenschutz-Folgenabschätzung nach Artikel 35 DS-GVO durchgeführt worden, mit der vor Beginn einer solchen Verarbeitung mögliche Risiken und deren Eindämmung bewertet werden müssen."
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The record describes a new or experimental technology being tested or deployed — for example, cameras or sensors mounted on test vehicles to develop a new driving-assistance feature. In its 2022 decision on Volkswagen, Germany's data protection authority for Lower Saxony found that the company tested a camera-based driving-assistance system without carrying out a DPIA — a breach of Article 35 — and without a data-processing agreement with the third party running the tests. That finding cuts against the company's position here. But the outcome depends on this company's own facts: whether the technology is genuinely novel to this kind of processing, and whether an assessment was completed and documented before testing began. Section 1 records whether that trigger is satisfied. (Data Protection Authority of Lower Saxony, Volkswagen, announced 26 July 2022; supervisory-authority decision — persuasive, non-binding outside its jurisdiction.)",
    "status_in_citation": true
  },
  {
    "hook_id": "edpb_guidelines:718bb432-ef28-4744-b169-bb9093fd2969:v1",
    "profile_id": "6cc71221-fc34-4cac-883c-97ca364b3bd4",
    "source_row_id": "718bb432-ef28-4744-b169-bb9093fd2969",
    "fact_atoms": [
      "class:employee_monitoring"
    ],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [
      "instrument:EU GDPR"
    ],
    "finding_span": "Systematic monitoring: processing used to observe, monitor or control data subjects, including data collected through networks or “a systematic monitoring of a publicly accessible area” (Article 35(3)(c))",
    "fact_pattern_paraphrase": "processing used to observe, monitor or control data subjects, such as a financial institution screening its customers against a credit reference or fraud database",
    "finding_paraphrase": "systematic monitoring is one of the WP248 criteria indicating processing likely to result in a high risk and supports an Article 35 DPIA obligation even without a public-space element",
    "settledness": "R1",
    "posture": "accepted",
    "factor_id": "the employee-monitoring trigger",
    "bears_on_element": "obligation",
    "authority_label": "Article 29 Working Party, Guidelines on Data Protection Impact Assessment (DPIA) and determining whether processing is \"likely to result in a high risk\" for the purposes of Regulation 2016/679",
    "regulator": "the Article 29 Working Party",
    "relevance": {
      "instrument": "GDPR",
      "factor_ids": [
        "the employee-monitoring trigger"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [
        "profiling_or_systematic_observation"
      ],
      "outcome_posture": "accepted"
    },
    "authority_label_short": "WP29, Guidelines on Data Protection Impact Assessment (DPIA) and determining whether processing is \"likely to result in a high risk\" for the purposes of Regulation 2016/679",
    "hook_version": 1,
    "source_status": "wp29_opinion",
    "status_label": "Article 29 Working Party opinion, 4 October 2017 — historical interpretive guidance, endorsed by the EDPB on 25 May 2018; current relevance verified 2026-09-09",
    "verb": "advised",
    "appeal_note": null,
    "verified_as_of": "2026-09-09",
    "pinpoint": {
      "kind": "page",
      "ref": "9",
      "anchor_span": "Systematic monitoring: processing used to observe, monitor or control data subjects, including data collected through networks or “a systematic monitoring of a publicly accessible area” (Article 35(3)(c))"
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The record describes ongoing, organized monitoring of a defined group of people — for example, screening customers against a fraud or watchlist database, or monitoring employees' activity over time. The Article 29 Working Party calls this \"systematic monitoring\": processing used to observe, monitor, or control people, including a financial institution's own customer-screening systems. Its guidance (WP248, endorsed by the EDPB) treats systematic monitoring as one of the criteria that triggers the Article 35 DPIA obligation, even without a public-space element. That guidance supports the assessment's position that a DPIA is required here. Section 1 records that determination. (Article 29 Working Party, Guidelines on Data Protection Impact Assessment (WP248 rev.01), Annex 1, criterion 3, adopted 4 October 2017; EDPB guidelines — interpretive guidance, not binding law, endorsed by the EDPB 25 May 2018.)",
    "status_in_citation": true
  },
  {
    "hook_id": "enforcement_actions:a3cf40b0-3625-4e78-bbe9-63624f17ceb0:v1",
    "profile_id": "db660964-3783-4e6c-a3a6-eeb476582a3c",
    "source_row_id": "a3cf40b0-3625-4e78-bbe9-63624f17ceb0",
    "fact_atoms": [
      "flag:automated_decision",
      "relationship:customer",
      "flag:large_scale"
    ],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [
      "flag:automated_decision"
    ],
    "finding_span": "Poste Italiane processed customer data excessively through a fraud prevention tool without a sufficient legal basis, proper transparency, or adequate data protection measures.",
    "fact_pattern_paraphrase": "a fraud-prevention tool collecting customer data at scale, deployed without an adequate legal basis, without meeting transparency obligations, and without a DPIA addressing the tool's own specific processing",
    "finding_paraphrase": "deploying the tool without a DPIA that addressed its own specific processing breaches Article 35",
    "settledness": "R3",
    "posture": "rejected",
    "factor_id": "the Article 35 obligation to conduct this assessment",
    "bears_on_element": "obligation",
    "authority_label": "Garante, Poste Italiane S.p.a., decision of 17 April 2026",
    "regulator": "Garante",
    "relevance": {
      "instrument": "GDPR",
      "factor_ids": [
        "the Article 35 obligation to conduct this assessment"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [
        "admt_use"
      ],
      "outcome_posture": "rejected"
    },
    "authority_label_short": "Garante, Poste Italiane S.p.a.",
    "hook_version": 1,
    "source_status": "sa_decision_appeal_pending",
    "status_label": "under appeal",
    "verb": "found",
    "appeal_note": "Provision no. 237 of 17/04/2026 temporarily removed from the Garante's website under art. 5, Legislative Decree 150/2011, following a precautionary order of the Tribunale di Roma dated 17/07/2026 suspending the decision's executive effectiveness; appeal pending (confirmed live on gpdp.it, 2026-09-09).",
    "verified_as_of": "2026-09-09",
    "pinpoint": {
      "kind": "field",
      "ref": "source_document_text",
      "anchor_span": "ai sensi degli artt. 57, par. 1, lett. f) e 83, del Regolamento, rileva l’illiceità del trattamento effettuato da Poste Italiane S.p.a., , con sede legale in Roma, Viale Europa 190, C.F. n. 01114601006 e da Postepay S.p.a., con sede legale in Roma, Viale Europa 190, C.F. n. 06874351007, in qualità di contitolari del trattamento, nei termini di cui in motivazione, per la violazione degli artt. 5, 6, 13, 25, 28, 32, 35 del Regolamento, nonché dell’art. 122 del Codice in materia di protezione dei dati personali"
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The record describes a fraud-prevention tool that collects customer data at scale. In its decision on Poste Italiane, the Italian data protection authority (Garante) found that the company deployed the tool without an adequate legal basis, without meeting its transparency obligations, and without a DPIA that addressed the tool's own specific processing — that last gap is what breaches Article 35. That finding cuts against the company's position here. But the outcome depends on this company's own facts: what the tool actually collects, whether that was assessed specifically rather than generically, and whether the assessment happened before the tool went live. Section 1 records whether that trigger is satisfied. (Garante, Poste Italiane S.p.A., decision of 17 April 2026; supervisory-authority decision — persuasive, non-binding outside its jurisdiction.)",
    "status_in_citation": true
  },
  {
    "hook_id": "enforcement_actions:dbfca969-3139-43d1-8a5b-7fff179f8db6:v1",
    "profile_id": "eab4ce07-f025-4d9e-9054-b6d4a67ea137",
    "source_row_id": "dbfca969-3139-43d1-8a5b-7fff179f8db6",
    "fact_atoms": [
      "class:employee_monitoring"
    ],
    "distinguishing_atoms": [],
    "not_distinguishable": false,
    "required_atoms": [
      "class:employee_monitoring"
    ],
    "finding_span": "The municipality unlawfully monitored employee internet usage and processed sensitive health data without a valid legal basis or proper transparency",
    "fact_pattern_paraphrase": "a municipal employer systematically monitoring its employees' internet usage",
    "finding_paraphrase": "systematic monitoring of employee internet usage requires a DPIA under WP248's systematic-monitoring criterion even where the monitoring is not carried out on a large scale",
    "settledness": "R3",
    "posture": "rejected",
    "factor_id": "the employee-monitoring trigger",
    "bears_on_element": "obligation",
    "authority_label": "Garante, Comune di Bolzano, decision of 13 May 2021",
    "regulator": "Garante",
    "relevance": {
      "instrument": "GDPR",
      "factor_ids": [
        "the employee-monitoring trigger"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [
        "Health information"
      ],
      "flags": [
        "employee_monitoring",
        "profiling_or_systematic_observation"
      ],
      "outcome_posture": "rejected"
    },
    "authority_label_short": "Garante, Comune di Bolzano",
    "hook_version": 1,
    "source_status": "sa_decision",
    "status_label": "supervisory-authority decision — persuasive, non-binding outside its jurisdiction",
    "verb": "found",
    "appeal_note": null,
    "verified_as_of": "2026-09-09",
    "pinpoint": {
      "kind": "field",
      "ref": "source_document_text",
      "anchor_span": "rileva l’illiceità del trattamento effettuato dal Comune di Bolzano per violazione degli artt. 5, 6, 9, 88 e 35 del Regolamento, nonché 113 e 114 del Codice"
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The record describes monitoring of employees' internet usage. In its decision on Comune di Bolzano, the Italian data protection authority (Garante) found that systematic monitoring of employee internet usage requires a DPIA under WP248's \"systematic monitoring\" criterion. That finding cuts against the company's position here. But the outcome depends on this company's own facts: whether the monitoring is organized and ongoing (systematic), or occasional and incidental. Section 1 records whether that trigger is satisfied. (Garante, Comune di Bolzano, decision of 13 May 2021; supervisory-authority decision — persuasive, non-binding outside its jurisdiction.)",
    "status_in_citation": true
  },
  {
    "hook_id": "edpb_guidelines:118b22d4-775e-4472-8f33-4a8d1eb22887:v1",
    "profile_id": "ee01587d-fbe2-42f2-b0ba-d043e1917c51",
    "source_row_id": "118b22d4-775e-4472-8f33-4a8d1eb22887",
    "fact_atoms": [
      "state:intake.reasons_to_conduct.sensitive_data=true"
    ],
    "distinguishing_atoms": [],
    "not_distinguishable": true,
    "required_atoms": [
      "instrument:EU GDPR"
    ],
    "finding_span": "An example would be a general hospital keeping patients’ medical records or a private investigator keeping offenders’ details.",
    "fact_pattern_paraphrase": "processing of special categories of personal data under Article 9 or of personal data relating to criminal convictions or offences under Article 10, such as a general hospital keeping the medical records of its patients or a private investigator keeping the details of offenders",
    "finding_paraphrase": "sensitive data or data of a highly personal nature is one of the WP248 criteria indicating processing likely to result in a high risk and supports an Article 35 DPIA obligation, extending beyond Article 9 and Article 10 to other data the GDPR treats as increasing the risk to rights and freedoms",
    "settledness": "R1",
    "posture": "accepted",
    "factor_id": "the Article 35 obligation to conduct this assessment",
    "bears_on_element": "obligation",
    "authority_label": "Article 29 Working Party, Guidelines on Data Protection Impact Assessment (DPIA) and determining whether processing is \"likely to result in a high risk\" for the purposes of Regulation 2016/679",
    "regulator": "the Article 29 Working Party",
    "relevance": {
      "instrument": "GDPR",
      "factor_ids": [
        "the Article 35 obligation to conduct this assessment"
      ],
      "use_case_class": null,
      "relationship": null,
      "data_categories": [],
      "flags": [
        "sensitive_pi"
      ],
      "outcome_posture": "accepted"
    },
    "authority_label_short": "WP29, Guidelines on Data Protection Impact Assessment (DPIA) and determining whether processing is \"likely to result in a high risk\" for the purposes of Regulation 2016/679",
    "hook_version": 1,
    "source_status": "wp29_opinion",
    "status_label": "Article 29 Working Party opinion, 4 October 2017 — historical interpretive guidance, endorsed by the EDPB on 25 May 2018; current relevance verified 2026-09-09",
    "verb": "advised",
    "appeal_note": null,
    "verified_as_of": "2026-09-09",
    "pinpoint": {
      "kind": "page",
      "ref": "9",
      "anchor_span": "An example would be a general hospital keeping patients’ medical records or a private investigator keeping offenders’ details."
    },
    "recognised_proposition": null,
    "condition_text": null,
    "condition_atoms": null,
    "material_facts": [],
    "distinguishing_pairs": [],
    "governing_provision_sentence": null,
    "hedge_variant": null,
    "hedge_sentence": null,
    "literal_sentence_override": "The record describes special-category data under Article 9 — for example, health, biometric, or genetic data, or data revealing racial or ethnic origin, political opinions, religious belief, or trade-union membership — data relating to criminal convictions or offences under Article 10, or other data whose sensitivity or personal nature creates a heightened risk to people's rights and freedoms, such as financial data revealing someone's economic situation or location data revealing their movements. The Article 29 Working Party's guidance (WP248, endorsed by the EDPB) names \"sensitive data or data of a highly personal nature\" as one of the criteria that triggers the Article 35 DPIA obligation — its own examples are a general hospital's patient records and a private investigator's file on offenders — and extends that same reasoning \"beyond these provisions of the GDPR\" to other categories the GDPR's own recitals treat as risk-increasing, including a person's financial circumstances and their location or movements. That guidance supports the assessment's position that a DPIA is required here. Section 1 records that determination. (Article 29 Working Party, Guidelines on Data Protection Impact Assessment (WP248 rev.01), Annex 1, criterion 4, adopted 4 October 2017; EDPB guidelines — interpretive guidance, not binding law, endorsed by the EDPB 25 May 2018.)",
    "status_in_citation": true
  }
];

// ── [RATIFY] — the direction matrix (doc 213 §4, amended by doc 222 §3 and
// doc 224), as data — VERBATIM COPY of LIA_HOOK_DIRECTION_MATRIX. See that
// file's own header: this table exists only so a byte-pin test can catch
// drift between the DATA and the CODE (`directionFor`, hook-types.ts, the
// shared, product-agnostic module both products' joins call). ─────────────

export interface DpiaHookMatrixRow {
  readonly posture: string;
  readonly fact_agreement: string;
  readonly engine_verdict: string;
  readonly shape: string;
  readonly note: string;
}

export const DPIA_HOOK_DIRECTION_MATRIX: readonly DpiaHookMatrixRow[] = [
  {
    posture: "accepted",
    fact_agreement: "same",
    engine_verdict: "any",
    shape: "S1 supports",
    note: "hedged to `likely` language; never lifts a determination",
  },
  {
    posture: "accepted",
    fact_agreement: "different / unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "nothing to say",
  },
  {
    posture: "conditional",
    fact_agreement: "same",
    engine_verdict: "passes, and every condition_atom holds on the record",
    shape: "S5b recognised + condition satisfied",
    note: "the engine's pass is what satisfies the condition; the hook only echoes it (doc 222 §3)",
  },
  {
    posture: "conditional",
    fact_agreement: "same",
    engine_verdict: "otherwise (fails / uncertain, or condition_atoms null / not all held)",
    shape: "S5a recognised, condition unresolved",
    note: "the guidance is relevant; whether its condition is met is Section {section}'s question — never asserted here (the doc 218 D1 defect)",
  },
  {
    posture: "conditional",
    fact_agreement: "different (a distinguishing pair holds)",
    engine_verdict: "passes",
    shape: "omit + assessor flag `authority_not_dispositive` (`rule_missing` when the pair expressly excludes)",
    note: "a silent source under a pass is nothing missing; an express exclusion under a pass is the lawyer's rule",
  },
  {
    posture: "conditional",
    fact_agreement: "different (a distinguishing pair holds)",
    engine_verdict: "fails / uncertain",
    shape: "S6 source silent (S6x where the pair expressly excludes)",
    note: "\"does not extend\" only from an authored `source_expressly_excludes` pair with a verified exclusion span (doc 222 §2.4)",
  },
  {
    posture: "conditional",
    fact_agreement: "unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "",
  },
  {
    posture: "rejected",
    fact_agreement: "same",
    engine_verdict: "fails / uncertain",
    shape: "S2 cuts against and applied",
    note: "the determination already reflects it",
  },
  {
    posture: "rejected",
    fact_agreement: "same",
    engine_verdict: "passes",
    shape: "omit + assessor flag `rule_missing`",
    note:
      "the lawyer's rule: an adverse authority on the same facts under a pass means a rule is missing — never printed as \"risk noted\"",
  },
  {
    posture: "rejected",
    fact_agreement: "different (a distinguishing pair holds)",
    engine_verdict: "any",
    shape: "S3 cuts against but distinguished",
    note: "renders only from the pair (source fact / record fact); never from an atom's generic phrase",
  },
  {
    posture: "rejected",
    fact_agreement: "unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "",
  },
  {
    posture: "contested (R4)",
    fact_agreement: "same",
    engine_verdict: "any",
    shape: "S4 noted as a boundary",
    note: "prints the derived status and the appeal note; no relation drawn",
  },
  {
    posture: "contested (R4)",
    fact_agreement: "different / unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "a contested decision on different facts adds nothing (doc 222 §3)",
  },
  {
    posture: "any",
    fact_agreement: "unknown from atoms",
    engine_verdict: "—",
    shape: "the stored two-leg selection's agreement, if one exists; else omit + flag `selection_pending`; legs disagreed → omit + flag `selection_unsettled` (the ROO item)",
    note: "doc 224 §1: a call is made only where no stored decision exists AND the pre-filter says either answer could print",
  },
  {
    posture: "any",
    fact_agreement: "`required_atoms` not all held",
    engine_verdict: "—",
    shape: "not nominated",
    note: "",
  },
];

// ── [RATIFY — DRAFT, unratified] — the atom-phrase map (doc 213 §5 pattern;
// this build's own DPIA vocabulary, doc 232). One ratified clause per
// closed-list atom value in HOOK_PRODUCT_REGISTRY.dpia
// (generate-corpus-hooks/_local/product-registry.ts). ──────────────────────

export const DPIA_ATOM_PHRASES: Readonly<Record<string, string>> = {
  // — classes —
  "class:employee_monitoring": "the processing monitors employees",
  "class:public_space_surveillance": "the processing systematically monitors a publicly accessible area",
  "class:algorithmic_decision": "the processing includes automated evaluation, scoring, or decision-making",
  "class:innovative_technology_use": "the processing uses a novel or innovative technology",
  "class:dataset_matching": "the processing matches or combines datasets",

  // — flags —
  "flag:biometric": "the processing includes biometric data",
  "flag:special_category": "the processing includes special-category data",
  "flag:children": "children are among the people affected",
  "flag:large_scale": "the processing is carried out on a large scale",
  "flag:vulnerable_subjects": "the processing concerns vulnerable data subjects",
  "flag:automated_decision": "the processing involves automated decision-making",
  "flag:cross_border_transfer": "the processing involves a cross-border transfer of personal data",

  // — relationships —
  "relationship:employee": "the people affected are employees of the controller",
  "relationship:customer": "the people affected are customers of the controller",
  "relationship:public": "the people affected are members of the public with no relationship to the controller",

  // — data categories (DPIA_DATA_CATEGORIES / DATA_CATS, DPIAFramework.enums.ts) —
  "data_category:Contact details": "the processing includes contact details",
  "data_category:Employee records": "the processing includes employee records",
  "data_category:Customer records": "the processing includes customer records",
  "data_category:Health or medical data": "the processing includes health or medical data",
  "data_category:Financial data": "the processing includes financial data",
  "data_category:Biometric data": "the processing includes biometric data",
  "data_category:Children's data": "the processing includes children's data",
  "data_category:Location data": "the processing includes location data",
  "data_category:Communications content": "the processing includes communications content",
  "data_category:Other": "the processing includes other categories of data not separately listed",

  // — instruments —
  "instrument:EU GDPR": "the processing is assessed under the EU GDPR",
  "instrument:UK GDPR": "the processing is assessed under the UK GDPR",

  // — state: atoms — the closed `reasons_to_conduct` vocabulary (17 options,
  // REASONS_TO_CONDUCT / DPIAFramework.enums.ts), true and false phrasing for
  // each (the `false` form is the only way to phrase an ABSENCE — the doc 223
  // defect this build designs out from day one: a hook may distinguish on a
  // record that DID NOT select a reason only through this explicit `=false`
  // phrase, never by reusing the `=true` phrase for an absent-polarity pair).
  "state:intake.reasons_to_conduct.art35_3a_evaluation_profiling=true":
    "the record selects systematic, extensive evaluation or profiling with significant effects as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.art35_3a_evaluation_profiling=false":
    "the record does not select systematic, extensive evaluation or profiling with significant effects as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.art35_3b_large_scale_special_category=true":
    "the record selects large-scale special-category or criminal-offence data as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.art35_3b_large_scale_special_category=false":
    "the record does not select large-scale special-category or criminal-offence data as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.art35_3c_public_area_monitoring=true":
    "the record selects large-scale systematic monitoring of a public area as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.art35_3c_public_area_monitoring=false":
    "the record does not select large-scale systematic monitoring of a public area as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.evaluation_scoring=true":
    "the record selects evaluation or scoring, including profiling or prediction, as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.evaluation_scoring=false":
    "the record does not select evaluation or scoring as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.automated_decision_making=true":
    "the record selects automated decision-making with a legal or significant effect as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.automated_decision_making=false":
    "the record does not select automated decision-making with a legal or significant effect as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.systematic_monitoring=true":
    "the record selects systematic monitoring of employees, a defined population, or a non-public space as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.systematic_monitoring=false":
    "the record does not select systematic monitoring of employees, a defined population, or a non-public space as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.sensitive_data=true":
    "the record selects sensitive or highly personal data as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.sensitive_data=false":
    "the record does not select sensitive or highly personal data as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.large_scale=true":
    "the record selects data processed on a large scale as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.large_scale=false":
    "the record does not select data processed on a large scale as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.matching_combining_datasets=true":
    "the record selects matching or combining datasets as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.matching_combining_datasets=false":
    "the record does not select matching or combining datasets as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.vulnerable_subjects=true":
    "the record selects data concerning vulnerable subjects as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.vulnerable_subjects=false":
    "the record does not select data concerning vulnerable subjects as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.innovative_technology=true":
    "the record selects innovative use of new technology as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.innovative_technology=false":
    "the record does not select innovative use of new technology as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.prevents_exercising_right=true":
    "the record selects that the processing prevents exercising a right or using a service as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.prevents_exercising_right=false":
    "the record does not select that the processing prevents exercising a right or using a service as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.required_by_national_law=true":
    "the record selects that the assessment is required by national law",
  "state:intake.reasons_to_conduct.required_by_national_law=false":
    "the record does not select that the assessment is required by national law",
  "state:intake.reasons_to_conduct.dpo_or_data_subject_recommendation=true":
    "the record selects a DPO or data-subject recommendation as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.dpo_or_data_subject_recommendation=false":
    "the record does not select a DPO or data-subject recommendation as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.required_by_code_of_conduct=true":
    "the record selects that the assessment is required by a code of conduct or standard",
  "state:intake.reasons_to_conduct.required_by_code_of_conduct=false":
    "the record does not select that the assessment is required by a code of conduct or standard",
  "state:intake.reasons_to_conduct.risk_management_accountability=true":
    "the record selects risk management or accountability as a (beneficial, non-mandatory) reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.risk_management_accountability=false":
    "the record does not select risk management or accountability as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.existing_processing_risk_changed=true":
    "the record selects that this is existing processing whose risk has changed as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.existing_processing_risk_changed=false":
    "the record does not select that this is existing processing whose risk has changed as a reason the assessment was undertaken",
};

// ── [RATIFY — DRAFT, unratified] — the sentence shapes (doc 213 §5 pattern
// as amended by doc 222 §4), DPIA-specific text. Slot NAMES are identical to
// LIA's shapes (dpia-hook-join.ts's renderer needs no product-specific
// branching); the WORDING differs where LIA's is legitimate-interest-
// specific (doc 232 build brief: "S5a/S5b/S6/S6x wording is LIA-specific …
// draft DPIA-appropriate shape text"). ─────────────────────────────────────

// DOC 238 (2026-09-09) — AMENDED, still [RATIFY — DRAFT, unratified]: doc 237
// §5 found no current shape, in any product, can produce any CEO-approved
// hook sentence (docs 223B/233/234/236). This revision (a) restructures
// every shape from a 2–4-sentence clause template into the approved
// 4–7-sentence paragraph form, (b) adds the `{quote}` slot (the verified
// `finding_span`, wrapped in quotation marks by the template — quote marks
// are ratified template text, never drafted content, so no verify.ts change
// is needed), (c) adds the optional `{governing_provision}` slot to S1–S4
// (S5a/S5b/S6/S6x already carry an equivalent rule statement via
// `{proposition}`/`{condition}`), and (d) rewords S2/S6x's section pointer
// from backward-asserting ("…and the determination in Section {section}
// reflects it") to forward-looking ("Whether that holds… is addressed in
// Section {section}") — matching every approved DPIA candidate this session
// (233 §"AENA": "Section 3 addresses whether that analysis is present";
// §"ICS": "Section 1 records whether that trigger is satisfied"). S1 is left
// backward-asserting on purpose (doc 233's WP248 candidate: "supports the
// assessment's position… Section 1 records that determination" — a
// SUPPORTING finding is properly asserted, not hedged as pending). The hedge
// itself is NOT template text — it is the hook's own CEO-approved
// `hedge_sentence` (hook-types.ts), appended verbatim by the join's
// `hedgeSuffix` after the citation; no generic hedge constant exists (doc
// 238 follow-up, 2026-09-09). See doc 238 §"DPIA" for the full proposal, a
// rendered example, and the CEO ratify/revise/hold line.

export const DPIA_HOOK_SHAPES: Readonly<Record<"S1" | "S2" | "S3" | "S4" | "S5a" | "S5b" | "S6" | "S6x", string>> = {
  S1:
    "The record identifies that {customer_fact}. In {authority}, {regulator} {verb} that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding supports the assessment's position on {factor}. {hedge}Section {section} records that determination. ({citation}; {status}.)",
  S2:
    "The record identifies that {customer_fact}. In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding cuts against the assessment's position on {factor}. {hedge}Whether that holds on this record is addressed in Section {section}. ({citation}; {status}.)",
  S3:
    "In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding turned on the fact that {source_fact}; on this record the assessment has instead identified {record_fact}. The decision marks a boundary rather than a finding against the record. ({citation}; {status}.)",
  S4:
    "In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". The record identifies {customer_fact}. That decision is {status}; it is noted as a boundary and is not applied. ({citation}.)",
  S5a:
    "In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}. That guidance is relevant to {factor}; whether its condition is satisfied is addressed in Section {section}. ({citation}; {status}.)",
  S5b:
    "In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}. That guidance is relevant to {factor}; whether its condition is satisfied is addressed in Section {section}. The facts identified in Section {section} satisfy that stated condition. ({citation}; {status}.)",
  S6:
    "The record identifies {record_fact}. In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}, but does not address whether the same conclusion follows where {record_fact}. The determination in Section {section} therefore rests on the separately identified rules and facts, not on that guidance. ({citation}; {status}.)",
  S6x:
    "The record identifies {record_fact}. In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}, and that {exclusion_paraphrase}; that exclusion applies to processing of the kind the record describes. Whether it applies here is addressed on {factor} in Section {section}. ({citation}; {status}.)",
};

// ── [RATIFY — DRAFT, unratified] — concept equivalence (doc 222 §2.3
// pattern). Two atoms naming the same underlying fact share a concept; the
// render dedupes `{customer_fact}` by concept. ────────────────────────────

export const DPIA_ATOM_CONCEPTS: Readonly<Record<string, string>> = {
  "flag:special_category": "special_category",
  "data_category:Health or medical data": "special_category",
  "state:intake.reasons_to_conduct.art35_3b_large_scale_special_category=true": "special_category",
  "flag:children": "children",
  "data_category:Children's data": "children",
  "state:intake.reasons_to_conduct.vulnerable_subjects=true": "vulnerable_subjects",
  "flag:vulnerable_subjects": "vulnerable_subjects",
  "flag:biometric": "biometric",
  "data_category:Biometric data": "biometric",
  "flag:large_scale": "large_scale",
  "state:intake.reasons_to_conduct.large_scale=true": "large_scale",
  "flag:automated_decision": "automated_decision",
  "class:algorithmic_decision": "automated_decision",
  "state:intake.reasons_to_conduct.automated_decision_making=true": "automated_decision",
  "class:employee_monitoring": "employee_monitoring",
  "state:intake.reasons_to_conduct.systematic_monitoring=true": "employee_monitoring",
};

/** The concept an atom names — itself when the table has no entry. */
export function dpiaAtomConcept(atom: string): string {
  return DPIA_ATOM_CONCEPTS[atom] ?? atom;
}

// ── [RATIFY — DRAFT, unratified] — factor phrases (doc 222 §5 pattern): the
// `{factor}` slot, without a leading article. Every factor maps to exactly
// one of DPIA's two hook elements (`DPIA_FACTOR_ELEMENT`, below) — doc 232's
// factor/determination → section map. ──────────────────────────────────────

const F_OBLIGATION = "the Article 35 obligation to conduct this assessment";
const F_EMPLOYEE_MONITORING = "the employee-monitoring trigger";
const F_ALGORITHMIC = "the automated-decision trigger";
const F_ADEQUACY = "the necessity and proportionality analysis";
const F_BIOMETRIC_ADEQUACY = "the adequacy of the biometric-processing analysis";
// doc 242, three-lawyer panel (2026-09-09): both live profile factor_ids
// verbatim, already following the "the [X] trigger" naming convention.
const F_CHILDRENS_DATA = "the children's-data trigger";
const F_INNOVATIVE_TECH = "the innovative-technology trigger";

export const DPIA_FACTOR_PHRASES: Readonly<Record<string, string>> = {
  [F_OBLIGATION]: "the obligation to conduct this assessment",
  [F_EMPLOYEE_MONITORING]: "the employee-monitoring trigger",
  [F_ALGORITHMIC]: "the automated-decision trigger",
  [F_ADEQUACY]: "necessity and proportionality",
  [F_BIOMETRIC_ADEQUACY]: "the adequacy of the biometric-processing analysis",
  // doc 242, three-lawyer panel (2026-09-09): both are Article 35(1)
  // trigger factors (WP248 criteria 7/8), the same kind of question as
  // employee-monitoring/automated-decision above — obligation, not
  // adequacy.
  [F_CHILDRENS_DATA]: "the children's-data trigger",
  [F_INNOVATIVE_TECH]: "the innovative-technology trigger",
};

// ── [RATIFY — DRAFT, unratified] — DOC 213 §2 pattern: factor → DPIA hook
// element ("obligation" | "adequacy" — dpia-hook-join.ts's
// `SECTION_FOR_ELEMENT`/`bears_on_element`). Copied verbatim into
// generate-corpus-hooks/_local/dpia-factor-element.ts (pinned by test), the
// same relationship LIA_FACTOR_ELEMENT has to
// generate-corpus-hooks/_local/factor-element.ts. ──────────────────────────

export const DPIA_FACTOR_ELEMENT: Readonly<Record<string, "obligation" | "adequacy">> = {
  [F_OBLIGATION]: "obligation",
  [F_EMPLOYEE_MONITORING]: "obligation",
  [F_ALGORITHMIC]: "obligation",
  [F_ADEQUACY]: "adequacy",
  [F_BIOMETRIC_ADEQUACY]: "adequacy",
  [F_CHILDRENS_DATA]: "obligation",
  [F_INNOVATIVE_TECH]: "obligation",
};

export function dpiaElementOf(factorId: string): "obligation" | "adequacy" | null {
  return DPIA_FACTOR_ELEMENT[factorId] ?? null;
}

// ── [RATIFY] — source status labels (doc 222 §2.7) — VERBATIM COPY of
// LIA_SOURCE_STATUS_LABELS. Product-agnostic: HookSourceStatus
// (hook-types.ts) carries no LIA-specific vocabulary. ──────────────────────

export const DPIA_SOURCE_STATUS_LABELS: Readonly<Record<string, string>> = {
  edpb_guidelines_final: "EDPB guidelines — interpretive guidance, not binding law",
  edpb_opinion: "EDPB Article 64 opinion — Board opinion, not a judicial decision",
  wp29_opinion: "Article 29 Working Party opinion — historical interpretive guidance",
  regulator_guidance: "regulatory guidance — non-binding",
  sa_decision: "supervisory-authority decision — persuasive, non-binding outside its jurisdiction",
  sa_decision_affirmed: "supervisory-authority decision, affirmed on appeal",
  sa_decision_appeal_pending: "under appeal",
};

// ── RATIFIED (LIA, CEO 2026-09-08) — BYTE-MIRRORED here, unchanged. Where an
// appeal is known to have been made, the join appends this sentence,
// verbatim, after the hook's sentence. ─────────────────────────────────────

export const DPIA_APPEAL_SENTENCE = "This matter is subject to an appeal which could invalidate this ruling.";

export const DPIA_SETTLEDNESS_LABELS: Readonly<Record<"R1" | "R2" | "R3" | "R4", string>> = {
  R1: "adopted guidance or settled authority",
  R2: "a settled line of decisions",
  R3: "a single supervisory authority's decision",
  R4: "under appeal / contested",
};
