// DPIA AUTHORITY HOOKS — pinned, generated file (doc 230 B1, doc 232).
//
// Mirrors run-li-assessment/_local/corpus/maps/lia-hooks.ts's structure
// exactly (doc 213's pattern). Generated by `generate-corpus-hooks` (action
// "generate") from ratified, unretired `public.authority_hooks` rows whose
// product is `dpia` and whose profile is itself stamped. Do not hand-edit
// `DPIA_HOOKS`: regenerate it.
// Run: dpia-hooks-v0-empty-2026-09-08-0
//
// EXCLUDED ROWS: none — zero rows have been drafted yet (no `authority_hooks`
// row with product='dpia' exists in the DB as of this build; verified
// read-only, 2026-09-08). `DPIA_HOOKS` ships `[]` until the first ratified
// hook lands; every consumer (dpia-hook-join.ts,
// _shared/ltp/dpia-skeleton-assemble.ts's v3 wire-in) already degrades to a
// no-op on an empty array — the SAME "unstamped hook is inert" law an
// unstamped rule already answers to.
//
// The `[RATIFY]` blocks below are DRAFT, UNRATIFIED — the CEO must ratify
// before DPIA_HOOKS_ENABLED flips. `DPIA_HOOK_DIRECTION_MATRIX`,
// `DPIA_SOURCE_STATUS_LABELS`, `DPIA_SETTLEDNESS_LABELS` and
// `DPIA_APPEAL_SENTENCE` are copied VERBATIM from LIA's own ratified bytes
// (run-li-assessment/_local/corpus/maps/lia-hooks.ts) — doc 213/222/224's
// matrix, status taxonomy and appeal sentence are product-agnostic by
// construction (hook-types.ts's `directionFor`/`HookSourceStatus` carry no
// LIA-specific vocabulary). `DPIA_ATOM_PHRASES`, `DPIA_HOOK_SHAPES`,
// `DPIA_ATOM_CONCEPTS`, `DPIA_FACTOR_PHRASES` and `DPIA_FACTOR_ELEMENT` are
// this build's own DPIA-specific drafting: the shape TEXT differs from
// LIA's (LIA's S5a/S5b/S6/S6x wording — "…whether legitimate interests is
// available where…" — is LIA-specific per the build brief; the slot NAMES
// are identical so `dpia-hook-join.ts`'s renderer needs no product-specific
// branching). `generate-corpus-hooks`'s own `generate` action will copy
// every block from the marker below to the end of this file verbatim once
// wired (`_local/dpia-hook-context-block.ts`, pinned by test) — see doc 232
// for the proposed diff to `generate-corpus-hooks/index.ts`'s
// `actionGenerate` this build could not apply directly (out of scope: that
// file is on the "do not modify" list pending the CPPA Risk agent's
// registry-dispatch generalisation).

import type { AuthorityHook } from "../../../../_shared/corpus/hook-types.ts";

export const DPIA_HOOKS_VERSION = "dpia-hooks-v0-empty-2026-09-08";

export const DPIA_HOOKS: readonly AuthorityHook[] = [];

// ── [RATIFY] — the direction matrix (doc 213 §4, amended by doc 222 §3 and
// doc 224), as data — VERBATIM COPY of LIA_HOOK_DIRECTION_MATRIX. See that
// file's own header: this table exists only so a byte-pin test can catch
// drift between the DATA and the CODE (`directionFor`, hook-types.ts, the
// shared, product-agnostic module both products' joins call). ─────────────

export interface DpiaHookMatrixRow {
  readonly posture: string;
  readonly fact_agreement: string;
  readonly engine_verdict: string;
  readonly shape: string;
  readonly note: string;
}

export const DPIA_HOOK_DIRECTION_MATRIX: readonly DpiaHookMatrixRow[] = [
  {
    posture: "accepted",
    fact_agreement: "same",
    engine_verdict: "any",
    shape: "S1 supports",
    note: "hedged to `likely` language; never lifts a determination",
  },
  {
    posture: "accepted",
    fact_agreement: "different / unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "nothing to say",
  },
  {
    posture: "conditional",
    fact_agreement: "same",
    engine_verdict: "passes, and every condition_atom holds on the record",
    shape: "S5b recognised + condition satisfied",
    note: "the engine's pass is what satisfies the condition; the hook only echoes it (doc 222 §3)",
  },
  {
    posture: "conditional",
    fact_agreement: "same",
    engine_verdict: "otherwise (fails / uncertain, or condition_atoms null / not all held)",
    shape: "S5a recognised, condition unresolved",
    note: "the guidance is relevant; whether its condition is met is Section {section}'s question — never asserted here (the doc 218 D1 defect)",
  },
  {
    posture: "conditional",
    fact_agreement: "different (a distinguishing pair holds)",
    engine_verdict: "passes",
    shape: "omit + assessor flag `authority_not_dispositive` (`rule_missing` when the pair expressly excludes)",
    note: "a silent source under a pass is nothing missing; an express exclusion under a pass is the lawyer's rule",
  },
  {
    posture: "conditional",
    fact_agreement: "different (a distinguishing pair holds)",
    engine_verdict: "fails / uncertain",
    shape: "S6 source silent (S6x where the pair expressly excludes)",
    note: "\"does not extend\" only from an authored `source_expressly_excludes` pair with a verified exclusion span (doc 222 §2.4)",
  },
  {
    posture: "conditional",
    fact_agreement: "unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "",
  },
  {
    posture: "rejected",
    fact_agreement: "same",
    engine_verdict: "fails / uncertain",
    shape: "S2 cuts against and applied",
    note: "the determination already reflects it",
  },
  {
    posture: "rejected",
    fact_agreement: "same",
    engine_verdict: "passes",
    shape: "omit + assessor flag `rule_missing`",
    note:
      "the lawyer's rule: an adverse authority on the same facts under a pass means a rule is missing — never printed as \"risk noted\"",
  },
  {
    posture: "rejected",
    fact_agreement: "different (a distinguishing pair holds)",
    engine_verdict: "any",
    shape: "S3 cuts against but distinguished",
    note: "renders only from the pair (source fact / record fact); never from an atom's generic phrase",
  },
  {
    posture: "rejected",
    fact_agreement: "unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "",
  },
  {
    posture: "contested (R4)",
    fact_agreement: "same",
    engine_verdict: "any",
    shape: "S4 noted as a boundary",
    note: "prints the derived status and the appeal note; no relation drawn",
  },
  {
    posture: "contested (R4)",
    fact_agreement: "different / unknown",
    engine_verdict: "any",
    shape: "omit",
    note: "a contested decision on different facts adds nothing (doc 222 §3)",
  },
  {
    posture: "any",
    fact_agreement: "unknown from atoms",
    engine_verdict: "—",
    shape: "the stored two-leg selection's agreement, if one exists; else omit + flag `selection_pending`; legs disagreed → omit + flag `selection_unsettled` (the ROO item)",
    note: "doc 224 §1: a call is made only where no stored decision exists AND the pre-filter says either answer could print",
  },
  {
    posture: "any",
    fact_agreement: "`required_atoms` not all held",
    engine_verdict: "—",
    shape: "not nominated",
    note: "",
  },
];

// ── [RATIFY — DRAFT, unratified] — the atom-phrase map (doc 213 §5 pattern;
// this build's own DPIA vocabulary, doc 232). One ratified clause per
// closed-list atom value in HOOK_PRODUCT_REGISTRY.dpia
// (generate-corpus-hooks/_local/product-registry.ts). ──────────────────────

export const DPIA_ATOM_PHRASES: Readonly<Record<string, string>> = {
  // — classes —
  "class:employee_monitoring": "the processing monitors employees",
  "class:public_space_surveillance": "the processing systematically monitors a publicly accessible area",
  "class:algorithmic_decision": "the processing includes automated evaluation, scoring, or decision-making",
  "class:innovative_technology_use": "the processing uses a novel or innovative technology",
  "class:dataset_matching": "the processing matches or combines datasets",

  // — flags —
  "flag:biometric": "the processing includes biometric data",
  "flag:special_category": "the processing includes special-category data",
  "flag:children": "children are among the people affected",
  "flag:large_scale": "the processing is carried out on a large scale",
  "flag:vulnerable_subjects": "the processing concerns vulnerable data subjects",
  "flag:automated_decision": "the processing involves automated decision-making",
  "flag:cross_border_transfer": "the processing involves a cross-border transfer of personal data",

  // — relationships —
  "relationship:employee": "the people affected are employees of the controller",
  "relationship:customer": "the people affected are customers of the controller",
  "relationship:public": "the people affected are members of the public with no relationship to the controller",

  // — data categories (DPIA_DATA_CATEGORIES / DATA_CATS, DPIAFramework.enums.ts) —
  "data_category:Contact details": "the processing includes contact details",
  "data_category:Employee records": "the processing includes employee records",
  "data_category:Customer records": "the processing includes customer records",
  "data_category:Health or medical data": "the processing includes health or medical data",
  "data_category:Financial data": "the processing includes financial data",
  "data_category:Biometric data": "the processing includes biometric data",
  "data_category:Children's data": "the processing includes children's data",
  "data_category:Location data": "the processing includes location data",
  "data_category:Communications content": "the processing includes communications content",
  "data_category:Other": "the processing includes other categories of data not separately listed",

  // — instruments —
  "instrument:EU GDPR": "the processing is assessed under the EU GDPR",
  "instrument:UK GDPR": "the processing is assessed under the UK GDPR",

  // — state: atoms — the closed `reasons_to_conduct` vocabulary (17 options,
  // REASONS_TO_CONDUCT / DPIAFramework.enums.ts), true and false phrasing for
  // each (the `false` form is the only way to phrase an ABSENCE — the doc 223
  // defect this build designs out from day one: a hook may distinguish on a
  // record that DID NOT select a reason only through this explicit `=false`
  // phrase, never by reusing the `=true` phrase for an absent-polarity pair).
  "state:intake.reasons_to_conduct.art35_3a_evaluation_profiling=true":
    "the record selects systematic, extensive evaluation or profiling with significant effects as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.art35_3a_evaluation_profiling=false":
    "the record does not select systematic, extensive evaluation or profiling with significant effects as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.art35_3b_large_scale_special_category=true":
    "the record selects large-scale special-category or criminal-offence data as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.art35_3b_large_scale_special_category=false":
    "the record does not select large-scale special-category or criminal-offence data as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.art35_3c_public_area_monitoring=true":
    "the record selects large-scale systematic monitoring of a public area as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.art35_3c_public_area_monitoring=false":
    "the record does not select large-scale systematic monitoring of a public area as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.evaluation_scoring=true":
    "the record selects evaluation or scoring, including profiling or prediction, as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.evaluation_scoring=false":
    "the record does not select evaluation or scoring as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.automated_decision_making=true":
    "the record selects automated decision-making with a legal or significant effect as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.automated_decision_making=false":
    "the record does not select automated decision-making with a legal or significant effect as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.systematic_monitoring=true":
    "the record selects systematic monitoring of employees, a defined population, or a non-public space as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.systematic_monitoring=false":
    "the record does not select systematic monitoring of employees, a defined population, or a non-public space as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.sensitive_data=true":
    "the record selects sensitive or highly personal data as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.sensitive_data=false":
    "the record does not select sensitive or highly personal data as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.large_scale=true":
    "the record selects data processed on a large scale as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.large_scale=false":
    "the record does not select data processed on a large scale as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.matching_combining_datasets=true":
    "the record selects matching or combining datasets as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.matching_combining_datasets=false":
    "the record does not select matching or combining datasets as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.vulnerable_subjects=true":
    "the record selects data concerning vulnerable subjects as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.vulnerable_subjects=false":
    "the record does not select data concerning vulnerable subjects as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.innovative_technology=true":
    "the record selects innovative use of new technology as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.innovative_technology=false":
    "the record does not select innovative use of new technology as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.prevents_exercising_right=true":
    "the record selects that the processing prevents exercising a right or using a service as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.prevents_exercising_right=false":
    "the record does not select that the processing prevents exercising a right or using a service as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.required_by_national_law=true":
    "the record selects that the assessment is required by national law",
  "state:intake.reasons_to_conduct.required_by_national_law=false":
    "the record does not select that the assessment is required by national law",
  "state:intake.reasons_to_conduct.dpo_or_data_subject_recommendation=true":
    "the record selects a DPO or data-subject recommendation as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.dpo_or_data_subject_recommendation=false":
    "the record does not select a DPO or data-subject recommendation as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.required_by_code_of_conduct=true":
    "the record selects that the assessment is required by a code of conduct or standard",
  "state:intake.reasons_to_conduct.required_by_code_of_conduct=false":
    "the record does not select that the assessment is required by a code of conduct or standard",
  "state:intake.reasons_to_conduct.risk_management_accountability=true":
    "the record selects risk management or accountability as a (beneficial, non-mandatory) reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.risk_management_accountability=false":
    "the record does not select risk management or accountability as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.existing_processing_risk_changed=true":
    "the record selects that this is existing processing whose risk has changed as a reason the assessment was undertaken",
  "state:intake.reasons_to_conduct.existing_processing_risk_changed=false":
    "the record does not select that this is existing processing whose risk has changed as a reason the assessment was undertaken",
};

// ── [RATIFY — DRAFT, unratified] — the sentence shapes (doc 213 §5 pattern
// as amended by doc 222 §4), DPIA-specific text. Slot NAMES are identical to
// LIA's shapes (dpia-hook-join.ts's renderer needs no product-specific
// branching); the WORDING differs where LIA's is legitimate-interest-
// specific (doc 232 build brief: "S5a/S5b/S6/S6x wording is LIA-specific …
// draft DPIA-appropriate shape text"). ─────────────────────────────────────

// DOC 238 (2026-09-09) — AMENDED, still [RATIFY — DRAFT, unratified]: doc 237
// §5 found no current shape, in any product, can produce any CEO-approved
// hook sentence (docs 223B/233/234/236). This revision (a) restructures
// every shape from a 2–4-sentence clause template into the approved
// 4–7-sentence paragraph form, (b) adds the `{quote}` slot (the verified
// `finding_span`, wrapped in quotation marks by the template — quote marks
// are ratified template text, never drafted content, so no verify.ts change
// is needed), (c) adds the optional `{governing_provision}` slot to S1–S4
// (S5a/S5b/S6/S6x already carry an equivalent rule statement via
// `{proposition}`/`{condition}`), and (d) rewords S2/S6x's section pointer
// from backward-asserting ("…and the determination in Section {section}
// reflects it") to forward-looking ("Whether that holds… is addressed in
// Section {section}") — matching every approved DPIA candidate this session
// (233 §"AENA": "Section 3 addresses whether that analysis is present";
// §"ICS": "Section 1 records whether that trigger is satisfied"). S1 is left
// backward-asserting on purpose (doc 233's WP248 candidate: "supports the
// assessment's position… Section 1 records that determination" — a
// SUPPORTING finding is properly asserted, not hedged as pending). The hedge
// itself is NOT template text — it is the hook's own CEO-approved
// `hedge_sentence` (hook-types.ts), appended verbatim by the join's
// `hedgeSuffix` after the citation; no generic hedge constant exists (doc
// 238 follow-up, 2026-09-09). See doc 238 §"DPIA" for the full proposal, a
// rendered example, and the CEO ratify/revise/hold line.

export const DPIA_HOOK_SHAPES: Readonly<Record<"S1" | "S2" | "S3" | "S4" | "S5a" | "S5b" | "S6" | "S6x", string>> = {
  S1:
    "The record identifies that {customer_fact}. In {authority}, {regulator} {verb} that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding supports the assessment's position on {factor}. {hedge}Section {section} records that determination. ({citation}; {status}.)",
  S2:
    "The record identifies that {customer_fact}. In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding cuts against the assessment's position on {factor}. {hedge}Whether that holds on this record is addressed in Section {section}. ({citation}; {status}.)",
  S3:
    "In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". That finding turned on the fact that {source_fact}; on this record the assessment has instead identified {record_fact}. The decision marks a boundary rather than a finding against the record. ({citation}; {status}.)",
  S4:
    "In {authority}, {regulator} found that where {fact_pattern}, {finding} — in its own words, \"{quote}\". The record identifies {customer_fact}. That decision is {status}; it is noted as a boundary and is not applied. ({citation}.)",
  S5a:
    "In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}. That guidance is relevant to {factor}; whether its condition is satisfied is addressed in Section {section}. ({citation}; {status}.)",
  S5b:
    "In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}. That guidance is relevant to {factor}; whether its condition is satisfied is addressed in Section {section}. The facts identified in Section {section} satisfy that stated condition. ({citation}; {status}.)",
  S6:
    "The record identifies {record_fact}. In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}, but does not address whether the same conclusion follows where {record_fact}. The determination in Section {section} therefore rests on the separately identified rules and facts, not on that guidance. ({citation}; {status}.)",
  S6x:
    "The record identifies {record_fact}. In {authority}, {regulator} {verb} that {proposition} — in its own words, \"{quote}\" — subject to {condition}, and that {exclusion_paraphrase}; that exclusion applies to processing of the kind the record describes. Whether it applies here is addressed on {factor} in Section {section}. ({citation}; {status}.)",
};

// ── [RATIFY — DRAFT, unratified] — concept equivalence (doc 222 §2.3
// pattern). Two atoms naming the same underlying fact share a concept; the
// render dedupes `{customer_fact}` by concept. ────────────────────────────

export const DPIA_ATOM_CONCEPTS: Readonly<Record<string, string>> = {
  "flag:special_category": "special_category",
  "data_category:Health or medical data": "special_category",
  "state:intake.reasons_to_conduct.art35_3b_large_scale_special_category=true": "special_category",
  "flag:children": "children",
  "data_category:Children's data": "children",
  "state:intake.reasons_to_conduct.vulnerable_subjects=true": "vulnerable_subjects",
  "flag:vulnerable_subjects": "vulnerable_subjects",
  "flag:biometric": "biometric",
  "data_category:Biometric data": "biometric",
  "flag:large_scale": "large_scale",
  "state:intake.reasons_to_conduct.large_scale=true": "large_scale",
  "flag:automated_decision": "automated_decision",
  "class:algorithmic_decision": "automated_decision",
  "state:intake.reasons_to_conduct.automated_decision_making=true": "automated_decision",
  "class:employee_monitoring": "employee_monitoring",
  "state:intake.reasons_to_conduct.systematic_monitoring=true": "employee_monitoring",
};

/** The concept an atom names — itself when the table has no entry. */
export function dpiaAtomConcept(atom: string): string {
  return DPIA_ATOM_CONCEPTS[atom] ?? atom;
}

// ── [RATIFY — DRAFT, unratified] — factor phrases (doc 222 §5 pattern): the
// `{factor}` slot, without a leading article. Every factor maps to exactly
// one of DPIA's two hook elements (`DPIA_FACTOR_ELEMENT`, below) — doc 232's
// factor/determination → section map. ──────────────────────────────────────

const F_OBLIGATION = "the Article 35 obligation to conduct this assessment";
const F_EMPLOYEE_MONITORING = "the employee-monitoring trigger";
const F_ALGORITHMIC = "the automated-decision trigger";
const F_ADEQUACY = "the necessity and proportionality analysis";
const F_BIOMETRIC_ADEQUACY = "the adequacy of the biometric-processing analysis";

export const DPIA_FACTOR_PHRASES: Readonly<Record<string, string>> = {
  [F_OBLIGATION]: "the obligation to conduct this assessment",
  [F_EMPLOYEE_MONITORING]: "the employee-monitoring trigger",
  [F_ALGORITHMIC]: "the automated-decision trigger",
  [F_ADEQUACY]: "necessity and proportionality",
  [F_BIOMETRIC_ADEQUACY]: "the adequacy of the biometric-processing analysis",
};

// ── [RATIFY — DRAFT, unratified] — DOC 213 §2 pattern: factor → DPIA hook
// element ("obligation" | "adequacy" — dpia-hook-join.ts's
// `SECTION_FOR_ELEMENT`/`bears_on_element`). Copied verbatim into
// generate-corpus-hooks/_local/dpia-factor-element.ts (pinned by test), the
// same relationship LIA_FACTOR_ELEMENT has to
// generate-corpus-hooks/_local/factor-element.ts. ──────────────────────────

export const DPIA_FACTOR_ELEMENT: Readonly<Record<string, "obligation" | "adequacy">> = {
  [F_OBLIGATION]: "obligation",
  [F_EMPLOYEE_MONITORING]: "obligation",
  [F_ALGORITHMIC]: "obligation",
  [F_ADEQUACY]: "adequacy",
  [F_BIOMETRIC_ADEQUACY]: "adequacy",
};

export function dpiaElementOf(factorId: string): "obligation" | "adequacy" | null {
  return DPIA_FACTOR_ELEMENT[factorId] ?? null;
}

// ── [RATIFY] — source status labels (doc 222 §2.7) — VERBATIM COPY of
// LIA_SOURCE_STATUS_LABELS. Product-agnostic: HookSourceStatus
// (hook-types.ts) carries no LIA-specific vocabulary. ──────────────────────

export const DPIA_SOURCE_STATUS_LABELS: Readonly<Record<string, string>> = {
  edpb_guidelines_final: "EDPB guidelines — interpretive guidance, not binding law",
  edpb_opinion: "EDPB Article 64 opinion — Board opinion, not a judicial decision",
  wp29_opinion: "Article 29 Working Party opinion — historical interpretive guidance",
  regulator_guidance: "regulatory guidance — non-binding",
  sa_decision: "supervisory-authority decision — persuasive, non-binding outside its jurisdiction",
  sa_decision_affirmed: "supervisory-authority decision, affirmed on appeal",
  sa_decision_appeal_pending: "under appeal",
};

// ── RATIFIED (LIA, CEO 2026-09-08) — BYTE-MIRRORED here, unchanged. Where an
// appeal is known to have been made, the join appends this sentence,
// verbatim, after the hook's sentence. ─────────────────────────────────────

export const DPIA_APPEAL_SENTENCE = "This matter is subject to an appeal which could invalidate this ruling.";

export const DPIA_SETTLEDNESS_LABELS: Readonly<Record<"R1" | "R2" | "R3" | "R4", string>> = {
  R1: "adopted guidance or settled authority",
  R2: "a settled line of decisions",
  R3: "a single supervisory authority's decision",
  R4: "under appeal / contested",
};
