-- Add source_url column
ALTER TABLE li_tracker_entries ADD COLUMN IF NOT EXISTS source_url text;

-- Clear existing seed data to replace with verified URLs
DELETE FROM li_tracker_entries WHERE source_article_id IS NULL;

-- Insert 39 seed rows with verified source URLs
INSERT INTO li_tracker_entries (
  processing_activity, outcome, signal_type, dpa_source,
  jurisdiction, summary, case_reference, confidence, last_confirmed, source_url
)
SELECT v.processing_activity, v.outcome, v.signal_type, v.dpa_source,
  v.jurisdiction, v.summary, v.case_reference, v.confidence,
  v.last_confirmed, v.source_url
FROM (VALUES
  ('Fraud prevention and detection for financial transactions', 'accepted', 'Official Guidance', 'EDPB', 'EU', 'EDPB Guidelines 1/2024 identify fraud prevention as a paradigmatic legitimate interest — strong candidate where data sharing logic is clearly disclosed and narrowly scoped.', 'EDPB Guidelines 1/2024 on LI', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('Network and information security — internal cybersecurity operations', 'accepted', 'Official Guidance', 'EDPB', 'EU', 'Expressly listed by the EDPB as a recognized legitimate interest area; widely accepted across EU DPAs without significant qualification.', 'EDPB Guidelines 1/2024 on LI', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('Internal administrative transfers within a corporate group', 'accepted', 'Official Guidance', 'EDPB', 'EU', 'Specifically identified in Recital 48 GDPR and confirmed in EDPB guidance as a legitimate interest, assuming ordinary safeguards apply.', 'GDPR Recital 48; EDPB Guidelines 1/2024', 'high', CURRENT_DATE, 'https://gdpr-info.eu/recitals/no-48/'),
  ('Basic anti-abuse measures and platform account security', 'accepted', 'Official Guidance', 'EDPB', 'EU', 'Good LI candidate where the use is genuinely tied to platform or network integrity; must be narrowly defined and not extend to general user monitoring.', 'EDPB Guidelines 1/2024 on LI', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('IT security incident response and forensic investigation', 'accepted', 'Official Guidance', 'EDPB', 'EU', 'Processing personal data to investigate and contain a security incident is recognized as a legitimate operational interest; must be proportionate to the incident scope.', 'EDPB Guidelines 1/2024 on LI', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('Physical security of premises and access control', 'accepted', 'Official Guidance', 'EDPB', 'EU', 'Commonly accepted in principle across EU DPAs; means used must still be proportionate — access logs yes, blanket monitoring of all movement no.', 'EDPB Guidelines 1/2024; national DPA guidance', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('Whistleblowing hotlines – internal compliance reporting channels', 'accepted', 'Official Guidance', 'EDPB', 'EU', 'EDPB and WP29 guidance confirm LI is a viable basis for internal reporting channels, provided data is limited to the investigation and access is restricted.', 'WP29 Opinion 1/2006; EDPB Guidelines 1/2024', 'high', CURRENT_DATE, 'https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2006/wp117_en.pdf'),
  ('Cybersecurity threat intelligence sharing between organizations', 'accepted', 'Official Guidance', 'EDPB', 'EU', 'EDPB materials expressly recognize cross-organization security sharing as a legitimate interest area, particularly in critical infrastructure contexts.', 'EDPB Guidelines 1/2024 on LI', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('Preventing service misuse – spam and bot detection', 'accepted', 'Official Guidance', 'EDPB', 'EU', 'Closely linked to network security; accepted as LI where the processing is necessary to detect and block automated abuse rather than to monitor users generally.', 'EDPB Guidelines 1/2024; ICO LIA Framework', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('Exercising or defending legal claims in litigation', 'accepted', 'Official Guidance', 'ICO', 'United Kingdom', 'ICO LIA framework recognizes defense or exercise of legal claims as a legitimate interest; processing must be limited to what the legal proceeding requires.', 'ICO Legitimate Interests Guidance 2024', 'high', CURRENT_DATE, 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/lawful-basis/legitimate-interests/'),
  ('Recognized Legitimate Interest basis under UK GDPR (Schedule 1 DPA 2018)', 'accepted', 'Official Guidance', 'ICO', 'United Kingdom', 'The UK Data (Use and Access) Act 2025 and ICO guidance of March 2026 clarify a recognized legitimate interest basis covering specific listed purposes including research, law enforcement support, and democratic engagement.', 'ICO Guidance on Recognized LI, March 2026', 'high', CURRENT_DATE, 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/lawful-basis/legitimate-interests/what-is-the-recognised-legitimate-interests-basis/'),
  ('Security logging and audit trails for regulatory compliance', 'accepted', 'Official Guidance', 'CNIL', 'France', 'CNIL guidance accepts security logging as LI for regulated entities; access must be role-limited and retention proportionate to audit requirements.', 'CNIL GDPR guidance on legitimate interests and security processing', 'high', CURRENT_DATE, 'https://www.cnil.fr/en/sheet-ndeg15-take-account-legal-basis-technical-implementation'),
  ('Direct marketing to existing customers', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'Potentially viable as LI under GDPR, but ePrivacy Directive and national direct-marketing rules can independently block or condition the practice regardless of LI assessment outcome.', 'EDPB Guidelines 06/2020; WP29 Opinion 06/2014', 'high', CURRENT_DATE, 'https://edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-062020-interplay-second-electronic-communications_en'),
  ('Internal analytics and business intelligence – low-risk aggregated', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'Often acceptable if analytics are genuinely low-risk, aggregated, not used for profiling individuals, and individuals would reasonably expect some performance measurement.', 'EDPB Guidelines 1/2024 on LI', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('Video surveillance and CCTV for security purposes', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'Security can be a legitimate interest for CCTV, but camera placement, field of view, retention period, notice, and intrusiveness are all independently decisive – each must pass necessity and balancing tests.', 'EDPB Guidelines 3/2019 on video devices', 'high', CURRENT_DATE, 'https://edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-32019-processing-personal-data-through-video_en'),
  ('Creditworthiness assessment before extending credit', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'Recognized as possible LI in some national DPA decisions, but analysis is highly fact-specific and may overlap with Article 22 automated decision-making obligations.', 'EDPB one-stop-shop case digest 2026', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/support-pool-experts-projects/one-stop-shop-case-digest-legal-basis_en'),
  ('Out-of-court debt collection for overdue amounts', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'Often viewed as a plausible LI, but disclosure obligations, proportionality of processing, and local debt-collection law all affect the outcome significantly.', 'EDPB Guidelines 1/2024; national DPA guidance', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('Product or service promotion to existing customers – expected low-impact', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'Better justified under LI when the marketing is low-impact, would be reasonably expected by customers, and is easy for individuals to object to.', 'WP29 Opinion 06/2014; EDPB Guidelines 1/2024', 'high', CURRENT_DATE, 'https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2014/wp217_en.pdf'),
  ('Property and premises protection – landlord or facilities management', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'Commonly legitimate in principle, but the means used must be proportionate – processing must not exceed what the protection purpose genuinely requires.', 'EDPB Guidelines 1/2024; national DPA guidance', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('Customer satisfaction surveys sent to existing customers', 'conditional', 'Official Guidance', 'ICO', 'United Kingdom', 'ICO guidance treats post-transaction surveys as potentially viable under LI where the relationship is recent, the survey is limited in scope, and the customer would reasonably expect contact.', 'ICO Direct Marketing Guidance 2023', 'high', CURRENT_DATE, 'https://ico.org.uk/for-organisations/direct-marketing-and-privacy-and-electronic-communications/guide-to-direct-marketing/'),
  ('Processing for scientific research with appropriate safeguards', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'Scientific research can support a legitimate interest claim but must be balanced against individual rights; Article 89 safeguards and data minimization principles apply independently.', 'GDPR Article 89; EDPB Guidelines 1/2024 on LI', 'high', CURRENT_DATE, 'https://gdpr-info.eu/art-89-gdpr/'),
  ('Obtaining personal data to enforce a specific active legal claim', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'More defensible where the processing is tied to a concrete, active legal claim rather than a general reservation of rights; scope must match the specific claim.', 'EDPB Guidelines 1/2024 on LI', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('AI deployment for customer-facing user assistance — bounded and expected', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'EDPB Opinion 28/2024 on AI indicates LI can be used in AI deployment where the use is expected by the user, bounded in scope, and lower-risk — subject to full balancing test.', 'EDPB Opinion 28/2024 on AI systems', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/opinion/opinion-282024-certain-data-protection-aspects-related-processing_en'),
  ('AI use for cybersecurity improvement and threat detection', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'Stronger case than adtech-style AI uses because the underlying interest aligns with recognized security interests; must still pass necessity and proportionality tests.', 'EDPB Opinion 28/2024 on AI systems', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/opinion/opinion-282024-certain-data-protection-aspects-related-processing_en'),
  ('Product improvement based on aggregated non-identified usage data', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'Recognized as a possible LI in EDPB materials but remains fact-specific — necessity and balancing tests must assess whether less intrusive means could achieve the same goal.', 'EDPB one-stop-shop case digest 2026', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/support-pool-experts-projects/one-stop-shop-case-digest-legal-basis_en'),
  ('Minimal fraud screening at checkout — limited data points transparent', 'conditional', 'Official Guidance', 'EDPB', 'EU', 'A stronger LI case when tied to concrete fraud risk signals, limited data points, and clear disclosure — weaker when screening extends to general risk profiling.', 'EDPB Guidelines 1/2024 on LI', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('Requiring additional identity data to prevent mistaken credit pulls', 'conditional', 'Enforcement Decision', 'EDPB', 'EU', 'Regulators have credited this kind of safeguard logic where it genuinely reduces misidentification risk; must be narrowly scoped and disclosed.', 'EDPB one-stop-shop case digest 2026', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/support-pool-experts-projects/one-stop-shop-case-digest-legal-basis_en'),
  ('Behavioral advertising and cross-service profiling', 'rejected', 'Enforcement Decision', 'EDPB', 'EU', 'EDPB one-stop-shop case digest (March 2026) cites Meta behavioral advertising as a paradigmatic necessity failure — less intrusive alternatives existed to achieve the same commercial objective.', 'EDPB one-stop-shop case digest 2026; Meta/DPC decision', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/support-pool-experts-projects/one-stop-shop-case-digest-legal-basis_en'),
  ('Cross-site tracking and third-party cookie tracking for ad targeting', 'rejected', 'Official Guidance', 'EDPB', 'EU', 'Where LI arguments struggle most in practice; once ePrivacy Directive rules requiring consent for cookie placement are layered in, LI as a GDPR basis cannot override the ePrivacy consent requirement.', 'EDPB Guidelines 06/2020; EDPB one-stop-shop digest 2026', 'high', CURRENT_DATE, 'https://edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-062020-interplay-second-electronic-communications_en'),
  ('Large-scale scraping and repurposing of publicly available personal data', 'rejected', 'Official Guidance', 'EDPB', 'EU', 'Even when data is technically public, LI still requires a precise and present interest, a strict necessity finding, and a favorable balancing test — general commercial data collection routinely fails.', 'EDPB one-stop-shop case digest 2026', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/support-pool-experts-projects/one-stop-shop-case-digest-legal-basis_en'),
  ('Extensive employee monitoring — keystroke logging and continuous screen capture', 'rejected', 'Official Guidance', 'EDPB', 'EU', 'High-risk processing due to fundamental power imbalance in employment context; most extensive monitoring fails the balancing test because employees cannot reasonably be expected to accept it.', 'EDPB Guidelines 1/2024; WP29 Opinion 2/2017 on employee monitoring', 'high', CURRENT_DATE, 'https://ec.europa.eu/newsroom/article29/items/610169'),
  ('Hidden ranking suppression and shadow banning for platform safety', 'rejected', 'Enforcement Decision', 'EDPB', 'EU', 'EDPB one-stop-shop case digest notes the platform safety interest was accepted in principle, but the measure failed the necessity and proportionality tests — less intrusive alternatives were available.', 'EDPB one-stop-shop case digest 2026', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/support-pool-experts-projects/one-stop-shop-case-digest-legal-basis_en'),
  ('Selling or licensing personal data to unrelated third parties for commercial gain', 'rejected', 'Official Guidance', 'EDPB', 'EU', 'No legitimate interest can justify commercial sale of personal data as a standalone activity; data subjects would not reasonably expect their data to be sold and the balancing test fails.', 'EDPB Guidelines 1/2024; ICO LIA Framework', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('Processing personal data to enforce a debt that was discharged or applied to wrong person', 'rejected', 'Enforcement Decision', 'CNIL', 'France', 'A claimed LI must be real and present at the time of processing — an LI that no longer exists or never applied cannot retrospectively justify processing.', 'CNIL enforcement; Italian DPA case 10233368 April 2026', 'high', CURRENT_DATE, 'https://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/10233368'),
  ('Tracking individuals location history over time for commercial profiling', 'rejected', 'Official Guidance', 'EDPB', 'EU', 'Location tracking at scale fails both the necessity and balancing tests; individuals have a strong privacy interest in their movements that commercial interests in profiling cannot override.', 'EDPB Guidelines 1/2024; national DPA enforcement', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('AI model training and development using personal data', 'contested', 'Official Guidance', 'EDPB', 'EU', 'EDPB Opinion 28/2024 says LI can be used in AI development in some cases, but only with a rigorous analysis — outcome is highly fact-specific and DPAs have reached different conclusions.', 'EDPB Opinion 28/2024 on AI systems', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/opinion/opinion-282024-certain-data-protection-aspects-related-processing_en'),
  ('Reporting payment defaults to credit registries', 'contested', 'Enforcement Decision', 'EDPB', 'EU', 'Can be argued under LI, but regulators have treated the legal basis and surrounding safeguards very carefully — outcome varies by national DPA and depends heavily on disclosure, accuracy, and proportionality.', 'EDPB one-stop-shop case digest 2026', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/support-pool-experts-projects/one-stop-shop-case-digest-legal-basis_en'),
  ('Customer phone number collection for walk-in service operations', 'contested', 'Official Guidance', 'EDPB', 'EU', 'Sometimes defensible but the controller needs a clearly stated present interest and must avoid collecting more than is needed for the operational purpose; outcomes vary across DPAs.', 'EDPB Guidelines 1/2024 on LI', 'high', CURRENT_DATE, 'https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-012024-processing-personal-data-based-legitimate_en'),
  ('Analytics and engagement tracking on child-directed platforms', 'contested', 'Official Guidance', 'EDPB', 'EU', 'Article 6(1)(f) itself flags children as requiring special protection in the balancing test; DPAs have generally been hostile to LI claims for any more than minimal processing on child-directed platforms.', 'GDPR Article 6(1)(f); EDPB Guidelines 1/2024', 'high', CURRENT_DATE, 'https://gdpr-info.eu/art-6-gdpr/')
) AS v(processing_activity, outcome, signal_type, dpa_source, jurisdiction, summary, case_reference, confidence, last_confirmed, source_url)
WHERE NOT EXISTS (
  SELECT 1 FROM li_tracker_entries e
  WHERE e.processing_activity = v.processing_activity AND e.dpa_source = v.dpa_source
);