
-- 1. Create jurisdictions table if not exists
CREATE TABLE IF NOT EXISTS public.jurisdictions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  iso_code text,
  region text,
  law_name text,
  dpa_name text,
  law_status text,
  dla_piper_url text,
  created_at timestamptz DEFAULT now()
);

-- 2. Enable RLS
ALTER TABLE public.jurisdictions ENABLE ROW LEVEL SECURITY;

-- 3. RLS policies (idempotent with DO blocks)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='jurisdictions' AND policyname='Public can read jurisdictions') THEN
    CREATE POLICY "Public can read jurisdictions" ON public.jurisdictions FOR SELECT TO anon, authenticated USING (true);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='jurisdictions' AND policyname='Service role manages jurisdictions') THEN
    CREATE POLICY "Service role manages jurisdictions" ON public.jurisdictions FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;

-- 4. Seed 164 DLA Piper jurisdictions
INSERT INTO public.jurisdictions (name, slug, region) VALUES
-- EU & UK (53)
('Albania','albania','EU & UK'),
('Algeria','algeria','EU & UK'),
('Armenia','armenia','EU & UK'),
('Austria','austria','EU & UK'),
('Azerbaijan','azerbaijan','EU & UK'),
('Belarus','belarus','EU & UK'),
('Belgium','belgium','EU & UK'),
('Bosnia and Herzegovina','bosnia-and-herzegovina','EU & UK'),
('Bulgaria','bulgaria','EU & UK'),
('Croatia','croatia','EU & UK'),
('Cyprus','cyprus','EU & UK'),
('Czech Republic','czech-republic','EU & UK'),
('Denmark','denmark','EU & UK'),
('Estonia','estonia','EU & UK'),
('Finland','finland','EU & UK'),
('France','france','EU & UK'),
('Georgia','georgia','EU & UK'),
('Germany','germany','EU & UK'),
('Gibraltar','gibraltar','EU & UK'),
('Greece','greece','EU & UK'),
('Guernsey','guernsey','EU & UK'),
('Hungary','hungary','EU & UK'),
('Iceland','iceland','EU & UK'),
('Ireland','ireland','EU & UK'),
('Italy','italy','EU & UK'),
('Jersey','jersey','EU & UK'),
('Kosovo','kosovo','EU & UK'),
('Kyrgyzstan','kyrgyzstan','EU & UK'),
('Latvia','latvia','EU & UK'),
('Liechtenstein','liechtenstein','EU & UK'),
('Lithuania','lithuania','EU & UK'),
('Luxembourg','luxembourg','EU & UK'),
('Malta','malta','EU & UK'),
('Moldova','moldova','EU & UK'),
('Monaco','monaco','EU & UK'),
('Montenegro','montenegro','EU & UK'),
('Netherlands','netherlands','EU & UK'),
('North Macedonia','north-macedonia','EU & UK'),
('Norway','norway','EU & UK'),
('Poland','poland','EU & UK'),
('Portugal','portugal','EU & UK'),
('Romania','romania','EU & UK'),
('Russia','russia','EU & UK'),
('Serbia','serbia','EU & UK'),
('Slovakia','slovakia','EU & UK'),
('Slovenia','slovenia','EU & UK'),
('Spain','spain','EU & UK'),
('Sweden','sweden','EU & UK'),
('Switzerland','switzerland','EU & UK'),
('Ukraine','ukraine','EU & UK'),
('United Kingdom','united-kingdom','EU & UK'),
('Uzbekistan','uzbekistan','EU & UK'),
-- Americas (31)
('Argentina','argentina','Americas'),
('Aruba','aruba','Americas'),
('Bahamas','bahamas','Americas'),
('Barbados','barbados','Americas'),
('Bermuda','bermuda','Americas'),
('Bolivia','bolivia','Americas'),
('Bonaire Sint Eustatius and Saba','bonaire-sint-eustatius-and-saba','Americas'),
('Brazil','brazil','Americas'),
('British Virgin Islands','british-virgin-islands','Americas'),
('Canada','canada','Americas'),
('Cayman Islands','cayman-islands','Americas'),
('Chile','chile','Americas'),
('Colombia','colombia','Americas'),
('Costa Rica','costa-rica','Americas'),
('Cuba','cuba','Americas'),
('Curacao','curacao','Americas'),
('Dominican Republic','dominican-republic','Americas'),
('Ecuador','ecuador','Americas'),
('El Salvador','el-salvador','Americas'),
('Guatemala','guatemala','Americas'),
('Haiti','haiti','Americas'),
('Honduras','honduras','Americas'),
('Mexico','mexico','Americas'),
('Nicaragua','nicaragua','Americas'),
('Panama','panama','Americas'),
('Paraguay','paraguay','Americas'),
('Peru','peru','Americas'),
('Trinidad and Tobago','trinidad-and-tobago','Americas'),
('United States','united-states','Americas'),
('Uruguay','uruguay','Americas'),
('Venezuela','venezuela','Americas'),
-- Asia Pacific (26)
('Australia','australia','Asia Pacific'),
('Bangladesh','bangladesh','Asia Pacific'),
('Brunei','brunei','Asia Pacific'),
('Cambodia','cambodia','Asia Pacific'),
('China','china','Asia Pacific'),
('Federated States of Micronesia','federated-states-of-micronesia','Asia Pacific'),
('Fiji','fiji','Asia Pacific'),
('Hong Kong SAR','hong-kong-sar','Asia Pacific'),
('India','india','Asia Pacific'),
('Indonesia','indonesia','Asia Pacific'),
('Japan','japan','Asia Pacific'),
('Laos','laos','Asia Pacific'),
('Macau SAR','macau-sar','Asia Pacific'),
('Malaysia','malaysia','Asia Pacific'),
('Mongolia','mongolia','Asia Pacific'),
('Myanmar','myanmar','Asia Pacific'),
('Nepal','nepal','Asia Pacific'),
('New Zealand','new-zealand','Asia Pacific'),
('Pakistan','pakistan','Asia Pacific'),
('Philippines','philippines','Asia Pacific'),
('Singapore','singapore','Asia Pacific'),
('South Korea','south-korea','Asia Pacific'),
('Sri Lanka','sri-lanka','Asia Pacific'),
('Taiwan','taiwan','Asia Pacific'),
('Thailand','thailand','Asia Pacific'),
('Vietnam','vietnam','Asia Pacific'),
-- Middle East & Africa (47)
('Angola','angola','Middle East & Africa'),
('Bahrain','bahrain','Middle East & Africa'),
('Benin','benin','Middle East & Africa'),
('Botswana','botswana','Middle East & Africa'),
('Burkina Faso','burkina-faso','Middle East & Africa'),
('Burundi','burundi','Middle East & Africa'),
('Cameroon','cameroon','Middle East & Africa'),
('Cape Verde','cape-verde','Middle East & Africa'),
('Chad','chad','Middle East & Africa'),
('Cote d Ivoire','cote-d-ivoire','Middle East & Africa'),
('Democratic Republic of Congo','democratic-republic-of-congo','Middle East & Africa'),
('Egypt','egypt','Middle East & Africa'),
('Equatorial Guinea','equatorial-guinea','Middle East & Africa'),
('Ethiopia','ethiopia','Middle East & Africa'),
('Gabon','gabon','Middle East & Africa'),
('Ghana','ghana','Middle East & Africa'),
('Guinea','guinea','Middle East & Africa'),
('Iran','iran','Middle East & Africa'),
('Israel','israel','Middle East & Africa'),
('Jordan','jordan','Middle East & Africa'),
('Kazakhstan','kazakhstan','Middle East & Africa'),
('Kenya','kenya','Middle East & Africa'),
('Kuwait','kuwait','Middle East & Africa'),
('Lebanon','lebanon','Middle East & Africa'),
('Lesotho','lesotho','Middle East & Africa'),
('Liberia','liberia','Middle East & Africa'),
('Libya','libya','Middle East & Africa'),
('Madagascar','madagascar','Middle East & Africa'),
('Mauritius','mauritius','Middle East & Africa'),
('Morocco','morocco','Middle East & Africa'),
('Mozambique','mozambique','Middle East & Africa'),
('Namibia','namibia','Middle East & Africa'),
('Nigeria','nigeria','Middle East & Africa'),
('Oman','oman','Middle East & Africa'),
('Qatar','qatar','Middle East & Africa'),
('Rwanda','rwanda','Middle East & Africa'),
('Saudi Arabia','saudi-arabia','Middle East & Africa'),
('Senegal','senegal','Middle East & Africa'),
('Sierra Leone','sierra-leone','Middle East & Africa'),
('South Africa','south-africa','Middle East & Africa'),
('Tanzania','tanzania','Middle East & Africa'),
('Tunisia','tunisia','Middle East & Africa'),
('Turkey','turkey','Middle East & Africa'),
('Uganda','uganda','Middle East & Africa'),
('United Arab Emirates','united-arab-emirates','Middle East & Africa'),
('Zambia','zambia','Middle East & Africa'),
('Zimbabwe','zimbabwe','Middle East & Africa')
ON CONFLICT (name) DO NOTHING;
