/**
 * ITEM 369-IR LEG 1 — TWO-FILE PDF DELIVERY for the Incident Response Playbook.
 *
 * One generation run yields TWO downloadable artifacts, each rendered here:
 *
 *   A. `standing_playbook`   — the pre-incident reference. Fourteen sections in
 *      the builder's locked `section_order`, the EDPB Art. 33 template field
 *      mapping rendered inside the statutory notification section, and the
 *      authority exhibit rendered LAST, immediately before the universal
 *      disclaimer that the caller appends.
 *
 *   B. `incident_worksheet`  — the blank forms. NO exhibit, no analysis, no
 *      pre-filled cell. The universal disclaimer is likewise the caller's final
 *      element.
 *
 * The universal disclaimer is NOT emitted here: `applyUniversalDisclaimerHtml`
 * in the caller appends it exactly once per document, as the final element.
 */

import { renderAuthorityExhibitHtml, AUTHORITY_EXHIBIT_CSS } from "../_shared/report-exhibits/authority-exhibit.ts";

function esc(s: unknown): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const SHELL_CSS = `
  * { box-sizing: border-box; }
  body { font-family:'Times New Roman', Times, serif; color:#1a1916; background:#f5f8fa;
    font-size:11pt; line-height:1.5; margin:0;
    -webkit-print-color-adjust:exact; print-color-adjust:exact; }
  .shell { background:#fff; border:1px solid #dde5ea; border-radius:14px; overflow:hidden; }
  .header { background:#0c2a44; color:#fff; padding:22px 26px 24px; }
  .header .eyebrow { font-size:9px; font-weight:600; text-transform:uppercase;
    letter-spacing:0.14em; color:#93b5c6; margin:0 0 4px; }
  .header h1 { font-family:'Georgia','Times New Roman',serif; font-size:22px; margin:0;
    line-height:1.25; font-weight:700; }
  .header .meta { margin-top:6px; font-size:11px; color:#cbd5e1; }
  .body { padding:22px 26px 26px; }
  .lede { font-size:11px; color:#5c6d7a; margin:0 0 18px; }
  h2.sec { font-family:'Georgia','Times New Roman',serif; font-size:15px; color:#0c2a44;
    margin:22px 0 8px; page-break-after:avoid; }
  h3.sub { font-size:12px; color:#0c2a44; margin:14px 0 6px; page-break-after:avoid; }
  table.grid { width:100%; border-collapse:collapse; font-size:10.5px; margin-bottom:6px;
    page-break-inside:avoid; }
  table.grid th { text-align:left; background:#edf2f5; border:1px solid #dde5ea;
    padding:5px 7px; font-weight:700; color:#0c2a44; }
  table.grid td { border:1px solid #dde5ea; padding:5px 7px; vertical-align:top; }
  table.grid td.blank { height:22px; }
  p.note { font-size:10px; color:#5c6d7a; margin:4px 0 0; }
  p.body-p { font-size:11px; margin:0 0 6px; }
  p.gap { font-size:10.5px; color:#5c6d7a; font-style:italic;
    border-left:3px solid #dde5ea; padding-left:9px; margin:4px 0; }
  dl.finding { font-size:10.5px; margin:0 0 8px; }
  dl.finding dt { font-weight:700; color:#0c2a44; margin-top:5px; }
  dl.finding dd { margin:0 0 2px; }
  .instruction { font-size:10px; color:#5c6d7a; margin:0 0 6px; }
  .prompt { font-size:11px; margin:10px 0 0; }
  .writeline { border-bottom:1px solid #c9d4dc; height:26px; margin-top:4px; }
  .field { border:1px solid #dde5ea; border-radius:6px; padding:6px 9px; margin-bottom:5px;
    page-break-inside:avoid; }
  .field .flabel { font-size:9px; font-weight:700; text-transform:uppercase;
    letter-spacing:0.05em; color:#5c6d7a; }
  .field .fvalue { font-size:10.5px; color:#1a1916; margin-top:2px; }
  .field .fblank { font-size:10.5px; color:#8a9eb1; font-style:italic; margin-top:2px;
    border-bottom:1px solid #c9d4dc; min-height:16px; }
  .field .fowner { font-size:9px; color:#8a9eb1; margin-top:3px; }
  footer { margin-top:22px; padding-top:10px; border-top:1px solid #dde5ea;
    font-size:9.5px; color:#5c6d7a; }
${AUTHORITY_EXHIBIT_CSS}
`;

function shell(title: string, eyebrow: string, metaLine: string, lede: string, inner: string): string {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${esc(title)}</title>
<style>${SHELL_CSS}</style></head><body>
<div class="shell">
  <div class="header">
    <p class="eyebrow">${esc(eyebrow)}</p>
    <h1>${esc(title)}</h1>
    <div class="meta">${esc(metaLine)}</div>
  </div>
  <div class="body">
    ${lede ? `<p class="lede">${esc(lede)}</p>` : ""}
    ${inner}
    <footer>Generated by <strong>EndUserPrivacy</strong> · enduserprivacy.com · Confirm every deadline and every named owner against your organisation's own records before operational reliance.</footer>
  </div>
</div>
</body></html>`;
}

// ── ARTIFACT A ────────────────────────────────────────────────────────
function renderTemplateFields(mapping: any): string {
  const tpl = mapping?.edpb_template;
  if (!tpl || !Array.isArray(tpl.sections) || tpl.sections.length === 0) return "";
  const sections = tpl.sections.map((s: any) => {
    const fields = (Array.isArray(s.fields) ? s.fields : []).map((f: any) => {
      const isBlank = f?.status !== "mapped" || !String(f?.value ?? "").trim();
      return `<div class="field">
  <div class="flabel">${esc(f?.label)}</div>
  ${isBlank
    ? `<div class="fblank">Blank — to be completed from the organisation's own record</div>`
    : `<div class="fvalue">${esc(f.value)}</div>`}
  ${f?.owner ? `<div class="fowner">Owner: ${esc(f.owner)}</div>` : ""}
</div>`;
    }).join("");
    return `<h3 class="sub">${esc(s.heading)}</h3>${fields}`;
  }).join("");
  return `<h3 class="sub">Article 33 notification template — field mapping</h3>
<p class="note">${esc(tpl.note)}</p>
<p class="note">Template structure: ${esc(tpl.template_label)}. ${esc(tpl.mapped_count)} field(s) carried from this record; ${esc(tpl.blank_count)} field(s) left deliberately blank.</p>
${sections}`;
}

function renderStandingSection(sec: any, index: number, mapping: any): string {
  const head = `<h2 class="sec">${index}. ${esc(sec?.heading)}</h2>`;
  let bodyHtml = "";

  if (sec?.information_needed) {
    bodyHtml = `<p class="gap">Not recorded. ${esc(sec.information_needed)}</p>`;
  } else if (sec?.kind === "table") {
    const cols: string[] = Array.isArray(sec.columns) ? sec.columns : [];
    const rows: string[][] = Array.isArray(sec.rows) ? sec.rows : [];
    bodyHtml = rows.length
      ? `<table class="grid"><thead><tr>${cols.map((c) => `<th>${esc(c)}</th>`).join("")}</tr></thead>
<tbody>${rows.map((r) => `<tr>${r.map((cell) => `<td>${esc(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table>
${sec.note ? `<p class="note">${esc(sec.note)}</p>` : ""}`
      : `<p class="gap">No rows were recorded for this table.</p>`;
  } else if (sec?.kind === "note") {
    bodyHtml =
      (sec.scope_note ? `<p class="note">${esc(sec.scope_note)}</p>` : "") +
      (Array.isArray(sec.body) ? sec.body : []).map((p: string) => `<p class="body-p">${esc(p)}</p>`).join("");
  } else if (sec?.kind === "finding") {
    bodyHtml = `<dl class="finding">
  <dt>Standard</dt><dd>${esc(sec.standard)}${sec.standard_citation ? ` — ${esc(sec.standard_citation)}` : ""}</dd>
  <dt>Record fact</dt><dd>${esc(sec.record_fact)}</dd>
  <dt>Application</dt><dd>${esc(sec.application)}</dd>
  <dt>Verdict</dt><dd>${esc(sec.verdict)}</dd>
</dl>`;
  } else if (sec?.kind === "pointer") {
    bodyHtml = `<p class="body-p">${esc(sec.note)}</p>`;
    // LEG 2 — the template field mapping renders inside the statutory
    // notification section, which is where the notification form is prepared.
    if (sec.id === "statutory_notification_determinations") {
      bodyHtml += renderTemplateFields(mapping);
    }
  }

  return head + bodyHtml;
}

/**
 * ARTIFACT A — the standing playbook. Sections in the builder's locked order,
 * exhibit last. Caller appends the universal disclaimer after this HTML.
 */
export function buildIRStandingPlaybookHTML(record: any): string {
  const report = record?.report_data ?? {};
  const pb = report?.standing_playbook;
  const intake = record?.intake_data ?? {};
  const org = record?.organization_name || intake?.organizationName || "";
  const jur: string[] = Array.isArray(intake?.jurisdictions) ? intake.jurisdictions : [];
  const sections: any[] = Array.isArray(pb?.sections) ? pb.sections : [];
  const order: string[] = Array.isArray(pb?.section_order) ? pb.section_order : [];
  const byId = new Map(sections.map((s) => [s?.id, s]));
  const ordered = order.length
    ? [
        ...order.map((id) => byId.get(id)).filter(Boolean),
        ...sections.filter((s) => !order.includes(s?.id)),
      ]
    : sections;

  const inner =
    (ordered.length
      ? ordered.map((s, i) => renderStandingSection(s, i + 1, report?.content_owner_mapping)).join("\n")
      : `<p class="gap">The standing playbook was not produced for this record.</p>`) +
    // Exhibit LAST — immediately before the universal disclaimer.
    renderAuthorityExhibitHtml(report?.authority_exhibit);

  const metaLine = [
    `Generated ${new Date(record?.created_at || Date.now()).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
    org || null,
    jur.length ? jur.join(", ") : null,
  ].filter(Boolean).join(" · ");

  return shell(
    pb?.title || (org ? `Incident Response Playbook — ${org}` : "Incident Response Playbook"),
    "Artifact A · Standing playbook",
    metaLine,
    pb?.template_note || "",
    inner,
  );
}

// ── ARTIFACT B ────────────────────────────────────────────────────────
function renderWorksheetForm(form: any): string {
  const head = `<h2 class="sec">${esc(form?.heading)}</h2>
<p class="instruction">${esc(form?.instruction)}</p>`;
  const prompts: string[] = Array.isArray(form?.prompts) ? form.prompts : [];
  if (prompts.length) {
    return head + prompts.map((p, i) =>
      `<p class="prompt">${i + 1}. ${esc(p)}</p><div class="writeline"></div><div class="writeline"></div>`
    ).join("");
  }
  const cols: string[] = Array.isArray(form?.columns) ? form.columns : [];
  const rows = Number(form?.blank_rows ?? 0);
  if (!cols.length || rows <= 0) return head;
  const bodyRows = Array.from({ length: rows })
    .map(() => `<tr>${cols.map(() => `<td class="blank"></td>`).join("")}</tr>`)
    .join("");
  return `${head}<table class="grid"><thead><tr>${cols.map((c) => `<th>${esc(c)}</th>`).join("")}</tr></thead><tbody>${bodyRows}</tbody></table>`;
}

/**
 * ARTIFACT B — the incident worksheet. Blank by design: every cell ships empty
 * and NO authority exhibit is rendered. Caller appends the universal disclaimer.
 */
export function buildIRWorksheetHTML(record: any): string {
  const report = record?.report_data ?? {};
  const ws = report?.incident_worksheet;
  const intake = record?.intake_data ?? {};
  const org = record?.organization_name || intake?.organizationName || "";
  const forms: any[] = Array.isArray(ws?.forms) ? ws.forms : [];

  const inner = forms.length
    ? forms.map(renderWorksheetForm).join("\n")
    : `<p class="gap">The incident worksheet was not produced for this record.</p>`;

  const metaLine = [
    `Generated ${new Date(record?.created_at || Date.now()).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
    org || null,
  ].filter(Boolean).join(" · ");

  return shell(
    ws?.title || (org ? `Incident Worksheet — ${org}` : "Incident Worksheet"),
    "Artifact B · Incident worksheet",
    metaLine,
    "Blank forms, completed during an incident. Nothing on these forms is pre-filled, and no entry here should be treated as a specimen answer.",
    inner,
  );
}
